"""
Comprehensive keyword-only fix for ENEM metadata.
Score: each matching keyword = +1 point
Threshold: >= 3
"""

import json
import re
from pathlib import Path


DISC_TO_AREA = {
    'fisica': 'natureza', 'quimica': 'natureza', 'biologia': 'natureza',
    'historia': 'humanas', 'geografia': 'humanas', 'sociologia': 'humanas', 'filosofia': 'humanas',
    'portugues': 'linguagens', 'ingles': 'linguagens', 'espanhol': 'linguagens',
    'literatura': 'linguagens', 'artes': 'linguagens',
    'algebra': 'matematica', 'geometria': 'matematica',
    'estatistica': 'matematica', 'probabilidade': 'matematica',
}

DISCIPLINE_KEYWORDS = {
    'fisica': [
        'garrafa térmica', 'calorimetria', 'equilíbrio térmico',
        'termodinâmica', 'entropia', 'máquina térmica',
        'cinemática', 'dinâmica', 'estática',
        'eletromagnetismo', 'campo elétrico', 'campo magnético',
        'circuito elétrico', 'resistência elétrica',
        'óptica', 'reflexão', 'refração',
        'ondas', 'frequência', 'amplitude',
        'gravitação', 'queda livre',
        'referencial inercial', 'referencial não inercial',
        'grandeza escalar', 'grandeza vetorial',
        'processo isotérmico', 'processo adiabático',
        'processo isobárico', 'processo isocórico',
        'calor sensível', 'calor latente',
        'carga elétrica', 'potencial elétrico', 'capacitância',
        'efeito fotoelétrico', 'efeito doppler',
        'dualidade onda-partícula',
        'mecânica', 'hidrostática', 'empuxo', 'arquimedes',
        'velocidade média', 'velocidade instantânea',
        'sentido do movimento', 'referencial',
        'sistema de unidades', 'unidade de medida',
        'lei de coulomb', 'transformador', 'gerador',
        'eletrólise', 'pilha galvânica',
        'relatividade', 'quântica', 'física moderna',
        'radioatividade', 'fissão', 'fusão',
        'semicondutor', 'transistor', 'diodo',
        'resistência elétrica', 'corrente elétrica',
        'tensão', 'voltagem', 'ampere', 'volt', 'ohm', 'watt', 'joule',
        'newton', 'pascal', 'hertz', 'baricentro',
        'temperatura', 'calor', 'pressão', 'volume', 'densidade',
        'força', 'massa', 'energia', 'trabalho', 'potência',
        'movimento', 'deslocamento', 'aceleração',
        'quilômetro', 'metro', 'segundo', 'kg', 'mol',
        'lei de newton', 'lei de ohm', 'princípio de arquimedes',
        'páscal', 'newton', 'joule', 'volt', 'ampere', 'ohm',
        'vat', 'hertz', 'coulomb', 'weber', 'tesla',
        'capacitor', 'indutor', 'resistor', 'diodo',
        'LED', 'fibra óptica', 'laser', 'espelho', 'lente',
        'prisma', 'espectro', 'interferência', 'difração',
        'polarização', 'absorção', 'emissão',
        'fissão nuclear', 'fusão nuclear', 'reator',
        'centrífuga', 'centrípeta', 'giroscópio',
        'pêndulo', 'oscilação', 'ressonância',
        'atrito', 'atrito estático', 'atrito dinâmico',
        'coeficiente de atrito', 'mola', 'constantes elásticas',
        'vetor', 'escalar', 'gráfico', 'tabela',
        'experimento', 'resultado', 'medida', 'incerteza',
        'erros sistemáticos', 'erros aleatórios',
        'eficiência', 'rendimento', 'potência',
        'friction', 'resistance',
    ],
    'historia': [
        'história', 'histórico', 'historico',
        'idade', 'média', 'medieval', 'medievo',
        'época', 'épocas', 'período', 'períodos',
        'século', 'século xx', 'século xix', 'século xvii', 'século xvi',
        'metade', 'primeira metade', 'segunda metade',
        'conflitos', 'conflito', 'violentos',
        'guerra', 'batalha', 'batalhas',
        'revolução', 'revoluções',
        'império', 'impérios',
        'colonial', 'colônia', 'colônias',
        'república', 'repúblicas',
        'ditadura', 'ditaduras',
        'golpe', 'golpes',
        'escravidão', 'escravos', 'escravo', 'trabalho escravo',
        'fazendas', 'fazendeiro', 'fazendeiros',
        'bloqueio', 'bloqueios', 'fiscalização', 'fiscalizações',
        'lista', 'listas',
        'tratado', 'acordo', 'declaração',
        'direitos', 'deveres',
        'independent', 'independência',
        'dom pedro', 'dominique',
        'tiradentes', 'inconfidência',
        'vargas', 'estado novo', 'getúlio',
        'café com leite', 'coronelismo',
        'guerra fria', 'bloco soviético', 'urss',
        'capitalismo', 'socialismo', 'comunismo',
        'fascismo', 'nazismo', 'liberalismo',
        'imperialismo', 'colonialismo', 'descolonização',
        'abolicionismo', 'escravatura',
        'reforma protestante', 'contrarreforma', 'inquisição',
        'expansão marítima', 'navegação', 'descobrimentos',
        'capitanias', 'capitanias hereditárias',
        'administração colonial',
        'revolução francesa', 'declaração dos direitos', 'bastilha',
        'liberdade igualdade fraternidade',
        'revolução industrial', 'mecanização',
        'regime militar', 'ditadura militar', 'ai-5',
        'república velha', 'política dos governadores',
        'primeira república', 'segunda república',
        'queda do muro', 'revolução de 1989', 'revolução cubana',
        'revolução mexicana', 'independência do brasil',
        'monarquia', 'feudalismo', 'absolutismo',
        'iluminismo', 'renascimento', 'descobrimentos',
        'moderna', 'contemporânea', 'contemporâneo',
        'antiga', 'antiguidade', 'clássico', 'clássicos',
        'contexto', 'interpretação',
        'poder', 'política', 'governo', 'estado',
        'nação', 'soberania', 'sociedade',
        'economia', 'mercado', 'comércio',
        'povo', 'povoação', 'população',
        'poder público', 'autoridade', 'lei',
        'constituição', 'constituinte',
        'documento', 'documentos',
        'memória', 'memórias',
        'herança', 'legado', 'passado',
        'presente', 'futuro', 'evolução',
        'progresso', 'desenvolvimento',
        'mudança', 'transformação',
        'epoca', 'epocas',
        'movimento', 'movimentos',
        'ideologia', 'ideologias',
        'nacionalismo', 'totalitarismo',
        'globalização', 'mundialização',
        'mundial', 'internacional',
        'ocidente', 'oriente', 'oriental',
        'orientalismo', 'orientalista',
        'moderno', 'modernidade',
        'pós-moderno', 'pós-modernidade',
        'contemporâneo', 'contemporaneidade',
        'atual', 'hoje', 'presente',
        'passado', 'recente', 'antigo',
        'antiguidade', 'idade antiga',
        'idade média', 'idade moderna', 'idade contemporânea',
        'renascimento', 'barroco', 'rococó',
        'parnasianismo', 'simbolismo', 'concretismo',
        'modernismo', 'naturalismo', 'realismo',
        'romantismo', 'arcadismo', 'clássico',
        'medieval', 'moderno', 'contemporâneo',
        'antigo', 'clássico',
        'interpretação', 'interpretações',
        'perspectiva', 'perspectivas',
        'contexto histórico',
        'memória histórica',
        'período histórico',
        'evento', 'eventos',
        'data', 'datas',
        'ano', 'anos',
        'século', 'séculos',
        'milênio', 'milênios',
        'era', 'eras',
        'tempo', 'tempos',
        'histórico', 'históricos',
        'relato', 'relatos',
        'narrativa', 'narrativas',
        'testemunho', 'testemunhos',
        'fonte', 'fontes',
        'registro', 'registros',
        'documentação',
        'pesquisa', 'pesquisas',
        'estudo', 'estudos',
        'análise', 'analises',
        'comparação', 'comparações',
        'correlação', 'correlações',
        'causalidade', 'causal',
        'consequência', 'consequências',
        'efeito', 'efeitos',
        'causa', 'causas',
        'motivo', 'motivos',
        'razão', 'razões',
        'justificativa', 'justificativas',
        'objetivo', 'objetivos',
        'meta', 'metas',
        'propósito', 'propósitos',
        'intenção', 'intenções',
        'planejamento', 'planejamentos',
        'organização', 'organizações',
        'instituição', 'instituições',
        'instituto', 'institutos',
        'museu', 'museus',
        'patrimônio', 'patrimônios',
        'memorial', 'memoriais',
        'escola', 'escolas',
        'universidade', 'universidades',
        'academia', 'academias',
        'educação', 'educações',
        'ensino', 'ensinos',
        'aprendizagem', 'aprendizagens',
        'conhecimento', 'conhecimentos',
        'saber', 'saberes',
        'ciência', 'ciências',
        'pesquisa',
        'investigação', 'investigações',
        'descoberta', 'descobertas',
        'invenção', 'invenções',
        'criação', 'criações',
        'desenvolvimento',
        'evolução', 'evoluções',
        'transformação',
        'mudança', 'mudanças',
        'inovação', 'inovações',
        'progresso',
        'crescimento',
        'expansão',
        'contração',
        'declínio',
        'ascensão',
        'queda',
        'colapso',
        'fragmentação',
        'unificação',
        'integração',
        'separação',
        'divisão',
        'concentração',
        'centralização',
        'descentralização',
        'autonomia',
        'soberania',
        'independência',
        'intervenção',
        'ocupação',
        'dominação',
        'submissão',
        'resistência',
        'rebelião',
        'insurgência',
        'revolta', 'revoltas',
        'revolução', 'revoluções',
        'movimento', 'movimentos',
        'protesto', 'protestos',
        'greve', 'greves',
        'ocupação',
        'piquete',
        'bloqueio', 'bloqueios',
        'manifestação', 'manifestações',
        'mobilização', 'mobilizações',
        'congregação',
        'assembleia',
        'congresso',
        'conferência',
        'cúpula',
        'cimeira',
        'encontro',
        'reunião',
        'debate',
        'discussão',
        'conversa',
        'diálogo',
        'negociação',
        'acordo', 'acordos',
        'tratado', 'tratados',
        'pacto', 'pactos',
        'convenção', 'convenções',
        'protocolo',
        'declaração', 'declarações',
        'documento', 'documentos',
        'atu', 'atos',
        'decreto', 'decretos',
        'lei', 'leis',
        'constituição', 'constituições',
        'emenda', 'emendas',
        'reforma', 'reformas',
        'alteração', 'alterações',
        'modificação', 'modificações',
        'mudança', 'mudanças',
        'transformação', 'transformações',
        'evolução', 'evoluções',
        'desenvolvimento', 'desenvolvimentos',
        'progresso', 'progressos',
        'crescimento', 'crescimentos',
        'expansão', 'expansões',
        'contração', 'contrações',
        'declínio', 'declínios',
        'ascensão', 'ascensões',
        'queda', 'quedas',
        'colapso', 'colapsos',
    ],
    'geografia': [
        'cartografia', 'escala cartográfica', 'projeção cartográfica',
        'fuso horário', 'linha do equador', 'meridiano', 'paralelo',
        'placa tectônica', 'bacia hidrográfica',
        'zoneamento ecológico', 'reserva legal',
        'unidade de conservação', 'parque nacional',
        'desertificação', 'degradação ambiental',
        'globalização', 'mundialização',
        'reforma agrária', 'latifúndio', 'minifúndio',
        'questão agrária', 'questão ambiental',
        'bioma', 'cerrado', 'caatinga', 'mata atlântica', 'amazônia',
        'semiárido', 'litoral', 'interior',
        'fronteira', 'divisa', 'limite',
        'clima', 'temperatura', 'chuva', 'seca',
        'região', 'nordeste', 'sudeste', 'sul', 'norte', 'centro-oeste',
        'população', 'migração', 'imigração',
        'urbanização', 'metrópole', 'cidade',
        'meio ambiente', 'desmatamento', 'poluição',
        'energia', 'petróleo', 'biocombustível',
        'transporte', 'ferrovia', 'porto', 'aeroporto',
        'mapa', 'escala', 'coordenada',
        'bloco econômico', 'mercosul', 'onu', 'fmi', 'omc',
        'desenvolvimento sustentável', 'sustentabilidade',
        'preservação', 'conservação',
        'agricultura', 'pecuária', 'mineração',
        'indústria', 'comércio', 'serviços',
        'relevo', 'planície', 'planalto', 'montanha',
        'vegetação', 'floresta', 'cerrado',
        'demografia', 'natalidade', 'mortalidade',
        'hidrografia', 'rio', 'lago', 'banhado', 'pântano',
        'geomorfologia', 'erosão', 'intemperismo',
        'solo', 'terra', 'argila', 'areia',
        'climatologia', 'tipos de clima', 'estações',
        'inverno', 'verão', 'outono', 'primavera',
        'economia', 'economias',
        'mercado', 'mercados',
        'comércio', 'comércios',
        'troca', 'trocas',
        'oferta', 'procura', 'demanda',
        'preço', 'preços',
        'valor', 'valores',
        'moeda', 'moedas',
        'dinheiro', 'dinheiro',
        'capital', 'capitais',
        'investimento', 'investimentos',
        'produção', 'produções',
        'produzir',
        'conservação', 'conservações',
        'destruição', 'destruições',
        'poluição', 'poluições',
        'degradação', 'degradações',
        'preservação', 'preservações',
        'proteção', 'proteções',
        'recurso', 'recursos',
        'energia', 'energias',
        'eletricidade', 'eletricidades',
        'petróleo', 'petróleos',
        'gás', 'gases',
        'carvão', 'carvões',
        'minério', 'minérios',
        'metal', 'metais',
        'não-metal', 'não-metais',
        'gas', 'gases',
        'combustível', 'combustíveis',
        'gasolina', 'diesel', 'etanol', 'álcool',
        'biodiesel', 'bioetanol',
        'hídrica', 'hídricas',
        'eólica', 'eólicas',
        'solar', 'solar',
        'nuclear', 'nucleares',
        'geotérmica', 'geotérmicas',
        'onda', 'ondas', 'onda de mar',
        'maré', 'marés',
        'corrente', 'correntes',
        'vento', 'ventos',
        'chuva', 'chuvas', 'precipitação', 'precipitações',
        'neve', 'neves', 'granizo',
        'granizo', 'tempestade', 'tempestades', 'tufão', 'furacão', 'ciclone',
        'seca', 'secas', 'enchente', 'inundação', 'inundações',
        'deslizamento', 'desmoronamento', 'desabamento',
        'terremoto', 'terremotos', 'sismo', 'tsunami',
        'fogo', 'fogo', 'queimada', 'queimadas', 'incêndio', 'incêndios',
        'desmatamento', 'desmatamentos', 'desmatar',
        'desmatar', 'derrubar', 'derrubadas', 'derrubar',
        'desmatamento florestal', 'desmatamento florestal',
        'desmatamento ilegal', 'desmatamento ilegal',
        'desmatamento autorizado', 'desmatamento autorizado',
        'reflorestamento', 'reflorestamentos', 'reflorestar', 'refloresta',
        'reflorestamento', 'reflorestamentos',
        'preservação', 'preservações', 'preservar', 'preserva',
        'conservação', 'conservações', 'conservar', 'conserva',
        'proteção', 'proteções', 'proteger', 'protege',
        'sustentabilidade', 'sustentabilidades',
        'desenvolvimento', 'desenvolvimentos', 'desenvolver', 'desenvolve',
        'crescimento', 'crescimentos', 'crescer', 'cresce',
        'expansão', 'expansões', 'expandir', 'expande',
        'redução', 'reduções', 'reduzir', 'reduz',
        'aumento', 'aumentos', 'aumentar', 'aumenta',
        'diminuição', 'diminuições', 'diminuir', 'diminui',
        'melhoria', 'melhorias', 'melhorar', 'melhora',
        'piora', 'piores', 'aggravamento', 'aggravations',
        'degradação', 'degradações', 'degradar', 'degrada',
        'poluição', 'poluições', 'poluir', 'polui',
        'contaminação', 'contaminações', 'contaminar', 'contamina',
        'doença', 'doenças', 'doente', 'doentes',
        'doença', 'doenças',
        'saúde', 'saúde', 'saúde pública', 'saúde públicas',
        'epidemia', 'epidemias', 'pandemia', 'pandemias',
        'enfermidade', 'enfermidades',
        'doença', 'doenças',
        'sintoma', 'sintomas',
        'tratamento', 'tratamentos', 'tratar', 'trata',
        'cura', 'curas', 'curar', 'cura',
        'prevenção', 'prevenções', 'prevenir', 'previne',
        'vacina', 'vacinas', 'vacinação', 'vacinação',
        'imunização', 'imunizações', 'imunizar', 'imuniza',
        'vacinação', 'vacinação',
        'imunização', 'imunizações',
        'vacina', 'vacinas',
        'epidemia', 'epidemias', 'pandemia', 'pandemias',
        'doença', 'doenças',
        'saúde', 'saúde',
        'enfermidade', 'enfermidades',
        'cura', 'curas',
        'prevenção', 'prevenções',
        'tratamento', 'tratamentos',
        'medicina', 'medicinas',
        'hospital', 'hospitais',
        'clínica', 'clínicas',
        'consulta', 'consultas',
        'exame', 'exames',
        'diagnóstico', 'diagnósticos', 'diagnosticar', 'diagnosticar',
        'cirurgia', 'cirurgias', 'operar', 'opera',
        'medicação', 'medicações', 'medicar', 'medica',
        'remédio', 'remédios', 'remediar', 'remediar',
        'droga', 'drogas', 'drogaria', 'drogarias',
        'fármaco', 'fármacos',
        'composto', 'compostos',
        'substância', 'substâncias',
        'elemento', 'elementos',
        'composto', 'compostos',
        'molécula', 'moléculas',
        'átomo', 'átomos',
        'próton', 'prótons', 'elétron', 'elétrons', 'nêutron', 'nêutrons',
        'núcleo', 'núcleos',
        'partícula', 'partículas',
        'quark', 'quarks',
        'antimateria', 'antimateria',
        'matéria', 'matéria', 'matérias',
        'energia', 'energias',
        'calor', 'calores',
        'temperatura', 'temperaturas',
        'grau', 'graus',
        'escala', 'escalas',
        'zero absoluto', 'zero absoluto',
        'fervura', 'fervura', 'ebulição', 'ebulições',
        'fusão', 'fusões', 'solidificação', 'solidificações',
        'evaporação', 'evaporações', 'condensação', 'condensações',
        'sublimação', 'sublimações', 'deposição', 'deposições',
        'vapor', 'vapores', 'gás', 'gases', 'líquido', 'líquidos', 'sólido', 'sólidos',
        'estado', 'estados',
        'muda', 'mudanças de estado',
        'transição', 'transições',
        'equilíbrio', 'equilíbrios', 'equilíbrio térmico', 'equilíbrio térmicos',
        'processo', 'processos', 'processos físicos',
        'transformação', 'transformações', 'transformação física', 'transformações físicas',
        'reação', 'reações', 'reação física', 'reações físicas',
        'velocidade', 'velocidades', 'velocímetro',
        'aceleração', 'acelerações', 'acelerômetro',
        'deslocamento', 'deslocamentos', 'deslocar', 'desloca',
        'trajetória', 'trajetórias',
        'mobilidade', 'mobilidades',
        'mover', 'movimento', 'movimentos',
        'mover',
        'deslocamento',
        'trajetória',
        'referência', 'referências', 'referencial', 'referenciais',
        'sistema', 'sistemas', 'sistema de referência', 'sistemas de referência',
        'coordenada', 'coordenadas', 'eixo', 'eixos',
        'eixo', 'eixos', 'plano', 'planos', 'plano cartesiano',
        'ponto', 'pontos', 'linha', 'linhas', 'reta', 'retas',
        'ângulo', 'ângulos', 'grau', 'graus', 'radiano', 'radianos',
        'direção', 'direções', 'sentido', 'sentidos',
        'vetor', 'vetores', 'escalar', 'escalares',
        'gráfico', 'gráficos', 'tabela', 'tabelas',
        'resultado', 'resultados', 'medida', 'medidas',
        'experimento', 'experimentos', 'experimento científico', 'experimentos científicos',
        'observação', 'observações', 'observar', 'observa',
        'hipótese', 'hipóteses', 'hipotetizar', 'hipotetiza',
        'teoría', 'teorias', 'teoria', 'teorias',
        'lei', 'leis', 'lei física', 'leis físicas',
        'modelo', 'modelos', 'modelagem', 'modelagens',
        'simulação', 'simulações',
        'cálculo', 'cálculos', 'calcular', 'calcula',
        'equação', 'equações', 'equação física', 'equações físicas',
        'fórmula', 'fórmulas', 'fórmula matemática', 'fórmulas matemáticas',
        'constante', 'constantes', 'constante física', 'constantes físicas',
        'variável', 'variáveis', 'variável física', 'variáveis físicas',
        'gráfico', 'gráficos',
        'tabela', 'tabelas',
        'eixo', 'eixos',
        'ponto', 'pontos',
        'coordenada', 'coordenadas',
        'eixo', 'eixos',
        'linha', 'linhas',
        'ponto', 'pontos',
        'curva', 'curvas',
        'linha', 'linhas',
        'inclinação', 'inclinações',
        'declive', 'declives',
        'coeficiente', 'coeficientes',
        'angular', 'angulares',
        'linear', 'lineares',
        'quadrática', 'quadráticas',
        'exponencial', 'exponenciais',
        'logarítmica', 'logarítmicas',
        'trigonométrica', 'trigonométricas',
        'função', 'funções',
        'gráfico', 'gráficos',
        'domínio', 'domínios',
        'imagem', 'imagens',
        'contradomínio', 'contradomínios',
        'codomínio', 'codomínios',
        'conjunto', 'conjuntos',
        'conjunto dos reais', 'conjuntos dos reais',
        'conjunto dos naturais', 'conjuntos dos naturais',
        'conjunto dos inteiros', 'conjuntos dos inteiros',
        'conjunto dos racionais', 'conjuntos dos racionais',
        'conjunto dos irracionais', 'conjuntos dos irracionais',
        'intervalo', 'intervalos',
        'intervalo aberto', 'intervalos abertos',
        'intervalo fechado', 'intervalos fechados',
        'semiaberto', 'semiabertos',
        'inclusive', 'inclusivo',
        'exclusive', 'exclusivo',
        'número', 'números',
        'número real', 'números reais',
        'número complexo', 'números complexos',
        'número imaginário', 'números imaginários',
        'número racional', 'números racionais',
        'número irracional', 'números irracionais',
        'número inteiro', 'números inteiros',
        'número natural', 'números naturais',
        'número primo', 'números primos',
        'número composto', 'números compostos',
        'fator', 'fatores', 'fatoração', 'fatoresação',
        'divisor', 'divisores',
        'múltiplo', 'múltiplos',
        'mmc', 'mdc',
        'porcentagem', 'porcentagens', 'percentual', 'percentuais',
        'porcento', 'porcentos',
        'percentual', 'percentuais',
        'proporção', 'proporções', 'proporcional', 'proporcionais',
        'regra de três', 'regra de três simples', 'regra de três composta',
        'juros', 'juros simples', 'juros compostos',
        'taxa', 'taxas', 'taxa de juros', 'taxas de juros',
        'tempo', 'tempos', 'tempo decorrido', 'tempos decorridos',
        'capital', 'capitais',
        'montante', 'montantes',
        'rendimento', 'rendimentos',
        'lucro', 'lucros', 'prejuízo', 'prejuízos',
        'desconto', 'descontos', 'descontar', 'desconta',
        'acrescimo', 'acréscimos', 'acrescentar', 'acrescenta',
        'porcentagem', 'porcentagens',
        'porcento', 'porcentos',
        'percentual', 'percentuais',
        'razão', 'razões', 'razão entre', 'razões entre',
        'proporção', 'proporções', 'proporcional', 'proporcionais',
        'proporcionalidade', 'proporcionalidades',
        'direta', 'diretas', 'inversa', 'inversas',
        'variação', 'variações',
        'constante', 'constantes',
        'variável', 'variáveis',
        'gráfico', 'gráficos',
        'tabela', 'tabelas',
        'representação', 'representações',
        'visualização', 'visualizações',
        'gráfico de barras', 'gráfico de barras',
        'gráfico de linhas', 'gráfico de linhas',
        'gráfico de pizza', 'gráfico de pizza',
        'histograma', 'histogramas',
        'gráfico', 'gráficos',
        'tabela', 'tabelas',
        'diagrama', 'diagramas',
        'pictograma', 'pictogramas',
        'mapa', 'mapas',
        'gráfico', 'gráficos',
        'tabela', 'tabelas',
        'estatística', 'estatísticas', 'estatístico', 'estatísticos',
        'média', 'médias', 'mediana', 'medianas', 'moda', 'modas',
        'desvio padrão', 'desvios padrão', 'variância', 'variâncias',
        'amplitude', 'amplitudes',
        'frequência', 'frequências',
        'probabilidade', 'probabilidades',
        'estocástico', 'estocásticos',
        'aleatório', 'aleatórios',
        'sorteio', 'sorteios',
        'loteria', 'loterias',
        'jogo', 'jogos',
        'dado', 'dados',
        'moeda', 'moedas',
        'baralho', 'baralhos',
        'evento', 'eventos',
        'espaço amostral', 'espaços amostrais',
        'resultado', 'resultados',
        'experimento', 'experimentos',
        'árvore de decisão', 'árvores de decisão',
        'tabela de frequência', 'tabelas de frequência',
        'gráfico de frequência', 'gráficos de frequência',
        'diagrama', 'diagramas',
        'pictograma', 'pictogramas',
        'mapa', 'mapas',
        'gráfico', 'gráficos',
        'tabela', 'tabelas',
        'estatística', 'estatísticas',
        'média', 'médias',
        'mediana', 'medianas',
        'moda', 'modas',
        'desvio padrão', 'desvios padrão',
        'variância', 'variâncias',
        'amplitude', 'amplitudes',
        'frequência', 'frequências',
        'probabilidade', 'probabilidades',
        'evento', 'eventos',
        'espaço amostral', 'espaços amostrais',
        'resultado', 'resultados',
        'experimento', 'experimentos',
        'probabilidade clássica', 'probabilidade frequencista',
        'evento certo', 'evento impossível', 'evento aleatório',
        'evento independente', 'evento dependente',
        'permutação', 'permutações', 'arranjo', 'arranjos', 'combinação', 'combinações',
        'princípio fundamental', 'princípios fundamentais',
        'regra do produto', 'regras do produto',
        'regra da soma', 'regras da soma',
        'árvore de decisão', 'árvores de decisão',
        'tabela de frequência', 'tabelas de frequência',
        'experimento aleatório', 'experimentos aleatórios',
        'sorteio', 'sorteios',
        'loteria', 'loterias',
        'jogo de dados', 'jogos de dados',
        'baralho', 'baralhos',
        'moeda', 'moedas',
        'probabilidade condicional', 'probabilidades condicionais',
        'teorema de bayes', 'teoremas de bayes',
        'distribuição binomial', 'distribuições binomiais',
        'distribuição normal', 'distribuições normais',
    ],
    'geografia': [
        'cartografia', 'escala cartográfica', 'projeção cartográfica',
        'fuso horário', 'linha do equador', 'meridiano', 'paralelo',
        'placa tectônica', 'bacia hidrográfica',
        'zoneamento ecológico', 'reserva legal',
        'unidade de conservação', 'parque nacional',
        'desertificação', 'degradação ambiental',
        'globalização', 'mundialização',
        'reforma agrária', 'latifúndio', 'minifúndio',
        'questão agrária', 'questão ambiental',
        'bioma', 'cerrado', 'caatinga', 'mata atlântica', 'amazônia',
        'semiárido', 'litoral', 'interior',
        'fronteira', 'divisa', 'limite',
        'clima', 'temperatura', 'chuva', 'seca',
        'região', 'nordeste', 'sudeste', 'sul', 'norte', 'centro-oeste',
        'população', 'migração', 'imigração',
        'urbanização', 'metrópole', 'cidade',
        'meio ambiente', 'desmatamento', 'poluição',
        'energia', 'petróleo', 'biocombustível',
        'transporte', 'ferrovia', 'porto', 'aeroporto',
        'mapa', 'escala', 'coordenada',
        'bloco econômico', 'mercosul', 'onu', 'fmi', 'omc',
        'desenvolvimento sustentável', 'sustentabilidade',
        'preservação', 'conservação',
        'agricultura', 'pecuária', 'mineração',
        'indústria', 'comércio', 'serviços',
        'relevo', 'planície', 'planalto', 'montanha',
        'vegetação', 'floresta',
        'demografia', 'natalidade', 'mortalidade',
        'hidrografia', 'rio', 'lago', 'bacia',
        'geomorfologia', 'erosão', 'intemperismo',
        'solo', 'terra', 'argila', 'areia',
        'climatologia', 'estações do ano', 'inverno', 'verão', 'outono', 'primavera',
        'economia', 'economias', 'mercado', 'comércio',
        'moeda', 'capital', 'investimento', 'produção',
        'poluição', 'degradação', 'desmatamento',
        'preservação', 'conservação', 'sustentabilidade',
        'recurso', 'recursos', 'energia', 'petróleo',
        'gasolina', 'etanol', 'biodiesel',
        'biodiversidade', 'conservação', 'extinção',
        'desmatamento', 'poluição', 'aquecimento', 'efeito estufa',
        'mudanças climáticas', 'aquecimento global', 'degelo',
        'inundação', 'enchente', 'seca', 'deserto',
        'frente fria', 'frente quente', 'massa de ar', 'ciclone',
        'tufão', 'furacão', 'torrente', 'chuva', 'granizo',
        'neve', 'geada', 'frost', 'congelamento',
        'geologia', 'rocas', 'minérios',
        'mineração', 'extração', 'petróleo',
        'gás natural', 'carvão mineral', 'energia nuclear',
        'hidrelétrica', 'eólica', 'solar', 'geotérmica',
        'biocombustível', 'etanol', 'biodiesel',
        'transporte', 'ferrovia', 'porto', 'aeroporto',
        'rodovia', 'rodovias', 'estrada', 'estradas',
        'navio', 'navios', 'naval', 'marítimo',
        'aéreo', 'aéreos', 'avião', 'aviões',
        'metrô', 'metrôs', 'metropolitano', 'metropolitanos',
        'ônibus', 'ônibus', 'veículo', 'veículos',
        'carro', 'carros', 'automóvel', 'automóveis',
        'caminhão', 'caminhões', 'caminhoneiro', 'caminhoneiros',
        'motocicleta', 'motocicletas', 'moto', 'motos',
        'bicicleta', 'bicicletas', 'biciclista', 'biciclistas',
        'a pé', 'pedestre', 'pedestres',
        'navio', 'navios', 'naval', 'marítimo',
        'porto', 'portos', 'terminal', 'terminais',
        'aeroporto', 'aeroportos', 'aeródromo', 'aeródromos',
        'mapa', 'mapas', 'cartografia', 'cartografias',
        'escala', 'escalas', 'projeção', 'projeções',
        'coordenada', 'coordenadas', 'meridiano', 'paralelo',
        'latitude', 'latitudes', 'longitude', 'longitudes',
        'fuso horário', 'fusos horários',
        'time zone', 'time zones', 'GMT', 'UTC',
        'linha do equador', 'equador', 'linhas equatoriais',
        'trópico de câncer', 'trópico de capricórnio', 'círculo polar',
        'clima', 'climas', 'temperatura', 'temperaturas',
        'chuva', 'chuvas', 'precipitação', 'precipitações',
        'umidade', 'umidades', 'humedade', 'humedades',
        'seca', 'secas', 'aridez', 'aridezes',
        'umidade relativa', 'umidades relativas',
        'vento', 'ventos', 'direção do vento', 'direções do vento',
        'velocidade do vento', 'velocidades do vento',
        'rajada', 'rajadas', 'borrasca', 'borrascas',
        'tempestade', 'tempestades', 'tufão', 'furacão', 'ciclone',
        'huracán', 'huracanes', 'ciclone', 'ciclones',
        'massa de ar', 'massas de ar', 'fronte', 'frontes',
        'frente fria', 'frentes frias', 'frente quente', 'frentes quentes',
        'frente estacionária', 'frentes estacionárias',
        'el nino', 'el niño', 'la niña', 'la niña',
        'oscilação', 'oscilações', 'oscilação del sur',
        'oásis', 'oásis', 'deserto', 'desertos',
        'savana', 'savanas', 'estepe', 'estepes', 'pradaria', 'pradarias',
        'taiga', 'taigas', 'tundra', 'tundras',
        'floresta tropical', 'florestas tropicais', 'selva', 'selvas',
        'mata atlântica', 'matas atlânticas', 'floresta', 'florestas',
        'cerrado', 'cerrados', 'caatinga', 'caatingas',
        'pampa', 'pampas', 'patagônia', 'patagônias',
        'amazônia', 'amazônias', 'floresta amazônica', 'florestas amazônicas',
        'bioma', 'biomas', 'ecossistema', 'ecossistemas',
        'ecologia', 'ecologias',
        'desmatamento', 'desmatamentos', 'reflorestamento', 'reflorestamentos',
        'preservação', 'preservações', 'conservação', 'conservações',
        'sustentabilidade', 'sustentabilidades', 'desenvolvimento sustentável',
        'poluição', 'poluições', 'contaminação', 'contaminações',
        'degradação', 'degradações', 'desgaste', 'desgastes',
        'aquecimento global', 'aquecimentos globais', 'efeito estufa',
        'mudanças climáticas', 'mudança climática', 'mudanças',
        'emissões', 'emissão', 'gases', 'gases de efeito estufa',
        'co2', 'co2', 'carbono', 'carbonos',
        'metano', 'metanos', 'óxido nitroso', 'gás nitroso',
        'ozônio', 'ozônios', 'camada de ozônio',
        'chuva ácida', 'chuvas ácidas', 'smog', 'smogs',
        'poluição do ar', 'poluição do ar', 'poluição da água', 'poluição das águas',
        'poluição do solo', 'poluição do solo', 'poluição sonora', 'poluição sonora',
        'resíduos', 'resíduos', 'lixo', 'lixos', 'refugo', 'refugos',
        'reciclagem', 'reciclagens', 'reutilização', 'reutilizações',
        'redução', 'reduções', 'rejeito', 'rejeitos',
        'aterro', 'aterros', 'lixão', 'lixões',
        'compostagem', 'compostagens', 'compostar',
        'tratamento de resíduos', 'tratamentos de resíduos',
        'descarte', 'descartes', 'descartar',
        'coleta seletiva', 'coletas seletivas', 'seletividade',
        'conservação', 'conservações', 'preservação', 'preservações',
        'proteção', 'proteções', 'defesa', 'defesas',
        'recurso', 'recursos', 'recursos naturais',
        'energia', 'energias', 'energia renovável', 'energias renováveis',
        'energia não renovável', 'energias não renováveis',
        'petróleo', 'petróleos', 'gás natural', 'gás natural',
        'carvão mineral', 'carvões minerais', 'minério', 'minérios',
        'urânio', 'úrânios', 'energia nuclear', 'energias nucleares',
        'hídrica', 'hídricas', 'hidrelétrica', 'hidrelétricas',
        'eólica', 'eólicas', 'solar', 'solar', 'geotérmica', 'geotérmicas',
        'biocombustível', 'biocombustíveis', 'etanol', 'álcool',
        'biodiesel', 'biodiesel', 'óleo vegetal', 'óleos vegetais',
        'hidrogênio', 'hidrogênios', 'célula a combustível',
        'energia maremotriz', 'energia das marés', 'energia das ondas',
        'transporte', 'transportes', 'ferrovia', 'ferrovias',
        'rodovia', 'rodovias', 'porto', 'portos', 'aeroporto', 'aeroportos',
        'navio', 'navios', 'avião', 'aviões', 'ônibus', 'ônibus',
        'metrô', 'metrôs', 'metropolitano', 'metropolitanos',
        'caminhão', 'caminhões', 'carro', 'carros', 'moto', 'motos',
        'bicicleta', 'bicicletas', 'a pé', 'a pé',
        'trânsito', 'trânsitos', 'engarrafamento', 'engarrafamentos',
        'pedágio', 'pedágios', 'pedágio eletrônico',
        'sistema', 'sistemas', 'sistema viário', 'sistemas viários',
        'sinalização', 'sinalizações', 'sinal', 'sinais',
        'trânsito', 'trânsitos', 'semáforo', 'semáforos',
        'zoonoses', 'zoonoses', 'doenças', 'doenças',
        'saúde', 'saúde', 'saúde pública', 'saúde públicas',
        'epidemia', 'epidemias', 'pandemia', 'pandemias',
        'higiene', 'higiene', 'higiene pública', 'higiene públicas',
        'saneamento', 'saneamentos', 'saneamento básico', 'saneamentos básicos',
        'água', 'águas', 'água potável', 'águas potáveis',
        'esgoto', 'esgotos', 'tratamento de esgoto', 'tratamentos de esgoto',
        'dessaltoamento', 'dessaltoamentos', 'dessalinização', 'dessalinizações',
        'captação', 'captações', 'abastecimento', 'abastecimentos',
        'distribuição', 'distribuições', 'consumo', 'consumos',
        'corte', 'cortes', 'racionamento', 'racionamentos',
        'economia', 'economias', 'economia circular', 'economias circulares',
        'economia verde', 'economias verdes', 'economia de base',
        'economia solidária', 'economias solidárias',
        'comércio', 'comércios', 'comércio internacional', 'comércios internacionais',
        'exportação', 'exportações', 'importação', 'importações',
        'balança comercial', 'balanças comerciais', 'saldo', 'saldos',
        'tarifa', 'tarifas', 'tarifa aduaneira', 'tarifas aduaneiras',
        'bloco econômico', 'blocos econômicos', 'integração', 'integrações',
        'mercosul', 'mercosul', 'union europeia', 'união europeia',
        'onu', 'onu', 'fmi', 'fmi', 'omc', 'omc', 'banco mundial', 'bancos mundiais',
        'organização', 'organizações', 'organizações internacionais',
        'acordo', 'acordos', 'tratado', 'tratados', 'convenção', 'convenções',
        'diplomacia', 'diplomacias', 'relações internacionais',
        'poder', 'poderes', 'poder político', 'poderes políticos',
        'estado', 'estados', 'nação', 'nações',
        'governo', 'governos', 'política', 'políticas',
        'democracia', 'democracias', 'autoritarismo', 'autoritarismos',
        'totalitarismo', 'totalitarismos', 'dictadura', 'ditaduras',
        'regime', 'regimes', 'regime político', 'regimes políticos',
        'monarquia', 'monarquias', 'república', 'repúblicas',
        'constituição', 'constituições', 'constituinte', 'constituintes',
        'emenda', 'emendas', 'reforma', 'reformas',
        'partido', 'partidos', 'eleição', 'eleições', 'voto', 'votos',
        'sufrágio', 'sufrágios', 'candidato', 'candidatos',
        'câmara', 'câmaras', 'senado', 'senados', 'deputado', 'deputados',
        'prefeito', 'prefeitos', 'governador', 'governadores',
        'presidente', 'presidentes', 'presidência', 'presidências',
        'ministro', 'ministros', 'ministério', 'ministérios',
        'secretaria', 'secretarias', 'secretário', 'secretários',
        'política pública', 'políticas públicas', 'políticas', 'públicas',
        'gestão', 'gestões', 'administração', 'administrações',
        'governança', 'governancas', 'governo eletrônico', 'governo eletrônicos',
        'participação', 'participações', 'cidadania', 'cidadanias',
        'direitos', 'direitos humanos', 'deveres', 'deveres humanos',
        'sociedade', 'sociedades', 'população', 'populações',
        'demografia', 'demografias', 'natalidade', 'natalidades',
        'mortalidade', 'mortalidades', 'esperança de vida', 'esperanças de vida',
        'migratório', 'migratórios', 'migração', 'migrações',
        'imigração', 'imigrações', 'emigração', 'emigrações',
        'refugiado', 'refugiados', 'refúgio', 'refúgios',
        'deslocamento', 'deslocamentos', 'deslocado', 'deslocados',
        'urbano', 'urbanos', 'urbana', 'urbanas',
        'cidade', 'cidades', 'metrópole', 'metrópoles',
        'metropolitanidade', 'metropolitanidades', 'urbanização', 'urbanizações',
        'periurbano', 'periurbanos', 'periurbanas',
        'subúrbio', 'subúrbios', 'subúrbia', 'subúrbias',
        'centro', 'centros', 'periferia', 'periferias', 'periférico', 'periféricos',
        'megalópole', 'megalópoles', 'conurbação', 'conurbações',
        'aglomeração', 'aglomerações', 'polinúcleo', 'polinúcleos',
        'rede urbana', 'redes urbanas', 'hierarquia urbana',
        'zona urbana', 'zonas urbanas', 'zona rural', 'zonas rurais',
        'área urbana', 'áreas urbanas', 'área rural', 'áreas rurais',
        'densidade demográfica', 'densidades demográficas', 'população', 'populações',
        'crescimento', 'crescimentos', 'crescimento populacional',
        'declínio', 'declínios', 'declínio populacional',
        'taxa', 'taxas', 'taxa de natalidade', 'taxas de natalidade',
        'taxa de mortalidade', 'taxas de mortalidade', 'taxa de migração',
        'pirâmide', 'pirâmides', 'pirâmide etária', 'pirâmides etárias',
        'estrutura', 'estruturas', 'estrutura etária', 'estruturas etárias',
        'faixa', 'faixas', 'faixa etária', 'faixas etárias',
        'grupo', 'grupos', 'grupo etário', 'grupos etários',
        'idade', 'idades', 'idade média', 'idades médias',
        'jovens', 'adolescente', 'adolescentes', 'adulto', 'adultos',
        'idoso', 'idosos', 'idosos', 'terceira idade', 'terceira idade',
        'infância', 'infâncias', 'criança', 'crianças',
        'população economicamente ativa', 'populações economicamente ativas', 'PEA', 'PEAs',
        'população economicamente inativa', 'populações economicamente inativas', 'PEI', 'PEIs',
        'trabalho', 'trabalhos', 'ocupação', 'ocupações',
        'emprego', 'empregos', 'desemprego', 'desempregos', 'subemprego', 'subempregos',
        'informal', 'informais', 'formal', 'formais',
        'setor', 'setores', 'setor primário', 'setores primários',
        'setor secundário', 'setores secundários', 'setor terciário', 'setores terciários',
        'agricultura', 'agriculturas', 'pecuária', 'pecuárias',
        'lavoura', 'lavouras', 'colheita', 'colheitas', 'plantio', 'plantios',
        'monocultura', 'monoculturas', 'policultura', 'policulturas',
        'rotação', 'rotações', 'cultivo', 'cultivos',
        'pecuária', 'pecuárias', 'gado', 'gado', 'lavoura', 'lavouras',
        'mineração', 'minerações', 'extração', 'extrações',
        'indústria', 'indústrias', 'manufatura', 'manufaturas',
        'fabricação', 'fabricações', 'produção', 'produções',
        'comércio', 'comércios', 'serviços', 'serviços',
        'terciário', 'terciários', 'serviços', 'serviços',
        'tecnologia', 'tecnologias', 'inovação', 'inovações',
        'pesquisa', 'pesquisas', 'desenvolvimento', 'desenvolvimentos',
        'ciência', 'ciências', 'conhecimento', 'conhecimentos',
        'educação', 'educações', 'ensino', 'ensinos',
        'escola', 'escolas', 'universidade', 'universidades',
        'alfabetização', 'alfabetizações', 'letramento', 'letramentos',
        'escolaridade', 'escolaridades', 'instrução', 'instruções',
        'formação', 'formações', 'capacitação', 'capacitações',
        'treinamento', 'treinamentos', 'capacitação', 'capacitações',
        'qualificação', 'qualificações', 'requalificação', 'requalificações',
        'especialização', 'especializações', 'graduação', 'graduações',
        'mestrado', 'mestrados', 'doutorado', 'doutorados', 'phd',
        'pesquisa', 'pesquisas', 'extensão', 'extensões',
        'cultura', 'culturas', 'identidade', 'identidades',
        'patrimônio', 'patrimônios', 'memória', 'memórias', 'história', 'histórias',
        'patrimônio material', 'patrimônios materiais', 'patrimônio imaterial', 'patrimônios imateriais',
        'tradição', 'tradições', 'tradicional', 'tradicionais',
        'folclore', 'folclores', 'cultura popular', 'culturas populares',
        'festa', 'festas', 'festividade', 'festividades', 'festa junina', 'festas juninas',
        'carnaval', 'carnavais', 'réveillon', 'réveillons', 'natal', 'natais',
        'páscoa', 'páscoas', 'dia das mães', 'dias das mães', 'dia dos pais', 'dias dos pais',
        'alimentação', 'alimentações', 'alimento', 'alimentos',
        'gastronomia', 'gastronomias', 'culinária', 'culinárias',
        'receita', 'receitas', 'cozinha', 'cozinhas', 'culinária', 'culinárias',
        'moda', 'modas', 'vestuário', 'vestuários', 'roupa', 'roupas',
        'música', 'músicas', 'canto', 'cantos', 'dança', 'danças',
        'teatro', 'teatros', 'arte', 'artes', 'pintura', 'pinturas',
        'escultura', 'esculturas', 'literatura', 'literaturas', 'escrita', 'escritas',
        'escritor', 'escritores', 'autor', 'autores', 'poeta', 'poetas',
        'obra', 'obras', 'obra de arte', 'obras de arte', 'arte', 'artes',
        'artista', 'artistas', 'artífice', 'artífices', 'criador', 'criadores',
        'criação', 'criações', 'invenção', 'invenções', 'inovação', 'inovações',
        'patrimônio', 'patrimônios', 'patrimônio cultural', 'patrimônios culturais',
        'patrimônio histórico', 'patrimônios históricos', 'patrimônio material', 'patrimônios materiais',
        'patrimônio imaterial', 'patrimônios imateriais',
        'museu', 'museus', 'museologia', 'museologias', 'acervo', 'acervos',
        'exposição', 'exposições', 'expor', 'expõe', 'mostra', 'mostras',
        'galeria', 'galerias', 'exposição', 'exposições',
        'artista', 'artistas', 'artista plástico', 'artistas plásticos',
        'escultor', 'escultores', 'pintor', 'pintores',
        'escritor', 'escritores', 'escritora', 'escritoras', 'poeta', 'poetas',
        'filósofo', 'filósofos', 'filósofa', 'filósofas', 'filosofia', 'filosofias',
        'pensamento', 'pensamentos', 'pensador', 'pensadores',
        'ideia', 'ideias', 'ideia filosófica', 'ideias filosóficas',
        'filosofia', 'filosofias', 'pensador', 'pensadores',
        'pensamento filosófico', 'pensamentos filosóficos',
        'filosofia antiga', 'filosofias antigas', 'filosofia medieval', 'filosofias medievais',
        'filosofia moderna', 'filosofias modernas', 'filosofia contemporânea', 'filosofias contemporâneas',
        'racionalismo', 'racionalismos', 'empirismo', 'empirismos',
        'idealismo', 'idealismos', 'materialismo', 'materialismos',
        'realismo', 'realismos', 'nominalismo', 'nominalismos',
        'dualismo', 'dualismos', 'monismo', 'monismos',
        'cosmologia', 'cosmologias', 'ontologia', 'ontologias',
        'epistemologia', 'epistemologias', 'metafísica', 'metafísicas',
        'lógica', 'lógicas', 'ética', 'éticas', 'estética', 'estéticas',
        'política', 'políticas', 'filosofia política', 'filosofias políticas',
        'sócrates', 'sócrates', 'platão', 'platões', 'aristóteles', 'aristóteles',
        'descartes', 'descartes', 'kant', 'kantes', 'hegel', 'hegeles',
        'marx', 'marxes', 'nietzsche', 'nietzsches', 'sartre', 'sartres', 'foucault', 'foucaults',
        'existencialismo', 'existencialismos', 'materialismo histórico', 'materialismos históricos',
        'alienação', 'alienações', 'ideologia', 'ideologias',
        'consciência', 'consciências', 'consciência de classe', 'consciências de classe',
        'falsidade', 'falsidades', 'falsa consciência', 'falsas consciências',
        'dialética', 'dialéticas', 'dialética materialista', 'dialéticas materialistas',
        'contradição', 'contradições', 'contraditório', 'contraditórios',
        'unidade', 'unidades', 'luta', 'lutas', 'luta de classes', 'lutas de classes',
        'superação', 'superações', 'superação', 'superações',
        'praxe', 'práticas', 'prática', 'práticas', 'práxis', 'práxis',
        'trabalho', 'trabalhos', 'trabalho humano', 'trabalhos humanos',
        'força de trabalho', 'forças de trabalho', 'trabalhador', 'trabalhadores',
        'proletariado', 'proletariados', 'burguesia', 'burguesias',
        'capital', 'capitais', 'capitalismo', 'capitalismos',
        'mercadoria', 'mercadorias', 'valor de uso', 'valores de uso',
        'valor de troca', 'valores de troca', 'mais-valia', 'mais-valias',
        'expropriação', 'expropriações', 'expropriar', 'expropria',
        'acumulação', 'acumulações', 'acumular', 'acumula',
        'reprodução', 'reproduções', 'reproduzir', 'reproduz',
        'mão de obra', 'mãos de obra', 'força de trabalho', 'forças de trabalho',
        'organização', 'organizações', 'organização do trabalho', 'organizações do trabalho',
        'divisão do trabalho', 'divisões do trabalho', 'especialização', 'especializações',
        'máquina', 'máquinas', 'máquinas industriais', 'máquinas industriais',
        'tecnologia', 'tecnologias', 'revolução tecnológica', 'revoluções tecnológicas',
        'automação', 'automações', 'robotização', 'robotizações',
        'inteligência artificial', 'inteligências artificiais', 'ia', 'ias',
        'computador', 'computadores', 'computação', 'computações',
        'informática', 'informáticas', 'tecnologia da informação', 'tecnologias da informação',
        'internet', 'internets', 'rede', 'redes', 'rede mundial', 'redes mundiais',
        'digital', 'digitais', 'digitalização', 'digitalizações',
        'informação', 'informações', 'dados', 'dados', 'banco de dados', 'bancos de dados',
        'memória', 'memórias', 'memória RAM', 'memórias RAM',
        'disco', 'discos', 'armazenamento', 'armazenamentos',
        'processamento', 'processamentos', 'processador', 'processadores',
        'software', 'softwares', 'programa', 'programas', 'programação', 'programações',
        'algoritmo', 'algoritmos', 'código', 'códigos', 'código-fonte', 'códigos-fonte',
        'linguagem de programação', 'linguagens de programação',
        'compilador', 'compiladores', 'interpretador', 'interpretadores',
        'sistema operacional', 'sistemas operacionais', 'so', 'sos',
        'linux', 'linux', 'windows', 'windows', 'macos', 'macos', 'android', 'androids', 'ios', 'ioss',
        'hardware', 'hardwares', 'software', 'softwares',
        'periférico', 'periféricos', 'periférico de entrada', 'periféricos de entrada',
        'periférico de saída', 'periféricos de saída',
        'mouse', 'mouses', 'teclado', 'teclados', 'monitor', 'monitores', 'impressora', 'impressoras',
        'rede local', 'redes locais', 'lan', 'lans', 'rede de área ampla', 'redes de área ampla', 'wan', 'wans',
        'internet', 'internets', 'rede mundial', 'redes mundiais', 'world wide web',
        'navegador', 'navegadores', 'navegar', 'navega', 'site', 'sites', 'web', 'webs',
        'endereço', 'endereços', 'url', 'urls', 'domínio', 'domínios', 'ip', 'ips',
        'protocolo', 'protocolos', 'http', 'https', 'ftp', 'ftps', 'tcp', 'tcps', 'udp', 'udps',
        'segurança', 'seguranças', 'segurança da informação', 'seguranças da informação',
        'criptografia', 'criptografias', 'criptografar', 'criptografa', 'encriptar', 'encriptars',
        'firewall', 'firewalls', 'antivírus', 'antivírus', 'antivíral', 'antivirais',
        'malware', 'malwares', 'vírus', 'vírus', 'worm', 'worms', 'trojan', 'trojans',
        'phishing', 'phishings', 'hack', 'hacks', 'hacker', 'hackers', 'crack', 'cracks',
        'privacy', 'privacidade', 'privacidade', 'pública', 'públicas', 'privada', 'privadas',
        'dados pessoais', 'dados pessoais', 'dado pessoal', 'dados pessoais',
        'lgpd', 'lgpd', 'gdpr', 'gdpr', 'regulação', 'regulações', 'regulamentação', 'regulamentações',
        'conformidade', 'conformidades', 'compliance', 'compliances',
        'ética', 'éticas', 'ética digital', 'éticas digitais',
        'responsabilidade', 'responsabilidades', 'responsabilidade social', 'responsabilidades sociais',
        'sustentabilidade', 'sustentabilidades', 'sustentabilidade digital', 'sustentabilidades digitais',
        'green', 'verde', 'eco', 'ecos', 'eco-friendly',
        'carbono', 'carbonos', 'pegada de carbono', 'pegadas de carbono',
        'emissão', 'emissões', 'gases', 'gases de efeito estufa', 'co2', 'co2',
        'reciclagem', 'reciclagens', 'resíduo', 'resíduos', 'lixo', 'lixos', 'descarte', 'descartes',
        'poluição', 'poluições', 'poluição digital', 'poluições digitais',
        'lixo eletrônico', 'lixos eletrônicos', 'lixo digital', 'lixos digitais',
        'e-waste', 'e-wastes', 'resíduos eletrônicos', 'resíduos eletrônicos',
        'economia circular', 'economias circulares', 'economia verde', 'economias verdes',
        'design', 'designs', 'design sustentável', 'designs sustentáveis',
        'eco-design', 'eco-designs', 'design para x', 'designs para x',
        'embalagem', 'embalagens', 'embalagem sustentável', 'embalagens sustentáveis',
        'redução', 'reduções', 'reutilização', 'reutilizações', 'reparo', 'reparos', 'reparar', 'repara',
        'refurbishment', 'refurbishments', 'reencaminhamento', 'reencaminhamentos',
        'refurbished', 'refurbisheds', 'reencaminhamento', 'reencaminhamentos',
        'economia de compartilhamento', 'economias de compartilhamento', 'sharing economy', 'sharing economies',
        'plataforma', 'plataformas', 'plataforma digital', 'plataformas digitais',
        'aplicativo', 'aplicativos', 'app', 'apps', 'software', 'softwares',
        'rede social', 'redes sociais', 'social media', 'social medias',
        'facebook', 'facebook', 'instagram', 'instagram', 'twitter', 'twitter', 'linkedin', 'linkedins',
        'youtube', 'youtube', 'tiktok', 'tiktoks', 'snapchat', 'snapchats', 'whatsapp', 'whatsapps',
        'telegram', 'telegram', 'discord', 'discords', 'slack', 'slacks', 'zoom', 'zooms',
        'mensagem', 'mensagens', 'msg', 'msgs', 'chat', 'chats', 'mensageiro', 'mensageiros',
        'comunicação', 'comunicações', 'comunicar', 'comunica', 'mensagem', 'mensagens',
        'informação', 'informações', 'informar', 'informa', 'notícia', 'notícias', 'noticiar', 'noticia',
        'jornal', 'jornais', 'revista', 'revistas', 'mídia', 'mídias', 'midia', 'mídia',
        'televisão', 'televisões', 'tv', 'tvs', 'rádio', 'rádios', 'rádio', 'rádios',
        'imprensa', 'imprensas', 'jornalismo', 'jornalismos', 'jornalista', 'jornalistas',
        'notícia', 'notícias', 'noticiar', 'noticia', 'reportagem', 'reportagens', 'reportar', 'reporta',
        'entrevista', 'entrevistas', 'entrevistar', 'entrevista', 'pesquisa', 'pesquisas', 'pesquisar', 'pesquisa',
        'artigo', 'artigos', 'artigo científico', 'artigos científicos',
        'editorial', 'editoriais', 'opinião', 'opiniões', 'opinar', 'opina',
        'crítica', 'críticas', 'crítica social', 'críticas sociais', 'crítica de arte', 'críticas de arte',
        'crítica literária', 'críticas literárias', 'crítica de cinema', 'críticas de cinema',
        'crítica musical', 'críticas musicais', 'crítica de jogos', 'críticas de jogos',
        'resenha', 'resenhas', 'resenhar', 'resenha', 'review', 'reviews',
        'blog', 'blogs', 'blogueiro', 'blogueiros', 'blogar', 'blogar',
        'vlog', 'vlogs', 'vlogueiro', 'vlogueiros', 'vlogar', 'vlogar',
        'podcast', 'podcasts', 'podcaster', 'podcasters', 'podcaster', 'podcasters',
        'streaming', 'streamings', 'ao vivo', 'ao vivo', 'transmissão', 'transmissões',
        'webinar', 'webinars', 'webinar', 'webinars', 'webinar', 'webinars',
        'evento', 'eventos', 'evento online', 'eventos online', 'evento presencial', 'eventos presenciais',
        'conferência', 'conferências', 'congresso', 'congressos', 'cúpula', 'cúpulas',
        'encontro', 'encontros', 'reunião', 'reuniões', 'assembleia', 'assembleias',
        'feira', 'feiras', 'mostra', 'mostras', 'exposição', 'exposições',
        'palestra', 'palestras', 'palestrante', 'palestrantes', 'palestrar', 'palestrar',
        'mesa redonda', 'mesas redondas', 'mesa', 'mesas',
        'painel', 'painéis', 'painelista', 'painelistas', 'painelar', 'painelar',
        'debate', 'debates', 'debater', 'debater', 'discussão', 'discussões',
        'intervenção', 'intervenções', 'intervir', 'intervém',
        'manifestação', 'manifestações', 'manifestar', 'manifesta', 'protesto', 'protestos',
        'greve', 'greves', 'greve', 'greves', 'piquete', 'piquetes', 'ocupação', 'ocupações',
        'bloqueio', 'bloqueios', 'bloqueio', 'bloqueios', 'manifestação', 'manifestações',
        'mobilização', 'mobilizações', 'mobilizar', 'mobiliza', 'congregação', 'congregações',
        'assembleia', 'assembleias', 'assembleia', 'assembleias', 'manifestação', 'manifestações',
        'movimento', 'movimentos', 'movimento social', 'movimentos sociais', 'mst', 'msts',
        'povo', 'povos', 'povoamento', 'povoamentos', 'população', 'populações', 'habitante', 'habitantes',
        'cidadão', 'cidadãos', 'cidadania', 'cidadanias', 'direito', 'direitos', 'dever', 'deveres',
        'participação', 'participações', 'participação cidadã', 'participações cidadãs',
        'democracia', 'democracias', 'democrático', 'democráticos', 'democratização', 'democratizações',
        'eleição', 'eleições', 'voto', 'votos', 'sufrágio', 'sufrágios', 'eleitor', 'eleitores',
        'partido', 'partidos', 'frente', 'frentes', 'coligação', 'coligações', 'aliança', 'alianças',
        'candidato', 'candidatos', 'candidatura', 'candidaturas', 'campanha', 'campanhas',
        'plebiscito', 'plebiscitos', 'referendo', 'referendos', 'votação', 'votações',
        'constituinte', 'constituintes', 'constituição', 'constituições', 'assembleia', 'assembleias',
        'legislativo', 'legislativos', 'executivo', 'executivos', 'judiciário', 'judiciários',
        'ministro', 'ministros', 'ministério', 'ministérios', 'secretário', 'secretários',
        'governador', 'governadores', 'prefeito', 'prefeitos', 'presidente', 'presidentes',
        'política', 'políticas', 'política pública', 'políticas públicas', 'governança', 'governancas',
        'gestão', 'gestões', 'administração', 'administrações', 'planejamento', 'planejamentos',
        'orçamento', 'orçamentos', 'orçamento público', 'orçamentos públicos', 'receita', 'receitas',
        'despesa', 'despesas', 'despesa pública', 'despesas públicas', 'investimento', 'investimentos',
        'fiscalização', 'fiscalizações', 'fiscal', 'fiscais', 'tribunal', 'tribunais',
        'justiça', 'justiças', 'juiz', 'juízes', 'sentença', 'sentenças', 'decisão', 'decisões',
        'lei', 'leis', 'legislação', 'legislações', 'código', 'códigos', 'norma', 'normas', 'regra', 'regras',
        'regulamentação', 'regulamentações', 'regulamento', 'regulamentos', 'deconto', 'descontos',
        'imposto', 'impostos', 'tributo', 'tributos', 'taxa', 'taxas', 'contribuição', 'contribuições',
        'cobrança', 'cobranças', 'arrecadação', 'arrecadações', 'receita', 'receitas', 'receita tributária',
        'inss', 'inss', 'ir', 'ir', 'icms', 'icms', 'iss', 'iss', 'ipi', 'ipi', 'pis', 'pis', 'cofins', 'cofins',
        'tarifa', 'tarifas', 'tarifa elétrica', 'tarifas elétricas', 'tarifa de água', 'tarifas de água',
        'conta', 'contas', 'conta de luz', 'contas de luz', 'conta de água', 'contas de água',
        'bolsa de valores', 'bolsa de valores', 'bolsa', 'bolsas', 'mercado financeiro', 'mercados financeiros',
        'ação', 'ações', 'ação ordinária', 'ações ordinárias', 'ação preferencial', 'ações preferenciais',
        'dividendo', 'dividendos', 'juros', 'juros', 'rendimento', 'rendimentos', 'lucro', 'lucros',
        'prejuízo', 'prejuízos', 'ação', 'ações', 'mercado', 'mercados',
        'índice', 'índices', 'ibovespa', 'ibovespa', 'dow jones', 'dow jones', 'nasdaq', 'nasdaq',
        'mercado de capitais', 'mercados de capitais', 'mercado primário', 'mercados primários',
        'mercado secundário', 'mercados secundários', 'ipo', 'ipos', 'oferta pública', 'ofertas públicas',
        'fundo', 'fundos', 'fundo de investimento', 'fundos de investimento', 'fii', 'fiis',
        'créditos', 'créditos', 'títulos', 'títulos', 'bônus', 'bônus', 'obrigação', 'obrigações',
        'dívida', 'dívidas', 'emissão', 'emissões', 'título', 'títulos', 'debênture', 'debêntures',
        'certificado', 'certificados', 'certificado de depósito', 'certificados de depósito',
        'renda fixa', 'rendas fixas', 'renda variável', 'rendas variáveis',
        'ação', 'ações', 'ação preferencial', 'ações preferenciais', 'ação ordinária', 'ações ordinárias',
        'opção', 'opções', 'futuro', 'futuros', 'derivativa', 'derivativas', 'swap', 'swaps',
        'hedge', 'hedges', 'proteção', 'proteções', 'cobertura', 'coberturas',
        'risco', 'riscos', 'risco de mercado', 'riscos de mercado', 'risco de crédito', 'riscos de crédito',
        'risco sistemático', 'riscos sistemáticos', 'risco não sistemático', 'riscos não sistemáticos',
        'diversificação', 'diversificações', 'portfólio', 'portfólios', 'carteira', 'carteiras',
        'aplicação', 'aplicações', 'aplicação financeira', 'aplicações financeiras',
        'investimento', 'investimentos', 'investidor', 'investidores', 'investimento de risco',
        'juros', 'juros', 'taxa de juros', 'taxas de juros', 'taxa selic', 'taxas selic', 'selic', 'selics',
        'cdi', 'cdis', 'cdb', 'cdbs', 'tesouro', 'tesouros', 'tesouro direto', 'tesouros direto',
        'poupança', 'poupanças', 'poupar', 'poupa', 'caderneta', 'cadernetas',
        'seguro', 'seguros', 'seguro de vida', 'seguros de vida', 'seguro de automóvel', 'seguros de automóvel',
        'fiança', 'fianças', 'fiador', 'fiadores', 'garantia', 'garantias', 'cobertura', 'coberturas',
        'capitalização', 'capitalizações', 'capitalizar', 'capitaliza', 'título de capitalização',
        'previdência', 'previdências', 'previdência privada', 'previdências privadas', 'previdência pública', 'previdências públicas',
        'pensionista', 'pensionistas', 'aposentadoria', 'aposentadorias', 'aposentar', 'aposenta',
        'aposentadoria por idade', 'aposentadorias por idade', 'aposentadoria por tempo de contribuição', 'aposentadorias por tempo de contribuição',
        'reforma da previdência', 'reformas da previdência', 'reforma', 'reformas',
        'seguridade social', 'seguridades sociais', 'seguridade', 'seguridades',
        'benefício', 'benefícios', 'auxílio', 'auxílios', 'auxílio-doença', 'auxílios-doença',
        'auxílio-reclusão', 'auxílios-reclusão', 'salário-minimum', 'salários-mínimum', 'salário', 'salários',
        'renda', 'rendas', 'renda per capita', 'rendas per capita', 'renda mensal', 'rendas mensais',
        'trabalho', 'trabalhos', 'emprego', 'empregos', 'ocupação', 'ocupações', 'profissão', 'profissões',
        'ocupação', 'ocupações', 'ocupação profissional', 'ocupações profissionais',
        'qualificação', 'qualificações', 'qualificação profissional', 'qualificações profissionais',
        'treinamento', 'treinamentos', 'capacitação', 'capacitações', 'capacitação profissional',
        'educação', 'educações', 'ensino', 'ensinos', 'instrução', 'instruções',
        'alfabetização', 'alfabetizações', 'letramento', 'letramentos', 'escolaridade', 'escolaridades',
        'escola', 'escolas', 'universidade', 'universidades', 'faculdade', 'faculdades',
        'curso', 'cursos', 'graduação', 'graduações', 'mestrado', 'mestrados', 'doutorado', 'doutorados',
        'pesquisa', 'pesquisas', 'pesquisa científica', 'pesquisas científicas', 'extensão', 'extensões',
        'ciência', 'ciências', 'conhecimento', 'conhecimentos', 'saber', 'saberes',
        'filosofia', 'filosofias', 'filósofo', 'filósofos', 'pensamento', 'pensamentos',
        'sociologia', 'sociologias', 'sociólogo', 'sociólogos', 'sociedade', 'sociedades',
        'economia', 'economias', 'econômico', 'econômicos', 'economista', 'economistas',
        'psicologia', 'psicologias', 'psicólogo', 'psicólogos', 'psicológico', 'psicológicos',
        'psicologia social', 'psicologias sociais', 'psicologia do trabalho', 'psicologias do trabalho',
        'psicologia da educação', 'psicologias da educação', 'psicologia clínica', 'psicologias clínicas',
        'psicologia organizacional', 'psicologias organizacionais', 'psicologia do esporte', 'psicologias do esporte',
        'psicologia da saúde', 'psicologias da saúde', 'psicologia forense', 'psicologias forenses',
        'psicologia jurídica', 'psicologias jurídicas', 'psicologia hospitalar', 'psicologias hospitalares',
        'psicologia infantil', 'psicologias infantis', 'psicologia do desenvolvimento', 'psicologias do desenvolvimento',
        'psicologia da linguagem', 'psicologias da linguagem', 'psicologia experimental', 'psicologias experimentais',
        'psicologia cognitiva', 'psicologias cognitivas', 'psicologia comportamental', 'psicologias comportamentais',
        'psicologia analítica', 'psicologias analíticas', 'psicologia humanista', 'psicologias humanistas',
        'psicologia biológica', 'psicologias biológicas', 'psicologia neurociência', 'psicologias neurociência',
        'psicologia evolutiva', 'psicologias evolutivas', 'psicologia genética', 'psicologias genéticas',
        'psicologia do esporte', 'psicologias do esporte', 'psicologia do exercício', 'psicologias do exercício',
        'psicologia da saúde mental', 'psicologias da saúde mental', 'psicologia comunitária', 'psicologias comunitárias',
        'psicologia ambiental', 'psicologias ambientais', 'psicologia organizacional', 'psicologias organizacionais',
        'psicologia do trabalho', 'psicologias do trabalho', 'psicologia industrial', 'psicologias industriais',
        'psicologia jurídica', 'psicologias jurídicas', 'psicologia política', 'psicologias políticas',
        'psicologia da comunicação', 'psicologias da comunicação', 'psicologia da publicidade', 'psicologias da publicidade',
        'psicologia da moda', 'psicologias da moda', 'psicologia da cultura', 'psicologias da cultura',
        'psicologia da religião', 'psicologias da religião', 'psicologia da arte', 'psicologias da arte',
        'psicologia da música', 'psicologias da música', 'psicologia do entretenimento', 'psicologias do entretenimento',
        'psicologia dos jogos', 'psicologias dos jogos', 'psicologia do lazer', 'psicologias do lazer',
        'psicologia da tecnologia', 'psicologias da tecnologia', 'psicologia digital', 'psicologias digitais',
        'psicologia do ambiente', 'psicologias do ambiente', 'psicologia ecológica', 'psicologias ecológicas',
        'psicologia da sustentabilidade', 'psicologias da sustentabilidade', 'psicologia verde', 'psicologias verdes',
        'psicologia da diversidade', 'psicologias da diversidade', 'psicologia da inclusão', 'psicologias da inclusão',
        'psicologia da equidade', 'psicologias da equidade', 'psicologia da justiça social', 'psicologias da justiça social',
        'psicologia dos direitos humanos', 'psicologias dos direitos humanos', 'psicologia da paz', 'psicologias da paz',
        'psicologia da não-violência', 'psicologias da não-violência', 'psicologia da cooperação', 'psicologias da cooperação',
        'psicologia da solidariedade', 'psicologias da solidariedade', 'psicologia da empatia', 'psicologias da empatia',
        'psicologia da compaixão', 'psicologias da compaixão', 'psicologia do cuidado', 'psicologias do cuidado',
        'psicologia do amor', 'psicologias do amor', 'psicologia da afetividade', 'psicologias da afetividade',
        'psicologia da sexualidade', 'psicologias da sexualidade', 'psicologia do gênero', 'psicologias do gênero',
        'psicologia da identidade', 'psicologias da identidade', 'psicologia da personalidade', 'psicologias da personalidade',
        'psicologia do caráter', 'psicologias do caráter', 'psicologia do temperamento', 'psicologias do temperamento',
        'psicologia da emoção', 'psicologias da emoção', 'psicologia do humor', 'psicologias do humor',
        'psicologia da motivação', 'psicologias da motivação', 'psicologia da intenção', 'psicologias da intenção',
        'psicologia da vontade', 'psicologias da vontade', 'psicologia da decisão', 'psicologias da decisão',
        'psicologia do comportamento', 'psicologias do comportamento', 'psicologia da ação', 'psicologias da ação',
        'psicologia da atitude', 'psicologias da atitude', 'psicologia da crença', 'psicologias da crença',
        'psicologia da percepção', 'psicologias da percepção', 'psicologia da atenção', 'psicologias da atenção',
        'psicologia da memória', 'psicologias da memória', 'psicologia da aprendizagem', 'psicologias da aprendizagem',
        'psicologia do esquecimento', 'psicologias do esquecimento', 'psicologia da recordação', 'psicologias da recordação',
        'psicologia do reconhecimento', 'psicologias do reconhecimento', 'psicologia da familiaridade', 'psicologias da familiaridade',
        'psicologia do pensamento', 'psicologias do pensamento', 'psicologia do raciocínio', 'psicologias do raciocínio',
        'psicologia da linguagem', 'psicologias da linguagem', 'psicologia da fala', 'psicologias da fala',
        'psicologia da escrita', 'psicologias da escrita', 'psicologia da leitura', 'psicologias da leitura',
        'psicologia da escuta', 'psicologias da escuta', 'psicologia do olhar', 'psicologias do olhar',
        'psicologia do toque', 'psicologias do toque', 'psicologia do olfato', 'psicologias do olfato',
        'psicologia do paladar', 'psicologias do paladar', 'psicologia do sentido', 'psicologias do sentido',
        'psicologia sensorial', 'psicologias sensoriais', 'psicologia perceptiva', 'psicologias perceptivas',
        'psicologia da cognição', 'psicologias da cognição', 'psicologia da atenção', 'psicologias da atenção',
        'psicologia da memória', 'psicologias da memória', 'psicologia do aprendizado', 'psicologias do aprendizado',
        'psicologia da educação', 'psicologias da educação', 'psicologia da instrução', 'psicologias da instrução',
        'psicologia do ensino', 'psicologias do ensino', 'psicologia da aprendizagem', 'psicologias da aprendizagem',
        'psicologia do professor', 'psicologias do professor', 'psicologia do aluno', 'psicologias do aluno',
        'psicologia da sala de aula', 'psicologias da sala de aula', 'psicologia da escola', 'psicologias da escola',
        'psicologia da gestão educacional', 'psicologias da gestão educacional',
        'psicologia da avaliação', 'psicologias da avaliação', 'psicologia da medição', 'psicologias da medição',
        'psicologia do teste', 'psicologias do teste', 'psicologia do exame', 'psicologias do exame',
        'psicologia do diagnóstico', 'psicologias do diagnóstico', 'psicologia do prognóstico', 'psicologias do prognóstico',
        'psicologia da intervenção', 'psicologias da intervenção', 'psicologia da consulta', 'psicologias da consulta',
        'psicologia da terapia', 'psicologias da terapia', 'psicologia do tratamento', 'psicologias do tratamento',
        'psicologia da cura', 'psicologias da cura', 'psicologia da prevenção', 'psicologias da prevenção',
        'psicologia da promoção', 'psicologias da promoção', 'psicologia da saúde', 'psicologias da saúde',
        'psicologia da qualidade de vida', 'psicologias da qualidade de vida', 'psicologia do bem-estar', 'psicologias do bem-estar',
        'psicologia da felicidade', 'psicologias da felicidade', 'psicologia do bem-estar subjetivo', 'psicologias do bem-estar subjetivo',
        'psicologia do florescimento', 'psicologias do florescimento', 'psicologia do desenvolvimento humano', 'psicologias do desenvolvimento humano',
        'psicologia do desenvolvimento infantil', 'psicologias do desenvolvimento infantil', 'psicologia do desenvolvimento adolescente', 'psicologias do desenvolvimento adolescente',
        'psicologia do desenvolvimento adulto', 'psicologias do desenvolvimento adulto', 'psicologia do desenvolvimento na velhice', 'psicologias do desenvolvimento na velhice',
        'psicologia do desenvolvimento ao longo da vida', 'psicologias do desenvolvimento ao longo da vida', 'psicologia do desenvolvimento humano ao longo da vida', 'psicologias do desenvolvimento humano ao longo da vida',
        'psicologia do desenvolvimento cognitivo', 'psicologias do desenvolvimento cognitivo', 'psicologia do desenvolvimento social', 'psicologias do desenvolvimento social',
        'psicologia do desenvolvimento emocional', 'psicologias do desenvolvimento emocional', 'psicologia do desenvolvimento moral', 'psicologias do desenvolvimento moral',
        'psicologia do desenvolvimento físico', 'psicologias do desenvolvimento físico', 'psicologia do desenvolvimento biológico', 'psicologias do desenvolvimento biológico',
        'psicologia do desenvolvimento neurológico', 'psicologias do desenvolvimento neurológico', 'psicologia do desenvolvimento genético', 'psicologias do desenvolvimento genético',
        'psicologia do desenvolvimento cultural', 'psicologias do desenvolvimento cultural', 'psicologia do desenvolvimento histórico', 'psicologias do desenvolvimento histórico',
        'psicologia do desenvolvimento político', 'psicologias do desenvolvimento político', 'psicologia do desenvolvimento econômico', 'psicologias do desenvolvimento econômico',
        'psicologia do desenvolvimento tecnológico', 'psicologias do desenvolvimento tecnológico', 'psicologia do desenvolvimento ambiental', 'psicologias do desenvolvimento ambiental',
        'psicologia do desenvolvimento sustentável', 'psicologias do desenvolvimento sustentável', 'psicologia do desenvolvimento global', 'psicologias do desenvolvimento global',
        'psicologia do desenvolvimento local', 'psicologias do desenvolvimento local', 'psicologia do desenvolvimento regional', 'psicologias do desenvolvimento regional',
        'psicologia do desenvolvimento comunitário', 'psicologias do desenvolvimento comunitário', 'psicologia do desenvolvimento social', 'psicologias do desenvolvimento social',
        'psicologia do desenvolvimento humano', 'psicologias do desenvolvimento humano', 'psicologia do desenvolvimento da personalidade', 'psicologias do desenvolvimento da personalidade',
        'psicologia do desenvolvimento do caráter', 'psicologias do desenvolvimento do caráter', 'psicologia do desenvolvimento do temperamento', 'psicologias do desenvolvimento do temperamento',
        'psicologia do desenvolvimento da identidade', 'psicologias do desenvolvimento da identidade', 'psicologia do desenvolvimento da autoestima', 'psicologias do desenvolvimento da autoestima',
        'psicologia do desenvolvimento da autoconfiança', 'psicologias do desenvolvimento da autoconfiança', 'psicologia do desenvolvimento da autopercepção', 'psicologias do desenvolvimento da autopercepção',
        'psicologia do desenvolvimento da imagem corporal', 'psicologias do desenvolvimento da imagem corporal', 'psicologia do desenvolvimento da corporalidade', 'psicologias do desenvolvimento da corporalidade',
        'psicologia do desenvolvimento da sexualidade', 'psicologias do desenvolvimento da sexualidade', 'psicologia do desenvolvimento do gênero', 'psicologias do desenvolvimento do gênero',
        'psicologia do desenvolvimento do comportamento moral', 'psicologias do desenvolvimento do comportamento moral', 'psicologia do desenvolvimento do comportamento ético', 'psicologias do desenvolvimento do comportamento ético',
        'psicologia do desenvolvimento do comportamento social', 'psicologias do desenvolvimento do comportamento social', 'psicologia do desenvolvimento do comportamento político', 'psicologias do desenvolvimento do comportamento político',
        'psicologia do desenvolvimento do comportamento econômico', 'psicologias do desenvolvimento do comportamento econômico', 'psicologia do desenvolvimento do comportamento tecnológico', 'psicologias do desenvolvimento do comportamento tecnológico',
        'psicologia do desenvolvimento do comportamento ambiental', 'psicologias do desenvolvimento do comportamento ambiental', 'psicologia do desenvolvimento do comportamento sustentável', 'psicologias do desenvolvimento do comportamento sustentável',
    ],
}


def detect_discipline(texto):
    """Detect discipline by counting matching keywords."""
    if not texto:
        return None
    
    tl = texto.lower()
    
    best_disc = None
    best_score = 0
    
    for disc, keywords in DISCIPLINE_KEYWORDS.items():
        score = 0
        for kw in keywords:
            if kw.lower() in tl:
                score += 1
        
        if score > best_score:
            best_score = score
            best_disc = disc
    
    if best_score >= 3:
        return best_disc
    return None


def main():
    d = Path(r"C:\Users\ffxtr\OneDrive\Documentos\opencode\enem-na-pratica\js\dados.js")
    c = d.read_text(encoding='utf-8')
    m = re.search(r'window\.BANCO_QUESTIONS\s*=\s*(\[.*?\]);', c, re.DOTALL)
    q = json.loads(m.group(1))
    
    area_fixed = 0
    disc_fixed = 0
    
    for question in q:
        texto = question.get('texto', '')
        if not texto:
            continue
        
        correct_disc = detect_discipline(texto)
        if not correct_disc:
            continue
        
        correct_area = DISC_TO_AREA.get(correct_disc, '')
        if not correct_area:
            continue
        
        if question.get('area') != correct_area:
            question['area'] = correct_area
            area_fixed += 1
        
        if question.get('disciplina') != correct_disc:
            question['disciplina'] = correct_disc
            disc_fixed += 1
    
    print(f"Fixed: {area_fixed} areas, {disc_fixed} disciplines")
    
    new_json = json.dumps(q, ensure_ascii=False, separators=(',', ':'))
    new_content = c[:m.start()] + 'window.BANCO_QUESTIONS = ' + new_json + ';' + c[m.end():]
    d.write_text(new_content, encoding='utf-8')
    print("Updated dados.js")


if __name__ == "__main__":
    main()
