#!/usr/bin/env python3
"""Compact ENEM question generator for years 2009-2012."""
import json, os, sys

os.makedirs("data", exist_ok=True)

def build_file(year, questions):
    """Write a year's questions to JSON file."""
    with open(f"data/{year}.json", "w", encoding="utf-8") as f:
        json.dump(questions, f, ensure_ascii=False, indent=2)
    # Count per area
    counts = {}
    for q in questions:
        a = q["area"]
        counts[a] = counts.get(a, 0) + 1
    return counts

# Helper: generate questions from compact tuples
# Format: (disc, ctx, text, pergunta, [5 opts], gab, dif, taxa)
def make_questions(year, area, qlist):
    prefix = {"linguagens":"L","humanas":"H","natureza":"N","matematica":"M"}[area]
    result = []
    for i, (disc, ctx, text, pergunta, opts, gab, dif, taxa) in enumerate(qlist, 1):
        result.append({
            "id": f"{prefix}{year}_{i:02d}",
            "ano": year,
            "area": area,
            "disciplina": disc,
            "contexto": ctx,
            "texto": text,
            "pergunta": pergunta,
            "opcoes": opts,
            "gabarito": gab,
            "dificuldade": dif,
            "taxaAcerto": taxa
        })
    return result

# We'll generate each year separately with distinct content
# For brevity, we generate 2009 first, then adapt for other years

def gen_year(year):
    questions = []
    seq = 0
    
    def add(area, disc, ctx, text, pergunta, opts, gab, dif, taxa):
        nonlocal seq
        seq += 1
        prefix = {"linguagens":"L","humanas":"H","natureza":"N","matematica":"M"}[area]
        questions.append({
            "id": f"{prefix}{year}_{seq:02d}",
            "ano": year,
            "area": area,
            "disciplina": disc,
            "contexto": ctx,
            "texto": text,
            "pergunta": pergunta,
            "opcoes": opts,
            "gabarito": gab,
            "dificuldade": dif,
            "taxaAcerto": taxa
        })
    
    return add, questions

def gen_2009():
    add, qs = gen_year(2009)
    
    # LINGUAGENS - Portugues (20)
    add("linguagens","portugues","Leia o texto abaixo para responder à questão.","A descoberta do pré-sal no Brasil, anunciada oficialmente em 2007 e confirmada em 2009, trouxe perspectivas de desenvolvimento sem precedentes para o país. Geólogos e engenheiros de petróleo trabalham intensamente para mapear essas reservas, que podem conter bilhões de barris de petróleo. No entanto, debates sobre a exploração sustentável e a distribuição dos lucros gerados por essa atividade dominam a pauta política nacional.","Considerando o contexto apresentado, a expressão 'bilhões de barris de petróleo' funciona como:",["Um adjetivo substantivado que qualifica a quantidade de petróleo encontrada","Uma locução adverbial de quantidade que modifica o verbo 'conter'","Um complemento nominal do substantivo 'reservas'","Um apostilhamento explicativo de 'pré-sal'","Um adjunto adverbial de quantidade que modifica o advérbio 'onde'"],"C",2,55)
    add("linguagens","portugues","Leia o poema abaixo para responder à questão.","No meio do caminho tinha uma pedra\ntinha uma pedra no meio do caminho\ntinha uma pedra\ntinha uma pedra no meio do caminho\ntinha uma pedra.\n\nNo meio do caminho tinha uma pedra.\n\nJamais me esquecerei desse acontecimento\nna vida de minhas retinas fatigadas.\n\n(Carlos Drummond de Andrade)","A repetição do termo 'pedra' ao longo do poema produz, no leitor, a sensação de:",["Vaidade diante da descoberta de uma novidade","Descaso diante de um obstáculo que se repete","Indiferença diante da monotonia cotidiana","Ansiedade diante de um evento surpreendente","Felicidade diante de uma situação inesperada"],"C",1,78)
    add("linguagens","portugues","Leia o texto abaixo para responder à questão.","A crise financeira que abalou os mercados globais a partir de 2008 atingiu plenamente o Brasil em 2009. O PIB registrou contração de 0,3%, quebrando uma sequência de anos de crescimento acelerado. Especialistas apontam que a desaceleração econômica teve impactos diretos no mercado de trabalho, com aumento do desemprego informal.","Assinale a alternativa em que a palavra destacada atua como substantivo.",["O PIB registrou contração de 0,3%","Especialistas apontam que a desaceleração econômica teve impactos diretos","O governo implementou medidas de estímulo","A crise abalou os mercados globais","Apesar disso, o governo ajudou a conter os efeitos"],"C",2,52)
    add("linguagens","portugues","Leia o texto abaixo para responder à questão.","A ficção científica brasileira tem ganhado espaço nos últimos anos. Escritores como Gerson Lodi-Roza vêm produzindo obras que misturam elementos da cultura popular com tecnologia e futurologia.","No trecho 'vêm produzindo obras', a locução verbal indica:",["Ação que começou no passado e pode continuar no futuro","Ação repetida em momentos diferentes do passado","Ação que começou no passado e continua no presente","Ação que começou e se encerrou antes de outra","Ação futura com relação ao momento da fala"],"C",1,72)
    add("linguagens","portugues","Leia o fragmento abaixo para responder à questão.","No Brasil de 2009, o debate sobre a revisão de férias compulsórias para servidores públicos ganhou repercussão nacional. O governo federal argumentava que a medida era necessária para reduzir o gasto público em meio à crise econômica.","No período 'a medida era necessária', identifique a classificação da palavra 'era':",["Verbo ser, no pretérito imperfeito do indicativo","Verbo ser, no pretérito imperfeito do subjuntivo","Verbo ser, no pretérito perfeito do indicativo","Verbo ser, no pretérito mais-que-perfeito","Verbo ser, no presente do indicativo"],"A",2,60)
    add("linguagens","portugues","Leia o texto abaixo para responder à questão.","A chegada de Obama à presidência dos Estados Unidos em janeiro de 2009 marcou um período de esperança para milhões de pessoas ao redor do mundo. O primeiro presidente afro-americano da nação mais poderosa do planeta prometia mudanças em políticas de saúde e educação.","Assinale a alternativa em que a expressão funciona como adjunto adverbial.",["A chegada de Obama à presidência","O primeiro presidente afro-americano da nação","Mais poderosa do planeta prometia mudanças","No Brasil, a diplomacia buscou fortalecer laços","Em meio à crise financeira"],"E",2,48)
    add("linguagens","portugues","Leia o trecho abaixo para responder à questão.","O Auto da Compadecida, de Glauber Rocha, é considerado uma das obras-primas do cinema brasileiro. Baseado na obra de Ariano Suassuna, a película retrata as aventuras de João Grilo e Chicó no sertão nordestino.","Assinale a alternativa com oração subordinada substantiva objetiva direta.",["O filme retrata as aventuras de João Grilo","O filme é considerado uma das obras-primas","Através de humor, o filme aborda temas","O filme aborda temas como a desigualdade","Lançado em 2000, tornou-se referência"],"A",3,32)
    add("linguagens","portugues","Leia o poema abaixo para responder à questão.","Morte e vida Severina é uma peça que retrata a vida de retirantes nordestinos. Severina busca sobrevivência em meio à seca e à miséria. A obra mescla poesia e drama.","A expressão 'cordão umbilical de todas as mortes' pode ser interpretada como:",["Uma referência literal à profissão de parteira","Um símbolo que liga a morte à vida em um ciclo contínuo","Uma metáfora para a pobreza extrema vivida pela personagem","Uma referência à religião da personagem","Um eufemismo para a tragédia vivida pela comunidade"],"B",1,74)
    add("linguagens","portugues","Leia o texto abaixo para responder à questão.","A popularização da internet no Brasil atingiu patamares recordes em 2009. Segundo o IBGE, aproximadamente 67 milhões de brasileiros tinham acesso à rede mundial de computadores.","Assinale a alternativa com período composto por subordinação.",["A popularização da internet atingiu patamares recordes","Segundo o IBGE, 67 milhões tinham acesso","O que representava cerca de 38% da população","O crescimento foi impulsionado pela queda no preço","Especialistas apontavam que a inclusão digital seria fundamental"],"E",1,70)
    add("linguagens","portugues","Leia o texto abaixo para responder à questão.","Em 2009, o Brasil sediou a Reunião de Chefes de Estado e de Governo da Unasul. O encontro abordou temas como a integração regional. O presidente Lula defendeu a criação de um banco sul-americano.","Assinale a alternativa com conjunção integrante.",["O encontro abordou temas como a integração regional","O presidente defendeu a criação de um banco que financiaria projetos","Alguns dos quais questionavam a viabilidade financeira","A proposta gerou debate entre os participantes","O encontro, realizado em Brasília, abordou temas"],"A",3,38)
    add("linguagens","portugues","Leia o poema abaixo para responder à questão.","Eu nasci sexta-feira, 13 de março, uma grande mancha de vinho tinto. Minha mãe disse: Minha filha, tudo isso vai passar.","O sujeito da oração 'uma grande mancha de vinho tinto' é:",["Sujeito simples, oculto, de referência indefinida","Sujeito composto, oculto, de referência definida","Sujeito inexistente (oração sem sujeito)","Sujeito simples, oculto, de referência definida","Sujeito indeterminado"],"C",2,54)
    add("linguagens","portugues","Leia o texto abaixo para responder à questão.","A ascensão do Twitter como ferramenta de comunicação política transformou a forma como os governantes interagem com a população. A rapidez com que as informações são compartilhadas na rede social trouxe desafios como a propagação de fake news.","No trecho 'a rapidez com que as informações são compartilhadas', a locução 'com que' atua como:",["Preposição regida pelo substantivo 'rapidez'","Conjunção integrante","Pronome relativo composto","Locução conjuntiva","Advérbio de modo"],"A",3,42)
    add("linguagens","portugues","Leia o texto abaixo para responder à questão.","O defining moment da carreira do músico brasileiro no cenário internacional pode ser marcado pela participação em festivais como o Rock in Rio. Em 2009, o festival celebrou sua sétima edição.","A expressão 'defining moment' pode ser traduzida corretamente como:",["Momento de definição","Ponto de encontro","Momento decisivo","Definição do momento","Ponto de definição"],"C",2,58)
    add("linguagens","portugues","Leia o texto abaixo para responder à questão.","A reforma do Código Civil brasileiro, implementada em 2002, completou sete anos de vigência em 2009. Uma das principais novidades foi o reconhecimento da união estável como entidade familiar.","Assinale a alternativa em que a palavra está empregada como verbo.",["A reforma completou sete anos de vigência","O novo código trouxe mudanças significativas","Uma das principais novidades foi o reconhecimento","A reforma também alterou a maioridade civil","A maioridade penal para crimes civis"],"D",1,80)
    add("linguagens","portugues","Leia o texto abaixo para responder à questão.","A commercialização de produtos orgânicos cresceu de forma significativa no Brasil em 2009. A pesquisa DataPopular revelou que 23% dos brasileiros já haviam consumido alimentos orgânicos.","No trecho 'um aumento de 15 pontos percentuais em relação ao ano anterior', a expressão funciona como:",["Adjunto adverbial de tempo","Complemento nominal do substantivo 'aumento'","Adjunto adverbial de proporção","Apostilhamento explicativo","Adjunto adverbial de comparação"],"B",2,50)
    add("linguagens","portugues","Leia o texto abaixo para responder à questão.","A Copa do Mundo Sub-20 de 2009, realizada no Egito, teve como campeã a seleção brasileira. O torneio serviu como vitrine para jovens talentos.","Na oração 'A Copa teve como campeã a seleção brasileira', a expressão 'como campeã' funciona como:",["Adjunto adverbial de modo","Complemento nominal do verbo 'teve'","Predicativo do sujeito","Apostilhamento explicativo","Adjunto adverbial de proporção"],"B",2,53)
    add("linguagens","portugues","Leia o texto abaixo para responder à questão.","A Empiricus, empresa especializada em recomendações de investimentos financeiros, investiu pesadamente em publicidade no Brasil em 2009. Muitos investidores buscavam orientação profissional em tempos de incerteza econômica.","Assinale a alternativa em que a palavra está empregada como adjetivo.",["A Empiricus investiu pesadamente em publicidade","O mercado financeiro brasileiro vivia um momento","Muitos investidores buscavam orientação profissional","Os ativos de menor risco","Tempos de incerteza econômica"],"C",2,57)
    add("linguagens","portugues","Leia o texto abaixo para responder à questão.","Em 2009, o Brasil vivia um momento de transformação digital. As redes sociais passaram a ser usadas como ferramentas de marketing político e de comunicação direta com os eleitores.","Assinale a alternativa com oração subordinada substantiva subjetiva.",["O governo implementou medidas que surtiram efeitos","O que surpreendeu a todos foi o resultado","Especialistas apontavam que a mudança seria fundamental","A transformação digital já havia começado","A mudança que ocorreu foi significativa"],"C",3,35)
    add("linguagens","portugues","Leia o poema abaixo para responder à questão.","Ora, se seres vivos se alimentam e se reproduzem, então a vida é simples e bela, pois cada ser vivo é um milagre da natureza.","O sujeito de 'cada ser vivo é um milagre' é:",["Sujeito simples, oculto","Sujeito simples, explícito, de referência definida","Sujeito inexistente","Sujeito composto, explícito","Sujeito indeterminado"],"B",2,56)
    add("linguagens","portugues","Leia o texto abaixo para responder à questão.","O movimento dos sem-teto ganhou força em 2009, com ocupações de terrenos urbanos em grandes capitais brasileiras. Organizações reivindicavam o direito à moradia digna.","Assinale a alternativa em que a palavra está empregada como advérbio.",["O movimento ganhou força significativa","Milhões de brasileiros vivem em condições precárias","Organizações reivindicavam o direito à moradia","A moradia era precária para milhões de pessoas","As ocupações ocorreram em grandes capitais brasileiras"],"E",2,55)
    
    # LINGUAGENS - Ingles (10)
    add("linguagens","ingles","Read the text below to answer the question.","The global financial crisis of 2008-2009 affected countries worldwide. The United States experienced its worst recession since the Great Depression. In Brazil, the impact was less severe due to the country's strong domestic market and sound macroeconomic policies.","According to the text, Brazil was less affected because of:",["The collapse of its banking system","Its strong domestic market and sound macroeconomic policies","The massive stimulus packages by other countries","Its isolation from the global financial system","The devaluation of the Brazilian currency"],"B",1,82)
    add("linguagens","ingles","Read the text below to answer the question.","The Internet has revolutionized the way people communicate and access information. In 2009, social media platforms like Facebook and Twitter experienced explosive growth.","What does the word 'integral' mean in the context of the passage?",["Secondary and unimportant","Complete and necessary","Optional and temporary","Limited and restricted","Outdated and irrelevant"],"B",1,79)
    add("linguagens","ingles","Read the text below to answer the question.","Climate change has become one of the most pressing issues of the 21st century. The United Nations Climate Change Conference held in Copenhagen in December 2009 brought together world leaders to negotiate a new agreement. However, the conference ended without a legally binding treaty.","What was the main outcome of the Copenhagen Climate Change Conference?",["A legally binding treaty was signed by all countries","The conference ended without a legally binding agreement","Greenhouse gas emissions were reduced by 50%","A new environmental agency was created","All countries committed to carbon neutrality by 2020"],"B",2,62)
    add("linguagens","ingles","Read the text below to answer the question.","The concept of sustainable development has gained prominence in recent years. Sustainable development is defined as development that meets the needs of the present without compromising the ability of future generations to meet their own needs.","According to the definition provided in the text, sustainable development aims to:",["Maximize short-term economic profits","Balance current needs with future generations' needs","Eliminate all industrial activities","Focus exclusively on environmental conservation","Prioritize social programs over economic growth"],"B",1,85)
    add("linguagens","ingles","Read the text below to answer the question.","Telemedicine has emerged as a promising solution to improve healthcare access in remote areas. This technology allows patients to consult with doctors through video calls. However, challenges such as the lack of adequate internet infrastructure remain significant obstacles.","According to the passage, what is a major barrier to the widespread adoption of telemedicine?",["The ineffectiveness of video consultations","The lack of adequate internet infrastructure","The high cost of medical equipment","The opposition of patients to technology","The refusal of insurance companies to cover telemedicine"],"B",2,65)
    add("linguagens","ingles","Read the text below to answer the question.","The Apple iPhone, launched in 2007, transformed the smartphone industry. The App Store, which opened in 2008, allowed developers to create and distribute software, creating a new economic ecosystem.","What does the word 'ecosystem' refer to in the context of the passage?",["The natural environment where the iPhone was manufactured","The interconnected network of developers, users, and applications","The physical stores where iPhones are sold","The factory assembly line where iPhones are produced","The recycling program for old iPhones"],"B",2,58)
    add("linguagens","ingles","Read the text below to answer the question.","Water scarcity is a growing concern in many parts of the world. Scientists are developing new technologies for water purification and desalination, which could help provide clean drinking water to millions.","What does the word 'desalination' mean in the context of the passage?",["The process of heating water to make it safe for drinking","The process of removing salt from seawater","The process of collecting rainwater in reservoirs","The process of freezing water for storage","The process of recycling wastewater"],"B",1,76)
    add("linguagens","ingles","Read the text below to answer the question.","The global food crisis had lasting effects on food security. The G8 nations pledged to provide $20 billion over three years to support agricultural development in developing countries.","What was the main goal of the G8 pledge mentioned in the text?",["To increase food prices in developed countries","To support agricultural development in developing countries","To reduce food production in all countries","To ban all international food trade","To eliminate organic farming worldwide"],"B",2,67)
    add("linguagens","ingles","Read the text below to answer the question.","Corporate social responsibility has gained increasing importance. Consumers showed growing preference for brands that demonstrated genuine commitment to social and environmental causes.","According to the text, younger consumers tended to prefer brands that:",["Offered the lowest prices in the market","Demonstrated commitment to social and environmental causes","Had the largest marketing budgets","Produced the most products","Were the oldest companies in the industry"],"B",1,83)
    add("linguagens","ingles","Read the text below to answer the question.","Renewable energy sources received significant attention in 2009. International cooperation and technology transfer were identified as key factors for accelerating the transition to clean energy worldwide.","What was identified as essential for accelerating the transition to clean energy?",["The complete ban on fossil fuel use","International cooperation and technology transfer","The elimination of all government subsidies","The closure of all nuclear power plants","The reduction of energy consumption by 50%"],"B",2,60)
    
    # LINGUAGENS - Espanhol (5)
    add("linguagens","espanhol","Lea el texto a continuación para responder a la pregunta.","En 2009, la crisis económica global afectó profundamente a Latinoamérica. Brasil, como la economía más grande de la región, jugó un papel fundamental en la recuperación económica.","¿Qué papel jugó Brasil en la recuperación económica regional?",["Redució sus exportaciones para proteger el mercado interno","Jugó un papel fundamental en la recuperación económica","Aumentó sus tasas de interés para controlar la inflación","Implementó políticas de austeridad para reducir el gasto público","Se aisló de la economía internacional"],"B",1,80)
    add("linguagens","espanhol","Lea el texto a continuación para responder a la pregunta.","El turismo sostenible se ha convertido en una tendencia creciente en América Latina. En Brasil, el Ministerio de Turismo lanzó una campaña para promover el turismo comunitario.","¿Cuál es el objetivo principal del turismo comunitario mencionado en el texto?",["Aumentar la construcción de hoteles de lujo","Generar ingresos para las poblaciones rurales","Reducir el número de visitantes internacionales","Promover el turismo en las grandes ciudades","Eliminar todos los programas de protección ambiental"],"B",2,68)
    add("linguagens","espanhol","Lea el texto a continuación para responder a la pregunta.","La educación a distancia ha experimentado un crecimiento significativo. En 2009, universidades comenzaron a ofrecer cursos a través de Internet.","¿Cuál es un desafío importante para la educación a distancia en América Latina?",["La falta de interés de los estudiantes","La falta de acceso a Internet de banda ancha","La abundancia de universidades físicas","El bajo costo de las tecnologías educativas","La excesiva regulación gubernamental"],"B",2,64)
    add("linguagens","espanhol","Lea el texto a continuación para responder a la pregunta.","El cine latinoamericano ganó reconocimiento internacional en 2009. El éxito se atribuye a la combinación de historias universales con perspectivas culturales únicas.","¿A qué se atribuye el éxito del cine latinoamericano según los críticos?",["Al uso exclusivo de efectos especiales","A la combinación de historias universales con perspectivas culturales únicas","A la coproducción exclusiva con Hollywood","Al bajo costo de producción de las películas","A la ausencia de competencia internacional"],"B",2,61)
    add("linguagens","espanhol","Lea el texto a continuación para responder a la pregunta.","En 2009, la Unión Europea firmó acuerdos de cooperación con varios países latinoamericanos. Brasil fue identificado como un socio estratégico para la UE.","¿Por qué Brasil fue identificado como socio estratégico para la Unión Europea?",["Por su pequeño tamaño económico","Por su tamaño económico e influencia política en la región","Por su aislamiento internacional","Por su baja producción industrial","Por su escasa población"],"B",1,78)
    
    # LINGUAGENS - Literatura (5)
    add("linguagens","literatura","Leia o trecho abaixo para responder à questão.","Clarice Lispector é uma das escritoras mais importantes da literatura brasileira. Em 'A Hora da Estrela', publicada em 1977, a autora retrata a trajetória de Macabéa, uma jovem nordestina que mora no Rio de Janeiro.","Em 'A Hora da Estrela', o narrador (Rodrigo S.M.) é um personagem que:",["Vive as mesmas experiências de Macabéa","Observa e comenta as ações de Macabéa sem interferir diretamente","É o protagonista da história","Participa ativamente da vida de Macabéa","Relata os fatos em primeira pessoa"],"B",2,56)
    add("linguagens","literatura","Leia o trecho abaixo para responder à questão.","Machado de Assis, considerado o maior escritor brasileiro, retratou a sociedade carioca do século XIX. Em 'Dom Casmurro', publicado em 1899, o narrador Bentinho relata seu relacionamento com Capitu.","Em 'Dom Casmurro', a ambiguidade narrativa permite ao leitor:",["Conhecer todos os pensamentos de Capitu","Decidir se Capitu traiu ou não Bentinho","Participar diretamente da narrativa","Saber exatamente o que aconteceu na história","Desconsiderar a opinião do narrador"],"B",1,75)
    add("linguagens","literatura","Leia o trecho abaixo para responder à questão.","O Modernismo brasileiro teve início com a Semana de Arte Moderna de 1922, realizada em São Paulo. O movimento buscava uma ruptura com os padrões literários acadêmicos e a valorização da cultura brasileira.","O principal objetivo do Modernismo brasileiro era:",["Manter os padrões literários acadêmicos","Valorizar a cultura europeia em detrimento da brasileira","Criar uma literatura mais livre e em contato com a realidade do povo","Retornar aos padrões do Arcadismo","Estabelecer uma linguagem formal e rigorosa"],"C",1,80)
    add("linguagens","literatura","Leia o trecho abaixo para responder à questão.","Graciliano Ramos é um dos principais nomes do Regionalismo brasileiro. Em 'Vidas Secas', publicado em 1938, o autor retrata a vida de uma família de retirantes no sertão nordestino.","Em 'Vidas Secas', a linguagem seca e direta do narrador tem como objetivo:",["Embelezar a paisagem nordestina","Espelhar a aridez e a dureza da vida no sertão","Criar uma atmosfera de fantasia","Mostrar a sofisticação da família de Fabiano","Destacar a riqueza cultural do sertão"],"B",2,58)
    add("linguagens","literatura","Leia o trecho abaixo para responder à questão.","O Barroco foi um movimento artístico que se desenvolveu na Europa entre os séculos XVI e XVIII. No Brasil, o Barroco teve grande influência na arte sacra. O principal expoente do Barroco brasileiro foi Aleijadinho.","O principal expoente do Barroco brasileiro foi:",["Machado de Assis","Aleijadinho","Cândido Portinari","Tarsila do Amaral","Oswald de Andrade"],"B",2,60)
    
    # LINGUAGENS - Artes (2)
    add("linguagens","artes","Leia o texto abaixo para responder à questão.","O cinema brasileiro ganhou reconhecimento internacional ao longo dos anos. O cinema nacional é conhecido por retratar a realidade social do Brasil de forma poética e reflexiva.","O cinema brasileiro é reconhecido internacionalmente por sua capacidade de:",["Produzir filmes de ficção científica com efeitos especiais","Retratar a realidade social do Brasil de forma poética e reflexiva","Copiar películas hollywoodianas com elenco brasileiro","Produzir filmes exclusivamente para o mercado interno","Utilizar apenas atores estrangeiros nas produções"],"B",1,79)
    add("linguagens","artes","Leia o texto abaixo para responder à questão.","A arte contemporânea brasileira tem ganhado destaque em galerias e museus ao redor do mundo. Artistas como Vik Muniz e Ernesto Neto são reconhecidos por suas instalações inovadoras.","A arte contemporânea brasileira é reconhecida por:",["Copiar estilos europeus tradicionais","Abordar temas como identidade e memória de forma inovadora","Utilizar apenas técnicas tradicionais","Focar exclusivamente em temas religiosos","Seguir padrões artísticos pré-definidos"],"B",2,57)
    
    # LINGUAGENS - Educação Física (2)
    add("linguagens","educacao_fisica","Leia o texto abaixo para responder à questão.","A importância da atividade física para a saúde tem sido amplamente divulgada. Estudos demonstraram que a prática regular de exercícios físicos pode reduzir o risco de doenças cardíacas em até 40%.","Segundo o texto, a prática regular de exercícios físicos pode reduzir o risco de doenças cardíacas em até:",["10%","20%","30%","40%","50%"],"D",1,85)
    add("linguagens","educacao_fisica","Leia o texto abaixo para responder à questão.","O esporte adaptado tem ganhado destaque no cenário esportivo. Atletas com deficiência física participam de competições internacionais como os Jogos Paralímpicos.","O esporte adaptado contribui para:",["Apenas a melhoria da condição física","A saúde física, a autoestima e a integração social","Exclusivamente competições esportivas","Apenas o desenvolvimento motor","Apenas o lazer individual"],"B",1,88)
    
    # LINGUAGENS - TIC (1)
    add("linguagens","tic","Leia o texto abaixo para responder à questão.","A tecnologia da informação transformou drasticamente a educação em todo o mundo. Em 2009, ferramentas como o Google Docs e o Moodle começaram a ser utilizadas em salas de aula brasileiras. O governo implementou o programa Um Computador por Aluno (UCA).","O programa Um Computador por Aluno (UCA) tinha como objetivo principal:",["Substituir completamente os professores por computadores","Proporcionar acesso a computadores e internet nas escolas públicas","Apenas ensinar programação de computadores","Vender computadores para escolas particulares","Apenas atualizar os laboratórios de informática"],"B",1,81)
    
    # HUMANAS - Historia (15)
    add("humanas","historia","Leia o texto abaixo para responder à questão.","A Segunda Guerra Mundial (1939-1945) foi o conflito mais devastador da história. O envolvimento do Brasil teve início em 1942, quando submarinos alemães afundaram navios mercantes brasileiros.","O envolvimento do Brasil na Segunda Guerra teve como consequência:",["O isolamento internacional do Brasil","O fortalecimento dos laços com os países do Eixo","O fortalecimento dos laços diplomáticos com os Estados Unidos e a Europa","A retirada do Brasil da Liga das Nações","A redução do poderio militar brasileiro"],"C",2,55)
    add("humanas","historia","Leia o texto abaixo para responder à questão.","A Revolução Industrial transformou a sociedade europeia a partir do século XVIII. A introdução da máquina a vapor revolucionou a produção têxtil, provocando a migração massiva de trabalhadores do campo para as cidades.","Uma das principais consequências da Revolução Industrial foi:",["O retorno dos trabalhadores ao campo","A migração massiva do campo para as cidades","A redução da oferta de empregos urbanos","A diminuição da produção têxtil","O fortalecimento da economia agrária"],"B",1,78)
    add("humanas","historia","Leia o texto abaixo para responder à questão.","A ditadura militar no Brasil (1964-1985) foi marcada por violações sistemáticas dos direitos humanos. Em 2009, o governo brasileiro criou a Comissão Nacional da Verdade para investigar os crimes cometidos durante a ditadura.","A Comissão Nacional da Verdade, criada em 2009, tinha como objetivo:",["Julgar e condenar os militares responsáveis pelos crimes","Investigar os crimes cometidos durante a ditadura militar","Criar monumentos em homenagem aos militares","Esquecer os eventos do período da ditadura","Promover a reconciliação sem investigar os fatos"],"B",2,60)
    add("humanas","historia","Leia o texto abaixo para responder à questão.","A colonização portuguesa no Brasil foi marcada pela exploração da mão de obra escravizada africana. O Quilombo dos Palmares, liderado por Zumbi, foi o maior exemplo de resistência negra no Brasil colonial.","O Quilombo dos Palmares representou:",["Uma comunidade de escravos que aceitaram passivamente sua condição","O maior exemplo de resistência negra contra a escravidão no Brasil colonial","Uma comunidade de portugueses que fugiram do Brasil","Um centro de comércio escravista","Uma fortaleza militar portuguesa"],"B",1,82)
    add("humanas","historia","Leia o texto abaixo para responder à questão.","A independência do Brasil, proclamada em 1822, foi um processo gradual que envolveu negociações políticas e conflitos armados. A independência marcou o início do período imperial brasileiro.","A independência do Brasil marcou o início de qual período histórico?",["O período colonial","O período imperial","O período republicano","O período vitoriano","O período regencial"],"B",1,85)
    add("humanas","historia","Leia o texto abaixo para responder à questão.","A Revolução Francesa de 1789 transformou profundamente a sociedade europeia. Os ideais de liberdade, igualdade e fraternidade inspiraram movimentos revolucionários em todo o mundo, incluindo o Brasil.","A Revolução Francesa influenciou movimentos no Brasil, como:",["A Proclamação da República","A Conjuração Baiana e a Inconfidência Mineira","A Abolição da Escravatura","A Independência do Brasil","A Revolução de 1930"],"B",2,56)
    add("humanas","historia","Leia o texto abaixo para responder à questão.","A Guerra Fria (1947-1991) opôs os Estados Unidos e a União Soviética em uma disputa ideológica pelo controle mundial. O Brasil manteve uma posição de não alinhamento.","Durante a Guerra Fria, a política externa brasileira foi caracterizada por:",["A aliança exclusiva com os Estados Unidos","Uma alternância entre proximidade com os EUA e independência diplomática","A aliança exclusiva com a União Soviética","O isolamento total do cenário internacional","A participação ativa em conflitos armados"],"B",3,38)
    add("humanas","historia","Leia o texto abaixo para responder à questão.","A Revolução de 1930 no Brasil marcou o fim da República Velha e o início da Era Vargas. Getúlio Vargas implementou reformas modernizadoras, incluindo direitos trabalhistas.","A Era Vargas foi caracterizada por:",["A descentralização do poder político","O intervencionismo estatal na economia e a criação de direitos trabalhistas","A redução do papel do Estado na economia","A democracia plena e o pluripartidarismo","O isolamento internacional do Brasil"],"B",2,52)
    add("humanas","historia","Leia o texto abaixo para responder à questão.","O Brasil Colônia foi caracterizado pela exploração da mão de obra escravizada africana e pelo sistema mercantilista. A Coroa Portuguesa mantinha controle absoluto sobre as colônias.","O sistema mercantilista na colônia brasileira significava:",["A autonomia econômica das colônias em relação à metrópole","O controle absoluto da Coroa Portuguesa sobre a economia colonial","A abertura do comércio com outros países europeus","O incentivo à industrialização nas colônias","A independência econômica das colônias"],"B",3,40)
    add("humanas","historia","Leia o texto abaixo para responder à questão.","O abolicionismo no Brasil foi um movimento que culminou na Lei Áurea de 1888, assinada pela Princesa Isabel. No entanto, a abolição não veio acompanhada de políticas de integração social dos ex-escravizados.","A ausência de políticas de integração social após a abolição gerou:",["O fortalecimento da igualdade racial","Profundas desigualdades sociais que persistem até hoje","A integração imediata dos ex-escravizados na sociedade","O reconhecimento formal dos direitos civis dos ex-escravizados","A distribuição de terras aos ex-escravizados"],"B",2,62)
    add("humanas","historia","Leia o texto abaixo para responder à questão.","A Segunda Guerra Mundial teve impactos profundos na sociedade brasileira. O envolvimento do Brasil no conflito fortaleceu a relação com os Estados Unidos e acelerou o processo de industrialização.","Uma das consequências do envolvimento do Brasil na Segunda Guerra foi:",["O isolamento diplomático do Brasil","O fortalecimento da relação com os Estados Unidos e o processo de industrialização","A redução do poderio militar brasileiro","O retorno à economia agrária","A diminuição da participação da classe trabalhadora na política"],"B",2,57)
    add("humanas","historia","Leia o texto abaixo para responder à questão.","A fuga da família real portuguesa para o Brasil em 1808 marcou um momento decisivo na história do país. A abertura dos portos às nações amigas em 1808 rompeu o monopólio comercial português.","A abertura dos portos às nações amigas em 1808 teve como consequência:",["O fortalecimento do monopólio comercial português","A permitiução do comércio com outros países além de Portugal","O isolamento econômico do Brasil","A volta ao sistema colonial","A proibição de importações"],"B",2,55)
    add("humanas","historia","Leia o texto abaixo para responder à questão.","O movimento operário brasileiro nasceu no início do século XX, com a imigração de trabalhadores europeus. A repressão do governo foi marcada pela Lei de Segurança Nacional de 1897.","O governo utilizou para reprimir o movimento operário:",["Políticas de incentivo à organização sindical","A Lei de Segurança Nacional de 1897, que proibia a propaganda anarquista","A criação de sindicatos governamentais","O reconhecimento imediato dos direitos trabalhistas","A distribuição de terras aos trabalhadores"],"B",3,35)
    add("humanas","historia","Leia o texto abaixo para responder à questão.","A redemocratização brasileira culminou com a eleição direta para presidente em 1989. O processo envolveu intensas mobilizações sociais, como as Diretas Já em 1984.","As Diretas Já em 1984 foram um movimento que:",["Defendia a continuação do regime militar","Exigia eleições diretas para presidente","Pedia o fechamento do Congresso Nacional","Apoioava a ditadura militar","Reivindicava a volta da monarquia"],"B",1,80)
    add("humanas","historia","Leia o texto abaixo para responder à questão.","A Constituição de 1988, conhecida como Constituição Cidadã, consolidou os direitos fundamentais e as garantias democráticas no Brasil. Ela estabeleceu separação de poderes e direitos sociais.","A Constituição de 1988 é chamada de Constituição Cidadã porque:",["Estabeleceu a ditadura militar","Consolidou direitos fundamentais e garantias democráticas","Aboliu a escravidão no Brasil","Criou o sistema monárquico","Proibiu eleições diretas"],"B",1,82)
    
    # HUMANAS - Geografia (15)
    add("humanas","geografia","Leia o texto abaixo para responder à questão.","O Brasil é um país de dimensões continentais, com diferentes biomas como a Floresta Amazônica, o Cerrado, a Mata Atlântica, o Pantanal e o Pampa. A diversidade biológica do Brasil é considerada a maior do mundo.","Uma das características do bioma Cerrado é:",["A predominância de florestas perenes de grande porte","A predominância de vegetação de cerrado, com árvores de troncos retorcidos e cascas grossas","A predominância de dunas de areia","A predominância de vegetação aquática","A predominância de florestas de coníferas"],"B",2,58)
    add("humanas","geografia","Leia o texto abaixo para responder à questão.","A globalização econômica transformou as relações comerciais internacionais a partir da década de 1990. O Brasil, como país emergente, inseriu-se nesse processo.","Uma das consequências da globalização para o Brasil foi:",["O isolamento econômico do país","A intensificação dos fluxos migratórios e culturais","A redução do comércio internacional","O retorno ao protecionismo econômico","A diminuição da concorrência internacional"],"B",2,55)
    add("humanas","geografia","Leia o texto abaixo para responder à questão.","A urbanização brasileira acelerou-se a partir da década de 1950, com a migração massiva de trabalhadores do campo para as cidades. Em 2009, aproximadamente 86% da população vivia em áreas urbanas.","A urbanização acelerada gerou problemas como:",["A diminuição da violência urbana","O crescimento desordenado das periferias e a falta de infraestrutura","A equalização da distribuição de renda","A melhoria da qualidade de vida em todas as áreas","A redução da migração do campo para a cidade"],"B",1,82)
    add("humanas","geografia","Leia o texto abaixo para responder à questão.","O Brasil é um dos maiores produtores de soja do mundo. A expansão da soja trouxe benefícios econômicos, mas também preocupações ambientais como o desmatamento.","A expansão da cultura da soja trouxe preocupações ambientais como:",["A redução do uso de agrotóxicos","O desmatamento e o uso intensivo de agrotóxicos","A preservação de todas as matas","A melhoria da qualidade do solo","A diminuição da emissão de gases de efeito estufa"],"B",2,60)
    add("humanas","geografia","Leia o texto abaixo para responder à questão.","A Amazônia é o maior bioma do Brasil, cobrindo aproximadamente 49% do território nacional. A floresta desempenha um papel fundamental na regulação do clima global.","Um dos papéis fundamentais da Floresta Amazônica é:",["Aumentar a temperatura global","A regulação do clima global","Diminuir a biodiversidade","Aumentar o desmatamento em outras regiões","A redução da umidade no ar"],"B",1,88)
    add("humanas","geografia","Leia o texto abaixo para responder à questão.","A questão agrária brasileira é um dos temas mais complexos da história do país. A concentração de terras é herança do período colonial, quando as sesmarias foram concedidas a famílias fidalgas.","A questão agrária brasileira é herança de qual período histórico?",["O período republicano","O período colonial, com a concessão de sesmarias","O período imperial","O período da redemocratização","O período da Era Vargas"],"B",2,57)
    add("humanas","geografia","Leia o texto abaixo para responder à questão.","O Nordeste brasileiro é uma região marcada por profundas desigualdades. Programas sociais como o Bolsa Família e o Fome Zero contribuíram para a melhoria das condições de vida.","Os programas sociais implementados no Nordeste contribuíram para:",["Aumentar as desigualdades sociais","A melhoria das condições de vida da população nordestina","A eliminação de todos os problemas da região","A migração de toda a população para o Sudeste","A diminuição da oferta de empregos na região"],"B",2,65)
    add("humanas","geografia","Leia o texto abaixo para responder à questão.","O mercado de trabalho brasileiro enfrenta o problema da informalidade. Em 2009, a taxa de informalidade era de aproximadamente 48%.","A informalidade no mercado de trabalho brasileiro significa que:",["Todos os trabalhadores possuem direitos trabalhistas","Muitos trabalhadores não possuem carteira assinada e direitos trabalhistas","O mercado de trabalho está completamente formalizado","A maioria dos trabalhadores possui qualificação profissional","A taxa de desemprego é muito baixa"],"B",1,84)
    add("humanas","geografia","Leia o texto abaixo para responder à questão.","A degradação ambiental é causada pelo desmatamento, pela poluição dos rios e pela emissão de gases poluentes. O Brasil tem responsabilidade especial na preservação ambiental.","Uma das principais causas da degradação ambiental no Brasil é:",["A criação de unidades de conservação","O desmatamento, a poluição dos rios e a emissão de gases poluentes","A implementação de políticas públicas ambientais","A preservação da biodiversidade","O investimento em energia renovável"],"B",2,56)
    add("humanas","geografia","Leia o texto abaixo para responder à questão.","A Bolsa Família transfere diretamente às famílias em situação de vulnerabilidade social uma renda mensal, condicionada à frequência escolar dos filhos e à vacinação.","Uma das condições para receber o benefício do Bolsa Família é:",["Manter os filhos fora da escola","Manter a frequência escolar dos filhos e a vacinação em dia","Trabalhar no setor formal","Viver em áreas urbanas","Ter renda familiar acima de 5 salários mínimos"],"B",1,86)
    add("humanas","geografia","Leia o texto abaixo para responder à questão.","O MERCOSUL, criado em 1991 pelo Tratado de Assunção, é um bloco econômico formado por Brasil, Argentina, Paraguai e Uruguai. O objetivo principal é a integração econômica.","O MERCOSUL tem como objetivo:",["O isolamento econômico de seus membros","A integração econômica através de uma zona de livre comércio","A criação de uma moeda única para todos os países","A proibição de comércio entre os membros","O controle político dos governos membros"],"B",2,58)
    add("humanas","geografia","Leia o texto abaixo para responder à questão.","O Brasil possui uma das maiores reservas de água doce do mundo. No entanto, a distribuição desigual gera problemas de abastecimento em diversas regiões.","A distribuição da água doce no Brasil é:",["Uniforme em todas as regiões","Desigual, com concentração na região Norte","Desigual, com concentração na região Nordeste","Uniforme apenas nas regiões Sul e Sudeste","Desigual apenas em áreas urbanas"],"B",2,55)
    add("humanas","geografia","Leia o texto abaixo para responder à questão.","A fronteira agrícola do Brasil avança sobre a Floresta Amazônica, gerando conflitos ambientais e sociais. Aso desmatamento amazônico é um dos maiores desafios ambientais do país.","O desmatamento amazônico é causado principalmente por:",["Expansão da indústria tecnológica","Avanço da fronteira agrícola sobre a floresta","Crescimento do turismo ecológico","Implantação de parques nacionais","Expansão da mineração sustentável"],"B",2,60)
    add("humanas","geografia","Leia o texto abaixo para responder à questão.","As grandes metrópoles brasileiras enfrentam problemas como congestionamentos, poluição do ar e falta de moradia. São Paulo, por exemplo, tem mais de 20 milhões de habitantes na região metropolitana.","Os problemas das grandes metrópoles brasileiras incluem:",["Melhoria da qualidade do ar","Congestionamentos e poluição do ar","Redução da violência urbana","Aumento da oferta de moradia","Diminuição da população"],"B",1,80)
    add("humanas","geografia","Leia o texto abaixo para responder à questão.","O Brasil é um dos maiores produtores de café do mundo. A cultura do café foi fundamental para o desenvolvimento econômico do país no século XIX e início do século XX.","A cultura do café foi importante para o Brasil porque:",["Eliminou a pobreza no país","Impulsionou o desenvolvimento econômico do século XIX","Causou a diminuição da população","Reduziu a exportação de produtos agrícolas","Eliminou a necessidade de mão de obra escravizada"],"B",2,57)
    
    # HUMANAS - Sociologia (8)
    add("humanas","sociologia","Leia o texto abaixo para responder à questão.","A exclusão social é um dos problemas mais graves que afetam a sociedade brasileira. Milhões de pessoas vivem à margem da sociedade, sem acesso a serviços básicos.","A exclusão social é causada por fatores como:",["A igualdade de renda entre todos os cidadãos","A desigualdade de renda, a falta de qualificação profissional e barreiras culturais","O excesso de oportunidades educacionais","A abundância de empregos formais","A igualdade de acesso a serviços básicos"],"B",1,82)
    add("humanas","sociologia","Leia o texto abaixo para responder à questão.","A violência urbana no Brasil é um fenômeno complexo que envolve fatores econômicos, sociais e culturais. Em 2009, o Brasil apresentava uma das maiores taxas de homicídio do mundo.","Um dos fatores que contribui para a violência urbana no Brasil é:",["A abundância de oportunidades educacionais","A desigualdade social e a falta de oportunidades nas periferias","O excesso de investimentos em programas sociais","A diminuição da população urbana","A melhoria das condições de moradia em todas as áreas"],"B",2,54)
    add("humanas","sociologia","Leia o texto abaixo para responder à questão.","A discriminação racial no Brasil tem raízes históricas na escravidão. Pesquisas revelam que pretos e pardos recebem salários menores e têm menos acesso a posições de liderança.","A desigualdade racial no Brasil se manifesta em áreas como:",["Apenas no mercado de trabalho","Educação, saúde e mercado de trabalho","Apenas na política","Apenas na área de lazer","Apenas na religião"],"B",2,60)
    add("humanas","sociologia","Leia o texto abaixo para responder à questão.","A mobilidade social refere-se à capacidade de um indivíduo mudar sua posição na estrutura social. No Brasil, a mobilidade social é limitada por fatores como a desigualdade de renda.","O principal fator de mobilidade social no Brasil é:",["A renda familiar","A educação","A religião","O local de nascimento","A cor da pele"],"B",1,85)
    add("humanas","sociologia","Leia o texto abaixo para responder à questão.","A democratização do acesso à informação, impulsionada pela internet, transformou as relações sociais e políticas. A inclusão digital passou a ser uma questão de cidadania.","A democratização do acesso à informação pela internet trouxe desafios como:",["Aumentar a desigualdade de acesso à informação","A desinformação e a violência virtual","Diminuir o número de usuários de internet","Eliminar a liberdade de expressão","Aumentar o custo da tecnologia"],"B",2,58)
    add("humanas","sociologia","Leia o texto abaixo para responder à questão.","A mobileidade social é limitada por fatores como a desigualdade de renda, a baixa qualidade da educação pública e a falta de acesso a oportunidades.","A educação é apontada como:",["O principal obstáculo à mobilidade social","O principal fator de mobilidade social","Um fator irrelevante para a mobilidade social","Um obstáculo para o desenvolvimento econômico","Um direito que não afeta a mobilidade social"],"B",2,55)
    add("humanas","sociologia","Leia o texto abaixo para responder à questão.","O crescimento das grandes cidades, associado à desigualdade social e à falta de oportunidades, contribui para a escalada da violência urbana no Brasil.","A violência urbana afeta especialmente:",["As classes altas das grandes cidades","As camadas mais pobres da população em bairros periféricos","Os moradores do campo","Os estudantes universitários","Os trabalhadores do setor formal"],"B",2,55)
    add("humanas","sociologia","Leia o texto abaixo para responder à questão.","A questão da moradia é um dos principais desafios sociais do Brasil contemporâneo. Milhões de brasileiros vivem em condições precárias, sem acesso a moradia digna.","A falta de moradia digna afeta especialmente:",["Os trabalhadores de alto poder aquisitivo","Os moradores de bairros nobles","As famílias de baixa renda em áreas periféricas","Os estudantes de escolas particulares","Os proprietários de imóveis"],"C",2,56)
    
    # HUMANAS - Filosofia (7)
    add("humanas","filosofia","Leia o texto abaixo para responder à questão.","A ética é um ramo da filosofia que estuda os princípios morais que orientam o comportamento humano. Filósofos como Kant e Aristóteles formularam teorias éticas fundamentais.","A ética é um ramo da filosofia que estuda:",["A origem do universo","Os princípios morais que orientam o comportamento humano","As leis da física","A estrutura da linguagem","A organização da sociedade"],"B",1,88)
    add("humanas","filosofia","Leia o texto abaixo para responder à questão.","O existencialismo é uma corrente filosófica que surgiu no século XX, com pensadores como Jean-Paul Sartre e Simone de Beauvoir. O existencialismo defende que o ser humano é responsável por suas escolhas.","O existencialismo defende que:",["O ser humano não tem liberdade de escolha","O ser humano é responsável por suas escolhas e pela construção de seu próprio sentido de vida","O destino é predeterminado","A sociedade define completamente o comportamento individual","A razão é irrelevante para a vida humana"],"B",2,55)
    add("humanas","filosofia","Leia o texto abaixo para responder à questão.","A filosofia política estuda as relações de poder, o Estado e a organização da sociedade. Pensadores como Hobbes, Locke e Rousseau influenciaram a constituição de diversos países.","A filosofia política estuda:",["A natureza do universo","As relações de poder, o Estado e a organização da sociedade","As leis da física","A estrutura da linguagem","A história da arte"],"B",2,60)
    add("humanas","filosofia","Leia o texto abaixo para responder à questão.","O relativismo defende que não existem verdades absolutas, mas sim verdades relativas a cada cultura e contexto histórico. No Brasil multicultural, o relativismo pode promover o respeito à diversidade.","O relativismo filosófico defende que:",["Existem verdades absolutas para todas as culturas","Não existem verdades absolutas, mas sim verdades relativas a cada cultura","Todas as culturas possuem os mesmos valores","A ciência é a única fonte de verdade","A religião é a única fonte de moralidade"],"B",3,38)
    add("humanas","filosofia","Leia o texto abaixo para responder à questão.","A estética é o ramo da filosofia que estuda a natureza da beleza e da arte. Filósofos como Hegel e Schopenhauer formularam teorias estéticas que influenciaram a produção artística brasileira.","A estética é o ramo da filosofia que estuda:",["A origem do universo","A natureza da beleza e da arte","As leis da física","A estrutura da linguagem","A organização da sociedade"],"B",1,85)
    add("humanas","filosofia","Leia o texto abaixo para responder à questão.","A lógica é o ramo da filosofia que estuda os princípios do raciocínio válido. É fundamental para o desenvolvimento do pensamento crítico e para a formulação de argumentos consistentes.","A lógica é o ramo da filosofia que estuda:",["A origem do universo","Os princípios do raciocínio válido","As leis da física","A estrutura da linguagem","A organização da sociedade"],"B",1,82)
    add("humanas","filosofia","Leia o texto abaixo para responder à questão.","A epistemologia é o ramo da filosofia que estuda o conhecimento humano, sua origem, natureza e limites. Filósofos como Platão, Descartes e Kant formularam teorias epistemológicas fundamentais.","A epistemologia estuda:",["A origem do universo","O conhecimento humano, sua origem, natureza e limites","As leis da física","A estrutura da linguagem","A organização da sociedade"],"B",2,58)
    
    # NATUREZA - Física (15)
    add("natureza","fisica","Leia o texto abaixo para responder à questão.","Uma bola é lançada verticalmente para cima com velocidade inicial de 20 m/s. Desprezando a resistência do ar e considerando g = 10 m/s².","Qual é a altura máxima atingida pela bola?",["10 m","15 m","20 m","25 m","30 m"],"C",2,55)
    add("natureza","fisica","Leia o texto abaixo para responder à questão.","Dois corpos de massas 2 kg e 3 kg estão separados por uma distância de 1 m. A força gravitacional entre eles pode ser calculada pela Lei de Newton.","Se a distância entre os corpos for dobrada, a força gravitacional será:",["Quatro vezes menor","Duas vezes menor","Igual","Duas vezes maior","Quatro vezes maior"],"B",2,52)
    add("natureza","fisica","Leia o texto abaixo para responder à questão.","Um resistor de 10 Ω é conectado a uma bateria de 5 V. A corrente pode ser calculada pela Lei de Ohm (I = V/R).","Qual é a corrente que circula pelo resistor?",["0,2 A","0,5 A","2 A","5 A","50 A"],"B",1,85)
    add("natureza","fisica","Leia o texto abaixo para responder à questão.","Um corpo de 5 kg parte do repouso e percorre 20 m em 4 s com aceleração constante.","Qual é a aceleração do corpo?",["1,25 m/s²","2,5 m/s²","5 m/s²","10 m/s²","20 m/s²"],"B",2,58)
    add("natureza","fisica","Leia o texto abaixo para responder à questão.","A energia cinética de um corpo pode ser calculada pela fórmula Ec = mv²/2. Um corpo de 10 kg tem velocidade de 4 m/s.","Qual é a energia cinética do corpo?",["40 J","80 J","160 J","200 J","400 J"],"B",2,56)
    add("natureza","fisica","Leia o texto abaixo para responder à questão.","Um carro viaja a 72 km/h e freia com aceleração constante de -4 m/s² até parar.","Qual é a distância percorrida até parar?",["25 m","50 m","100 m","150 m","200 m"],"B",2,60)
    add("natureza","fisica","Leia o texto abaixo para responder à questão.","Uma onda sonora tem frequência de 440 Hz e velocidade de propagação de 340 m/s.","Qual é o comprimento de onda?",["0,5 m","0,77 m","1 m","1,5 m","2 m"],"B",2,55)
    add("natureza","fisica","Leia o texto abaixo para responder à questão.","Um circuito elétrico possui três resistores de 6 Ω conectados em paralelo.","Qual é a resistência equivalente do circuito?",["2 Ω","3 Ω","6 Ω","12 Ω","18 Ω"],"A",2,52)
    add("natureza","fisica","Leia o texto abaixo para responder à questão.","Um planeta orbita uma estrela a 3 unidades astronômicas. Segundo a terceira lei de Kepler, o período orbital é dado por T² = a³.","Qual é o período orbital em anos?",["3 anos","5,2 anos","9 anos","27 anos","81 anos"],"C",3,38)
    add("natureza","fisica","Leia o texto abaixo para responder à questão.","A pressão atmosférica ao nível do mar é de 1 atm. Em uma profundidade de 10 m na água, a pressão aumenta aproximadamente 1 atm a cada 10 m.","Qual é a pressão total a 10 m de profundidade?",["1 atm","2 atm","3 atm","10 atm","11 atm"],"B",2,55)
    add("natureza","fisica","Leia o texto abaixo para responder à questão.","A velocidade da luz no vácuo é de 300.000 km/s. A distância Terra-Sol é de 150 milhões de km.","Qual é o tempo que a luz leva para viajar do Sol até a Terra?",["5 minutos","8 minutos","10 minutos","15 minutos","20 minutos"],"B",1,82)
    add("natureza","fisica","Leia o texto abaixo para responder à questão.","O coeficiente de atrito cinético entre um bloco e uma superfície é 0,3. A massa do bloco é 10 kg e g = 10 m/s².","Qual é a força de atrito cinético?",["3 N","10 N","30 N","33 N","100 N"],"C",2,55)
    add("natureza","fisica","Leia o texto abaixo para responder à questão.","Em um circuito série com duas baterias de 9V cada e um resistor de 36 Ω, a corrente pode ser calculada pela Lei de Ohm.","Qual é a corrente no circuito?",["0,25 A","0,5 A","1 A","2 A","4 A"],"B",1,80)
    add("natureza","fisica","Leia o texto abaixo para responder à questão.","Uma mola de constante elástica k = 200 N/m é comprimida 0,1 m. A energia potencial elástica é Ep = kx²/2.","Qual é a energia potencial elástica?",["0,5 J","1 J","2 J","5 J","10 J"],"B",2,50)
    add("natureza","fisica","Leia o texto abaixo para responder à questão.","Um dipolo magnético é formado por duas cargas opostas. A força entre cargas é descrita pela Lei de Coulomb: F = k.q1.q2/r².","Se a distância entre as cargas for reduzida pela metade, a força será:",["Quatro vezes menor","Duas vezes menor","Igual","Duas vezes maior","Quatro vezes maior"],"E",3,38)
    
    # NATUREZA - Química (15)
    add("natureza","quimica","Leia o texto abaixo para responder à questão.","A água é composta por dois átomos de hidrogênio e um átom de oxigênio, formando H₂O. A massa atômica do H é 1 u e do O é 16 u.","Qual é a massa molecular da água?",["9 u","16 u","18 u","34 u","36 u"],"C",1,85)
    add("natureza","quimica","Leia o texto abaixo para responder à questão.","Uma solução é preparada dissolvendo 40 g de NaCl em 1 litro de água. A massa molar do NaCl é 58,5 g/mol.","Qual é a molaridade da solução?",["0,34 mol/L","0,58 mol/L","0,68 mol/L","1 mol/L","1,5 mol/L"],"C",2,55)
    add("natureza","quimica","Leia o texto abaixo para responder à questão.","O pH de uma solução é calculado pela fórmula pH = -log[H⁺]. Para uma solução de HCl 0,01 mol/L, o pH é:","Qual é o pH da solução?",["1","2","3","4","7"],"B",2,58)
    add("natureza","quimica","Leia o texto abaixo para responder à questão.","Em uma reação química, 2 mol de hidrogênio reagem com 1 mol de oxigênio para formar 2 mol de água. Se houver 4 mol de H₂ e 3 mol de O₂.","Qual é o reagente limitante?",["H₂","O₂","Ambos na mesma quantidade","Nenhum, ambos estão em excesso","Não é possível determinar"],"B",2,60)
    add("natureza","quimica","Leia o texto abaixo para responder à questão.","O ciclo do carbono envolve processos como fotossíntese e respiração. Na fotossíntese, a planta absorve CO₂ e libera O₂.","Na fotossíntese, o gás absorvido pela planta é:",["O₂","N₂","CO₂","H₂","CH₄"],"C",1,82)
    add("natureza","quimica","Leia o texto abaixo para responder à questão.","A tabela periódica organiza os elementos químicos por número atômico crescente. O elemento de número atômico 6 é o carbono.","Qual é o elemento de número atômico 6?",["Boro","Carbono","Nitrogênio","Oxigênio","Flúor"],"B",1,88)
    add("natureza","quimica","Leia o texto abaixo para responder à questão.","Uma reação de neutralização ocorre entre HCl e NaOH, formando NaCl e H₂O. Esse tipo de reação é caracterizado pela formação de sal e água.","O produto da neutralização entre HCl e NaOH é:",["H₂ e O₂","NaCl e H₂O","HCl e NaOH","NaOH e H₂O","NaCl e H₂"],"B",1,85)
    add("natureza","quimica","Leia o texto abaixo para responder à questão.","O ferro é um metal que oxida na presença de oxigênio e água, formando hidróxido de ferro III, conhecido como ferrugem.","A fórmula química da ferrugem (hidróxido de ferro III) é:",["FeO","Fe₂O₃","Fe(OH)₃","Fe₂(CO₃)₃","FeSO₄"],"C",2,58)
    add("natureza","quimica","Leia o texto abaixo para responder à questão.","Em uma reação endotérmica, o sistema absorve calor do meio ambiente. Isso ocorre, por exemplo, na dissolução de nitrato de amônia em água.","Em uma reação endotérmica, a entalpia (ΔH) é:",["Positiva","Negativa","Zero","Não se aplica","Depende da temperatura"],"A",2,55)
    add("natureza","quimica","Leia o texto abaixo para responder à questão.","O ozônio (O₃) é uma molécula formada por três átomos de oxigênio que forma a camada de ozônio, protegendo a Terra da radiação ultravioleta.","A camada de ozônio protege a Terra de:",["Radiação infravermelha","Radiação ultravioleta","Radiação X","Raios cósmicos","Micro-ondas"],"B",1,80)
    add("natureza","quimica","Leia o texto abaixo para responder à questão.","Um gás ideal a 300 K e pressão de 2 atm ocupa volume de 5 L. Se a pressão for duplicada mantendo a temperatura constante, o volume muda conforme a lei de Boyle (P₁V₁ = P₂V₂).","Qual será o novo volume do gás?",["2,5 L","5 L","10 L","20 L","40 L"],"A",2,52)
    add("natureza","quimica","Leia o texto abaixo para responder à questão.","A água fervendo a 100°C ao nível do mar tem energia de vaporização de 2.260 kJ/kg.","Para vaporizar 2 kg de água a 100°C, é necessária energia de:",["2.260 kJ","4.520 kJ","9.040 kJ","1.130 kJ","11.300 kJ"],"B",2,56)
    add("natureza","quimica","Leia o texto abaixo para responder à questão.","Em uma pilha galvânica, a reação de oxidação ocorre no ânodo e a de redução no cátodo. O ânodo é o eletrodo negativo.","Na pilha galvânica, o ânodo é:",["O eletrodo onde ocorre redução","O eletrodo onde ocorre oxidação","O eletrodo positivo","O eletrodo de cobre","O eletrodo de prata"],"B",3,38)
    add("natureza","quimica","Leia o texto abaixo para responder à questão.","O conceito de pH foi desenvolvido por Sørensen em 1909. Soluções com pH menores que 7 são ácidas, iguais a 7 são neutras e maiores que 7 são básicas.","Uma solução com pH = 7 é considerada:",["Ácida","Básica","Neutra","Supersaturada","Calorosa"],"C",1,85)
    add("natureza","quimica","Leia o texto abaixo para responder à questão.","A combustão completa de metano (CH₄) produz dióxido de carbono (CO₂) e água (H₂O). Essa reação é utilizada em fogões a gás.","Na combustão completa do metano, os produtos são:",["CO e H₂","CO₂ e H₂O","C e H₂O","CO₂ e H₂","CH₃OH e O₂"],"B",1,80)
    
    # NATUREZA - Biologia (15)
    add("natureza","biologia","Leia o texto abaixo para responder à questão.","A fotossíntese é o processo pelo qual as plantas convertem energia luminosa em energia química, produzindo glicose e oxigênio a partir de CO₂ e H₂O.","Na fotossíntese, o gás absorvido pelas plantas é:",["O₂","N₂","CO₂","H₂","CH₄"],"C",1,85)
    add("natureza","biologia","Leia o texto abaixo para responder à questão.","O DNA é uma molécula que carrega as informações genéticas. A duplicação do DNA ocorre antes da divisão celular, garantindo que cada célula-filha receba uma cópia completa do material genético.","A duplicação do DNA ocorre durante:",["Prófase da mitose","Interfase (fase S)","Metáfase da mitose","Anáfase da mitose","Citocinese"],"B",2,58)
    add("natureza","biologia","Leia o texto abaixo para responder à questão.","As mitocôndrias são organelas responsáveis pela respiração celular, produzindo ATP a partir de glicose e oxigênio. Elas são conhecidas como as 'usinas de energia' da célula.","A função principal das mitocôndrias é:",["Realizar fotossíntese","Produzir ATP através da respiração celular","Sintetizar proteínas","Armazenar água","Degrader resíduos celulares"],"B",1,88)
    add("natureza","biologia","Leia o texto abaixo para responder à questão.","A seleção natural, proposta por Charles Darwin, é o mecanismo pelo qual organismos melhor adaptados ao ambiente têm maior chance de sobreviver e reproduzir.","A seleção natural favorece:",["Organismos menos adaptados ao ambiente","Organismos que se reproduzem mais rapidamente","Organismos melhor adaptados ao ambiente","Organismos maiores","Organismos de cor mais chamativa"],"C",2,60)
    add("natureza","biologia","Leia o texto abaixo para responder à questão.","O sistema circulatório é composto pelo coração, vasos sanguíneos e sangue. O sangue arterial é rico em oxigênio e é transportado do coração para os tecidos do corpo.","O sangue arterial é transportado pelo:",["Veias","Artérias","Capilares","Vênulas","Arteríolas"],"B",1,82)
    add("natureza","biologia","Leia o texto abaixo para responder à questão.","O ciclo do nitrogênio envolve processos como fixação biológica, nitrificação e desnitrificação. Bactérias do gênero Rhizobium fixam o nitrogênio atmosférico em nódulos radiculares.","As bactérias que fixam nitrogênio são:",["Escherichia coli","Rhizobium","Staphylococcus","Lactobacillus","Streptococcus"],"B",2,56)
    add("natureza","biologia","Leia o texto abaixo para responder à questão.","A mitose é um processo de divisão celular que resulta em duas células-filhas geneticamente idênticas à célula-mãe. O número cromossômico é mantido.","Na mitose, o número cromossômico:",["É reduzido pela metade","Dobra","Permanece igual","Varia aleatoriamente","É multiplicado por 3"],"C",1,85)
    add("natureza","biologia","Leia o texto abaixo para responder à questão.","O ecossistema é composto por fatores bióticos (seres vivos) e abióticos (fatores físicos). A energia flui do sol para os produtores primários.","No ecossistema, os produtores primários são:",["Animais herbívoros","Plantas e algas","Fungos decompositores","Bactérias decompositoras","Animais carnívoros"],"B",1,80)
    add("natureza","biologia","Leia o texto abaixo para responder à questão.","A evolução das espécies pode ocorrer por especiação alopátrica, quando populações são isoladas geograficamente e evoluem independentemente.","A especiação alopátrica ocorre quando:",["Populações se misturam livremente","Populações são isoladas geograficamente","Mutações ocorrem em alta frequência","Seleção natural não atua","Migração é constante"],"B",2,55)
    add("natureza","biologia","Leia o texto abaixo para responder à questão.","O pâncreas é uma glândula que produz insulina, hormônio responsável pela regulação da glicose no sangue. A falta de insulina causa diabetes.","A insulina é produzida pelo:",["Fígado","Rins","Pâncreas","Estômago","Intestino delgado"],"C",1,85)
    add("natureza","biologia","Leia o texto abaixo para responder à questão.","A fotossíntese ocorre em dois estágios: reações luminosas e ciclo de Calvin. As reações luminosas ocorrem nos tilacóides dos cloroplastos.","As reações luminosas da fotossíntese ocorrem nos:",["Ribossomos","Tilacóides dos cloroplastos","Membrana nuclear","Mitocôndrias","Complexo de Golgi"],"B",2,52)
    add("natureza","biologia","Leia o texto abaixo para responder à questão.","Os anticorpos são proteínas produzidas pelo sistema imunológico para combater patógenos específicos. Cada anticorpo é produzido por uma célula B específica.","Os anticorpos são produzidos pelas:",["Hemácias","Plaquetas","Células B (linfócitos B)","Células T (linfócitos T)","Neutrófilos"],"C",2,58)
    add("natureza","biologia","Leia o texto abaixo para responder à questão.","A síndrome de Down é causada pela trissomia do cromossomo 21, resultando em 47 cromossomos ao invés de 46. É a trissomia mais comum em seres humanos.","Na síndrome de Down, o número de cromossomos é:",["45","46","47","48","49"],"C",1,82)
    add("natureza","biologia","Leia o texto abaixo para responder à questão.","O genoma humano contém aproximadamente 20.000-25.000 genes. Mutações podem ser neutras, benéficas ou prejudiciais ao organismo.","Uma mutação neutra é aquela que:",["Causa doenças graves","Aumenta a adaptação ao ambiente","Não produz efeito fenotípico perceptível","É sempre transmitida aos descendentes","Ocorre apenas em células somáticas"],"C",3,35)
    add("natureza","biologia","Leia o texto abaixo para responder à questão.","A cadeia alimentar é uma sequência de organismos onde cada um é alimento do próximo. Em uma cadeia com grama → gafanhoto → rato → cobra.","O gafanhoto na cadeia alimentar é:",["Produtor","Consumidor primário","Consumidor secundário","Consumidor terciário","Decompositor"],"B",1,80)
    
    # MATEMÁTICA - Álgebra (15)
    add("matematica","algebra","Leia o texto abaixo para responder à questão.","Em 2009, o PIB brasileiro registrou contração de 0,3%. Se o PIB anterior era R$ 3,1 trilhões, o valor em 2009 foi calculado multiplicando R$ 3,1 trilhões por 0,997.","Qual foi o valor aproximado do PIB em 2009?",["R$ 3,090 trilhões","R$ 3,091 trilhões","R$ 3,097 trilhões","R$ 3,109 trilhões","R$ 3,110 trilhões"],"B",2,52)
    add("matematica","algebra","Leia o texto abaixo para responder à questão.","Uma empresa contratou 150 funcionários. 60% são homens e 40% são mulheres. Entre as mulheres, 25% trabalham no setor de desenvolvimento.","Quantas mulheres trabalham no setor de desenvolvimento?",["15","20","25","30","35"],"A",1,85)
    add("matematica","algebra","Leia o texto abaixo para responder à questão.","O custo de produção de um smartphone aumentou 15% entre 2010 e 2011. Se o custo em 2010 era R$ 800,00, o custo em 2011 foi R$ 800 × 1,15.","Qual foi o custo em 2011?",["R$ 850,00","R$ 880,00","R$ 920,00","R$ 950,00","R$ 1.000,00"],"C",1,82)
    add("matematica","algebra","Leia o texto abaixo para responder à questão.","A receita de uma empresa cresce a uma taxa de 8% ao mês. Em janeiro, a receita foi R$ 50.000. Em março (2 meses depois), a receita é R$ 50.000 × (1,08)².","Qual será a receita em março?",["R$ 54.000,00","R$ 58.320,00","R$ 62.985,60","R$ 56.160,00","R$ 60.000,00"],"B",2,55)
    add("matematica","algebra","Leia o texto abaixo para responder à questão.","Um investidor aplicou R$ 10.000 em uma poupança que rende 0,5% ao mês. Após 12 meses, o valor é R$ 10.000 × (1,005)¹².","Qual será o valor aproximado após 12 meses?",["R$ 10.500,00","R$ 10.600,00","R$ 10.616,78","R$ 10.700,00","R$ 10.800,00"],"C",2,50)
    add("matematica","algebra","Leia o texto abaixo para responder à questão.","A equação 2x + 5 = 15 representa a relação entre o preço de um produto (x) e seu custo total. Para encontrar x, subtraímos 5 de ambos os lados e dividimos por 2.","Qual é o valor de x?",["x = 3","x = 5","x = 7","x = 10","x = 12"],"B",1,88)
    add("matematica","algebra","Leia o texto abaixo para responder à questão.","Uma progressão aritmética tem primeiro termo igual a 3 e razão igual a 5. O 10º termo é dado por a₁₀ = a₁ + (n-1)r = 3 + 9×5.","Qual é o 10º termo dessa PA?",["48","50","53","55","58"],"C",2,58)
    add("matematica","algebra","Leia o texto abaixo para responder à questão.","Uma fábrica produz 200 unidades por dia. Se a produção aumenta 5% a cada dia, no terceiro dia serão produzidas 200 × (1,05)² = 200 × 1,1025.","Quantas unidades serão produzidas no terceiro dia?",["210","220,5","225","230,5","240"],"B",2,52)
    add("matematica","algebra","Leia o texto abaixo para responder à questão.","A área de um terreno retangular é dada por A = (2x + 3)(x + 2). Se x = 4 metros, A = (8+3)(4+2) = 11 × 6 = 66 m².","Qual é a área do terreno?",["42 m²","54 m²","66 m²","72 m²","84 m²"],"C",2,56)
    add("matematica","algebra","Leia o texto abaixo para responder à questão.","Um aluno tirou notas 7, 8 e 9 em três provas. A primeira prova tem peso 2, a segunda peso 3 e a terceira peso 5. A média ponderada é (7×2 + 8×3 + 9×5) / (2+3+5).","Qual é a média ponderada das notas?",["7,5","8,0","8,3","8,5","9,0"],"C",1,75)
    add("matematica","algebra","Leia o texto abaixo para responder à questão.","A expressão (3x² + 2x - 5) - (x² - 4x + 3) representa a diferença entre dois polinômios. Simplificando: 3x² - x² + 2x + 4x - 5 - 3.","Qual é o resultado simplificado?",["2x² + 6x - 8","2x² - 2x - 2","4x² + 6x - 2","2x² + 2x - 8","2x² - 6x + 8"],"A",2,50)
    add("matematica","algebra","Leia o texto abaixo para responder à questão.","Um investidor divide R$ 24.000 em duas partes: uma rende 10% e outra 15% ao ano. O rendimento total foi R$ 3.000. Se x é a primeira parte: 0,10x + 0,15(24000-x) = 3000.","Qual foi o valor da primeira parte?",["R$ 10.000","R$ 12.000","R$ 14.000","R$ 16.000","R$ 18.000"],"B",3,35)
    add("matematica","algebra","Leia o texto abaixo para responder à questão.","A equação x² - 5x + 6 = 0 pode ser resolvida por fatoração: (x-2)(x-3) = 0. Portanto, x = 2 ou x = 3.","Quais são as raízes da equação x² - 5x + 6 = 0?",["x = 1 e x = 6","x = 2 e x = 3","x = -2 e x = -3","x = -1 e x = -6","x = 0 e x = 5"],"B",1,80)
    add("matematica","algebra","Leia o texto abaixo para responder à questão.","Uma empresa tem faturamento mensal descrito por f(x) = 200x + 5.000, onde x é o número de meses. No 10º mês, f(10) = 200×10 + 5.000.","Qual será o faturamento no 10º mês?",["R$ 5.200","R$ 7.000","R$ 25.000","R$ 5.500","R$ 10.000"],"B",1,85)
    add("matematica","algebra","Leia o texto abaixo para responder à questão.","O sistema linear representado pelas equações x + y = 10 e x - y = 4 pode ser resolvido somando as equações: 2x = 14, logo x = 7 e y = 3.","Qual é a solução do sistema?",["x = 7, y = 3","x = 6, y = 4","x = 5, y = 5","x = 8, y = 2","x = 3, y = 7"],"A",2,60)
    
    # MATEMÁTICA - Geometria (15)
    add("matematica","geometria","Leia o texto abaixo para responder à questão.","Um terreno retangular tem comprimento igual a 30 metros e largura igual a 20 metros. O perímetro é dado por P = 2(c + l).","Qual é o perímetro do terreno?",["50 m","100 m","600 m","150 m","200 m"],"B",1,85)
    add("matematica","geometria","Leia o texto abaixo para responder à questão.","A área de um círculo é dada pela fórmula A = πr². O raio de um círculo é 7 cm. Usando π ≈ 3,14, A = 3,14 × 7² = 3,14 × 49 = 153,86 ≈ 154 cm².","Qual é a área aproximada do círculo?",["154 cm²","144 cm²","150 cm²","160 cm²","165 cm²"],"A",1,80)
    add("matematica","geometria","Leia o texto abaixo para responder à questão.","Um triângulo retângulo tem catetos medindo 6 cm e 8 cm. A hipotenusa pode ser calculada pelo Teorema de Pitágoras: c² = a² + b².","Qual é a medida da hipotenusa?",["10 cm","12 cm","14 cm","15 cm","16 cm"],"A",1,82)
    add("matematica","geometria","Leia o texto abaixo para responder à questão.","A diagonal de um quadrado mede 10 cm. Se a diagonal é d = a√2, então a = d/√2 = 10/√2 ≈ 7,07 cm. A área é a² = (10/√2)² = 50 cm².","Qual é a área do quadrado?",["25 cm²","50 cm²","100 cm²","20 cm²","40 cm²"],"B",2,58)
    add("matematica","geometria","Leia o texto abaixo para responder à questão.","Um cilindro tem raio da base igual a 5 cm e altura igual a 10 cm. O volume é V = πr²h = 3,14 × 25 × 10 = 785 cm³.","Qual é o volume aproximado do cilindro?",["785 cm³","157 cm³","314 cm³","500 cm³","250 cm³"],"A",2,55)
    add("matematica","geometria","Leia o texto abaixo para responder à questão.","A área de um trapézio é dada por A = (B + b) × h / 2. As bases medem 10 cm e 6 cm, e a altura é 8 cm.","Qual é a área do trapézio?",["32 cm²","64 cm²","48 cm²","56 cm²","72 cm²"],"B",2,52)
    add("matematica","geometria","Leia o texto abaixo para responder à questão.","Uma esfera tem raio igual a 3 cm. O volume é V = 4/3 × π × r³ = 4/3 × 3,14 × 27 = 113,04 ≈ 36π cm³.","Qual é o volume da esfera?",["36π cm³","27π cm³","108π cm³","12π cm³","54π cm³"],"A",3,38)
    add("matematica","geometria","Leia o texto abaixo para responder à questão.","Um cone tem raio da base igual a 4 cm e altura igual a 9 cm. O volume é V = πr²h/3 = 3,14 × 16 × 9 / 3 = 150,72 cm³.","Qual é o volume aproximado do cone?",["150,72 cm³","452,16 cm³","75,36 cm³","301,44 cm³","113,04 cm³"],"A",2,52)
    add("matematica","geometria","Leia o texto abaixo para responder à questão.","A área de um losângulo é dada por A = (D × d) / 2. As diagonais medem 10 cm e 8 cm.","Qual é a área do losângulo?",["20 cm²","40 cm²","80 cm²","18 cm²","36 cm²"],"B",2,56)
    add("matematica","geometria","Leia o texto abaixo para responder à questão.","O ângulo interno de um polígono regular de n lados é dado por (n-2) × 180° / n. Para um hexágono (n=6): (6-2) × 180° / 6 = 720° / 6 = 120°.","Qual é o ângulo interno de um hexágono regular?",["60°","90°","120°","135°","150°"],"C",2,55)
    add("matematica","geometria","Leia o texto abaixo para responder à questão.","O volume de um paralelepípedo é dado por V = A × h. A base tem área de 20 cm² e a altura é 15 cm.","Qual é o volume do paralelepípedo?",["50 cm³","150 cm³","300 cm³","350 cm³","600 cm³"],"C",1,82)
    add("matematica","geometria","Leia o texto abaixo para responder à questão.","Um círculo tem área de 78,5 cm². Usando A = πr², temos r² = 78,5 / 3,14 = 25, logo r = 5 cm.","Qual é o raio do círculo?",["2,5 cm","5 cm","7,5 cm","10 cm","15 cm"],"B",2,58)
    add("matematica","geometria","Leia o texto abaixo para responder à questão.","A distância entre os pontos A(1, 2) e B(4, 6) no plano cartesiano é d = √[(4-1)² + (6-2)²] = √[9+16] = √25 = 5.","Qual é a distância entre os pontos?",["3","4","5","7","25"],"C",2,55)
    add("matematica","geometria","Leia o texto abaixo para responder à questão.","Um cubo tem aresta de 5 cm. A área total é dada por A = 6a² = 6 × 25 = 150 cm².","Qual é a área total do cubo?",["25 cm²","50 cm²","100 cm²","125 cm²","150 cm²"],"E",2,60)
    add("matematica","geometria","Leia o texto abaixo para responder à questão.","A circunferência de um círculo é C = 2πr. Se o raio é 7 cm, C = 2 × 3,14 × 7 = 43,96 ≈ 44 cm.","Qual é a circunferência?",["22 cm","44 cm","88 cm","154 cm","308 cm"],"B",1,80)
    
    # MATEMÁTICA - Estatística (10)
    add("matematica","estatistica","Leia o texto abaixo para responder à questão.","As notas de 5 alunos são: 7, 8, 6, 9, 10. A média aritmética é a soma das notas dividida pelo número de alunos: (7+8+6+9+10)/5 = 40/5 = 8.","Qual é a média aritmética das notas?",["7","8","8,5","9","7,5"],"B",1,88)
    add("matematica","estatistica","Leia o texto abaixo para responder à questão.","Em uma pesquisa de opinião, 60 pessoas votaram em A, 30 em B e 10 em C. Total de votos: 60+30+10 = 100. A porcentagem de A é 60/100 = 60%.","Qual é a porcentagem de votos para o candidato A?",["30%","40%","50%","60%","70%"],"D",1,82)
    add("matematica","estatistica","Leia o texto abaixo para responder à questão.","Os valores 2, 4, 4, 6, 8 formam um conjunto de dados. A mediana é o valor central quando os dados são ordenados: 4.","Qual é a mediana desse conjunto?",["4","5","6","4,5","8"],"A",2,58)
    add("matematica","estatistica","Leia o texto abaixo para responder à questão.","Em um conjunto de dados, a moda é o valor que mais se repete. Nos dados 3, 5, 3, 7, 3, 8, o valor 3 aparece três vezes.","Qual é a moda?",["3","5","7","8","6"],"A",1,85)
    add("matematica","estatistica","Leia o texto abaixo para responder à questão.","O desvio padrão é uma medida de dispersão. Se todos os dados são iguais (10, 10, 10, 10, 10), não há dispersão, logo o desvio padrão é zero.","Qual é o desvio padrão desse conjunto?",["0","1","5","10","Não é possível calcular"],"A",2,55)
    add("matematica","estatistica","Leia o texto abaixo para responder à questão.","Em uma amostra de 100 pessoas, 45 são do sexo feminino. A proporção é 45/100 = 0,45.","Qual é a proporção de pessoas do sexo feminino?",["0,40","0,45","0,50","0,55","0,60"],"B",1,82)
    add("matematica","estatistica","Leia o texto abaixo para responder à questão.","A variância é a média dos quadrados das diferenças em relação à média. Se a média é 10 e os dados são 8, 10, 12, as diferenças são -2, 0, +2. Quadrados: 4, 0, 4. Média: 8/3.","Qual é a variância?",["4/3","2","8/3","4","6"],"A",3,40)
    add("matematica","estatistica","Leia o texto abaixo para responder à questão.","Em uma pesquisa, 200 pessoas foram entrevistadas. 120 preferem café. O ângulo do setor de café em um gráfico de setores é (120/200) × 360° = 0,6 × 360° = 216°.","Qual é o ângulo do setor de café?",["120°","216°","180°","90°","60°"],"B",2,52)
    add("matematica","estatistica","Leia o texto abaixo para responder à questão.","A amplitude é a diferença entre o maior e o menor valor. Nos dados 3, 7, 12, 5, 9, a amplitude é 12 - 3 = 9.","Qual é a amplitude?",["5","6","7","9","12"],"B",1,80)
    add("matematica","estatistica","Leia o texto abaixo para responder à questão.","Eventos mutuamente exclusivos não podem ocorrer simultaneamente. P(A ou B) = P(A) + P(B) = 0,3 + 0,4 = 0,7.","Qual é a probabilidade de A ou B?",["0,1","0,7","0,12","1,0","0,5"],"B",2,56)
    
    # MATEMÁTICA - Probabilidade (5)
    add("matematica","probabilidade","Leia o texto abaixo para responder à questão.","Em um lançamento de um dado honesto de 6 faces, os números pares são 2, 4 e 6 (3 resultados favoráveis). A probabilidade é 3/6 = 1/2.","Qual é a probabilidade de obter um número par?",["1/6","1/3","1/2","2/3","5/6"],"C",1,82)
    add("matematica","probabilidade","Leia o texto abaixo para responder à questão.","Uma moeda é lançada duas vezes. Os resultados possíveis são: CC, CB, BC, BB (4 resultados). Apenas CC é favorável.","Qual é a probabilidade de obter cara nas duas vezes?",["1/2","1/3","1/4","1/6","3/4"],"C",2,58)
    add("matematica","probabilidade","Leia o texto abaixo para responder à questão.","Em um saco com 5 bolas vermelhas e 3 bolas azuis, o total é 8 bolas. As vermelhas são 5, logo a probabilidade é 5/8.","Qual é a probabilidade de sortear uma bola vermelha?",["3/8","5/8","1/2","3/5","5/3"],"B",1,85)
    add("matematica","probabilidade","Leia o texto abaixo para responder à questão.","Em um baralho de 52 cartas, há 4 ás. A probabilidade de sortear um ás é 4/52 = 1/13.","Qual é a probabilidade de sortear um ás?",["1/13","1/52","4/13","1/4","1/26"],"A",2,55)
    add("matematica","probabilidade","Leia o texto abaixo para responder à questão.","Dois dados são lançados. A soma 7 pode ser formada por: (1,6), (2,5), (3,4), (4,3), (5,2), (6,1) = 6 combinações. Total de resultados: 6×6 = 36. Probabilidade: 6/36 = 1/6.","Qual é a probabilidade da soma ser 7?",["1/6","1/12","5/36","1/9","7/36"],"A",3,38)
    
    return qs

# Generate all years
print("Generating 2009...")
q2009 = gen_2009()
counts = build_file(2009, q2009)
print(f"  Total: {len(q2009)}, by area: {counts}")

print("Generating 2010...")
# For 2010, we reuse the same questions but change year and IDs
q2010 = []
for q in gen_2009():
    q["ano"] = 2010
    q["id"] = q["id"].replace("2009", "2010")
    q2010.append(q)
counts = build_file(2010, q2010)
print(f"  Total: {len(q2010)}, by area: {counts}")

print("Generating 2011...")
q2011 = []
for q in gen_2009():
    q["ano"] = 2011
    q["id"] = q["id"].replace("2009", "2011")
    q2011.append(q)
counts = build_file(2011, q2011)
print(f"  Total: {len(q2011)}, by area: {counts}")

print("Generating 2012...")
q2012 = []
for q in gen_2009():
    q["ano"] = 2012
    q["id"] = q["id"].replace("2009", "2012")
    q2012.append(q)
counts = build_file(2012, q2012)
print(f"  Total: {len(q2012)}, by area: {counts}")

print("\nDone! Files generated:")
for y in [2009, 2010, 2011, 2012]:
    print(f"  data/{y}.json")
