#!/usr/bin/env python3
import json, os
os.makedirs('data', exist_ok=True)
def q(id,ano,area,disc,texto,pergunta,opcoes,gab,diff,taxa):
    return {"id":id,"ano":ano,"area":area,"disciplina":disc,"contexto":"Leia o texto abaixo para responder à questão.","texto":texto,"pergunta":pergunta,"opcoes":opcoes,"gabarito":gab,"dificuldade":diff,"taxaAcerto":taxa}
Q=[];n=1;p="L";a="linguagens"
# Portugues 20
d="portugues"
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"O movimento greve climática global inspirado por Greta Thunberg mobilizou milhões em 2019. Participantes exigiram ações concretas dos governantes para enfrentar a crise climática.","O movimento greve climática de 2019 mobilizou para:",["Apenas celebrar meio ambiente","Exigir ações concretas dos governantes para enfrentar crise climática","Apenas fazer turismo ecológico","Eliminar todas as indústrias","Apenas protestos sem demandas"],"B",1,76));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"A pauta ambiental ganhou força nas eleições municipais de 2019. Candidatos incorporaram propostas de sustentabilidade em campanhas, respondendo à demanda crescente da população por ações ambientais.","A pauta ambiental em 2019 ganhou força porque:",["Não tinha importância","A população crescentemente demandava ações ambientais","Apenas por imposição legal","Por倡议 de empresas privadas","Apenas por modismo"],"B",2,52));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"A comunicação sobre mudanças climáticas tem se tornado cada vez mais importante nos meios de comunicação. Jornalistas desempenham papel fundamental na divulgação de informações científicas.","A comunicação sobre mudanças climáticas é importante porque:",["Não tem relevância","Divulga informações científicas essenciais para tomada de decisão","Apenas entreter o público","Apenas vender produtos ecológicos","Não tem relação com política"],"B",1,80));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"O discurso sobre sustentabilidade tem se tornado cada vez mais presente no debate público. Empresas, governos e sociedade civil discutem a necessidade de mudanças nos padrões de consumo e produção.","O discurso sobre sustentabilidade em 2019 discutiu:",["Manter padrões atuais de consumo","Necessidade de mudanças nos padrões de consumo e produção","Apenas celebrar natureza","Eliminar todas as indústrias","Não houve debate sobre sustentabilidade"],"B",2,55));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"A literatura ecológica tem ganhado espaço nas editoras brasileiras. Autores contemporâneos utilizam ficção para explorar temas como desmatamento, poluição e preservação ambiental.","A literatura ecológica contribui ao:",["Ignorar questões ambientais","Explorar temas ambientais através da ficção e conscientizar o público","Apenas decorar estantes","Celebrar destruição da natureza","Não ter nenhuma relevância"],"B",2,50));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"O uso de linguagem inclusiva e sensível ao ambiente tem se tornado tendência na comunicação corporativa. Empresas e instituições adaptam suas mensagens para refletir compromissos ambientais.","O uso de linguagem sensível ao ambiente busca:",["Mascarar práticas antiecológicas","Refletir compromissos ambientais nas comunicações institucionais","Apenas seguir tendências de mercado","Eliminar todas as empresas poluidoras","Não ter impacto na sociedade"],"B",2,48));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"A educação ambiental tem se tornado cada vez mais importante nos currículos escolares. Escolas incluem temas como sustentabilidade, reciclagem e preservação em seus programas.","A educação ambiental é importante porque:",["Não tem relevância","Forma cidadãos conscientes sobre questões ambientais","Apenas ocupar tempo dos alunos","Apenas seguir modismo","Não tem impacto na sociedade"],"B",1,82));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"O jornalismo ambiental tem desempenhado papel importante na cobertura de questões como desmatamento na Amazônia e poluição urbana. Repórteres especializados investigam e divulgam informações.","O jornalismo ambiental contribui ao:",["Ignorar problemas ambientais","Investigar e divulgar informações sobre questões ambientais","Apenas celebrar governos","Apenas vender produtos sustentáveis","Não ter nenhuma relevância"],"B",1,78));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"A comunicação de crise ambiental é um desafio para governos e empresas. Desastres como vazamentos de óleo exigem respostas rápidas e transparentes da comunicação institucional.","A comunicação de crise ambiental é um desafio porque:",["Não há crise ambiental","Exige respostas rápidas e transparentes para manter credibilidade","Apenas causar pânico","Apenas esconder a verdade","Não ter impacto na sociedade"],"B",2,52));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"O ativismo digital ambiental tem se tornado ferramenta poderosa para mobilizar pessoas em torno de causas ecológicas. Redes sociais permitem organização de campanhas e protestos de forma rápida.","O ativismo digital ambiental é uma ferramenta porque:",["Não tem impacto","Permite mobilizar pessoas rapidamente em torno de causas ecológicas","Apenas entreter usuários","Apenas vender produtos sustentáveis","Não tem relação com política"],"B",2,50));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"A cobertura midiática das mobilizações climáticas de 2019 foi ampla. Meios de comunicação de diferentes países divulgaram manifestações e debateram demandas dos manifestantes.","A cobertura midiática foi importante porque:",["Não teve impacto","Divulgou mobilizações e debates sobre ações climáticas","Apenas entreter público","Apenas criticar manifestantes","Não teve relevância"],"B",1,76));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"A linguagem nos discursos sobre mudança climática tem evoluído. Cientistas e ativistas buscam formas mais eficazes de comunicar a urgência da crise climática para diferentes públicos.","A evolução da linguagem busca:",["Manter público ignorante","Encontrar formas mais eficazes de comunicar urgência da crise","Apenas causar pânico","Apenas entreter público","Não ter impacto na sociedade"],"B",2,52));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"O debate sobre transição energética tem se intensificado nos meios de comunicação. A discussão sobre substituição de combustíveis fósseis por fontes renováveis tem ganhado espaço.","O debate sobre transição energética busca:",["Manter uso de combustíveis fósseis","Discutir substituição de combustíveis fósseis por fontes renováveis","Apenas vender painéis solares","Apenas criticar governos","Não ter impacto na sociedade"],"B",2,50));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"A arte ecológica tem se tornado forma de expressão para artistas que desejam conscientizar sobre questões ambientais. Instalações utilizam materiais reciclados e temas ecológicos.","A arte ecológica contribui ao:",["Ignorar questões ambientais","Conscientizar o público sobre questões ambientais através da expressão artística","Apenas decorar espaços","Celebrar destruição da natureza","Não ter nenhuma relevância"],"B",2,48));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"O greenwashing é uma prática de empresas que utilizam marketing ambiental para criar imagem sustentável, sem necessariamente adotar práticas realmente sustentáveis.","O greenwashing é uma prática que:",["Beneficia o meio ambiente","Cria imagem sustentável sem adotar práticas realmente sustentáveis","Apenas marketing comum","É benéfico para a sociedade","Não existe"],"B",2,55));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"A comunicação de riscos ambientais é essencial para a proteção da população. Alertas sobre enchentes e desastres naturais devem ser comunicados de forma clara e eficaz.","A comunicação de riscos ambientais é essencial porque:",["Não há riscos","Protege população ao informar sobre desastres naturais","Apenas causar pânico","Apenas entreter público","Não tem impacto na sociedade"],"B",1,80));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"O uso de dados e estatísticas na comunicação ambiental tem se tornado cada vez mais importante. Números sobre emissões ajudam a fundamentar argumentos e mobilizar opinião pública.","O uso de dados busca:",["Mascarar verdade científica","Fundamentar argumentos com informações concretas para mobilizar opinião pública","Apenas impressionar público","Apenas vender produtos sustentáveis","Não ter impacto na sociedade"],"B",2,52));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"A jornalista Maria Thereza Goulart destacou a importância do jornalismo ambiental para formação de opinião pública informada sobre questões climáticas e de sustentabilidade.","O jornalismo ambiental contribui ao:",["Ignorar problemas ambientais","Informar população sobre questões climáticas e de sustentabilidade","Apenas entreter público","Apenas criticar governos","Não ter relevância"],"B",1,78));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"A comunicação corporativa sustentável tem se tornado exigência do mercado. Empresas que não comunicam práticas ambientais de forma transparente podem sofrer críticas e perda de reputação.","A comunicação corporativa sustentável busca:",["Mascarar práticas antiecológicas","Comunicar de forma transparente práticas ambientais da empresa","Apenas seguir tendências de mercado","Eliminar todas as empresas poluidoras","Não ter impacto na sociedade"],"B",2,50));n+=1
# Ingles 10
d="ingles"
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"The global climate strike movement, inspired by Greta Thunberg, mobilized millions worldwide in 2019. Participants demanded concrete action from governments to address the climate crisis.","The climate strike mobilized people to:",["Simply celebrate nature","Demand concrete government action on climate change","Only promote eco-tourism","Eliminate all industries","Make protests without demands"],"B",1,75));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"Environmental awareness has increased significantly in recent years. People are more concerned about plastic pollution, deforestation and climate change. This has led to changes in consumer behavior.","Environmental awareness increased because:",["People are less concerned","Growing concern about pollution, deforestation and climate change","Laws have forced people to care","Companies have marketed eco-products","There are no environmental problems"],"B",1,80));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"Sustainable development has become a central theme in policy discussions. Governments seek ways to balance economic growth with environmental protection.","Sustainable development seeks to:",["Prioritize economic growth at all costs","Balance economic growth with environmental protection","Eliminate all economic activity","Ignore environmental concerns","Focus only on short-term profits"],"B",2,52));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"Youth activism on climate change has become a global phenomenon. Young people use social media to organize protests and demand action from political leaders on environmental issues.","Youth climate activism seeks to:",["Ignore environmental problems","Demand action from political leaders on environmental issues","Simply gain attention on social media","Oppose all forms of government","Focus only on economic issues"],"B",2,50));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"The concept of carbon footprint has become increasingly popular. Individuals and companies are encouraged to measure and reduce their greenhouse gas emissions.","The carbon footprint concept aims to:",["Increase greenhouse gas emissions","Encourage measurement and reduction of greenhouse gas emissions","Simply label products as green","Ignore climate change","Focus only on energy costs"],"B",1,78));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"Renewable energy has become increasingly important in global energy discussions. Countries are transitioning from fossil fuels to solar, wind and other renewable sources.","The transition to renewable energy aims to:",["Continue using fossil fuels indefinitely","Reduce carbon emissions by transitioning to renewable sources","Eliminate all energy production","Increase dependence on oil imports","Ignore climate change"],"B",2,55));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"Corporate sustainability reporting has become standard practice for many large companies. Organizations publish reports detailing their environmental impact and sustainability efforts.","Corporate sustainability reporting aims to:",["Hide environmental impact","Transparently communicate environmental impact and sustainability efforts","Simply follow legal requirements","Increase company profits","Ignore environmental concerns"],"B",2,48));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"Climate change denial remains a challenge in public discourse. Despite scientific consensus, some individuals continue to question the reality of human-caused climate change.","Climate change denial is a challenge because:",["It supports scientific evidence","It undermines action on a critical global issue","It promotes environmental awareness","It encourages renewable energy adoption","It has no impact on public opinion"],"B",2,52));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"The circular economy model has gained attention as an alternative to the linear economy. This model emphasizes reuse, recycling and sustainable production.","The circular economy model emphasizes:",["Continuous extraction of natural resources","Reuse, recycling and sustainable production","Increasing waste generation","Ignoring environmental impacts","Focusing only on short-term profits"],"B",2,50));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"Environmental education has become increasingly important in schools worldwide. Students learn about sustainability, climate change and environmental responsibility from an early age.","Environmental education aims to:",["Ignore environmental problems","Educate students about sustainability and environmental responsibility","Simply follow curriculum requirements","Oppose all forms of development","Focus only on academic grades"],"B",1,82));n+=1
# Espanhol 5
d="espanhol"
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"El movimiento de huelga climática global, inspirado por Greta Thunberg, movilizó a millones en 2019. Los participantes exigieron acciones concretas de los gobiernos para enfrentar la crisis climática.","La huelga climática de 2019 movilizó para:",["Simplemente celebrar naturaleza","Exigir acciones concretas de gobiernos para enfrentar crisis climática","Solo promover turismo ecológico","Eliminar todas las industrias","Hacer protestas sin demandas"],"B",1,72));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"La conciencia ambiental ha aumentado significativamente. Las personas están más preocupadas por contaminación por plásticos, deforestación y cambio climático.","La conciencia ambiental aumentó porque:",["Personas están menos preocupadas","Mayor preocupación por contaminación, deforestación y cambio climático","Leyes han obligado a preocuparse","Empresas han comercializado productos ecológicos","No hay problemas ambientales"],"B",1,70));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"El desarrollo sostenible se ha convertido en tema central en discusiones políticas. Gobiernos buscan equilibrar crecimiento económico con protección ambiental.","El desarrollo sostenible busca:",["Priorizar crecimiento económico a toda costa","Equilibrar crecimiento económico con protección ambiental","Eliminar toda actividad económica","Ignorar preocupaciones ambientales","Enfocarse solo en ganancias a corto plazo"],"B",2,48));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"El activismo juvenil sobre cambio climático se ha convertido en fenómeno global. Jóvenes utilizan redes sociales para organizar protestas y exigir acción a líderes políticos.","El activismo juvenil climático busca:",["Ignorar problemas ambientales","Exigir acción a líderes políticos sobre temas ambientales","Simplemente ganar atención en redes sociales","Oponerse a todas las formas de gobierno","Enfocarse solo en temas económicos"],"B",2,50));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"El concepto de huella de carbono se ha vuelto cada vez más popular. Se anima a individuos y empresas a medir y reducir sus emisiones de gases de efecto invernadero.","La huella de carbono busca:",["Aumentar emisiones de gases de efecto invernadero","Animar a medir y reducir emisiones de gases de efecto invernadero","Simplemente etiquetar productos como ecológicos","Ignorar cambio climático","Enfocarse solo en costos de energía"],"B",1,68));n+=1
# Literatura 5
d="literatura"
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"A ecocrítica é movimento literário que analisa relação entre literatura e meio ambiente. Autores buscam valorizar obras que retratam natureza e alertam sobre problemas ambientais.","A ecocrítica contribui ao:",["Ignorar relação literatura-meio ambiente","Analisar e valorizar obras que retratam natureza e alertam sobre problemas ambientais","Apenas celebrar destruição da natureza","Não ter nenhuma relevância","Apenas decorar estantes"],"B",2,52));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"A poesia ambiental tem ganhado espaço na literatura contemporânea. Poetas brasileiros utilizam versos para denunciar desmatamento, poluição e outros problemas ambientais.","A poesia ambiental contribui ao:",["Ignorar problemas ambientais","Denunciar desmatamento, poluição e outros problemas através da poesia","Apenas decorar livros","Celebrar destruição da natureza","Não ter nenhuma relevância"],"B",2,50));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"A Hora da Estrela de Clarice Lispector explora a relação do ser humano com o ambiente urbano e as desigualdades sociais que afetam a vida nas cidades.","A Hora da Estrela explora:",["Apenas beleza da natureza","Relação do ser humano com ambiente urbano e desigualdades sociais","Apenas vida no campo","Apenas política internacional","Não explora nenhuma relação"],"B",2,48));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"O Quinze de Rachel de Queiroz retrata a seca no sertão nordestino e seus impactos na população. A obra é exemplo de como a literatura pode retratar problemas ambientais e sociais.","O Quinze retrata:",["Beleza do litoral brasileiro","Seca no sertão nordestino e seus impactos na população","Vida urbana no Rio de Janeiro","Política internacional","Não retrata nenhum problema ambiental"],"B",2,52));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"A literatura infantil ambiental tem ganhado espaço no Brasil. Livros para crianças abordam temas como reciclagem e preservação de animais de forma lúdica e educativa.","A literatura infantil ambiental contribui ao:",["Ignorar questões ambientais","Conscientizar crianças sobre preservação e reciclagem de forma lúdica","Apenas entreter crianças","Celebrar destruição da natureza","Não ter nenhuma relevância"],"B",1,80));n+=1
# Artes 2
d="artes"
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"A arte sustentável tem se tornado tendência no mundo artístico. Artistas utilizam materiais reciclados e técnicas sustentáveis para criar obras que conscientizam sobre questões ambientais.","A arte sustentável contribui ao:",["Ignorar questões ambientais","Utilizar materiais reciclados para conscientizar sobre questões ambientais","Apenas decorar espaços","Celebrar destruição da natureza","Não ter nenhuma relevância"],"B",2,50));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"As intervenções artísticas em espaços públicos têm abordado temas ambientais. Instalações que denunciam poluição e desmatamento ganham visibilidade em cidades brasileiras.","As intervenções artísticas ambientais buscam:",["Decorar espaços sem mensagem","Denunciar poluição e desmatamento através de instalações artísticas","Apenas entreter população","Celebrar destruição da natureza","Não ter nenhuma relevância"],"B",2,52));n+=1
# Educacao Fisica 2
d="educacao_fisica"
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"A prática de atividades ao ar livre tem ganhado importância na promoção da saúde e da conscientização ambiental. Caminhadas e trilhas em ambientes naturais conectam pessoas com a natureza.","A prática ao ar livre promove:",["Apenas exercício físico","Saúde e conscientização ambiental ao conectar pessoas com natureza","Apenas competição esportiva","Apenas lazer","Não tem relação com meio ambiente"],"B",1,78));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"O esporte sustentável tem se tornado prática em eventos esportivos ao redor do mundo. Organizadores buscam reduzir o impacto ambiental de suas atividades.","O esporte sustentável busca:",["Aumentar impacto ambiental","Reduzir impacto ambiental das atividades esportivas","Apenas entreter público","Celebrar destruição da natureza","Não ter nenhuma relevância"],"B",2,50));n+=1
# TIC 1
d="tic"
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"A tecnologia desempenha papel importante no monitoramento ambiental. Sensores, satélites e sistemas de informação geográfica auxiliam no acompanhamento de desmatamento e poluição.","A tecnologia contribui ao:",["Ignorar problemas ambientais","Auxiliar no acompanhamento de desmatamento, poluição e mudanças climáticas","Apenas entreter público","Apenas vender produtos eletrônicos","Não ter nenhuma relevância"],"B",1,82));n+=1
# HUMANAS
p="H";a="humanas"
# Historia 15
d="historia"
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"As mobilizações climáticas de 2019 marcaram momento histórico na conscientização ambiental global. Milhões de pessoas saíram às ruas em diferentes países para exigir ações contra o aquecimento global.","As mobilizações de 2019 marcaram:",["Momento de indiferença","Momento histórico na conscientização ambiental global","Apenas protestos pontuais","Fim de todos os conflitos ambientais","Não tiveram impacto"],"B",2,52));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"A história do ambientalismo no Brasil remonta ao século XIX com criação de primeiras unidades de conservação. O movimento ambientalista só ganhou força nas décadas de 1970 e 1980.","O ambientalismo brasileiro ganhou força em:",["Século XVIII","Décadas de 1970 e 1980","Apenas no século XXI","Nunca ganhou força","Apenas no século XIX"],"B",2,55));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"A Conferência das Nações Unidas (Rio-92) foi marco na história ambiental brasileira. O Brasil sediou evento que reuniu líderes mundiais para discutir questões ambientais.","A Rio-92 foi importante porque:",["Não teve importância","Reuniu líderes mundiais para discutir questões ambientais no Brasil","Apenas gerou protestos","Não envolveu o Brasil","Não teve impacto na política ambiental"],"B",2,50));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"A história da exploração dos recursos naturais no Brasil é marcada por ciclos econômicos que causaram impactos ambientais significativos. Da cana-de-açúcar ao minério, cada ciclo deixou marcas.","A exploração de recursos naturais causou:",["Nenhum impacto ambiental","Impactos ambientais significativos ao longo da história","Apenas benefícios econômicos","Apenas desenvolvimento tecnológico","Não afetou o meio ambiente"],"B",2,52));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"O desmatamento na Amazônia tem longa história que remonta ao período colonial. Abertura de estradas e expansão da agropecuária no século XX intensificaram destruição da floresta.","O desmatamento amazônico intensificou-se com:",["Preservação da floresta","Abertura de estradas e expansão da agropecuária no século XX","Apenas atividades artesanais","Não houve desmatamento","Apenas na época colonial"],"B",2,50));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"Os movimentos sociais ambientais brasileiros têm longa trajetória de luta pela preservação do meio ambiente e pelos direitos das comunidades tradicionais.","Os movimentos sociais ambientais buscaram:",["Destruir meio ambiente","Proteger meio ambiente e direitos das comunidades tradicionais","Apenas obter lucro","Apenas causar distúrbios","Não tiveram importância"],"B",2,55));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"A legislação ambiental brasileira tem se fortalecido ao longo do tempo. Desde criação do CONAMA em 1984 até o Código Florestal, Brasil estabeleceu arcabouço legal para proteção ambiental.","A legislação ambiental brasileira busca:",["Destruir meio ambiente","Proteger meio ambiente através de arcabouço legal","Apenas dificultar desenvolvimento","Apenas beneficiar empresas privadas","Não teve impacto"],"B",2,50));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"As COPs são reuniões anuais das nações signatárias da Convenção-Quadro sobre Mudança do Clima. São fundamentais para o progresso nas negociações climáticas globais.","As COPs são importantes porque:",["Não têm importância","São fundamentais para progresso nas negociações climáticas globais","Apenas geram polêmica","Não envolvem o Brasil","Não têm impacto na política ambiental"],"B",2,52));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"O Acordo de Paris, firmado em 2015, estabeleceu metas para redução das emissões de gases de efeito estufa. O Brasil se comprometeu a reduzir suas emissões.","O Acordo de Paris estabeleceu:",["Nenhuma meta de redução","Metas para redução das emissões de gases de efeito estufa","Apenas promessas sem compromisso","Não envolveu o Brasil","Não teve impacto na política ambiental"],"B",2,50));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"O Parque Nacional de Itatiaia, criado em 1937, foi o primeiro parque nacional do Brasil. A preservação de áreas naturais tem se tornado cada vez mais importante na política ambiental.","O primeiro parque nacional do Brasil foi criado em:",["1920","1937","1950","1970","1990"],"B",1,78));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"A exploração do petróleo no Brasil tem longa história que envolve descobertas offshore e debates sobre impactos ambientais. A pré-sal é um dos maiores achados recentes.","A exploração de petróleo envolve:",["Apenas benefícios econômicos","Debates sobre impactos ambientais e desenvolvimento tecnológico","Apenas exportação de recursos","Não afeta meio ambiente","Não teve desenvolvimento tecnológico"],"B",2,55));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"A ocupação do cerrado brasileiro tem gerado preocupações ambientais. Conversão de áreas em lavouras e pastagens tem causado perda de biodiversidade e emissões de gases de efeito estufa.","A ocupação do cerrado gera preocupações porque:",["Não causa impacto","Causa perda de biodiversidade e emissões de gases de efeito estufa","Apenas gera empregos","Apenas aumenta produção agrícola","Não afeta meio ambiente"],"B",2,50));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"Os acidentes de Mariana (2015) e Brumadinho (2019) destacaram os riscos ambientais da atividade minerária no Brasil. O rompimento de barragens causou danos ambientais e humanos severos.","Os acidentes de Mariana e Brumadinho destacaram:",["Benefícios da mineração","Riscos ambientais da atividade minerária","Apenas lucros obtidos","Não causaram danos ambientais","Apenas prejuízos econômicos"],"B",2,52));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"A política ambiental brasileira tem passado por transformações. De governos que priorizaram desenvolvimento econômico a governos que fortaleceram proteção ambiental, país testou diferentes abordagens.","A política ambiental brasileira transformou-se ao:",["Não ter mudança","Testar diferentes abordagens entre desenvolvimento e proteção ambiental","Apenas priorizar desenvolvimento","Apenas priorizar proteção","Não ter importância"],"B",2,50));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"A internacionalização da questão ambiental coloca Brasil em destaque nos debates globais. A Amazônia é considerada patrimônio da humanidade e seu destino interessa a todas as nações.","A internacionalização coloca Brasil em destaque porque:",["Brasil não tem importância","Amazônia é considerada patrimônio da humanidade","Apenas por interesses econômicos","Não envolve o Brasil","Não tem impacto na política internacional"],"B",2,48));n+=1
# Geografia 15
d="geografia"
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"As mobilizações climáticas de 2019 ocorreram em diferentes cidades do Brasil e do mundo. A distribuição geográfica dos protestos demonstrou que a questão ambiental é preocupação global.","A distribuição dos protestos demonstrou:",["Apenas países ricos se preocupam","Questão ambiental é preocupação global","Brasil não participou","Apenas jovens protestaram","Não houve protestos"],"B",2,52));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"O desmatamento amazônico tem impactos que vão além das fronteiras brasileiras. A floresta exerce influência no clima de toda a América do Sul e tem papel fundamental no equilíbrio climático global.","O desmatamento tem impactos globais porque:",["Afeta apenas o Brasil","Floresta amazônica influencia clima de toda América do Sul e equilíbrio climático global","Apenas gera lucro para empresas","Não causa impacto","Apenas afeta biodiversidade local"],"B",2,55));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"A distribuição desigual dos recursos naturais no Brasil gera tensões regionais. Regiões como Norte e Centro-Oeste possuem riquezas naturais exploradas em benefício de outras regiões.","A distribuição desigual gera:",["Igualdade entre regiões","Tensões regionais devido à exploração de riquezas naturais","Apenas benefícios para todas as regiões","Não causa problema","Apenas desenvolvimento econômico"],"B",2,50));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"A urbanização brasileira tem impactos ambientais significativos. Crescimento desordenado gera poluição do ar, falta de saneamento básico e destruição de áreas verdes.","A urbanização gera impactos porque:",["Não causa impacto","Crescimento desordenado gera poluição, falta de saneamento e destruição de áreas verdes","Apenas melhora infraestrutura","Apenas aumenta população","Não afeta meio ambiente"],"B",2,48));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"A exploração da biodiversidade amazônica gera debates sobre desenvolvimento sustentável. Brasil possui riqueza biológica enorme que pode ser utilizada de forma sustentável.","A biodiversidade amazônica pode gerar:",["Apenas destruição ambiental","Renda e emprego quando utilizada de forma sustentável","Apenas lucro para empresas estrangeiras","Não tem valor econômico","Apenas problemas ambientais"],"B",2,52));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"A questão hídrica brasileira é importante. Brasil possui maior reserva de água doce do mundo, mas enfrenta problemas de distribuição e poluição que afetam milhões de pessoas.","A questão hídrica é importante porque:",["Não há problemas com água","Brasil possui grandes reservas, mas enfrenta problemas de distribuição e poluição","Apenas gera lucro para empresas","Não afeta população","Não tem relevância geopolítica"],"B",2,50));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"A mudança no uso do solo é principal fator que contribui para mudanças climáticas. No Brasil, conversão de florestas em áreas agrícolas tem liberado grandes quantidades de gases de efeito estufa.","A mudança no uso do solo contribui ao:",["Não ter influência","Liberar grandes quantidades de gases de efeito estufa ao converter florestas em áreas agrícolas","Apenas aumentar produção agrícola","Apenas gerar empregos","Não afeta clima"],"B",2,55));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"A globalização tem impactos ambientais que afetam diferentes regiões. Produção em escala global gera poluição, esgotamento de recursos naturais e mudanças climáticas.","A globalização tem impactos porque:",["Não causa impacto","Produção em escala global gera poluição, esgotamento de recursos e mudanças climáticas","Apenas gera benefícios econômicos","Apenas aumenta consumo","Não afeta meio ambiente"],"B",2,50));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"A mobilidade urbana sustentável tem se tornado tema de discussão. Investimento em transporte público, ciclovias e áreas pedonais busca reduzir poluição e melhorar qualidade de vida.","A mobilidade sustentável busca:",["Aumentar poluição","Reduzir poluição e melhorar qualidade de vida com transporte público e infraestrutura sustentável","Apenas facilitar uso de carros","Apenas causar transtornos","Não tem impacto no meio ambiente"],"B",2,48));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"A matriz energética brasileira é composta majoritariamente por fontes renováveis. No entanto, Brasil ainda depende de combustíveis fósseis em alguns setores da economia.","A matriz energética brasileira é composta por:",["Apenas combustíveis fósseis","Fontes renováveis, mas ainda depende de combustíveis fósseis em alguns setores","Apenas energia nuclear","Apenas energia solar","Não possui energia renovável"],"B",2,52));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"Os conflitos por terra no Brasil estão associados a questões ambientais. Disputa por terras produtivas gera tensões entre pequenos agricultores, grandes propriedades e comunidades tradicionais.","Os conflitos por terra estão associados a:",["Apenas questões econômicas","Questões ambientais e disputa por terras produtivas","Apenas questões políticas","Não existem conflitos por terra","Apenas questões religiosas"],"B",2,50));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"A política de irrigação no Brasil tem impactos ambientais. Uso inadequado da água para irrigação pode causar salinização do solo e esgotamento de recursos hídricos.","A política de irrigação tem impactos porque:",["Não causa impacto","Uso inadequado da água pode causar salinização do solo e esgotamento de recursos hídricos","Apenas aumenta produção agrícola","Apenas gera empregos","Não afeta meio ambiente"],"B",2,48));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"A questão dos resíduos sólidos é problema geográfico urbano. Destinação inadequada do lixo gera contaminação do solo e da água, além de problemas de saúde pública.","A questão dos resíduos sólidos gera:",["Nenhum impacto","Impactos ambientais como contaminação do solo e da água, além de problemas de saúde pública","Apenas benefícios econômicos","Apenas melhoria da infraestrutura","Não afeta população"],"B",2,52));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"A preservação do cerrado brasileiro tem se tornado pauta importante na política ambiental. Bioma abriga biodiversidade enorme e desempenha papel fundamental no ciclo da água.","A preservação do cerrado é importante porque:",["Não tem importância","Abriga biodiversidade enorme e desempenha papel fundamental no ciclo da água","Apenas gera lucro para empresas","Não afeta meio ambiente","Apenas tem importância local"],"B",2,50));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"O manejo florestal sustentável é tema geográfico importante. Manejo adequado das florestas pode garantir exploração econômica sem comprometer sustentabilidade ambiental.","O manejo florestal sustentável busca:",["Destruir florestas","Garantir exploração econômica sem comprometer sustentabilidade ambiental","Apenas extrair madeira","Apenas causar desmatamento","Não tem impacto no meio ambiente"],"B",2,52));n+=1
# Sociologia 8
d="sociologia"
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"O ativismo climático de 2019 pode ser analisado sob perspectiva sociológica. Movimento demonstra como diferentes grupos sociais se mobilizam em torno de causas comuns.","O ativismo climático demonstra:",["Desinteresse da sociedade","Como diferentes grupos sociais se mobilizam em torno de causas comuns","Apenas protestos pontuais","Fim de todos os conflitos sociais","Não teve impacto na sociedade"],"B",2,52));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"A responsabilidade social das empresas tem se tornado cada vez mais importante. Empresas são cobradas por práticas ambientais e sociais por consumidores, investidores e sociedade civil.","A responsabilidade social busca:",["Ignorar práticas ambientais e sociais","Atender demandas de consumidores, investidores e sociedade civil por práticas responsáveis","Apenas aumentar lucros","Apenas seguir tendências de mercado","Não tem impacto na sociedade"],"B",2,50));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"A mobilização social em torno da causa ambiental tem se intensificado. Diferentes segmentos da sociedade têm se envolvido em movimentos pela preservação do meio ambiente.","A mobilização social ambiental intensificou ao:",["Não ter envolvimento social","Envolver diferentes segmentos da sociedade em movimentos pela preservação","Apenas protestos de jovens","Apenas ações governamentais","Não teve impacto na sociedade"],"B",2,52));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"A desigualdade social tem impactos ambientais. Populações mais pobres são mais vulneráveis a desastres naturais e poluição, sendo as principais vítimas dos problemas ambientais.","A desigualdade social tem impactos porque:",["Não afeta meio ambiente","Populações mais pobres são mais vulneráveis a desastres e poluição","Apenas afeta economia","Não tem relação com sociedade","Apenas afeta política"],"B",2,50));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"O papel dos movimentos sociais ambientais é fundamental para pressão por mudanças nas políticas públicas. Organizações desempenham função de fiscalização e proposição de alternativas sustentáveis.","Os movimentos desempenham função de:",["Apoio ao governo","Fiscalização e proposição de alternativas sustentáveis às políticas públicas","Apenas causar distúrbios","Apenas obter lucro","Não têm importância"],"B",2,55));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"A educação ambiental tem se tornado ferramenta de transformação social. Ao conscientizar a população sobre questões ambientais, contribui para formação de cidadãos mais engajados.","A educação ambiental contribui ao:",["Ignorar questões ambientais","Conscientizar a população e formar cidadãos mais engajados","Apenas seguir currículo escolar","Apenas entreter alunos","Não tem impacto na sociedade"],"B",1,80));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"O consumo sustentável tem se tornado tendência entre consumidores brasileiros. Cada vez mais pessoas buscam produtos ecologicamente corretos e apoiam empresas com práticas sustentáveis.","O consumo sustentável busca:",["Aumentar desperdício","Estimular compra de produtos ecologicamente corretos e apoio a empresas sustentáveis","Apenas economizar dinheiro","Apenas seguir tendências","Não tem impacto no meio ambiente"],"B",2,52));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"A responsabilidade ambiental é questão de justiça social. Populações que menos contribuem para problemas ambientais são frequentemente as mais afetadas pelas consequências da degradação.","A responsabilidade ambiental é justiça social porque:",["Todos contribuem igualmente","Populações que menos contribuem são mais afetadas pela degradação","Apenas afeta ricos","Não tem relação com justiça","Não afeta sociedade"],"B",2,48));n+=1
# Filosofia 7
d="filosofia"
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"A ética ambiental é ramo da filosofia que questiona relação entre seres humanos e natureza. Pensaadores como Aldo Leopold e Arne Næss desenvolveram conceitos que influenciam debate ambiental.","A ética ambiental questiona:",["Relação entre seres humanos e natureza","Apenas economia do país","Apenas política internacional","Não tem relevância filosófica","Não tem impacto na sociedade"],"A",2,50));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"O desenvolvimento sustentável, popularizado em 1987, propõe que desenvolvimento econômico deve respeitar limites ambientais. Filosofia ambiental questiona se conceito é suficiente para resolver crise ecológica.","A filosofia questiona se desenvolvimento sustentável é:",["Solução para todos os problemas","Suficiente para resolver crise ecológica","Irrelevante para sociedade","Apenas modismo","Não tem impacto na política"],"B",2,48));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"O Deep Ecology, desenvolvido por Arne Næss, propõe reformulação radical da relação entre seres humanos e natureza. Essa abordagem filosófica influencia movimentos ambientalistas ao redor do mundo.","O Deep Ecology propõe:",["Manter relação atual entre seres humanos e natureza","Reformulação radical da relação entre seres humanos e natureza","Apenas proteger biodiversidade","Apenas gerar lucro","Não tem impacto na sociedade"],"B",3,35));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"A questão da justiça ambiental é tema filosófico fundamental. Filosofia questiona como custos e benefícios da atividade humana devem ser distribuídos entre diferentes grupos sociais e gerações futuras.","A justiça ambiental questiona:",["Como distribuir custos e benefícios entre grupos sociais e gerações futuras","Apenas economia do país","Apenas política internacional","Não tem relevância filosófica","Não tem impacto na sociedade"],"A",2,52));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"O conceito de responsabilidade intergeracional é importante na filosofia ambiental. Ideia de que geração atual tem responsabilidade com gerações futuras influencia políticas públicas.","A responsabilidade intergeracional propõe:",["Cada geração deve cuidar apenas de si mesma","Geração atual tem responsabilidade com gerações futuras","Não há responsabilidade entre gerações","Apenas governo tem responsabilidade","Não tem impacto na sociedade"],"B",2,50));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"A filosofia ambiental questiona fundamentos éticos das decisões que afetam o meio ambiente. Conceitos como valor intrínseco da natureza e dignidade dos seres vivos são debatidos por pensadores contemporâneos.","A filosofia ambiental questiona:",["Apenas economia","Fundamentos éticos das decisões que afetam o meio ambiente","Apenas política","Não tem relevância","Não tem impacto na sociedade"],"B",2,52));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"O ecossocialismo combina preocupações ambientais com análise socialista da economia. Essa abordagem questiona capitalismo como sistema responsável pela crise ecológica.","O ecossocialismo combina:",["Apenas preocupações ambientais","Preocupações ambientais com análise socialista da economia","Apenas análise econômica","Não tem relevância filosófica","Não tem impacto na sociedade"],"B",3,32));n+=1
# NATUREZA
p="N";a="natureza"
# Fisica 15
d="fisica"
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"A eficiência energética é fundamental para enfrentar crise climática. Desenvolvimento de tecnologias mais eficientes pode reduzir consumo de energia e emissões de gases de efeito estufa.","A eficiência energética busca:",["Aumentar consumo de energia","Reduzir consumo de energia e emissões de gases de efeito estufa","Eliminar todas as fontes de energia","Substituir completamente fontes renováveis","Aumentar custos de produção"],"B",1,80));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"As energias renováveis, como solar e eólica, têm ganhado espaço na matriz energética brasileira. São consideradas mais limpas porque não emitem poluentes durante operação.","Uma vantagem das energias renováveis é:",["São mais baratas que todas as outras fontes","Não emitem poluentes durante sua operação","Podem ser utilizadas em qualquer lugar","Não dependem de condições climáticas","Substituem completamente fontes fósseis"],"B",1,78));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"O aquecimento global é um dos maiores desafios ambientais. Aumento da temperatura média do planeta está associado à emissão de gases de efeito estufa provenientes de atividades humanas.","O aquecimento global é causado principalmente por:",["Diminuição da radiação solar","Emissão de gases de efeito estufa por atividades humanas","Movimento da Terra em torno do Sol","Erupções vulcânicas naturais","Atividade de planetas vizinhos"],"B",1,75));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"A energia nuclear é fonte controversa. Pode gerar grandes quantidades de eletricidade sem emitir gases de efeito estufa, mas riscos de acidentes e problema do lixo radioativo geram preocupações.","Uma desvantagem da energia nuclear é:",["Emite gases de efeito estufa em grandes quantidades","Risco de acidentes e problema do lixo radioativo","Não pode gerar eletricidade","É muito barata e acessível","Não utiliza urânio como combustível"],"B",2,52));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"O princípio da conservação da energia estabelece que energia não pode ser criada nem destruída, apenas transformada. Esse princípio é fundamental para compreensão dos processos energéticos.","O princípio da conservação da energia estabelece que:",["A energia pode ser criada e destruída","A energia não pode ser criada nem destruída, apenas transformada","A energia sempre se dissipa no meio ambiente","A energia só pode ser transformada em calor","A energia é ilimitada na natureza"],"B",2,50));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"A Segunda Lei da Termodinâmica afirma que entropia total de sistema isolado só pode aumentar ao longo do tempo. Essa lei tem implicações para eficiência energética e sustentabilidade.","A Segunda Lei implica que:",["Energia pode ser usada infinitamente sem perdas","Sistemas energéticos sempre se tornam menos eficientes","Máquinas de movimento perpétuo são possíveis","Entropia pode diminuir em sistemas isolados","Eficiência energética não é importante"],"B",3,30));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"O efeito fotoelétrico, explicado por Einstein, é base do funcionamento de painéis solares fotovoltaicos, que convertem luz solar diretamente em eletricidade de forma limpa e renovável.","O efeito fotoelétrico é utilizado em:",["Motores a combustão","Painéis solares fotovoltaicos","Turbinas eólicas","Usinas nucleares","Baterias de carros elétricos"],"B",2,52));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"A energia eólica, gerada pelo vento, é uma das fontes renováveis com maior potencial de crescimento no Brasil. Instalação de parques eólicos pode contribuir significativamente para matriz energética sustentável.","A energia eólica é renovável porque:",["Utiliza combustíveis fósseis","Depende de fonte inesgotável como o vento","É muito barata de produzir","Não causa nenhum impacto ambiental","Pode ser utilizada em qualquer lugar"],"B",1,76));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"A eficiência de máquina térmica é limitada pela Segunda Lei da Termodinâmica. Essa lei estabelece que nenhum ciclo pode ser 100% eficiente na conversão de calor em trabalho.","A Segunda Lei limita a eficiência ao:",["Permitir 100% de eficiência","Estabelecer que nenhuma máquina pode ser 100% eficiente","Aumentar eficiência conforme temperatura aumenta","Permitir motores de movimento perpétuo","Eliminar todas as perdas de energia"],"B",3,28));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"A lei de Ohm descreve relação entre tensão, corrente e resistência em circuitos elétricos. Essa lei é fundamental para projeto de sistemas de distribuição de energia elétrica eficientes.","A lei de Ohm descreve relação entre:",["Temperatura e pressão","Tensão, corrente e resistência em circuitos elétricos","Massa e aceleração","Volume e pressão de um gás","Comprimento de onda e frequência"],"B",2,55));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"A potência elétrica é medida em watts e representa taxa de consumo de energia. Reduzir consumo de energia é essencial para enfrentar crise climática.","Se um eletrodoméstico consome 80 watts, significa que consome:",["80 joules de energia por segundo","80 joules de energia por hora","80 watts de energia por minuto","80 newtons de força","80 volts de tensão"],"A",2,48));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"A transferência de calor pode ocorrer por condução, convecção e radiação. Radiação é transferência de calor por ondas eletromagnéticas, sem necessidade de meio material.","Transferência de calor por radiação ocorre através de:",["Contato direto entre materiais","Movimento de fluidos","Ondas eletromagnéticas","Condução elétrica","Pressão atmosférica"],"C",2,48));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"A energia solar é uma das fontes renováveis mais promissoras. Brasil possui alta incidência de radiação solar em grande parte de seu território, tornando energia solar opção viável e sustentável.","O Brasil tem potencial para energia solar porque:",["Não possui incidência de radiação solar","Possui alta incidência de radiação solar em grande parte do território","É país frio e nublado","Não tem espaço para instalação de painéis","Energia solar é proibida no país"],"B",1,78));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"O efeito estufa é fenômeno natural que ajuda a manter temperatura da Terra adequada. No entanto, emissão excessiva de gases de efeito estufa tem intensificado processo, contribuindo para aquecimento global.","O efeito estufa em excesso causa:",["Resfriamento do planeta","Aquecimento global","Aumento da camada de ozônio","Diminuição da temperatura dos oceanos","Redução da radiação solar"],"B",1,82));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"A camada de ozônio é importante para proteção da vida na Terra. Destruição dessa camada por substâncias químicas como CFCs é problema ambiental que afeta proteção contra radiação ultravioleta.","A camada de ozônio é importante porque:",["Bloqueia toda a radiação solar","Protege contra radiação ultravioleta prejudicial","Mantém temperatura constante","Impede formação de nuvens","Produz oxigênio para respiração"],"B",2,52));n+=1
# Quimica 15
d="quimica"
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"A água é recurso natural essencial para a vida. No entanto, apenas 2,5% da água do planeta é doce e acessível para consumo humano. Poluição das águas tem se tornado problema crescente.","A principal preocupação com poluição das águas é:",["Aumento do nível dos oceanos","Diminuição da disponibilidade de água potável","Aquecimento da água dos rios","Diminuição da evaporação","Aumento da salinidade dos rios"],"B",1,80));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"Os agrotóxicos são amplamente utilizados na agricultura brasileira. No entanto, uso excessivo pode causar contaminação do solo, da água e dos alimentos. Química ambiental estuda impactos desses produtos.","O uso excessivo de agrotóxicos pode causar:",["Aumento da produtividade agrícola","Contaminação do solo, da água e dos alimentos","Melhoria da qualidade do solo","Aumento da biodiversidade","Redução dos custos de produção"],"B",2,52));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"O plástico é um dos materiais mais utilizados, mas sua produção e descarte inadequado causam sérios problemas ambientais. Muitos plásticos são produzidos a partir de petróleo, recurso não renovável.","Um problema ambiental associado ao uso de plásticos é:",["Redução da poluição dos oceanos","Contaminação dos oceanos e decomposição lenta","Aumento da biodiversidade marinha","Diminuição do uso de petróleo","Fortalecimento do solo"],"B",1,78));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"As baterias de íon-lítio são as mais utilizadas em dispositivos eletrônicos e veículos elétricos. Oferecem alta densidade de energia, mas produção e descarte inadequados causam problemas ambientais.","Uma vantagem das baterias de íon-lítio é:",["São baratas e fáceis de produzir","Oferecem alta densidade de energia e são leves","São 100% recicláveis sem resíduos","Não causam nenhum impacto ambiental","Podem ser utilizadas infinitamente"],"B",2,48));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"O efeito estufa é fenômeno natural que ajuda a manter temperatura da Terra adequada. Emissão excessiva de gases de efeito estufa tem intensificado processo, contribuindo para aquecimento global.","O efeito estufa em excesso causa:",["Resfriamento do planeta","Aquecimento global","Aumento da camada de ozônio","Diminuição da temperatura dos oceanos","Redução da radiação solar"],"B",1,82));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"A tabela periódica organiza elementos de acordo com número atômico e propriedades químicas. Conhecimento da tabela periódica é essencial para entender composição da matéria e suas transformações.","A tabela periódica organiza elementos de acordo com:",["Sua cor e textura","Seu número atômico e propriedades químicas","Sua massa molecular","Sua temperatura de fusão","Sua origem geográfica"],"B",2,52));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"A reciclagem de materiais como alumínio, papel e vidro é importante para sustentabilidade. Alumínio pode ser reciclado infinitamente sem perder suas propriedades.","O alumínio pode ser reciclado:",["Apenas uma vez","Até perder suas propriedades","Infinitamente sem perder suas propriedades","Nunca pode ser reciclado","Apenas em fábricas especiais"],"C",2,50));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"A combustão é reação química que libera energia. A queima de combustíveis fósseis libera gases de efeito estufa na atmosfera, contribuindo para aquecimento global.","A combustão de combustíveis fósseis libera:",["Oxigênio puro","Gases de efeito estufa que contribuem para aquecimento global","Apenas vapor de água","Substâncias que protegem camada de ozônio","Elementos químicos radioativos"],"B",1,76));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"A purificação de água é essencial para garantir acesso à água potável. Métodos incluem filtração, desinfecção química e tratamento por ultravioleta, que removem impurezas e microorganismos nocivos.","O principal objetivo da purificação de água é:",["Tornar a água mais bonita","Remover impurezas e microorganismos nocivos para consumo humano","Aumentar o sabor da água","Eliminar todos os minerais da água","Tornar a água mais quente"],"B",1,84));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"Os polímeros são materiais formados por moléculas grandes repetidas, como o plástico. Muitos polímeros são derivados do petróleo e sua decomposição pode levar centenas de anos.","Uma desvantagem dos polímeros convencionais é:",["São biodegradáveis rapidamente","Sua decomposição pode levar centenas de anos","São muito caros de produzir","Não têm aplicações práticas","São sempre recicláveis"],"B",2,52));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"O ozônio é molécula formada por três átomos de oxigênio. Na estratosfera, o ozônio protege a vida na Terra absorvendo radiação ultravioleta prejudicial.","Na estratosfera, o ozônio é importante porque:",["Causa problemas respiratórios","Protege a vida na Terra absorvendo radiação ultravioleta","Aumenta a temperatura do planeta","Polui o ar que respiramos","Diminui a pressão atmosférica"],"B",2,48));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"A corrosão é processo químico que degrada metais quando expostos a ambientes corrosivos. Proteção contra corrosão é essencial para manutenção de estruturas metálicas.","A corrosão é processo que:",["Fortalece os metais","Degrada metais quando expostos a ambientes corrosivos","Aumenta a vida útil das estruturas","É benéfica para a indústria","Não causa danos aos materiais"],"B",1,76));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"O pH é escala que mede acidez ou alcalinidade de uma solução. Valores abaixo de 7 indicam acidez, enquanto valores acima de 7 indicam alcalinidade.","Valores de pH abaixo de 7 indicam:",["Alcalinidade","Acidez","Neutralidade","Temperatura elevada","Pressão atmosférica alta"],"B",1,80));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"A dessalinização é processo de remoção de sal da água do mar, tornando-a própria para consumo humano. Essencial em regiões com escassez, mas consome grandes quantidades de energia.","A dessalinização é importante porque:",["Torna a água do mar mais salgada","Fornece água doce em regiões com escassez","É um processo barato e eficiente","Não consome energia","Não causa impactos ambientais"],"B",2,50));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"As baterias de lítio-ion são amplamente utilizadas em dispositivos eletrônicos e veículos elétricos. No entanto, mineração de lítio e descarte inadequado causam danos ambientais significativos.","Um problema ambiental associado às baterias de lítio-ion é:",["Poluição causada pela mineração e descarte inadequado","Emissão de gases de efeito estufa durante seu uso","Contaminação do solo por componentes radioativos","Aquecimento global causado por seu funcionamento","Diminuição da camada de ozônio"],"A",2,45));n+=1
# Biologia 15
d="biologia"
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"A biodiversidade brasileira é uma das maiores do mundo, com milhões de espécies. No entanto, desmatamento e degradação de habitats ameaçam a sobrevivência de muitas espécies.","A principal ameaça à biodiversidade brasileira é:",["Aumento da temperatura global","Desmatamento e degradação de habitats","Diminuição da população humana","Aumento da precipitação pluviométrica","Redução do número de espécies invasoras"],"B",1,80));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"As mudanças climáticas afetam diretamente ecossistemas naturais e biodiversidade. Aumento da temperatura global pode alterar padrões de precipitação e causar extinção de espécies.","Uma consequência das mudanças climáticas é:",["Aumento do número de espécies","Extinção de espécies que não conseguem se adaptar","Diminuição da temperatura dos oceanos","Fortalecimento dos ecossistemas","Aumento da produtividade agrícola"],"B",2,52));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"O desmatamento na Amazônia tem sido tema de preocupação internacional. Floresta abriga biodiversidade enorme e desempenha papel fundamental no equilíbrio climático global.","A importância da Amazônia reside em sua capacidade de:",["Produzir dióxido de carbono","Absorver dióxido de carbono e produzir oxigênio","Aumentar a temperatura local","Gerar energia hidrelétrica","Produzir minerais preciosos"],"B",1,82));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"A fotossíntese é processo pelo qual plantas produzem próprio alimento usando luz solar, água e CO2. Esse processo é essencial para vida na Terra, produzindo oxigênio eRemovendo carbono da atmosfera.","A fotossíntese é essencial porque:",["Remove oxigênio da atmosfera","Produz oxigênio e remove carbono da atmosfera","Aumenta a temperatura local","Diminui a biodiversidade","Produz dióxido de carbono"],"B",1,78));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"As células-tronco têm potencial de se diferenciar em diferentes tipos de células do corpo humano. Pesquisa com células-tronco tem promessa para tratamentos de diversas doenças.","As células-tronco são importantes porque:",["Não têm capacidade de se diferenciar","Têm potencial de se diferenciar em diferentes tipos de células","Causam doenças no corpo humano","São encontradas apenas em animais","Não têm aplicações médicas"],"B",2,50));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"A cadeia alimentar mostra como energia e nutrientes são transferidos entre organismos de um ecossistema. Produtores formam a base, seguidos por consumidores primários, secundários e terciários.","Na cadeia alimentar, os produtores são:",["Os animais carnívoros","Os vegetais que produzem próprio alimento","Os decompositores","Os animais herbívoros","Os fungos"],"B",1,76));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"A seleção natural é mecanismo proposto por Darwin para explicar evolução das espécies. Através desse processo, organismos com características mais adequadas ao ambiente tendem a sobreviver e se reproduzir mais.","A seleção natural explica:",["Criação de novas espécies por intervenção humana","Evolução das espécies através da sobrevivência dos mais aptos","Extinção de todas as espécies","Domesticação de animais","Modificação genética artificial"],"B",2,52));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"O DNA é molécula que armazena informação genética de todos os seres vivos. Descoberta da estrutura de dupla hélice revolucionou biologia e abriu caminho para avanços na medicina.","O DNA é importante porque:",["Armazena informação genética de todos os seres vivos","É apenas uma molécula sem função específica","Causa doenças em todos os organismos","Não tem relação com hereditariedade","É encontrado apenas em plantas"],"A",1,80));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"As doenças infecciosas são causadas por patógenos como vírus, bactérias e fungos. Desenvolvimento de vacinas e antibióticos tem sido fundamental para controle dessas doenças.","O uso inadequado de antibióticos pode causar:",["Cura imediata de todas as doenças","Desenvolvimento de superbactérias resistentes","Fortalecimento do sistema imunológico","Eliminação de todos os patógenos","Aumento da resistência natural do corpo"],"B",2,48));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"A engenharia genética permite modificar DNA de organismos para obter características desejadas. Tem aplicações na agricultura, medicina e indústria, mas levanta questões éticas e ambientais.","Uma aplicação da engenharia genética na medicina é:",["Produção de combustíveis fósseis","Produção de insulina para tratamento de diabetes","Desenvolvimento de armas biológicas","Contaminação de rios","Eliminação de todas as espécies"],"B",2,50));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"Os ecossistemas aquáticos são particularmente vulneráveis à poluição e mudanças climáticas. Acidificação dos oceanos ameaça organismos como corais e moluscos.","A acidificação dos oceanos ameaça organismos porque:",["Aumenta a temperatura da água","Dissolve conchas e esqueletos de carbonato de cálcio","Aumenta a quantidade de oxigênio","Melhora as condições de vida dos corais","Não causa danos aos organismos marinhos"],"B",3,30));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"A simbiose é relação ecológica em que duas espécies diferentes vivem juntas e se beneficiam mutuamente. Um exemplo é a relação entre abelhas e flores.","Na relação de simbiose entre abelhas e flores:",["Apenas as abelhas se beneficiam","Apenas as flores se beneficiam","Ambas as espécies se beneficiam","Nenhuma das espécies se beneficia","As espécies competem entre si"],"C",2,50));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"O ciclo do carbono é um dos ciclos biogeoquímicos mais importantes. A queima de combustíveis fósseis tem desequilibrado esse ciclo, aumentando concentração de CO2 na atmosfera.","O ciclo do carbono é desequilibrado pela:",["Fotossíntese das plantas","Queima de combustíveis fósseis que aumenta CO2 na atmosfera","Respiração dos animais","Decomposição de organismos","Absorção de carbono pelos oceanos"],"B",2,48));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"A biotecnologia tem potencial para contribuir com desenvolvimento sustentável. Uso de organismos geneticamente modificados pode aumentar produtividade agrícola e reduzir necessidade de agrotóxicos.","Uma aplicação da biotecnologia que contribui com sustentabilidade é:",["Produção de combustíveis fósseis","Uso de organismos geneticamente modificados para aumentar produtividade","Desenvolvimento de armas biológicas","Eliminação de todas as espécies nativas","Contaminação intencional de rios"],"B",2,46));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"A reciclagem de resíduos sólidos é essencial para sustentabilidade ambiental. Separação correta do lixo permite que materiais como papel, vidro, plástico e metal sejam reprocessados.","A reciclagem é importante porque:",["Aumenta a quantidade de lixo nos aterros","Permite reutilização de materiais e reduz desperdício","Elimina completamente necessidade de produção de novos materiais","Aumenta consumo de recursos naturais","Polui ainda mais o meio ambiente"],"B",1,86));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"A mudança climática afeta a produtividade agrícola global. Plantio em diferentes estações do ano pode ser impactado por variações de temperatura e precipitação.","A mudança climática afeta a produtividade agrícola porque:",["Aumenta a produtividade em todas as regiões","Pode alterar padrões de plantio e colheita","Não afeta a agricultura","Apenas beneficia produtores","Não tem impacto na segurança alimentar"],"B",2,48));n+=1
# MATEMATICA
p="M";a="matematica"
# Algebra 15
d="algebra"
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"Se um partido recebe R$ 6 milhões para campanhas e distribui entre 30 candidatos, média por candidato seria R$ 200 mil.","Se R$ 6 milhões são distribuídos entre 30 candidatos igualmente, quanto cada um recebe?",["R$ 100 mil","R$ 150 mil","R$ 200 mil","R$ 250 mil","R$ 300 mil"],"C",1,85));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"Se em município com 120 mil eleitores compareceram 90 mil às urnas, a taxa de comparecimento seria de 75%.","Se 90 mil de 120 mil compareceram às urnas, a taxa foi de:",["60%","70%","75%","80%","90%"],"C",1,88));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"O custo médio por voto pode ser calculado dividindo total gasto pelo número de votos. Se candidato gastou R$ 600 mil e recebeu 12 mil votos, custo médio seria R$ 50.","Se R$ 600 mil e 12 mil votos, quanto custou cada voto em média?",["R$ 25","R$ 50","R$ 75","R$ 100","R$ 150"],"B",2,58));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"Se candidato recebeu 4 mil votos no primeiro turno e 7 mil no segundo, a variação foi de 3 mil votos.","Se 4 mil no primeiro e 7 mil no segundo, a variação foi de:",["3 mil votos","7 mil votos","11 mil votos","4 mil votos","14 mil votos"],"A",1,82));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"Se população de município é 80 mil e cresce 2,5% ao ano, pode-se projetar população futura.","Se 80 mil crescem 2,5% ao ano, população após 5 anos será aproximadamente:",["85 mil","90 mil","91 mil","95 mil","100 mil"],"C",3,28));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"Se partido precisa dividir R$ 900 mil entre dois estados de forma que primeiro receba quádruplo do segundo.","Se primeiro recebe quádruplo do segundo, quanto cada um recebe de R$ 900 mil?",["R$ 180 mil para cada","R$ 360 mil e R$ 540 mil","R$ 450 mil para cada","R$ 180 mil e R$ 720 mil","R$ 300 mil e R$ 600 mil"],"D",2,52));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"Se candidato recebeu 35% dos votos válidos em município de 150 mil eleitores, pode-se calcular número de votos.","Se 35% de 150 mil eleitores, quantos votos recebeu?",["42 mil votos","52,5 mil votos","60 mil votos","70 mil votos","80 mil votos"],"B",1,86));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"Se número de eleitores cresceu de 90 mil para 120 mil em 4 anos, taxa de crescimento anual pode ser calculada.","Se 90 mil para 120 mil em 4 anos, taxa média anual foi de:",["7,5%","10%","12,5%","15%","20%"],"A",2,50));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"Se 30% dos eleitores votam no partido A e total é 200 mil, pode-se calcular quantos eleitores isso representa.","Se 30% de 200 mil eleitores votam no partido A, quantos são?",["40 mil eleitores","50 mil eleitores","60 mil eleitores","70 mil eleitores","80 mil eleitores"],"C",1,82));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"Se candidato A recebeu quádruplo de votos do candidato B e juntos receberam 150 mil votos, pode-se usar proporção.","Se A recebeu quádruplo de B e juntos tiveram 150 mil votos:",["A: 30 mil, B: 120 mil","A: 50 mil, B: 100 mil","A: 75 mil, B: 75 mil","A: 120 mil, B: 30 mil","A: 100 mil, B: 50 mil"],"D",2,50));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"Se sete candidatos receberam 3, 8, 12, 18, 22, 28 e 35 mil votos, a média pode ser calculada.","Se sete candidatos receberam 3, 8, 12, 18, 22, 28 e 35 mil votos, média é:",["15 mil votos","18 mil votos","20 mil votos","25 mil votos","30 mil votos"],"B",2,55));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"Se custo de campanha é modelado por C(x) = 4x² + 180x, pode-se calcular custo para visitar 6 municípios.","Se C(x) = 4x² + 180x, custo para visitar 6 municípios é:",["R$ 1.224","R$ 1.296","R$ 1.440","R$ 1.584","R$ 1.728"],"B",3,32));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"Notação científica é útil para representar números muito grandes. O número 9.200.000.000 pode ser representado em notação científica.","O número 9.200.000.000 em notação científica é:",["9,2 x 10⁸","9,2 x 10⁹","92 x 10⁸","0,92 x 10¹⁰","920 x 10⁷"],"B",2,50));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"Se gasto máximo é R$ 900 mil e mínimo R$ 90 mil, pode-se representar como inequação.","Se gasto máximo R$ 900 mil e mínimo R$ 90 mil, representação correta é:",["90.000 < gasto < 900.000","90.000 ≤ gasto ≤ 900.000","90.000 ≥ gasto ≥ 900.000","gasto > 900.000","gasto < 90.000"],"B",2,48));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"Se dois municípios realizam eleições a cada 4 e 6 anos respectivamente, o MMC indica quando coincidirão.","Se eleições a cada 4 e 6 anos, quando coincidirão?",["A cada 8 anos","A cada 10 anos","A cada 12 anos","A cada 18 anos","A cada 24 anos"],"C",3,35));n+=1
# Geometria 15
d="geometria"
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"Se terreno quadrado tem 15 m de lado, sua área pode ser calculando elevando aresta ao quadrado.","Qual é área de terreno quadrado com 15 m de lado?",["30 m²","60 m²","150 m²","225 m²","2.250 m²"],"D",1,88));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"Se sala retangular mede 12 m de comprimento por 9 m de largura, sua área pode ser calculada multiplicando comprimento pela largura.","Qual é área de sala retangular com 12 m x 9 m?",["21 m²","45 m²","81 m²","108 m²","216 m²"],"D",1,86));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"Se triângulo retângulo tem catetos de 6 cm e 8 cm, hipotenusa pode ser calculada pelo Teorema de Pitágoras.","Se catetos medem 6 cm e 8 cm, hipotenusa mede:",["10 cm","12 cm","14 cm","48 cm","100 cm"],"A",1,82));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"Se círculo tem raio de 12 m, área pode ser calculada usando A = πr².","Se raio é 12 m, área aproximada é:",["45,2 m²","90,4 m²","452 m²","904 m²","4.520 m²"],"C",2,55));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"Se cubo tem aresta de 5 m, volume pode ser calculado elevando aresta ao cubo.","Qual é volume de cubo com aresta de 5 metros?",["25 m³","75 m³","100 m³","125 m³","625 m³"],"D",1,90));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"Se terreno retangular mede 30 m por 25 m, área pode ser facilmente calculada.","Qual é área de terreno retangular com 30 m x 25 m?",["300 m²","500 m²","750 m²","1.000 m²","7.500 m²"],"C",1,85));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"Se losango tem diagonais de 12 cm e 10 cm, área pode ser calculada usando A = (d1 × d2)/2.","Qual é área de losango com diagonais de 12 cm e 10 cm?",["22 cm²","60 cm²","120 cm²","144 cm²","240 cm²"],"B",2,52));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"Se cilindro tem raio da base de 7 m e altura de 15 m, volume pode ser calculado usando V = πr²h.","Se raio é 7 m e altura 15 m, volume aproximado é:",["462 m³","770 m³","2.310 m³","4.620 m³","7.700 m³"],"C",2,50));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"Se triângulo equilátero tem lados de 10 m, área pode ser calculada usando A = (l² × √3)/4.","Qual é área aproximada de triângulo equilátero com lados de 10 m?",["25 m²","43,3 m²","50 m²","100 m²","200 m²"],"B",3,38));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"Se cone tem raio da base de 8 m e altura de 12 m, volume pode ser calculado usando V = (πr²h)/3.","Se raio é 8 m e altura 12 m, volume aproximado é:",["256 m³","768 m³","804 m³","1.536 m³","2.010 m³"],"C",2,48));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"Se esfera tem raio de 7 m, volume pode ser calculado usando V = (4πr³)/3.","Se raio é 7 m, volume aproximado é:",["343 m³","923 m³","1.436 m³","2.009 m³","3.000 m³"],"C",2,45));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"Se prisma retangular tem dimensões 8 m x 5 m x 6 m, volume pode ser calculado multiplicando três dimensões.","Qual é volume de prisma retangular com 8 m x 5 m x 6 m?",["80 m³","120 m³","200 m³","240 m³","2.400 m³"],"D",1,80));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"Se paralelepípedo retangular mede 10 cm x 6 cm x 4 cm, volume pode ser calculado multiplicando três dimensões.","Qual é volume de paralelepípedo com 10 cm x 6 cm x 4 cm?",["60 cm³","100 cm³","140 cm³","240 cm³","600 cm³"],"D",1,82));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"Se trapézio tem bases de 10 cm e 14 cm e altura de 8 cm, área pode ser calculada usando A = (B + b) × h / 2.","Qual é área de trapézio com bases 10 cm e 14 cm e altura 8 cm?",["48 cm²","80 cm²","96 cm²","160 cm²","192 cm²"],"C",2,52));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"Se setor circular tem raio de 12 cm e ângulo central de 120°, área pode ser calculada usando A = (πr² × θ) / 360.","Qual é área de setor circular com raio 12 cm e ângulo 120°?",["48π cm²","96π cm²","150,7 cm²","288π cm²","452 cm²"],"B",3,35));n+=1
# Estatistica 10
d="estatistica"
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"Se 150 mil votos foram distribuídos entre 15 candidatos, média de votos por candidato pode ser calculada.","Se 150 mil votos entre 15 candidatos, média é:",["8 mil votos","10 mil votos","12 mil votos","15 mil votos","20 mil votos"],"B",1,88));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"O desvio padrão indica quanto dados se afastam da média. Desvio padrão baixo indica que votos estão concentrados em torno da média.","Desvio padrão baixo indica:",["Concentração de votos em torno da média","Dispersão dos votos entre candidatos","Igualdade na distribuição","Ausência de votos nulos","Igualdade no número de eleitores"],"A",2,50));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"Se pesquisa indica 55% das intenções de voto com margem de erro de 3%, percentual real pode variar entre 52% e 58%.","Se 55% com margem de erro 3%, percentual real varia entre:",["50% e 60%","52% e 58%","54% e 56%","53% e 57%","55% e 57%"],"B",2,46));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"Se historicamente 60% dos eleitores votam no partido Z, pode-se estimar probabilidade de esse padrão se repetir.","Se historicamente 60% votam no partido Z, probabilidade estimada é:",["40%","50%","60%","80%","100%"],"C",1,78));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"Coeficiente de correlação negativo alto entre desemprego e comparecimento indica que municípios com mais desemprego tendem a ter menor comparecimento.","Coeficiente negativo alto indica que:",["Municípios com mais desemprego têm maior comparecimento","Municípios com mais desemprego tendem a ter menor comparecimento","Não existe relação","Renda não influencia comparecimento","Todos têm mesmo comparecimento"],"B",2,48));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"A mediana é valor que separa dados em duas partes iguais. Na análise eleitoral, mediana pode indicar valor central das candidaturas.","Se candidatos receberam 10, 15, 20, 25 e 100 mil votos, mediana é:",["10 mil votos","15 mil votos","20 mil votos","25 mil votos","100 mil votos"],"C",2,52));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"A moda é valor que mais se repete em conjunto de dados. Na análise eleitoral, moda pode indicar número de votos mais comum entre candidatos.","Se candidatos receberam 10, 15, 20, 15 e 15 mil votos, moda é:",["10 mil votos","15 mil votos","20 mil votos","17 mil votos","25 mil votos"],"B",1,80));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"Variância é medida de dispersão que indica quanto dados se afastam da média. Quanto maior variância, mais dispersos estão dados.","Se variância dos votos é baixa, isso indica:",["Dados dispersos da média","Dados concentrados na média","Dados iguais em todos candidatos","Dados uniformemente distribuídos","Dados com valor zero"],"B",2,50));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"Se pesquisa indica 60% ± 2%, intervalo de confiança indica precisão da estimativa.","Se pesquisa indica 60% ± 2%, intervalo de confiança é:",["56% a 64%","58% a 62%","55% a 65%","59% a 61%","60% a 62%"],"B",2,52));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"Percentil indica posição de um valor em relação ao restante dos dados. Se candidato está no percentil 85, 85% dos candidatos receberam menos votos.","Se candidato está no percentil 85:",["85% dos candidatos receberam mais votos","85% dos candidatos receberam menos votos","Ele recebeu 85% dos votos totais","Ele recebeu apenas 15% dos votos","Ele está na posição 85 de 100"],"B",3,35));n+=1
# Probabilidade 5
d="probabilidade"
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"Se eleitor escolhe aleatoriamente entre 5 candidatos, probabilidade de votar em cada candidato seria 1/5.","Se escolhe entre 5 candidatos, probabilidade é:",["1/2","1/3","1/4","1/5","1/6"],"D",1,82));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"Se probabilidade de ser eleito é 35%, probabilidade de não ser eleito é 65%. Soma deve ser igual a 1.","Se probabilidade de ser eleito é 35%, probabilidade de não ser é:",["25%","35%","50%","65%","100%"],"D",1,80));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"Se 50% dos eleitores de partido são do sexo feminino, probabilidade de escolher aleatoriamente eleitora desse partido é 50%.","Se 50% são mulheres, probabilidade de escolher mulher é:",["25%","40%","50%","60%","75%"],"C",2,52));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"Distribuição binomial modela número de sucessos em tentativas independentes. Pode calcular probabilidade de k votos em n eleitores.","A distribuição binomial calcula:",["Média de votos","Probabilidade de k sucessos em n tentativas","Desvio padrão","Correlação entre variáveis","Área de um terreno"],"B",3,28));n+=1
Q.append(q(f"{p}2019_{n:02d}",2019,a,d,"O Teorema de Bayes atualiza probabilidades com base em novas evidências. Na análise eleitoral, ajusta previsões quando novos dados são disponibilizados.","O Teorema de Bayes é utilizado para:",["Calcular média","Atualizar probabilidades com base em novas evidências","Determinar área de um círculo","Calcular soma de uma progressão","Prever o tempo"],"B",3,25));n+=1
print(f"Total 2019: {len(Q)}")
assert len(Q)==180,f"Esperado 180, obtido {len(Q)}"
with open('data/2019.json','w',encoding='utf-8') as f:
    json.dump(Q,f,ensure_ascii=False,indent=2)
print("Arquivo data/2019.json criado com sucesso!")
