import json, os
random_seed = 2009
questions = []
id_counter = 1

def q(area, disc, ctx, text, pergunta, opts, gab, dif, taxa):
    global id_counter
    prefix = {"linguagens":"L","humanas":"H","natureza":"N","matematica":"M"}[area]
    qid = f"{prefix}2009_{id_counter:02d}"
    id_counter += 1
    return {"id":qid,"ano":2009,"area":area,"disciplina":disc,"contexto":ctx,"texto":text,"pergunta":pergunta,"opcoes":opts,"gabarito":gab,"dificuldade":dif,"taxaAcerto":taxa}

# LINGUAGENS - Portugues (20)
questions.append(q("linguagens","portugues","Leia o texto abaixo para responder à questão.","A descoberta do pré-sal no Brasil, anunciada oficialmente em 2007 e confirmada em 2009, trouxe perspectivas de desenvolvimento sem precedentes para o país. Geólogos e engenheiros de petróleo trabalham intensamente para mapear essas reservas, que podem conter bilhões de barris de petróleo. No entanto, debates sobre a exploração sustentável e a distribuição dos lucros gerados por essa atividade dominam a pauta política nacional.","Considerando o contexto apresentado, a expressão 'bilhões de barris de petróleo' funciona como:",["Um adjetivo substantivado que qualifica a quantidade de petróleo encontrada","Uma locução adverbial de quantidade que modifica o verbo 'conter'","Um complemento nominal do substantivo 'reservas'","Um apostilhamento explicativo de 'pré-sal'","Um adjunto adverbial de quantidade que modifica o advérbio 'onde'"],"C",2,55))
questions.append(q("linguagens","portugues","Leia o poema abaixo para responder à questão.","No meio do caminho tinha uma pedra\ntinha uma pedra no meio do caminho\ntinha uma pedra\ntinha uma pedra no meio do caminho\ntinha uma pedra.\n\nNo meio do caminho tinha uma pedra.\n\nJamais me esquecerei desse acontecimento\nna vida de minhas retinas fatigadas.\n\n(Carlos Drummond de Andrade)","A repetição do termo 'pedra' ao longo do poema produz, no leitor, a sensação de:",["Vaidade diante da descoberta de uma novidade","Descaso diante de um obstáculo que se repete","Indiferença diante da monotonia cotidiana","Ansiedade diante de um evento surpreendente","Felicidade diante de uma situação inesperada"],"C",1,78))
questions.append(q("linguagens","portugues","Leia o texto abaixo para responder à questão.","A crise financeira que abalou os mercados globais a partir de 2008 atingiu plenamente o Brasil em 2009. O PIB registrou contração de 0,3%, quebrando uma sequência de anos de crescimento acelerado. Especialistas apontam que a desaceleração econômica teve impactos diretos no mercado de trabalho, com aumento do desemprego informal.","Assinale a alternativa em que a palavra destacada atua como substantivo.",["O PIB registrou contração de 0,3%","Especialistas apontam que a desaceleração econômica teve impactos diretos","O governo implementou medidas de estímulo","A crise abalou os mercados globais","Apesar disso, o governo ajudou a conter os efeitos"],"C",2,52))
questions.append(q("linguagens","portugues","Leia o texto abaixo para responder à questão.","A ficção científica brasileira tem ganhado espaço nos últimos anos. Escritores como Gerson Lodi-Roza e Roberto de Sousa Cudiguey vêm produzindo obras que misturam elementos da cultura popular com tecnologia e futurologia. Essas narrativas frequentemente retratam cenários em que a sociedade brasileira enfrenta desafios.","No trecho 'vêm produzindo obras', a locução verbal indica:",["Ação que começou no passado e pode continuar no futuro","Ação repetida em momentos diferentes do passado","Ação que começou no passado e que continua no presente","Ação que começou no passado e se encerrou antes de outra","Ação futura com relação ao momento da fala"],"C",1,72))
questions.append(q("linguagens","portugues","Leia o fragmento abaixo para responder à questão.","No Brasil de 2009, o debate sobre a revisão de férias compulsórias para servidores públicos ganhou repercussão nacional. O governo federal argumentava que a medida era necessária para reduzir o gasto público em meio à crise econômica. Por outro lado, sindicatos dos servidores criticaram a proposta.","No período 'O governo federal argumentava que a medida era necessária', identifique a classificação gramatical da palavra 'era':",["Verbo ser, no pretérito imperfeito do indicativo, na terceira pessoa do singular","Verbo ser, no pretérito imperfeito do subjuntivo, na terceira pessoa do singular","Verbo ser, no pretérito perfeito do indicativo, na terceira pessoa do singular","Verbo ser, no pretérito mais-que-perfeito do indicativo, na terceira pessoa do singular","Verbo ser, no presente do indicativo, na terceira pessoa do singular"],"A",2,60))
questions.append(q("linguagens","portugues","Leia o texto abaixo para responder à questão.","A chegada de Obama à presidência dos Estados Unidos em janeiro de 2009 marcou um período de esperança para milhões de pessoas ao redor do mundo. O primeiro presidente afro-americano da nação mais poderosa do planeta prometia mudanças em políticas de saúde, educação e relações internacionais.","Assinale a alternativa em que a expressão funciona como adjunto adverbial.",["A chegada de Obama à presidência dos Estados Unidos","O primeiro presidente afro-americano da nação","Mais poderosa do planeta prometia mudanças","No Brasil, a diplomacia buscou fortalecer os laços comerciais","Em meio à crise financeira"],"E",2,48))
questions.append(q("linguagens","portugues","Leia o trecho abaixo para responder à questão.","O Auto da Compadecida, de Glauber Rocha, é considerado uma das obras-primas do cinema brasileiro. Baseado na obra de Ariano Suassuna, a película retrata as aventuras de João Grilo e Chicó no sertão nordestino. Através de humor e crítica social, o filme aborda temas como a desigualdade social.","Assinale a alternativa em que há uma oração subordinada substantiva objetiva direta.",["O filme retrata as aventuras de João Grilo","O filme é considerado uma das obras-primas do cinema brasileiro","Através de humor e crítica social, o filme aborda temas","O filme aborda temas como a desigualdade social","Lançado em 2000, tornou-se referência"],"A",3,32))
questions.append(q("linguagens","portugues","Leia o poema abaixo para responder à questão.","Morte e vida Severina é uma peça que retrata a vida de retirantes nordestinos. Severina é uma personagem que busca sobrevivência em meio à seca e à miséria. A obra mescla poesia e drama, denunciando as condições sociais do sertão nordestino.","A expressão 'cordão umbilical de todas as mortes' pode ser interpretada como:",["Uma referência literal à profissão de parteira da personagem","Um símbolo que liga a morte à vida em um ciclo contínuo","Uma metáfora para a pobreza extrema vivida pela personagem","Uma referência à religião da personagem","Um eufemismo para a tragédia vivida pela comunidade"],"B",1,74))
questions.append(q("linguagens","portugues","Leia o texto abaixo para responder à questão.","A popularização da internet no Brasil atingiu patamares recordes em 2009. Segundo o IBGE, aproximadamente 67 milhões de brasileiros tinham acesso à rede mundial de computadores. O crescimento foi impulsionado pela queda no preço dos computadores pessoais e pela expansão das redes de banda larga.","Assinale a alternativa em que há um período composto por subordinação.",["A popularização da internet atingiu patamares recordes","Segundo o IBGE, aproximadamente 67 milhões tinham acesso","O que representava cerca de 38% da população","O crescimento foi impulsionado pela queda no preço","Especialistas apontavam que a inclusão digital seria fundamental"],"E",1,70))
questions.append(q("linguagens","portugues","Leia o texto abaixo para responder à questão.","Em 2009, o Brasil sediou a Reunião de Chefes de Estado e de Governo da Unasul. O encontro, realizado em Brasília, abordou temas como a integração regional e o desenvolvimento sustentável. O presidente Lula defendeu a criação de um banco sul-americano de desenvolvimento.","Assinale a alternativa em que a palavra destacada atua como conjunção integrante.",["O encontro abordou temas como a integração regional","O presidente defendeu a criação de um banco que financiaria projetos","Alguns dos quais questionavam a viabilidade financeira","A proposta gerou debate entre os participantes","O encontro, realizado em Brasília, abordou temas"],"A",3,38))
questions.append(q("linguagens","portugues","Leia o trecho abaixo para responder à questão.","Eu nasci sexta-feira, 13 de março, uma grande mancha de vinho tinto. Minha mãe disse: Minha filha, tudo isso vai passar. O poema expressa a fragilidade da condição humana diante do destino.","O sujeito da oração 'uma grande mancha de vinho tinto' é do tipo:",["Sujeito simples, oculto, de referência indefinida","Sujeito composto, oculto, de referência definida","Sujeito inexistente (oração sem sujeito)","Sujeito simples, oculto, de referência definida","Sujeito indeterminado"],"C",2,54))
questions.append(q("linguagens","portugues","Leia o texto abaixo para responder à questão.","A ascensão do Twitter como ferramenta de comunicação política transformou a forma como os governantes interagem com a população. No Brasil, políticos começaram a usar a plataforma para divulgar suas ações governamentais. No entanto, a rapidez com que as informações são compartilhadas também trouxe desafios.","No trecho 'a rapidez com que as informações são compartilhadas', a locução 'com que' atua como:",["Preposição regida pelo substantivo 'rapidez'","Conjunção integrante","Pronome relativo composto","Locução conjuntiva","Advérbio de modo"],"A",3,42))
questions.append(q("linguagens","portugues","Leia o texto abaixo para responder à questão.","O defining moment da carreira do músico brasileiro no cenário internacional pode ser marcado pela participação em festivais como o Rock in Rio. Em 2009, o festival celebrou sua sétima edição, reunindo artistas nacionais e internacionais.","A expressão 'defining moment' pode ser traduzida corretamente como:",["Momento de definição","Ponto de encontro","Momento decisivo","Definição do momento","Ponto de definição"],"C",2,58))
questions.append(q("linguagens","portugues","Leia o texto abaixo para responder à questão.","A reforma do Código Civil brasileiro, implementada em 2002, completou sete anos de vigência em 2009. O novo código trouxe mudanças significativas em áreas como direito de família e direito das obrigações. Uma das principais novidades foi o reconhecimento da união estável como entidade familiar.","Assinale a alternativa em que a palavra destacada está sendo empregada como verbo.",["A reforma do Código Civil completou sete anos de vigência","O novo código trouxe mudanças significativas","Uma das principais novidades foi o reconhecimento","A reforma também alterou a maioridade civil","A maioridade penal para crimes civis"],"D",1,80))
questions.append(q("linguagens","portugues","Leia o texto abaixo para responder à questão.","A commercialização de produtos orgânicos cresceu de forma significativa no Brasil em 2009. A pesquisa DataPopular revelou que 23% dos brasileiros já haviam consumido alimentos orgânicos, um aumento de 15 pontos percentuais em relação ao ano anterior.","No trecho 'Um aumento de 15 pontos percentuais em relação ao ano anterior', a expressão sublinhada funciona como:",["Adjunto adverbial de tempo","Complemento nominal do substantivo 'aumento'","Adjunto adverbial de proporção","Apostilhamento explicativo","Adjunto adverbial de comparação"],"B",2,50))
questions.append(q("linguagens","portugues","Leia o texto abaixo para responder à questão.","A Copa do Mundo Sub-20 de 2009, realizada no Egito, teve como campeã a seleção brasileira. O torneio reuniu as melhores seleções juvenis do mundo e serviu como vitrine para jovens talentos. A conquista brasileira foi celebrada como uma demonstração da força da formação de jogadores no país.","Na oração 'A Copa teve como campeã a seleção brasileira', a expressão 'como campeã' funciona como:",["Adjunto adverbial de modo","Complemento nominal do verbo 'teve'","Predicativo do sujeito","Apostilhamento explicativo","Adjunto adverbial de proporção"],"B",2,53))
questions.append(q("linguagens","portugues","Leia o texto abaixo para responder à questão.","A Empiricus, empresa especializada em recomendações de investimentos financeiros, investiu pesadamente em publicidade no Brasil em 2009. O mercado financeiro brasileiro vivia um momento de instabilidade após a crise global, e muitos investidores buscavam orientação profissional.","Assinale a alternativa em que a palavra destacada está empregada como adjetivo.",["A Empiricus investiu pesadamente em publicidade","O mercado financeiro brasileiro vivia um momento","Muitos investidores buscavam orientação profissional","Os ativos de menor risco","Tempos de incerteza econômica"],"C",2,57))
questions.append(q("linguagens","portugues","Leia o texto abaixo para responder à questão.","A ascensão do Twitter como ferramenta de comunicação política transformou a forma como os governantes interagem com a população. Em 2009, o Brasil vivia um momento de transformação digital. As redes sociais passaram a ser usadas como ferramentas de marketing político e de comunicação direta com os eleitores.","Assinale a alternativa em que há uma oração subordinada substantiva subjetiva.",["O governo implementou medidas que surtiram efeitos","O que surpreendeu a todos foi o resultado","Especialistas apontavam que a mudança seria fundamental","A transformsão digital já havia começado","A mudança que ocorreu foi significativa"],"C",3,35))
questions.append(q("linguagens","portugues","Leia o poema abaixo para responder à questão.","Ora (-Se) bored se é bom para a alma\nMas (Se) seres vivos se alimentam\nE seres vivos se reproduzem\nEntão a vida é simples e bela\nPois cada ser vivo é um milagre\nDa natureza\n\n(Carlos Drummond de Andrade)","O sujeito da oração 'cada ser vivo é um milagre' é:",["Sujeito simples, oculto, de referência indefinida","Sujeito simples, explícito, de referência definida","Sujeito inexistente","Sujeito composto, explícito","Sujeito indeterminado"],"B",2,56))
questions.append(q("linguagens","portugues","Leia o texto abaixo para responder à questão.","O movimento dos sem-teto ganhou força em 2009, com ocupações de terrenos urbanos em grandes capitais brasileiras. Organizações sociais e movimentos populares reivindicavam o direito à moradia digna para milhões de brasileiros que viviam em condições precárias.","Assinale a alternativa em que a palavra destacada atua como advérbio.",["O movimento ganhou força significativa","Millhões de brasileiros vivem em condições precárias","Organizações reivindicavam o direito à moradia digna","A moradia era precária para milhões de pessoas","As ocupações ocorreram em grandes capitais brasileiras"],"E",2,55))

# LINGUAGENS - Ingles (10)
questions.append(q("linguagens","ingles","Read the text below to answer the question.","The global financial crisis of 2008-2009 affected countries worldwide. The United States experienced its worst recession since the Great Depression. In Brazil, the impact was less severe than expected, largely due to the country's strong domestic market and sound macroeconomic policies.","According to the text, Brazil was less affected by the financial crisis because of:",["The collapse of its banking system","Its strong domestic market and sound macroeconomic policies","The massive stimulus packages implemented by other countries","Its isolation from the global financial system","The devaluation of the Brazilian currency"],"B",1,82))
questions.append(q("linguagens","ingles","Read the text below to answer the question.","The Internet has revolutionized the way people communicate and access information. In 2009, social media platforms like Facebook and Twitter experienced explosive growth. These platforms changed the dynamics of political campaigns, marketing strategies, and personal relationships.","What does the word 'integral' mean in the context of the passage?",["Secondary and unimportant","Complete and necessary","Optional and temporary","Limited and restricted","Outdated and irrelevant"],"B",1,79))
questions.append(q("linguagens","ingles","Read the text below to answer the question.","Climate change has become one of the most pressing issues of the 21st century. The United Nations Climate Change Conference held in Copenhagen in December 2009 brought together world leaders to negotiate a new agreement. However, the conference ended without a legally binding treaty.","What was the main outcome of the Copenhagen Climate Change Conference?",["A legally binding treaty was signed by all countries","The conference ended without a legally binding agreement","Greenhouse gas emissions were reduced by 50%","A new environmental agency was created","All countries committed to carbon neutrality by 2020"],"B",2,62))
questions.append(q("linguagens","ingles","Read the text below to answer the question.","The concept of sustainable development has gained prominence in recent years. Sustainable development is defined as development that meets the needs of the present without compromising the ability of future generations to meet their own needs.","According to the definition, sustainable development aims to:",["Maximize short-term economic profits","Balance current needs with future generations' needs","Eliminate all industrial activities","Focus exclusively on environmental conservation","Prioritize social programs over economic growth"],"B",1,85))
questions.append(q("linguagens","ingles","Read the text below to answer the question.","Telemedicine has emerged as a promising solution to improve healthcare access in remote areas. Studies conducted in 2009 showed that telemedicine consultations were as effective as in-person visits. However, challenges such as the lack of adequate internet infrastructure remain significant obstacles.","According to the passage, what is a major barrier to the widespread adoption of telemedicine?",["The ineffectiveness of video consultations","The lack of adequate internet infrastructure","The high cost of medical equipment","The opposition of patients to technology","The refusal of insurance companies to cover telemedicine"],"B",2,65))
questions.append(q("linguagens","ingles","Read the text below to answer the question.","The Apple iPhone, launched in 2007, transformed the smartphone industry. The App Store, which opened in 2008, allowed developers to create and distribute software, creating a new economic ecosystem.","What does 'ecosystem' refer to in the context?",["The natural environment where the iPhone was manufactured","The interconnected network of developers, users, and applications","The physical stores where iPhones are sold","The factory assembly line where iPhones are produced","The recycling program for old iPhones"],"B",2,58))
questions.append(q("linguagens","ingles","Read the text below to answer the question.","Water scarcity is a growing concern worldwide. Scientists are developing new technologies for water purification and desalination, which could help provide clean drinking water to millions.","What does 'desalination' mean in the context?",["The process of heating water to make it safe for drinking","The process of removing salt from seawater","The process of collecting rainwater in reservoirs","The process of freezing water for storage","The process of recycling wastewater"],"B",1,76))
questions.append(q("linguagens","ingles","Read the text below to answer the question.","The global food crisis had lasting effects on food security. The G8 nations pledged to provide $20 billion to support agricultural development in developing countries.","What was the main goal of the G8 pledge?",["To increase food prices in developed countries","To support agricultural development in developing countries","To reduce food production in all countries","To ban all international food trade","To eliminate organic farming worldwide"],"B",2,67))
questions.append(q("linguagens","ingles","Read the text below to answer the question.","Corporate social responsibility has gained increasing importance. Consumers showed growing preference for brands that demonstrated genuine commitment to social and environmental causes.","Younger consumers tended to prefer brands that:",["Offered the lowest prices in the market","Demonstrated commitment to social and environmental causes","Had the largest marketing budgets","Produced the most products","Were the oldest companies in the industry"],"B",1,83))
questions.append(q("linguagens","ingles","Read the text below to answer the question.","Renewable energy sources received significant attention in 2009. Solar and wind energy technologies experienced rapid growth. International cooperation and technology transfer were identified as key factors for accelerating the transition to clean energy.","What was identified as essential for accelerating the transition to clean energy?",["The complete ban on fossil fuel use","International cooperation and technology transfer","The elimination of all government subsidies","The closure of all nuclear power plants","The reduction of energy consumption by 50%"],"B",2,60))

# LINGUAGENS - Espanhol (5)
questions.append(q("linguagens","espanhol","Lea el texto a continuación para responder a la pregunta.","En 2009, la crisis económica global afectó profundamente a Latinoamérica. Brasil, como la economía más grande de la región, jugó un papel fundamental en la recuperación.","Según el texto, ¿qué papel jugó Brasil en la recuperación económica regional?",["Redució sus exportaciones para proteger el mercado interno","Jugó un papel fundamental en la recuperación económica","Aumentó sus tasas de interés para controlar la inflación","Implementó políticas de austeridad","Se aisló de la economía internacional"],"B",1,80))
questions.append(q("linguagens","espanhol","Lea el texto a continuación para responder a la pregunta.","El turismo sostenible se ha convertido en una tendencia creciente en América Latina. En Brasil, el Ministerio de Turismo lanzó una campaña para promover el turismo comunitario.","¿Cuál es el objetivo principal del turismo comunitario mencionado?",["Aumentar la construcción de hoteles de lujo","Generar ingresos para las poblaciones rurales","Reducir el número de visitantes internacionales","Promover el turismo en las grandes ciudades","Eliminar todos los programas de protección ambiental"],"B",2,68))
questions.append(q("linguagens","espanhol","Lea el texto a continuación para responder a la pregunta.","La educación a distancia ha experimentado un crecimiento significativo. En 2009, universidades comenzaron a ofrecer cursos a través de Internet.","¿Cuál es un desafío importante para la educación a distancia en América Latina?",["La falta de interés de los estudiantes","La falta de acceso a Internet de banda ancha","La abundancia de universidades físicas","El bajo costo de las tecnologías educativas","La excesiva regulación gubernamental"],"B",2,64))
questions.append(q("linguagens","espanhol","Lea el texto a continuación para responder a la pregunta.","El cine latinoamericano ganó reconocimiento internacional en 2009. El éxito se atribuye a la combinación de historias universales con perspectivas culturales únicas.","¿A qué se atribuye el éxito del cine latinoamericano?",["Al uso exclusivo de efectos especiales","A la combinación de historias universales con perspectivas culturales únicas","A la coproducción exclusiva con Hollywood","Al bajo costo de producción","A la ausencia de competencia internacional"],"B",2,61))
questions.append(q("linguagens","espanhol","Lea el texto a continuación para responder a la pregunta.","En 2009, la Unión Europea firmó acuerdos de cooperación con varios países latinoamericanos. Brasil fue identificado como un socio estratégico para la UE.","¿Por qué Brasil fue identificado como socio estratégico para la UE?",["Por su pequeño tamaño económico","Por su tamaño económico e influencia política en la región","Por su aislamiento internacional","Por su baja producción industrial","Por su escasa población"],"B",1,78))

# LINGUAGENS - Literatura (5)
questions.append(q("linguagens","literatura","Leia o trecho abaixo para responder à questão.","Clarice Lispector é uma das escritoras mais importantes da literatura brasileira. Em 'A Hora da Estrela', a autora retrata a trajetória de Macabéa, uma jovem nordestina que mora no Rio de Janeiro.","Em 'A Hora da Estrela', o narrador é um personagem que:",["Vive as mesmas experiências de Macabéa","Observa e comenta as ações de Macabéa sem interferir diretamente","É o protagonista da história","Participa ativamente da vida de Macabéa","Relata os fatos em primeira pessoa"],"B",2,56))
questions.append(q("linguagens","literatura","Leia o trecho abaixo para responder à questão.","Machado de Assis retratou a sociedade carioca do século XIX. Em 'Dom Casmurro', o narrador Bentinho relata seu relacionamento com Capitu. A obra é marcada pela ambiguidade narrativa.","Em 'Dom Casmurro', a ambiguidade narrativa permite ao leitor:",["Conhecer todos os pensamentos de Capitu","Decidir se Capitu traiu ou não Bentinho","Participar diretamente da narrativa","Saber exatamente o que aconteceu","Desconsiderar a opinião do narrador"],"B",1,75))
questions.append(q("linguagens","literatura","Leia o trecho abaixo para responder à questão.","O Modernismo brasileiro teve início com a Semana de Arte Moderna de 1922. O movimento buscava uma ruptura com os padrões literários acadêmicos e a valorização da cultura brasileira.","O principal objetivo do Modernismo brasileiro era:",["Manter os padrões literários acadêmicos","Valorizar a cultura europeia em detrimento da brasileira","Criar uma literatura mais livre e em contato com a realidade do povo","Retornar aos padrões do Arcadismo","Estabelecer uma linguagem formal e rigorosa"],"C",1,80))
questions.append(q("linguagens","literatura","Leia o trecho abaixo para responder à questão.","Graciliano Ramos é um dos principais nomes do Regionalismo brasileiro. Em 'Vidas Secas', o autor retrata a vida de uma família de retirantes no sertão nordestino. A obra é marcada por uma linguagem seca e direta.","Em 'Vidas Secas', a linguagem seca tem como objetivo:",["Embelezar a paisagem nordestina","Espelhar a aridez e a dureza da vida no sertão","Criar uma atmosfera de fantasia","Mostrar a sofisticação da família de Fabiano","Destacar a riqueza cultural do sertão"],"B",2,58))
questions.append(q("linguagens","literatura","Leia o trecho abaixo para responder à questão.","O Barroco foi um movimento artístico que se desenvolveu na Europa entre os séculos XVI e XVIII. No Brasil, o Barroco teve grande influência na arte sacra. O principal expoente do Barroco brasileiro foi Aleijadinho.","O principal expoente do Barroco brasileiro foi:",["Machado de Assis","Aleijadinho","Cândido Portinari","Tarsila do Amaral","Oswald de Andrade"],"B",2,60))

# LINGUAGENS - Artes (2)
questions.append(q("linguagens","artes","Leia o texto abaixo para responder à questão.","O cinema brasileiro ganhou reconhecimento internacional ao longo dos anos. O cinema nacional é conhecido por retratar a realidade social do Brasil de forma poética e reflexiva.","O cinema brasileiro é reconhecido internacionalmente por:",["Produzir filmes de ficção científica com efeitos especiais","Retratar a realidade social do Brasil de forma poética e reflexiva","Copiar películas hollywoodianas com elenco brasileiro","Produzir filmes exclusivamente para o mercado interno","Utilizar apenas atores estrangeiros"],"B",1,79))
questions.append(q("linguagens","artes","Leia o texto abaixo para responder à questão.","A arte contemporânea brasileira tem ganhado destaque em galerias e museus ao redor do mundo. Artistas como Vik Muniz e Ernesto Neto são reconhecidos por suas instalações inovadoras.","A arte contemporânea brasileira é reconhecida por:",["Copiar estilos europeus tradicionais","Abordar temas como identidade e memória de forma inovadora","Utilizar apenas técnicas tradicionais","Focar exclusivamente em temas religiosos","Seguir padrões artísticos pré-definidos"],"B",2,57))

# LINGUAGENS - Educação Física (2)
questions.append(q("linguagens","educacao_fisica","Leia o texto abaixo para responder à questão.","A importância da atividade física para a saúde tem sido amplamente divulgada. Estudos demonstraram que a prática regular de exercícios pode reduzir o risco de doenças cardíacas em até 40%.","Segundo o texto, a prática regular de exercícios pode reduzir o risco de doenças cardíacas em até:",["10%","20%","30%","40%","50%"],"D",1,85))
questions.append(q("linguagens","educacao_fisica","Leia o texto abaixo para responder à questão.","O esporte adaptado tem ganhado destaque no cenário esportivo. Atletas com deficiência física participam de competições internacionais. O esporte adaptado promove a saúde física, a autoestima e a integração social.","O esporte adaptado contribui para:",["Apenas a melhoria da condição física","A saúde física, a autoestima e a integração social","Exclusivamente competições esportivas","Apenas o desenvolvimento motor","Apenas o lazer individual"],"B",1,88))

# LINGUAGENS - TIC (1)
questions.append(q("linguagens","tic","Leia o texto abaixo para responder à questão.","A tecnologia da informação transformou drasticamente a educação. Em 2009, ferramentas como o Google Docs e o Moodle começaram a ser utilizadas em salas de aula brasileiras. O governo implementou o programa Um Computador por Aluno (UCA).","O programa UCA tinha como objetivo principal:",["Substituir completamente os professores por computadores","Proporcionar acesso a computadores e internet nas escolas públicas","Apenas ensinar programação de computadores","Vender computadores para escolas particulares","Apenas atualizar os laboratórios de informática"],"B",1,81))

print(f"Linguagens: {len(questions)} questions")
with open("data/2009_ling.json","w",encoding="utf-8") as f:
    json.dump(questions,f,ensure_ascii=False,indent=2)
