import json
import random
import os

random.seed(42)

def generate_questions(year):
    questions = []
    q_num = 1
    
    # ===== LINGUAGENS (45 questions) =====
    # Portugues (20)
    portugues_items = [
        ("Leia o texto sobre o Brasil em 2013.", "O Brasil vivia um período de intensas transformações sociais e econômicas. A classe média crescia e o consumo popular atingia níveis inéditos, impulsionado pelo crédito facilitado e pela política de transferência de renda. Contudo, especialistas alertavam para os riscos de um crescimento baseado em crédito e não em produtividade real.", "O texto apresenta um paradoxo típico do contexto brasileiro de 2013. Qual a relação lógica entre o crescimento do consumo e o alerta dos especialistas?", [["O crescimento do consumo é sustentável apenas quando baseado em crédito.", "O consumo popular cresceu devido à política de transferência de renda.", "O alerta dos especialistas indica riscos de um modelo baseado em crédito, não em produtividade.", "O texto defende o fim da política de transferência de renda.", "A classe média brasileira não deveria consumir tanto."], "C"]),
        ("Analise a crônica abaixo.", "Manhã de sábado. O padre abre o templo para a missa. O fiel entra, olha ao redor, procura um lugar, e senta. Os bancos são todos iguais. Não há reservas. Mas há preferências. Cada fiel tem o seu lugar de sempre, que ninguém se atreve a ocupar, mesmo que não haja nenhum aviso visível.", "O trecho retrata um comportamento social a partir da experiência religiosa. Que aspecto da cultura brasileira está sendo ilustrado?", [["A hierarquia religiosa formalizada no estatuto da Igreja.", "O individualismo exacerbado do fiel brasileiro.", "A constituição de um espaço de poder simbólico, onde a posse se dá pelo costume, e não pela regra.", "A resistência do povo brasileiro às mudanças sociais.", "O descaso dos fiéis com as normas da Igreja."], "C"]),
        ("Leia o poema de Carlos Drummond de Andrade.", "No meio do caminho tinha uma pedra\\ntinha uma pedra no meio do caminho\\ntinha uma pedra\\ntinha uma pedra no meio do caminho tinha uma pedra.", "Que sentimento o eu lírico expressa no poema?", [["A amargura de uma vida difícil.", "A celebração da liberdade.", "A resignação fatalista diante da existência.", "O júbilo de viver em viagem.", "A crítica à monotonia cotidiana."], "C"]),
        ("Leia o trecho de romance abaixo.", "Quando a luz do sol bateu no rosto do velho, ele abriu os olhos e viu que estava em um quarto estranho. Tentou se levantar, mas sentiu uma dor aguda nas costas. Olhou ao redor e viu um vaso de flores na mesinha de cabeceira, um relógio parado e uma janela aberta para o jardim.", "A descrição do ambiente e do personagem remete a um contexto de que época?", [["Século XVIII, durante o Iluminismo europeu.", "Finais do século XIX, em hotel antigo e mal frequentado.", "Início do século XX, em pequena hospedaria brasileira de província.", "Anos 1950, em hotel de luxo na capital federal.", "Época colonial, em casa de sesmeiro no interior da Bahia."], "C"]),
        ("Analise a charge sobre políticos brasileiros.", "Acharge mostra um político segurando um cartaz com a frase 'Eu sou o povo', enquanto o povo ao redor grita 'Mentira!'. Acharge ironiza a apropriação da voz popular por parte dos políticos durante os protestos de 2013.", "Acharge ironiza que aspecto do desenvolvimento brasileiro?", [["A lentidão burocrática e a dificuldade de transformar planos em ação concreta.", "A má qualidade dos materiais de construção.", "A falta de mão de obra qualificada.", "A ausência de investimento estrangeiro.", "A corrupção nas licitações públicas."], "A"]),
        ("Leia o texto publicitário abaixo.", "Você merece o melhor. Não aceite menos. Compre agora e garanta a qualidade que só nós oferecemos. Afinal, sua vida não pode esperar.", "A linguagem publicitária emprega qual recurso persuasivo principal?", [["O apelo à racionalidade, com dados e estatísticas.", "O apelo à emoção, associando o produto a um direito pessoal.", "O apelo à tradição, ligando o produto à cultura brasileira.", "O apelo à autoridade, com citações de especialistas.", "O apelo à economia, destacando preços baixos."], "B"]),
        ("Leia o poema abaixo.", "Eu não quero mais a vida\\nQue antes eu pedia\\nAo Grande Tudo\\nVim te dizer\\nQue não preciso mais\\nDe tom o a vida\\nVim te dizer\\nQue não vou mais aceitar\\nO que a vida me der.", "A atitude do eu lírico em relação à vida reflete que sentimento?", [["Resignação total diante do destino.", "Rejeição ao conformismo e busca de autonomia.", "Alegria de viver sem metas.", "Aprovação das decisões alheias.", "Perda total da esperança."], "B"]),
        ("Analise o quadrinho abaixo.", "Um personagem está sentado em um banco de praça, observando as pessoas passarem. Pensa consigo mesmo: 'Todos parecem tão ocupados... Será que alguém tem tempo para respirar?'", "A reflexão do personagem critica que aspecto da vida moderna?", [["A solidão das grandes cidades.", "A pressa e a superficialidade das relações sociais contemporâneas.", "A falta de escola no campo.", "A desigualdade entre ricos e pobres.", "A violência urbana crescente."], "B"]),
        ("Leia o texto abaixo.", "O semáforo ficou verde. Os carros começaram a se movimentar. Mas um pedestre, distraído, continuou caminhando, sem perceber a mudança. O motorista ao lado buzina. O pedestre olha, surpreso, e apressa o passo, sem pedir desculpas.", "A cena descrita revela um conflito típico de grandes centros urbanos. Qual?", [["A poluição sonora excessiva das cidades.", "A disputa por espaço entre veículos e pedestres.", "A falta de sinalização viária adequada.", "A necessidade de leis mais rigorosas para pedestres.", "A ausência de fiscalização nas vias públicas."], "B"]),
        ("Leia o texto sobre a escola.", "A escola não é apenas um espaço de transmissão de conhecimentos, mas também de formação de valores. Quando o professor ensina matemática, ele também ensina lógica, ordem, disciplina. Quando ensina história, transmite memória, identidade, cidadania.", "A afirmação defende que a educação escolar deve ser compreendida como:", [["Um espaço exclusivo de formação profissional.", "Um mecanismo de controle social da juventude.", "Um processo que vai além do conteúdo disciplinar, formando cidadãos.", "Um privilégio de poucos na sociedade brasileira.", "Uma responsabilidade apenas do Estado."], "C"]),
        ("Leia o trecho de crônica sobre Brasília.", "Em Brasília, o bonde do metrô, sem vitais, faz um silêncio pesado. O barulho se faz só com as vozes dos passageiros, que comem, leem, dormem, mexem no celular. Ninguém olha para ninguém. Todos olham para dentro de si mesmos.", "A descrição do metrô de Brasília ilustra que fenômeno social?", [["A integração cultural dos brasileiros nas grandes cidades.", "A individualização e o isolamento nas relações sociais contemporâneas.", "A modernização do transporte público no Centro-Oeste.", "A elitização do acesso ao transporte coletivo.", "A valorização do silêncio nas grandes metrópoles."], "B"]),
        ("Leia o texto sobre o consumidor brasileiro.", "O consumidor brasileiro de 2013 era mais exigente do que nunca. Com o aumento do poder de compra, ele buscava qualidade, variedade e preço justo. As empresas, para atender a essa demanda, investiam em marketing digital e em programas de fidelidade.", "Apassagem caracteriza que mudança no comportamento do consumidor brasileiro?", [["A retirada do mercado formal.", "O aumento da exigência em relação aos produtos e serviços.", "A preferência por produtos importados.", "A redução do consumo por necessidade.", "A valorização exclusiva do preço."], "B"]),
        ("Leia o poema sobre solidão.", "Solidão, você é a melhor companhia\\nQuando o mundo é mudo\\nE os amigos estão ocupados\\nSolidão, você é a melhor amiga\\nQuando o silêncio é mais forte\\nQue qualquer palavra", "O eu lírico valoriza a solidão porque ela representa:", [["A fuga total da realidade.", "A possibilidade de introspecção e autoconhecimento.", "A melancolia de quem não tem amigos.", "A incapacidade de se comunicar.", "A rejeição ao convívio social."], "B"]),
        ("Leia o texto sobre protestos de 2013.", "Em 2013, o Brasil sediou a Copa das Confederações e enfrentou protestos massivos nas ruas. Os manifestantes pediam melhorias nos serviços públicos, como saúde, educação e transporte. O governo federal tentou minimizar a dimensão dos atos, mas a pressão popular cresceu.", "O texto apresenta um conflito entre:", [["A política externa e a política interna do Brasil.", "O poder público e o setor privado.", "As expectativas da população e a resposta do governo aos protestos.", "A imprensa internacional e a imprensa brasileira.", "A elite política e a classe trabalhadora."], "C"]),
        ("Analise a charge sobre o Brasil.", "Acharge mostra dois homens em um canteiro de obras. Um deles, com capacete, diz ao outro: 'Nós precisamos construir o futuro, mas primeiro temos que tirar o Brasil do papel'. O outro, rindo, responde: 'Mas o Brasil já está no papel, só falta construir'.", "ACharge ironiza um estereótipo social brasileiro. Qual é ele?", [["A desigualdade de gênero nas relações familiares brasileiras.", "A dificuldade dos homens em envelhecer.", "A valorização da juventude feminina em detrimento da autonomia da mulher.", "A incapacidade masculina de cozinhar.", "A evolução do papel da mulher na sociedade."], "C"]),
        ("Leia o texto sobre infraestrutura.", "Na década de 2010, o Brasil viveu um período de otimismo econômico. A classe C cresceu, o consumo se expandiu e o país foi incluído no grupo dos BRICS. No entanto, a infraestrutura pública permanecia precária, e a desigualdade social, apesar dos avanços, continuava como marca registrada da sociedade brasileira.", "O trecho apresenta uma contradição típica do Brasil contemporâneo. Qual é ela?", [["A crescente inclusão social e a estabilidade política.", "O crescimento econômico e a precariedade da infraestrutura pública.", "A ampliação da classe média e a redução da inflação.", "O investimento em educação e a redução da violência.", "A expansão do crédito e a queda do desemprego."], "B"]),
        ("Leia o poema sobre amor.", "Agora é só ver\\nque o amor não se compra,\\nnão se vende,\\nnão se pede,\\nnão se empresta,\\nnão se rouba,\\nnão se perde,\\nnão se ganha,\\nnão se tem,\\nnão se persegue,\\nnão se segura,\\nnão se controls,\\nnão se liga,\\nnão se desliga,\\nnão se mange,\\nnão se diga.\\nAgora é só ver.", "A repetição de negações no poema tem qual efeito de sentido?", [["A humorística, mostrando a simplicidade do amor.", "A reforçar a ideia de que o amor escapa a qualquer forma de controle ou posse.", "A enfatizar a难dade de encontrar o amor verdadeiro.", "A criticar o consumismo na relação amorosa.", "A celebrar a liberdade de não amar."], "B"]),
        ("Leia o texto sobre protestos.", "Os manifestantes de 2013 ocuparam as ruas de diversas cidades brasileiras, expressando insatisfação com a qualidade dos serviços públicos. A Copa das Confederações serviu como palco para a pressão popular, que exigia melhorias em saúde, educação e transporte.", "A relação entre o ditado e a investigação científica revela que:", [["O ditado está equivocado, pois riscos devem ser evitados.", "A sabedoria popular contradiz a ciência.", "A linguagem popular e a científica lidam com a mesma questão por perspectivas complementares, não excludentes.", "A ciência refuta completamente a sabedoria popular.", "O ditado é irrelevante para a sociedade contemporânea."], "C"]),
        ("Leia o texto sobre resistência.", "A resistência do povo brasileiro às mudanças sociais tem raízes históricas profundas. Desde o período colonial, as elites dominantes buscaram manter o status quo, enquanto os movimentos populares lutavam por transformações. Esse confronto marcou a história política do Brasil.", "O trecho retrata um comportamento social. Que aspecto da cultura brasileira está sendo ilustrado?", [["A hierarquia religiosa formalizada no estatuto da Igreja.", "O individualismo exacerbado do fiel brasileiro.", "A constituição de um espaço de poder simbólico, onde a posse se dá pelo costume, e não pela regra.", "A resistência do povo brasileiro às mudanças sociais.", "O descaso dos fiéis com as normas da Igreja."], "C"]),
        ("Leia o poema sobre o homem comum.", "O homem comum caminha pela vida\\nSem grandes sonhos, sem grandes conquistas\\nMas carrega no peito a esperança\\nDe um amanhã melhor, mais justo, mais livre.", "O poema apresenta como tema central:", [["A natureza bela e serena.", "A frustração diante de um obstáculo repetitivo e inevitável.", "A esperança de encontrar uma nova estrada.", "A celebração da vida no campo.", "A crítica ao progresso urbano."], "B"]),
    ]
    
    for ctx, txt, perg, (opts, gab) in portugues_items:
        diff = random.choices([1,2,3], weights=[40,40,20])[0]
        taxa = random.randint(65,85) if diff==1 else (random.randint(40,65) if diff==2 else random.randint(15,40))
        questions.append({"id": f"L{year}_{q_num:02d}", "ano": year, "area": "linguagens", "disciplina": "portugues", "contexto": ctx, "texto": txt, "pergunta": perg, "opcoes": opts, "gabarito": gab, "dificuldade": diff, "taxaAcerto": taxa})
        q_num += 1
    
    # Ingles (10)
    ingles_items = [
        ("Leia o texto em inglês sobre redes sociais.", "The rise of social media has transformed the way we communicate. Platforms like Facebook and Twitter allow people to share their thoughts instantly, regardless of distance. However, this constant connectivity has also raised concerns about privacy, mental health, and the spread of misinformation.", "According to the text, what is the main negative impact of social media?", [["It is too expensive for most people to use.", "It has completely replaced face-to-face communication.", "It has raised concerns about privacy, mental health, and misinformation.", "It only works in English-speaking countries.", "It is only used by young people."], "C"]),
        ("Leia o poema The Road Not Taken.", "Two roads diverged in a yellow wood,\\nAnd sorry I could not travel both\\nAnd be one traveler, long I stood\\nAnd looked down one as far as I could\\nTo where it bent in the undergrowth.", "The poem explores the theme of:", [["The importance of following rules.", "The inevitability of making choices.", "The joy of traveling with friends.", "The fear of the unknown.", "The certainty of destiny."], "B"]),
        ("Leia a notícia sobre o governo dos EUA.", "In 2013, the United States government faced a partial shutdown after Congress failed to reach an agreement on the federal budget. The shutdown affected millions of federal workers and led to the closure of national parks and museums.", "What caused the US government shutdown in 2013?", [["A natural disaster.", "A failure to reach an agreement on the federal budget.", "An economic crisis.", "A presidential election.", "A foreign policy dispute."], "B"]),
        ("Leia o texto sobre globalização.", "Globalization has brought both benefits and challenges to developing countries. While it has increased trade and investment, it has also led to job losses in traditional industries and cultural homogenization.", "According to the text, which is a negative effect of globalization?", [["Increased trade.", "Job losses in traditional industries.", "Higher literacy rates.", "Better healthcare.", "More international cooperation."], "B"]),
        ("Leia o poema Do not go gentle.", "Do not go gentle into that good night,\\nOld age should burn and rave at close of day;\\nRage, rage against the dying of the light.", "The poem by Dylan Thomas encourages:", [["Acceptance of death.", "Resistance and struggle against mortality.", "Celebration of youth.", "Withdrawal from society.", "Acceptance of old age."], "B"]),
        ("Leia o texto sobre mudança climática.", "Climate change is one of the most pressing issues of the 21st century. Scientists warn that if global temperatures continue to rise, we could face catastrophic consequences, including rising sea levels and extreme weather events.", "What could happen if global temperatures continue to rise?", [["A decrease in sea levels.", "More moderate weather.", "Catastrophic consequences, including rising sea levels.", "A decrease in extreme weather.", "Nothing significant."], "C"]),
        ("Leia o texto sobre a internet.", "The Internet has revolutionized access to information. Today, anyone with a smartphone can access a vast library of knowledge. However, this abundance of information also poses challenges, such as distinguishing credible sources from misinformation.", "What is the main challenge mentioned regarding Internet access?", [["The high cost of smartphones.", "The difficulty of connecting to the Internet.", "Distinguishing credible sources from misinformation.", "The slow speed of connections.", "The lack of content available."], "C"]),
        ("Leia o texto sobre energia renovável.", "Renewable energy sources, such as solar and wind power, are becoming increasingly important as the world moves away from fossil fuels. These sources are cleaner, more sustainable, and help reduce greenhouse gas emissions.", "Why are renewable energy sources considered important?", [["They are cheaper than fossil fuels.", "They are cleaner and more sustainable.", "They are more efficient than fossil fuels.", "They are easier to produce.", "They are available everywhere."], "B"]),
        ("Leia o poema Hope is the thing with feathers.", "Hope is the thing with feathers\\nThat perches in the soul,\\nAnd sings the tune without the words,\\nAnd never stops at all.", "In Emily Dickinson's poem, hope is compared to:", [["A bird.", "A flower.", "A river.", "A star.", "A child."], "A"]),
        ("Leia o texto sobre turismo no Brasil.", "The tourism industry in Brazil grew significantly in 2013, driven by international events such as the Confederations Cup. Cities like Rio de Janeiro and São Paulo saw an increase in foreign visitors, bringing economic benefits but also challenges related to infrastructure and security.", "What challenge did the growth of tourism in Brazil present?", [["A decrease in foreign visitors.", "A decrease in hotel prices.", "Challenges related to infrastructure and security.", "An increase in unemployment.", "A decrease in local spending."], "C"]),
    ]
    
    for ctx, txt, perg, (opts, gab) in ingles_items:
        diff = random.choices([1,2,3], weights=[40,40,20])[0]
        taxa = random.randint(65,85) if diff==1 else (random.randint(40,65) if diff==2 else random.randint(15,40))
        questions.append({"id": f"L{year}_{q_num:02d}", "ano": year, "area": "linguagens", "disciplina": "ingles", "contexto": ctx, "texto": txt, "pergunta": perg, "opcoes": opts, "gabarito": gab, "dificuldade": diff, "taxaAcerto": taxa})
        q_num += 1
    
    # Espanhol (5)
    espanhol_items = [
        ("Leia o texto em espanhol sobre a Copa das Confederações.", "En 2013, Brasil recibió la Copa de las Confederaciones, un evento que demostró la capacidad del país para organizar grandes competiciones deportivas. Sin embargo, también hubo protestas ciudadanas que expresaron insatisfacción con la calidad de los servicios públicos.", "Según el texto, ¿qué conflicto surgió durante la Copa de las Confederaciones en 2013?", [["Un conflicto entre jugadores y entrenadores.", "Protestas ciudadanas sobre servicios públicos.", "Un problema con la infraestructura deportiva.", "Un desastre natural durante el evento.", "Una disputa entre estados brasileños."], "B"]),
        ("Leia o texto sobre a Amazônia.", "La Amazónia es el pulmón del mundo. Su selva alberga una biodiversidad única, pero la deforestación amenaza su existencia. Los gobiernos de la región intentan equilibrar desarrollo económico con protección ambiental, pero el desafío es enorme.", "¿Cuál es el desafío principal mencionado en el texto?", [["La falta de lluvias en la región.", "Equilibrar el desarrollo económico con la protección ambiental.", "La escasez de trabajadores en la selva.", "El exceso de turistas en la Amazonía.", "La construcción de nuevas carreteras."], "B"]),
        ("Leia o poema em espanhol.", "Yo no sé de las piedras del camino,\\nYo no sé del ruido con que pasan,\\nYo no sé de las cosas del camino,\\nPero sé de tu voz y de tu paso,\\nQue son mis dos pilotos y mis dos muletas.", "El poema expresa una relación de dependencia afectiva. ¿Cuál es la imagen central?", [["La voz y el paso como guía y apoyo.", "Las piedras del camino como obstáculo.", "El ruido del viento como compañía.", "La luz del sol como esperanza.", "El cielo azul como libertad."], "A"]),
        ("Leia o texto sobre turismo sustentável.", "El turismo sostenible se ha convertido en una tendencia global. Los viajeros buscan experiencias que respeten el medio ambiente y apoyen a las comunidades locales. Sin embargo, la falta de regulación en algunos destinos puede generar impactos negativos.", "Según el texto, ¿cuál es el principal desafío del turismo sostenible?", [["La falta de regulación que puede generar impactos negativos.", "El alto costo de los viajes ecológicos.", "La escasez de turistas interesados.", "La falta de alojamientos sostenibles.", "La prohibición de viajar a ciertas zonas."], "A"]),
        ("Leia o texto sobre educação na América Latina.", "En América Latina, el acceso a la educación superior ha aumentado en las últimas décadas. Sin embargo, la calidad de la enseñanza sigue siendo un desafío, y la deserción escolar sigue siendo alta en muchas regiones.", "¿Cuál es el principal desafío mencionado en el texto?", [["La falta de universidades.", "La calidad de la enseñanza y la deserción escolar.", "El bajo número de profesores.", "La escasez de libros de texto.", "El exceso de alumnos por aula."], "B"]),
    ]
    
    for ctx, txt, perg, (opts, gab) in espanhol_items:
        diff = random.choices([1,2,3], weights=[40,40,20])[0]
        taxa = random.randint(65,85) if diff==1 else (random.randint(40,65) if diff==2 else random.randint(15,40))
        questions.append({"id": f"L{year}_{q_num:02d}", "ano": year, "area": "linguagens", "disciplina": "espanhol", "contexto": ctx, "texto": txt, "pergunta": perg, "opcoes": opts, "gabarito": gab, "dificuldade": diff, "taxaAcerto": taxa})
        q_num += 1
    
    # Literatura (5)
    literatura_items = [
        ("Leia o trecho sobre Guimarães Rosa.", "Em Grande Sertão: Veredas, de Guimarães Rosa, o personagem Riobaldo narra suas aventuras no sertão mineiro. O texto é rico em linguagem inventiva, com neologismos e construções que desafiam a norma culta, mas que capturam a essência do falar sertanejo.", "A linguagem de Rosa tem qual característica marcante?", [["O uso exclusivo de vocabulário europeu.", "A valorização da norma culta portuguesa.", "A criação de neologismos e construções que desafiam a gramática.", "O uso de linguagem técnica científica.", "A imitação direta do falar carioca."], "C"]),
        ("Leia o poema de Drummond.", "No meio do caminho tinha uma pedra\\ntinha uma pedra no meio do caminho\\ntinha uma pedra\\ntinha uma pedra no meio do caminho tinha uma pedra.", "O poema apresenta como tema central:", [["A natureza bela e serena.", "A frustração diante de um obstáculo repetitivo e inevitável.", "A esperança de encontrar uma nova estrada.", "A celebração da vida no campo.", "A crítica ao progresso urbano."], "B"]),
        ("Leia o texto sobre o Modernismo.", "O Modernismo brasileiro, representado por autores como Mário de Andrade e Oswald de Andrade, buscou criar uma literatura autenticamente brasileira, rompendo com o padrão europeu e valorizando a língua falada no Brasil.", "O Movimento Modernista teve como principal objetivo:", [["Retornar à literatura clássica europeia.", "Criar uma literatura que expressasse a realidade brasileira.", "Defender a exclusão da língua portuguesa na literatura.", "Promover a literatura exclusivamente para a elite.", "Afastar o Brasil da cultura internacional."], "B"]),
        ("Leia o poema existencialista.", "Ora, pois, eu pergunto,\\nporque é que o homem?\\nOu antes,\\npor que é que o homem se afigura?\\nAfigura-se por acaso,\\nporque é que há-de ser?\\nOu antes,\\nporque é que há-de ser apenas?", "O eu lírico expressa:", [["A certeza de que a vida tem um sentido claro.", "A angústia existencial diante da condição humana.", "A alegria de viver no presente.", "A rejeição ao passado.", "A celebração da natureza."], "B"]),
        ("Leia o texto sobre literatura de província.", "A literatura de província brasileira retratou o cotidiano dos pequenos municípios, com seus costumes, tradições e conflitos. Autores como Monteiro Lobato e Rachel de Queiroz contribuíram para essa tradição literária, que valoriza a identidade regional.", "A literatura de província se caracteriza por:", [["A exclusão de temas regionais.", "O retrato do cotidiano e dos costumes dos pequenos municípios.", "A valorização exclusiva da cultura europeia.", "O foco em grandes centros urbanos.", "A rejeição da tradição oral."], "B"]),
    ]
    
    for ctx, txt, perg, (opts, gab) in literatura_items:
        diff = random.choices([1,2,3], weights=[40,40,20])[0]
        taxa = random.randint(65,85) if diff==1 else (random.randint(40,65) if diff==2 else random.randint(15,40))
        questions.append({"id": f"L{year}_{q_num:02d}", "ano": year, "area": "linguagens", "disciplina": "literatura", "contexto": ctx, "texto": txt, "pergunta": perg, "opcoes": opts, "gabarito": gab, "dificuldade": diff, "taxaAcerto": taxa})
        q_num += 1
    
    # Artes (2)
    artes_items = [
        ("Analise a obra de Tarsila do Amaral.", "A obra Abaporu, de Tarsila do Amaral, é um dos ícones do Modernismo brasileiro. A figura humana representada possui cabeça pequena, pés enormes e está sentada em um campo verde, simbolizando a conexão do homem brasileiro com a terra.", "A obra Abaporu representa:", [["A influência europeia na arte brasileira.", "A conexão do homem brasileiro com a terra e a valorização do primitivismo.", "A rejeição à cultura indígena.", "A representação de um ser sobrenatural.", "A crítica ao sistema capitalista."], "B"]),
        ("Leia o texto sobre o Barroco brasileiro.", "O Barroco brasileiro, presente em obras como as de Aleijadinho, combinou a religiosidade católica com elementos da cultura popular. As esculturas e arquiteturas barrocas marcaram a arte colonial no Brasil.", "O Barroco brasileiro se destacou por:", [["A rejeição da religião católica.", "A combinação de religiosidade católica com elementos da cultura popular.", "A influência exclusiva da cultura indígena.", "O uso de materiais industriais nas obras.", "A simplicidade nas formas arquitetônicas."], "B"]),
    ]
    
    for ctx, txt, perg, (opts, gab) in artes_items:
        diff = random.choices([1,2,3], weights=[40,40,20])[0]
        taxa = random.randint(65,85) if diff==1 else (random.randint(40,65) if diff==2 else random.randint(15,40))
        questions.append({"id": f"L{year}_{q_num:02d}", "ano": year, "area": "linguagens", "disciplina": "artes", "contexto": ctx, "texto": txt, "pergunta": perg, "opcoes": opts, "gabarito": gab, "dificuldade": diff, "taxaAcerto": taxa})
        q_num += 1
    
    # Educação Física (2)
    ef_items = [
        ("Leia o texto sobre atividades físicas.", "A prática de atividades físicas regulares é essencial para a manutenção da saúde. Estudos demonstram que o exercício físico reduz o risco de doenças crônicas, como diabetes e hipertensão, além de melhorar a qualidade do sono e a disposição no dia a dia.", "Segundo o texto, qual é o principal benefício da prática regular de exercícios físicos?", [["Aumento da massa muscular.", "Redução do risco de doenças crônicas e melhoria da qualidade de vida.", "Prevenção de doenças infecciosas.", "Melhoria exclusiva da saúde mental.", "Aumento da capacidade de concentração."], "B"]),
        ("Analise o caso do atleta.", "Um atleta amador participa de uma corrida de rua. Durante o trajeto, ele sente tontura e falta de ar. Ao chegar ao final, ele é socorrido por médicos, que diagnosticam desidratação severa e hipotermia.", "O que pode ter causado os sintomas do atleta?", [["Falta de aquecimento antes da corrida.", "Desidratação e hipotermia por falta de hidratação e proteção adequadas.", "Excesso de hidratação durante a corrida.", "Falta de treinamento adequado.", "Exposição excessiva ao sol."], "B"]),
    ]
    
    for ctx, txt, perg, (opts, gab) in ef_items:
        diff = random.choices([1,2,3], weights=[40,40,20])[0]
        taxa = random.randint(65,85) if diff==1 else (random.randint(40,65) if diff==2 else random.randint(15,40))
        questions.append({"id": f"L{year}_{q_num:02d}", "ano": year, "area": "linguagens", "disciplina": "educacao_fisica", "contexto": ctx, "texto": txt, "pergunta": perg, "opcoes": opts, "gabarito": gab, "dificuldade": diff, "taxaAcerto": taxa})
        q_num += 1
    
    # TIC (1)
    ctx, txt, perg, (opts, gab) = ("Leia o texto sobre tecnologia.", "A revolução digital transformou a forma como as pessoas se comunicam, trabalham e acessam a informação. A inteligência artificial e a automação estão cada vez mais presentes no cotidiano, gerando debates sobre o futuro do emprego e a privacidade dos dados.", "O texto apresenta que transformação a revolução digital trouxe para a sociedade?", [["A diminuição do acesso à informação.", "A transformação na comunicação, trabalho e acesso à informação.", "O fim da necessidade de trabalhar.", "A redução do uso da tecnologia no cotidiano.", "O isolamento total das pessoas."], "B"])
    diff = random.choices([1,2,3], weights=[40,40,20])[0]
    taxa = random.randint(65,85) if diff==1 else (random.randint(40,65) if diff==2 else random.randint(15,40))
    questions.append({"id": f"L{year}_{q_num:02d}", "ano": year, "area": "linguagens", "disciplina": "tic", "contexto": ctx, "texto": txt, "pergunta": perg, "opcoes": opts, "gabarito": gab, "dificuldade": diff, "taxaAcerto": taxa})
    q_num += 1
    
    # ===== HUMANAS (45 questions) =====
    # Historia (15)
    historia_items = [
        ("Leia o texto sobre a crise política brasileira.", "No início dos anos 2010, o Brasil vivia um período de crescimento econômico e redução da desigualdade social, impulsionado por políticas de transferência de renda. Contudo, a crise política que se intensificou a partir de 2013 abalou a confiança na classe política e levou a protestos massivos em diversas cidades do país.", "O texto apresenta que fator foi determinante para a crise política brasileira do início dos anos 2010?", [["A inflação elevada e o desemprego em massa.", "A perda de confiança na classe política e protestos nas ruas.", "A recessão econômica internacional.", "A ditadura militar no poder.", "A falta de investimento em educação."], "B"]),
        ("Analise a charge sobre política.", "Acharge mostra um político segurando um cartaz com a frase 'Eu sou o povo', enquanto o povo ao redor grita 'Mentira!'. Acharge ironiza a apropriação da voz popular por parte dos políticos durante os protestos de 2013.", "A charge retrata qual fenômeno político do período?", [["A união entre políticos e povo.", "A apropriação da voz popular pelos políticos em meio aos protestos.", "A popularidade dos políticos entre os manifestantes.", "O apoio popular às reformas políticas.", "A isenção dos políticos durante os protestos."], "B"]),
        ("Leia o texto sobre a eleição de 2012.", "A eleição de 2012 no Brasil foi marcada pela vitória de Dilma Rousseff para a presidência, em um contexto de relativa estabilidade econômica e avanços sociais. No entanto, já se anunciavam sinais de desgaste político e econômico que eclodiriam nos anos seguintes.", "A eleição de 2012 representou que momento na história política brasileira?", [["O início de uma nova ditadura militar.", "A consolidação de um período de estabilidade seguido por sinais de crise iminente.", "O fim da democracia no Brasil.", "A ascensão de um governo de extrema direita.", "O retorno ao regime monárquico."], "B"]),
        ("Leia o texto sobre a Lava Jato.", "A Operação Lava Jato, deflagrada em 2014, revelou um esquema bilionário de corrupção envolvendo a Petrobras e grandes construtoras. O caso abalou a política brasileira e levou à prisão de diversos empresários e políticos de alto escalão.", "A Operação Lava Jato teve qual impacto na política brasileira?", [["Reforçou a imagem de integridade dos políticos.", "Revelou um esquema bilionário de corrupção e levou à prisão de políticos.", "Não teve impacto significativo na política.", "Aumentou a confiança da população nos governantes.", "Causou apenas danos econômicos."], "B"]),
        ("Leia o texto sobre protestos de 2013.", "Os manifestantes de 2013 ocuparam as ruas de diversas cidades brasileiras, expressando insatisfação com a qualidade dos serviços públicos. A Copa das Confederações serviu como palco para a pressão popular, que exigia melhorias em saúde, educação e transporte.", "Os protestos de 2013 foram motivados por:", [["O aumento do imposto de renda.", "Insatisfação com a qualidade dos serviços públicos.", "A proibição de manifestações.", "O fechamento de escolas.", "A redução do salário mínimo."], "B"]),
        ("Leia o texto sobre a política de transferência de renda.", "O programa Bolsa Família, implementado em 2003, tornou-se um dos maiores programas de transferência de renda do mundo. Ele ajudou a reduzir a fome e a pobreza extrema no Brasil, mas também gerou debates sobre a dependência do Estado.", "O programa Bolsa Família teve qual impacto social?", [["Aumentou a dependência do Estado sem reduzir a pobreza.", "Ajudou a reduzir a fome e a pobreza extrema no Brasil.", "Não teve impacto na redução da desigualdade.", "Causou aumento da inflação.", "Eliminou completamente a pobreza."], "B"]),
        ("Analise a charge sobre desigualdade.", "Acharge mostra duas crianças sentadas na calçada: uma com uniforme escolar e mochila, outra vendendo doces na esquina. Ao fundo, um cartaz diz: 'Todos têm direito à educação'.", "A charge denuncia:", [["A igualdade de oportunidades entre as crianças.", "A desigualdade no acesso à educação entre crianças de diferentes classes sociais.", "A abundância de escolas em todas as regiões.", "A eficiência do sistema educacional.", "A melhoria da qualidade da educação."], "B"]),
        ("Leia o texto sobre mobilidade social.", "A mobilidade social no Brasil tem sido um tema de debate constante. Apesar dos avanços nas últimas décadas, a transição de classes sociais ainda é lenta e dependente de fatores como educação e acesso ao mercado de trabalho.", "O texto apresenta que a mobilidade social no Brasil é:", [["Rápida e acessível a todos.", "Lenta e dependente de fatores como educação e acesso ao trabalho.", "Inexistente na sociedade brasileira.", "Determinada exclusivamente pela renda familiar.", "Facilitada pelo governo federal."], "B"]),
        ("Leia o texto sobre o sistema político brasileiro.", "O sistema político brasileiro é caracterizado por uma fragmentação partidária, com diversos partidos representados no Congresso Nacional. Essa fragmentação dificulta a governabilidade e gera instabilidade política.", "A fragmentação partidária no Brasil causa:", [["Maior estabilidade política.", "Dificuldades de governabilidade e instabilidade política.", "Aumento da representatividade popular.", "Melhoria na qualidade das leis.", "Redução da corrupção."], "B"]),
        ("Analise a charge sobre protestos.", "Acharge mostra manifestantes segurando cartazes com diversas demandas, desde melhorias em saúde e educação até a redução do preço do transporte público. O governo tenta minimizar a importância dos atos.", "Os protestos de 2013 demonstraram:", [["O apoio popular ao governo.", "A insatisfação da população com diversos problemas sociais.", "A união entre governo e manifestantes.", "A aceitação das políticas públicas vigentes.", "A falta de interesse da população por política."], "B"]),
        ("Leia o texto sobre a economia brasileira.", "A economia brasileira dos anos 2010 apresentou sinais contraditórios. De um lado, houve crescimento do consumo e redução do desemprego. De outro, a inflação permaneceu elevada e a produtividade não acompanhou o ritmo de crescimento.", "A economia brasileira dos anos 2010 apresentou:", [["Estabilidade total em todos os indicadores.", "Sinais contraditórios entre crescimento do consumo e inflação elevada.", "Recessão completa em todos os setores.", "Crescimento uniforme em todas as regiões.", "Ausência de qualquer problema econômico."], "B"]),
        ("Leia o texto sobre o papel da imprensa.", "A imprensa brasileira desempenha um papel fundamental na fiscalização do poder público. Durante os protestos de 2013, a cobertura jornalística ajudou a amplificar as vozes da sociedade civil e a cobrar respostas do governo.", "O papel da imprensa durante os protestos de 2013 foi:", [["Silenciar as manifestações populares.", "Amplificar as vozes da sociedade civil e cobrar respostas do governo.", "Apoiar exclusivamente o governo.", "Ignorar os problemas sociais.", "Causar instabilidade política desnecessária."], "B"]),
        ("Leia o texto sobre reforma política.", "A reforma política no Brasil é um tema recorrente nos debates públicos. Propostas como o financiamento público de campanhas e a regulamentação da propaganda eleitoral são discutidas há anos, mas enfrentam resistência de muitos políticos.", "A reforma política no Brasil enfrenta:", [["Apoio unânime de todos os partidos.", "Resistência de muitos políticos e dificuldades de aprovação.", "Falta de interesse da população.", "Aprovação rápida no Congresso.", "Ausência de qualquer proposta concreta."], "B"]),
        ("Analise a charge sobre governo.", "Acharge mostra um político prometendo melhorias para a população, enquanto por trás dele, seus aliados distribuem benefícios entre si. O povo observa desconfiado.", "Acharge retrata:", [["A união entre governo e povo.", "A desconfiança da população em relação às promessas políticas.", "O apoio popular às políticas públicas.", "A transparência na gestão pública.", "A eficiência do governo em cumprir promessas."], "B"]),
        ("Leia o texto sobre participação cidadã.", "A participação cidadã é essencial para o funcionamento da democracia. Através do voto, da manifestação pacífica e do controle social, os cidadãos podem influenciar as decisões públicas e cobrar responsabilidades dos governantes.", "A participação cidadã na democracia se dá por:", [["Apenas o voto.", "O voto, manifestações pacíficas e controle social.", "Apenas manifestações de rua.", "Apenas o pagamento de impostos.", "Apenas o consumo de produtos nacionais."], "B"]),
    ]
    
    for ctx, txt, perg, (opts, gab) in historia_items:
        diff = random.choices([1,2,3], weights=[40,40,20])[0]
        taxa = random.randint(65,85) if diff==1 else (random.randint(40,65) if diff==2 else random.randint(15,40))
        questions.append({"id": f"H{year}_{q_num:02d}", "ano": year, "area": "humanas", "disciplina": "historia", "contexto": ctx, "texto": txt, "pergunta": perg, "opcoes": opts, "gabarito": gab, "dificuldade": diff, "taxaAcerto": taxa})
        q_num += 1
    
    # Geografia (15)
    geografia_items = [
        ("Leia o texto sobre desigualdade regional.", "O Brasil é um país continental, com enorme diversidade geográfica e cultural. Suas regiões apresentam contrastes marcantes em termos de desenvolvimento econômico, com o Sudeste concentrando a maior parte da riqueza nacional, enquanto o Norte e o Nordeste enfrentam maiores desafios sociais e ambientais.", "O texto apresenta que desafio geográfico o Brasil enfrenta?", [["A uniformidade cultural em todo o território.", "A concentração da riqueza no Sudeste e desafios sociais nas demais regiões.", "A inexistência de recursos naturais no Norte.", "A superpopulação nas grandes cidades.", "A falta de infraestrutura em todas as regiões."], "B"]),
        ("Leia o texto sobre a Amazônia.", "A Amazônia é a maior floresta tropical do mundo e abriga uma biodiversidade incomparável. No entanto, o desmatamento, a mineração ilegal e a expansão da agropecuária ameaçam constantemente esse ecossistema vital para o equilíbrio climático do planeta.", "O texto apresenta que ameaça a Floresta Amazônica enfrenta?", [["A superproteção por parte do governo.", "A desmatamento, mineração ilegal e expansão da agropecuária.", "A escassez de chuvas na região.", "O aumento do turismo na área.", "A falta de biodiversidade."], "B"]),
        ("Leia o texto sobre globalização.", "O processo de globalização intensificou a interdependência entre os países, promovendo o fluxo de capitais, tecnologias e informações. No entanto, esse processo também gerou críticas quanto à soberania nacional e à homogeneização cultural.", "O texto apresenta que crítica ao processo de globalização?", [["A redução da interdependência entre os países.", "A homogeneização cultural e a ameaça à soberania nacional.", "O isolamento dos países em relação ao mercado global.", "A diminuição do fluxo de informações.", "A ausência de tecnologia nos países pobres."], "B"]),
        ("Leia o texto sobre urbanização.", "A urbanização brasileira se acelerou nas últimas décadas, atraindo milhões de pessoas do campo para as cidades. No entanto, essa migração gerou desafios como a precariedade da infraestrutura urbana, o aumento da violência e a segregação espacial.", "A urbanização acelerada no Brasil gerou:", [["Melhoria da qualidade de vida nas cidades.", "Precariedade da infraestrutura, violência e segregação espacial.", "Redução do êxodo rural.", "Aumento do emprego no campo.", "Melhoria da distribuição de renda."], "B"]),
        ("Analise a charge sobre meio ambiente.", "Acharge mostra uma fábrica despejando resíduos em um rio, enquanto um peixe olha para trás com expressão de preocupação. O cartaz ao lado diz: 'Progresso a qualquer custo'.", "Acharge critica:", [["O desenvolvimento sustentável.", "O progresso que ignora os impactos ambientais.", "A falta de indústrias no país.", "A poluição do ar nas cidades.", "O aumento da produção agrícola."], "B"]),
        ("Leia o texto sobre recursos hídricos.", "O Brasil possui cerca de 12% de toda a água doce do mundo. No entanto, a distribuição desse recurso é desigual, com escassez em regiões semiáridas e desperdício nas grandes cidades.", "O principal desafio hídrico do Brasil é:", [["A falta total de água doce.", "A distribuição desigual e o desperdício nas grandes cidades.", "O excesso de água em todas as regiões.", "A poluição de todos os rios.", "A escassez de água apenas no Norte."], "B"]),
        ("Leia o texto sobre mobilidade urbana.", "A mobilidade urbana nas grandes cidades brasileiras é um dos maiores desafios contemporâneos. O congestionamento, a poluição e a falta de transporte público de qualidade afetam a qualidade de vida da população.", "O texto apresenta que problema a mobilidade urbana enfrenta?", [["A falta de veículos nas cidades.", "Congestionamento, poluição e falta de transporte público de qualidade.", "A abundância de transporte público.", "A redução do tráfego de veículos.", "A melhoria da qualidade do ar."], "B"]),
        ("Analise a charge sobre zoneamento.", "Acharge mostra um mapa de uma cidade com áreas residenciais, comerciais e industriais claramente delimitadas. Ao lado, uma família procura por uma casa em bairro tranquilo, mas todos já estão lotados.", "Acharge retrata:", [["A abundância de moradias em todas as regiões.", "A dificuldade de encontrar moradia em bairros residenciais tranquilos.", "A falta de planejamento urbano.", "O excesso de áreas verdes na cidade.", "A igualdade entre bairros."], "B"]),
        ("Leia o texto sobre turismo.", "O turismo é uma das principais fontes de renda para diversas regiões do Brasil. Cidades como Gramado, Bonito e Fernando de Noronha atraem milhões de visitantes todos os anos, gerando emprego e renda.", "O turismo no Brasil contribui para:", [["A redução do emprego formal.", "A geração de emprego e renda em diversas regiões.", "O aumento da pobreza local.", "A degradação do meio ambiente.", "A diminuição do Produto Interno Bruto."], "B"]),
        ("Leia o texto sobre energias renováveis.", "O Brasil é um dos maiores produtores de energia renovável do mundo. A energia hidrelétrica responde por cerca de 65% da matriz energética do país, seguida pela biomassa e pela energia eólica.", "A matriz energética brasileira é composta principalmente por:", [["Petróleo e gás natural.", "Energia hidrelétrica, seguida por biomassa e eólica.", "Carvão mineral.", "Energia nuclear.", "Energia solar fotovoltaica."], "B"]),
        ("Analise a charge sobre saneamento.", "Acharge mostra um rio poluído ao lado de um bairro de periferia, onde crianças brincam perto da água suja. Um cartaz diz: 'Saneamento básico é direito de todos'.", "A charge denuncia:", [["A abundância de saneamento básico em todas as regiões.", "A falta de saneamento básico em áreas periféricas.", "O excesso de água limpa nas cidades.", "A melhoria da qualidade da água.", "A redução da poluição nos rios."], "B"]),
        ("Leia o texto sobre agronegócio.", "O agronegócio brasileiro é um dos maiores do mundo, responsável por uma parcela significativa das exportações do país. No entanto, a expansão da fronteira agrícola gera conflitos ambientais e sociais, especialmente na Amazônia e no Cerrado.", "O agronegócio brasileiro enfrenta qual desafio?", [["A falta de tecnologia no campo.", "Conflitos ambientais e sociais com a expansão da fronteira agrícola.", "A redução da produção de alimentos.", "O fechamento de todas as exportações.", "A escassez de água para irrigação."], "B"]),
        ("Leia o texto sobre desigualdade social.", "A desigualdade social no Brasil se manifesta em diversas dimensões, incluindo renda, educação, saúde e acesso a serviços básicos. Embora tenha havido avanços nas últimas décadas, o país ainda enfrenta enormes disparidades entre regiões e classes sociais.", "A desigualdade social no Brasil se manifesta em:", [["Apenas na renda.", "Diversas dimensões, incluindo renda, educação, saúde e acesso a serviços básicos.", "Apenas nas grandes cidades.", "Apenas no campo.", "Apenas entre brancos e negros."], "B"]),
        ("Analise a charge sobre transportes.", "Acharge mostra um ônibus lotado na hora do rush, com passageiros apertados e suados. O motorista diz: 'Próxima parada: inferno'.", "A charge retrata:", [["O conforto do transporte público.", "A superlotação e as condições insatisfatórias do transporte público.", "A eficiência do sistema de transportes.", "A falta de passageiros nos ônibus.", "A qualidade do serviço prestado."], "B"]),
        ("Leia o texto sobre clima.", "O Brasil apresenta grande diversidade climática, desde o equatorial no Norte até o subtropical no Sul. Essa variação climática influencia diretamente a agricultura, o modo de vida da população e a economia de cada região.", "A diversidade climática do Brasil influencia:", [["Apenas a temperatura nas grandes cidades.", "A agricultura, o modo de vida e a economia de cada região.", "Apenas o turismo no litoral.", "Apenas a vegetação do Norte.", "Nenhum aspecto da sociedade brasileira."], "B"]),
    ]
    
    for ctx, txt, perg, (opts, gab) in geografia_items:
        diff = random.choices([1,2,3], weights=[40,40,20])[0]
        taxa = random.randint(65,85) if diff==1 else (random.randint(40,65) if diff==2 else random.randint(15,40))
        questions.append({"id": f"H{year}_{q_num:02d}", "ano": year, "area": "humanas", "disciplina": "geografia", "contexto": ctx, "texto": txt, "pergunta": perg, "opcoes": opts, "gabarito": gab, "dificuldade": diff, "taxaAcerto": taxa})
        q_num += 1
    
    # Sociologia (8)
    sociologia_items = [
        ("Leia o texto sobre movimentos sociais.", "Os movimentos sociais brasileiros, como o Movimento dos Trabalhadores Rurais Sem Terra (MST) e o Movimento dos Trabalhadores Sem Teto (MTST), têm lutado por reformas agrária e habitacional, denunciando as desigualdades no acesso à terra e à moradia.", "Os movimentos sociais mencionados no texto lutam por:", [["O aumento dos juros bancários.", "A reforma agrária e habitacional, combatendo desigualdades de acesso à terra e moradia.", "A redução da inflação.", "O fim da legislação trabalhista.", "O aumento do poder da iniciativa privada."], "B"]),
        ("Leia o texto sobre acesso à educação.", "O acesso à educação superior no Brasil ainda é privilégio de poucos. Apesar dos programas de cotas e bolsas de estudo, a maioria dos jovens de baixa renda não consegue ingressar em universidades, reproduzindo as desigualdades sociais.", "O texto apresenta que problema no sistema educacional brasileiro?", [["A existência de muitas universidades públicas.", "A reprodução das desigualdades sociais pelo acesso restrito ao ensino superior.", "O excesso de vagas nas universidades.", "A qualidade inferior das universidades privadas.", "A falta de interesse dos jovens pelo estudo."], "B"]),
        ("Analise a charge sobre desigualdade.", "Acharge mostra duas crianças sentadas na calçada: uma com uniforme escolar e mochila, outra vendendo doces na esquina. Ao fundo, um cartaz diz: 'Todos têm direito à educação'.", "A charge denuncia:", [["A igualdade de oportunidades entre as crianças.", "A desigualdade no acesso à educação entre crianças de diferentes classes sociais.", "A abundância de escolas em todas as regiões.", "A eficiência do sistema educacional.", "A melhoria da qualidade da educação."], "B"]),
        ("Leia o texto sobre trabalho.", "O mercado de trabalho brasileiro apresenta grandes desafios, como a informalidade, a desigualdade salarial entre gêneros e raças, e a precariedade das condições de trabalho em diversos setores da economia.", "O mercado de trabalho brasileiro enfrenta quais desafios?", [["A formalidade total em todos os setores.", "Informalidade, desigualdade salarial e precariedade das condições de trabalho.", "A igualdade salarial entre todos os trabalhadores.", "A ausência de leis trabalhistas.", "O pleno emprego em todas as regiões."], "B"]),
        ("Leia o texto sobre cidadania.", "A cidadania plena exige o exercício de direitos e deveres. No Brasil, muitos cidadãos enfrentam barreiras para o pleno exercício de seus direitos, como o acesso à saúde, educação e moradia dignas.", "A cidadania plena no Brasil é dificultada por:", [["A existência de direitos exagerados.", "Barreiras para o acesso a saúde, educação e moradia dignas.", "A falta de deveres por parte dos cidadãos.", "O excesso de obrigações fiscais.", "A ausência de leis no país."], "B"]),
        ("Analise a charge sobre transporte.", "Acharge mostra um ônibus lotado na hora do rush, com passageiros apertados e suados. O motorista diz: 'Próxima parada: inferno'.", "A charge retrata:", [["O conforto do transporte público.", "A superlotação e as condições insatisfatórias do transporte público.", "A eficiência do sistema de transportes.", "A falta de passageiros nos ônibus.", "A qualidade do serviço prestado."], "B"]),
        ("Leia o texto sobre mobilidade social.", "A mobilidade social no Brasil tem sido um tema de debate constante. Apesar dos avanços nas últimas décadas, a transição de classes sociais ainda é lenta e dependente de fatores como educação e acesso ao mercado de trabalho.", "O texto apresenta que a mobilidade social no Brasil é:", [["Rápida e acessível a todos.", "Lenta e dependente de fatores como educação e acesso ao trabalho.", "Inexistente na sociedade brasileira.", "Determinada exclusivamente pela renda familiar.", "Facilitada pelo governo federal."], "B"]),
        ("Leia o texto sobre participação política.", "A participação política dos jovens brasileiros tem aumentado nos últimos anos, impulsionada por movimentos nas redes sociais e pela mobilização em torno de causas sociais. No entanto, a abstenção eleitoral ainda é alta entre essa faixa etária.", "A participação política dos jovens brasileiros tem:", [["Diminuído nos últimos anos.", "Aumentado, mas a abstenção eleitoral ainda é alta.", "Sido sempre baixa e constante.", "Sido substituída pela participação dos idosos.", "Nenhum impacto na política nacional."], "B"]),
    ]
    
    for ctx, txt, perg, (opts, gab) in sociologia_items:
        diff = random.choices([1,2,3], weights=[40,40,20])[0]
        taxa = random.randint(65,85) if diff==1 else (random.randint(40,65) if diff==2 else random.randint(15,40))
        questions.append({"id": f"H{year}_{q_num:02d}", "ano": year, "area": "humanas", "disciplina": "sociologia", "contexto": ctx, "texto": txt, "pergunta": perg, "opcoes": opts, "gabarito": gab, "dificuldade": diff, "taxaAcerto": taxa})
        q_num += 1
    
    # Filosofia (7)
    filosofia_items = [
        ("Leia o texto sobre verdade.", "A filosofia ocidental, desde Platão até os dias de hoje, tem debatido a questão da verdade. Enquanto alguns filósofos defendem que a verdade é objetiva e universal, outros argumentam que ela é construída historicamente e depende do contexto cultural.", "O texto apresenta que debate filosófico fundamental?", [["A existência de Deus.", "A questão da verdade e sua natureza objetiva ou construída socialmente.", "A origem do universo.", "A definição de beleza.", "O sentido da vida humana."], "B"]),
        ("Leia o texto sobre ética kantiana.", "A ética kantiana é centrada no dever moral, independentemente das consequências. Para Kant, agir moralmente significa agir por dever, e não por inclinação ou interesse pessoal. Esse princípio é conhecido como imperativo categórico.", "Segundo Kant, agir moralmente significa:", [["Agir por interesse pessoal.", "Agir de acordo com as consequências positivas.", "Agir por dever, independentemente das inclinações pessoais.", "Agir para agradar aos outros.", "Agir conforme as leis do Estado."], "C"]),
        ("Leia o texto sobre existencialismo.", "O existencialismo, representado por filósofos como Jean-Paul Sartre e Simone de Beauvoir, defende que o ser humano é condicionado à liberdade. Cada escolha individual define quem somos, e não há uma essência humana pré-determinada.", "A principal tese do existencialismo é:", [["O ser humano é determinado pelo destino.", "A existência precede a essência, e cada escolha define quem somos.", "A liberdade humana é uma ilusão.", "A vida não tem sentido.", "A razão deve guiar todas as ações humanas."], "B"]),
        ("Leia o texto sobre Platão.", "A filosofia de Platão é fundamentada na teoria das Ideias. Para Platão, o mundo sensível é apenas uma cópia imperfeita do mundo das Ideias, que é o mundo verdadeiro e eterno. A justiça, por exemplo, é uma Ideia que existe perfeitamente no mundo inteligível.", "Segundo Platão, o mundo sensível é:", [["O mundo verdadeiro e eterno.", "Uma cópia imperfeita do mundo das Ideias.", "Um mundo ilusório que deve ser rejeitado.", "Um mundo criado pelos deuses.", "Um mundo autossuficiente."], "B"]),
        ("Analise a charge sobre liberdade.", "Acharge mostra uma pessoa trancada em uma jaula dourada, olhando para fora com expressão de desejo. Ao lado, um Cartaz diz: 'Liberdade é um estado de espírito'.", "A charge questiona:", [["A existência da liberdade absoluta.", "As limitações impostas pela sociedade em relação à liberdade individual.", "A felicidade de estar preso.", "A ausência de desejos humanos.", "A suficiência da prisão."], "B"]),
        ("Leia o texto sobre justiça social.", "A justiça social é um conceito filosófico que busca garantir a distribuição equitativa de recursos, oportunidades e direitos entre os membros de uma sociedade. Filósofos como John Rawls propuseram teorias para orientar políticas públicas mais justas.", "O conceito de justiça social busca:", [["A concentração de recursos nas mãos de poucos.", "A distribuição equitativa de recursos, oportunidades e direitos.", "A eliminação total do Estado.", "O aumento da desigualdade social.", "A ausência de qualquer tipo de regulação."], "B"]),
        ("Leia o texto sobre autonomia.", "A autonomia é um conceito central na filosofia moral. Um ser autônomo é capaz de agir de acordo com sua própria razão e valores, sem ser determinado por forças externas. Kant considerava a autonomia a base da dignidade humana.", "A autonomia, segundo a filosofia, significa:", [["Seguir as ordens dos outros sem questionar.", "Agir de acordo com a própria razão e valores, sem determinação externa.", "Ser governado por desejos irracionais.", "Depender totalmente do Estado.", "Aceitar qualquer norma imposta."], "B"]),
    ]
    
    for ctx, txt, perg, (opts, gab) in filosofia_items:
        diff = random.choices([1,2,3], weights=[40,40,20])[0]
        taxa = random.randint(65,85) if diff==1 else (random.randint(40,65) if diff==2 else random.randint(15,40))
        questions.append({"id": f"H{year}_{q_num:02d}", "ano": year, "area": "humanas", "disciplina": "filosofia", "contexto": ctx, "texto": txt, "pergunta": perg, "opcoes": opts, "gabarito": gab, "dificuldade": diff, "taxaAcerto": taxa})
        q_num += 1
    
    # ===== NATUREZA (45 questions) =====
    # Física (15)
    fisica_items = [
        ("Leia o texto sobre mecânica clássica.", "A mecânica clássica, desenvolvida por Isaac Newton, descreve o movimento dos corpos macroscópicos. As três leis do movimento de Newton formam a base para a compreensão de fenômenos como a queda livre, o movimento planetário e a dinâmica dos corpos em diferentes situações.", "Segundo Newton, a Primeira Lei do Movimento afirma que:", [["Todo corpo permanece em repouso ou em movimento retilíneo uniforme, a menos que uma força externa atue sobre ele.", "A força é igual à massa vezes a aceleração.", "A cada ação corresponde uma reação de igual intensidade e sentidos opostos.", "A energia não pode ser criada nem destruída.", "A gravidade é diretamente proporcional à massa."], "A"]),
        ("Leia o texto sobre termodinâmica.", "A energia é um conceito fundamental na física. A Primeira Lei da Termodinâmica estabelece que a energia não pode ser criada nem destruída, apenas transformada de uma forma para outra. Esse princípio é essencial para a compreensão dos processos energéticos no universo.", "Segundo a Primeira Lei da Termodinâmica, a energia:", [["Pode ser criada a partir do nada.", "Pode ser destruída completamente.", "Não pode ser criada nem destruída, apenas transformada.", "É sempre conservada em sua forma original.", "Depende da massa dos corpos para existir."], "C"]),
        ("Leia o texto sobre relatividade.", "A relatividade restrita de Einstein introduziu conceitos revolucionários, como a dilatação do tempo e a contração do comprimento. Esses efeitos só se tornam significativos quando os objetos se movem a velocidades próximas da luz.", "Segundo a relatividade restrita, o que acontece quando um objeto se aproxima da velocidade da luz?", [["O tempo permanece constante.", "O objeto perde massa.", "O tempo se dilata e o comprimento se contrai.", "O objeto ganha energia infinita imediatamente.", "O objeto para de se movimentar."], "C"]),
        ("Leia o texto sobre efeito estufa.", "O efeito estufa é um fenômeno natural que mantém a Terra aquecida. No entanto, a emissão excessiva de gases de efeito estufa, como o CO2, tem intensificado esse processo, causando o aquecimento global e mudanças climáticas drásticas.", "O efeito estufa é intensificado pela emissão excessiva de:", [["Oxigênio.", "Nitrogênio.", "Gases de efeito estufa, como o CO2.", "Hidrogênio.", "Argônio."], "C"]),
        ("Leia o texto sobre conservação de energia.", "A Segunda Lei da Termodinâmica estabelece que a entropia de um sistema isolado sempre aumenta. Isso significa que a energia se dissipa progressivamente, tornando-se menos disponível para realizar trabalho útil.", "A Segunda Lei da Termodinâmica estabelece que:", [["A entropia de um sistema isolado sempre diminui.", "A entropia de um sistema isolado sempre aumenta.", "A energia é sempre conservada.", "O trabalho útil pode ser realizado infinitamente.", "A temperatura sempre permanece constante."], "B"]),
        ("Leia o texto sobre óptica.", "A luz pode se comportar como onda e como partícula. O efeito fotoelétrico, explicado por Einstein, demonstra que a luz é composta por fótons, que transferem energia para os elétrons dos materiais, causando a emissão de elétrons.", "O efeito fotoelétrico demonstra que a luz:", [["Apenas se comporta como onda.", "Apenas se comporta como partícula.", "Pode se comportar como partícula, transferindo energia para elétrons.", "Não possui energia.", "É sempre refletida pelos materiais."], "C"]),
        ("Leia o texto sobre eletricidade.", "A lei de Ohm estabelece a relação entre tensão, resistência e corrente elétrica. Essa lei é fundamental para a compreensão de circuitos elétricos e é amplamente utilizada na engenharia eletrônica.", "Segundo a lei de Ohm, a corrente elétrica é:", [["Diretamente proporcional à resistência.", "Inversamente proporcional à tensão.", "Diretamente proporcional à tensão e inversamente proporcional à resistência.", "Independente da tensão.", "Sempre constante em qualquer circuito."], "C"]),
        ("Leia o texto sobre ondas sonoras.", "O som é uma vibração mecânica que se propaga por meio de um meio elástico. A velocidade do som varia de acordo com o meio de propagação, sendo maior nos sólidos e menor nos gases.", "A velocidade do som é:", [["Maior nos gases que nos sólidos.", "A mesma em todos os meios.", "Maior nos sólidos que nos gases.", "Inexistente no vácuo.", "Sempre constante."], "C"]),
        ("Leia o texto sobre magnetismo.", "O campo magnético é gerado por cargas elétricas em movimento. Os ímãs permanentes possuem campos magnéticos constantes, enquanto os eletroímãs geram campos magnéticos ao receberem corrente elétrica.", "O campo magnético é gerado por:", [["Apenas ímãs permanentes.", "Cargas elétricas em movimento.", "Apenas eletroímãs.", "A gravidade.", "A luz."], "B"]),
        ("Leia o texto sobre queda livre.", "Na queda livre, um corpo em queda é acelerado pela gravidade da Terra, que possui valor aproximado de 9,8 m/s². A velocidade final de um corpo em queda livre depende da altura da queda e da aceleração gravitacional.", "Na queda livre, a aceleração da gravidade é:", [["0 m/s².", "9,8 m/s².", "19,6 m/s².", "4,9 m/s².", "Depende da massa do corpo."], "B"]),
        ("Leia o texto sobre calor.", "A transferência de calor pode ocorrer por condução, convecção e radiação. Na condução, o calor se transfere por contato direto. Na convecção, o calor se transfere pelo movimento de fluidos. Na radiação, o calor se transfere por ondas eletromagnéticas.", "A transferência de calor por radiação ocorre:", [["Por contato direto.", "Pelo movimento de fluidos.", "Por ondas eletromagnéticas.", "Apenas no vácuo.", "Apenas em sólidos."], "C"]),
        ("Leia o texto sobre trabalho e energia.", "O trabalho mecânico é definido como o produto da força pela distância percorrida na direção da força. A unidade de trabalho no Sistema Internacional é o joule (J).", "O trabalho mecânico é medido em:", [["Metros (m).", "Newtons (N).", "Joules (J).", "Watts (W).", "Pascal (Pa)."], "C"]),
        ("Leia o texto sobre momento linear.", "O momento linear (quantidade de movimento) de um corpo é definido como o produto de sua massa por sua velocidade. A conservação do momento linear é um princípio fundamental da mecânica.", "O momento linear é definido como:", [["A razão entre massa e velocidade.", "O produto da massa pela velocidade.", "A soma da massa e da velocidade.", "A razão entre velocidade e massa.", "O produto da massa pela aceleração."], "B"]),
        ("Leia o texto sobre gravitação universal.", "A lei da gravitação universal de Newton estabelece que toda massa no universo atrai todas as outras massas com uma força diretamente proporcional ao produto de suas massas e inversamente proporcional ao quadrado da distância entre elas.", "A força gravitacional é:", [["Diretamente proporcional à distância.", "Inversamente proporcional ao quadrado da distância.", "Independente das massas.", "Sempre constante.", "Reativa apenas entre corpos grandes."], "B"]),
        ("Leia o texto sobre oscilações.", "O movimento harmônico simples é um tipo de movimento oscilatório onde a força restauradora é diretamente proporcional ao deslocamento do corpo em relação à sua posição de equilíbrio.", "No movimento harmônico simples, a força restauradora é:", [["Inversamente proporcional ao deslocamento.", "Diretamente proporcional ao deslocamento.", "Sempre constante.", "Depende apenas da massa.", "Inexistente na posição de equilíbrio."], "B"]),
    ]
    
    for ctx, txt, perg, (opts, gab) in fisica_items:
        diff = random.choices([1,2,3], weights=[40,40,20])[0]
        taxa = random.randint(65,85) if diff==1 else (random.randint(40,65) if diff==2 else random.randint(15,40))
        questions.append({"id": f"N{year}_{q_num:02d}", "ano": year, "area": "natureza", "disciplina": "fisica", "contexto": ctx, "texto": txt, "pergunta": perg, "opcoes": opts, "gabarito": gab, "dificuldade": diff, "taxaAcerto": taxa})
        q_num += 1
    
    # Química (15)
    quimica_items = [
        ("Leia o texto sobre molécula de água.", "A água é essencial para a vida. Sua molécula, composta por dois átomos de hidrogênio e um de oxigênio (H2O), possui propriedades únicas, como alta capacidade de dissolução e coesão, que são fundamentais para os processos biológicos e ambientais.", "A molécula de água (H2O) é composta por:", [["Dois átomos de oxigênio e um de hidrogênio.", "Dois átomos de hidrogênio e um de oxigênio.", "Um átomo de hidrogênio e dois de oxigênio.", "Um átomo de carbono e dois de oxigênio.", "Dois átomos de nitrogênio e um de hidrogênio."], "B"]),
        ("Leia o texto sobre tabela periódica.", "A tabela periódica é organizada de acordo com o número atômico dos elementos. Os elementos de um mesmo grupo químico apresentam propriedades semelhantes, devido à configuração eletrônica semelhante de seus átomos.", "Os elementos de um mesmo grupo na tabela periódica apresentam:", [["Propriedades químicas completamente diferentes.", "O mesmo número de massa.", "Propriedades químicas semelhantes, devido à configuração eletrônica semelhante.", "O mesmo número de prótons.", "A mesma reatividade em todas as situações."], "C"]),
        ("Leia o texto sobre corrosão.", "A corrosão é um processo químico que degrada metais, como o ferro, em contato com oxigênio e água. Esse processo causa danos a estruturas como pontes, navios e automóveis, gerando prejuízos econômicos significativos.", "A corrosão do ferro ocorre devido à reação com:", [["Nitrogênio e hidrogênio.", "Oxigênio e água.", "Carbono e oxigênio.", "Nitrogênio e oxigênio.", "Hidrogênio e carbono."], "B"]),
        ("Leia o texto sobre ozônio.", "O ozônio (O3) é uma molécula de oxigênio com três átomos, encontrada na camada de ozônio da atmosfera. Essa camada protege a Terra da radiação ultravioleta do sol, que pode causar câncer de pele e danos aos ecossistemas.", "A função da camada de ozônio é:", [["Absorver a radiação ultravioleta do sol.", "Emitir radiação ultravioleta.", "Refletir a luz solar.", "Gerar oxigênio para respiração.", "Aumentar a temperatura da Terra."], "A"]),
        ("Leia o texto sobre combustão.", "A combustão é uma reação química entre uma substância combustível e oxigênio, que libera energia na forma de calor e luz. Esse processo é essencial para a geração de energia em veículos, usinas e residências.", "A combustão é uma reação que libera:", [["Apenas calor.", "Calor e luz, devido à reação com oxigênio.", "Apenas luz.", "Apenas gases poluentes.", "Apenas vapor d'água."], "B"]),
        ("Leia o texto sobre dissolução.", "A dissolução é o processo pelo qual um soluto se mistura com um solvente para formar uma solução. A velocidade da dissolução pode ser influenciada por fatores como temperatura, agitação e tamanho das partículas do soluto.", "A velocidade da dissolução pode ser aumentada por:", [["Diminuição da temperatura.", "Aumento do tamanho das partículas do soluto.", "Aumento da temperatura e agitação.", "Diminuição da quantidade de solvente.", "Uso de soluto em grandes blocos."], "C"]),
        ("Leia o texto sobre pH.", "A escala de pH mede o grau de acidez ou alcalinidade de uma substância. Valores de pH menores que 7 indicam acidez, pH igual a 7 indica neutralidade e valores maiores que 7 indicam alcalinidade.", "Uma solução com pH igual a 4 é:", [["Neutra.", "Ácida.", "Básica.", "Anfótera.", "Insatura."], "B"]),
        ("Leia o texto sobre gasolina.", "A gasolina é uma mistura de hidrocarbonetos utilizada como combustível em veículos automotores. A adição de etanol à gasolina, prática comum no Brasil, reduz a emissão de poluentes e dependência de petróleo.", "A adição de etanol à gasolina no Brasil tem como objetivo:", [["Aumentar a emissão de poluentes.", "Reduzir a emissão de poluentes e a dependência de petróleo.", "Aumentar o consumo de combustível.", "Diminuir a potência do motor.", "Eliminar completamente a poluição."], "B"]),
        ("Leia o texto sobre processos de separação.", "Os processos de separação são utilizados para isolar componentes de uma mistura. Entre eles estão a filtração, a destilação, a evaporação e a centrifugação, cada um adequado para diferentes tipos de misturas.", "A filtração é utilizada para separar:", [["Líquidos miscíveis.", "Sólidos insolúveis de líquidos.", "Líquidos com diferentes pontos de ebulição.", "Gases de líquidos.", "Sólidos solúveis de líquidos."], "B"]),
        ("Leia o texto sobre ligação iônica.", "A ligação iônica ocorre quando um átomo doa elétrons para outro, formando íons de cargas opostas que se atraem. Essa ligação é comum em compostos como o cloreto de sódio (NaCl).", "Na ligação iônica, os íons se atraem porque:", [["Possuem a mesma carga elétrica.", "Possuem cargas elétricas opostas.", "Não possuem carga elétrica.", "Estão sempre em estado sólido.", "São formados apenas por metais."], "B"]),
        ("Leia o texto sobre oxidação.", "A oxidação é uma reação química na qual uma substância perde elétrons. A oxidação do ferro, por exemplo, resulta na formação de ferrugem, que é um óxido de ferro.", "A oxidação é um processo em que:", [["Uma substância ganha elétrons.", "Uma substância perde elétrons.", "Não há troca de elétrons.", "A temperatura diminui drasticamente.", "A substância se torna líquida."], "B"]),
        ("Leia o texto sobre equilíbrio químico.", "O equilíbrio químico é atingido quando as velocidades das reações direta e inversa se equalizam, resultando em concentrações constantes dos reagentes e produtos.", "No equilíbrio químico, as concentrações dos reagentes e produtos:", [["Continuam mudando indefinidamente.", "Se equalizam e permanecem constantes.", "Chegam a zero.", "Aumentam indefinidamente.", "São sempre iguais."], "B"]),
        ("Leia o texto sobre proteção contra corrosão.", "A proteção contra corrosão pode ser feita por diversos métodos, como pintura, galvanização e uso de inibidores. Esses métodos buscam impedir ou retardar a reação química entre o metal e o ambiente.", "A galvanização consiste em:", [["Pintar o metal com tinta anticorrosiva.", "Revestir o metal com uma camada de zinco.", "Submergir o metal em água fervente.", "Aumentar a temperatura do metal.", "Remover o metal da superfície."], "B"]),
        ("Leia o texto sobre compostos orgânicos.", "Os compostos orgânicos são baseados na molécula de carbono e estão presentes em todos os seres vivos. Eles podem ser classificados em hidrocarbonetos, álcoois, ácidos, ésteres e outros grupos funcionais.", "Os compostos orgânicos são baseados no elemento:", [["Oxigênio.", "Carbono.", "Hidrogênio.", "Nitrogênio.", "Enxofre."], "B"]),
        ("Leia o texto sobre reações ácido-base.", "As reações ácido-base são comuns na química e na vida cotidiana. Um exemplo é a reação entre o bicarbonato de sódio e o vinagre, que gera dióxido de carbono e água.", "Na reação entre bicarbonato de sódio e vinagre, é produzido:", [["Apenas água.", "Dióxido de carbono e água.", "Apenas sal.", "Oxigênio.", "Hidrogênio."], "B"]),
    ]
    
    for ctx, txt, perg, (opts, gab) in quimica_items:
        diff = random.choices([1,2,3], weights=[40,40,20])[0]
        taxa = random.randint(65,85) if diff==1 else (random.randint(40,65) if diff==2 else random.randint(15,40))
        questions.append({"id": f"N{year}_{q_num:02d}", "ano": year, "area": "natureza", "disciplina": "quimica", "contexto": ctx, "texto": txt, "pergunta": perg, "opcoes": opts, "gabarito": gab, "dificuldade": diff, "taxaAcerto": taxa})
        q_num += 1
    
    # Biologia (15)
    biologia_items = [
        ("Leia o texto sobre fotossíntese.", "A fotossíntese é o processo pelo qual as plantas, algas e algumas bactérias convertem energia luminosa em energia química, produzindo oxigênio e glicose. Esse processo é essencial para a vida na Terra, pois é a base da cadeia alimentar.", "A fotossíntese produz:", [["Apenas oxigênio.", "Apenas glicose.", "Oxigênio e glicose a partir de energia luminosa.", "Apenas energia térmica.", "Apenas dióxido de carbono."], "C"]),
        ("Leia o texto sobre cadeia alimentar.", "A cadeia alimentar é composta por produtores, consumidores e decompositores. Os produtores, como as plantas, são a base da cadeia, convertendo energia solar em alimento. Os consumidores se alimentam uns dos outros, formando diferentes níveis tróficos.", "Na cadeia alimentar, os produtores são:", [["Os animais carnívoros.", "As plantas e organismos que produzem seu próprio alimento.", "Os animais herbívoros.", "Os decompositores.", "Os parasitas."], "B"]),
        ("Leia o texto sobre células.", "A célula é a unidade básica da vida. Elas podem ser procarióticas, sem núcleo definido, ou eucarióticas, com núcleo delimitado por membrana. As células eucarióticas animais e vegetais apresentam organelas como mitocôndrias e ribossomos, responsáveis por funções vitais.", "A principal diferença entre células procarióticas e eucarióticas é:", [["A presença de mitocôndrias.", "A presença ou ausência de núcleo definido.", "A forma da célula.", "O tamanho da célula.", "O número de ribossomos."], "B"]),
        ("Leia o texto sobre evolução.", "A evolução darwiniana explica a diversidade das espécies por meio da seleção natural. Os organismos melhor adaptados ao ambiente têm maior chance de sobreviver e se reproduzir, passando suas características para as gerações seguintes.", "Segundo Darwin, o mecanismo que impulsiona a evolução é:", [["A seleção artificial.", "A seleção natural, onde os organismos mais adaptados sobrevivem e se reproduzem.", "A mutação aleatória sem influência do ambiente.", "A competição entre espécies de diferentes ecossistemas.", "O acaso absoluto, sem qualquer influência ambiental."], "B"]),
        ("Leia o texto sobre biodiversidade.", "A biodiversidade é a variedade de vida em um ecossistema. A perda de biodiversidade pode causar desequilíbrios ambientais, afetando a cadeia alimentar, a polinização e o ciclo dos nutrientes. A conservação da biodiversidade é essencial para a sustentabilidade do planeta.", "A perda de biodiversidade pode causar:", [["O aumento da produtividade agrícola.", "Desequilíbrios ambientais e afetação da cadeia alimentar.", "Aumento da polinização por insetos.", "Melhoria da qualidade do ar.", "Aumento da disponibilidade de água doce."], "B"]),
        ("Leia o texto sobre DNA.", "O DNA (ácido desoxirribonucléico) é a molécula que contém as instruções genéticas para o desenvolvimento e funcionamento de todos os seres vivos. Ele é composto por nucleotídeos e possui estrutura de hélice dupla.", "O DNA é composto por:", [["Lipídeos.", "Nucleotídeos.", "Aminoácidos.", "Glicídios.", "Vitaminas."], "B"]),
        ("Leia o texto sobre mutações.", "As mutações são alterações no material genético que podem ocorrer naturalmente ou por influência de fatores externos, como radiação e substâncias químicas. Nem todas as mutações são prejudiciais; algumas podem ser neutras ou até benéficas.", "As mutações genéticas podem ser causadas por:", [["Apenas fatores internos do organismo.", "Radiação, substâncias químicas e fatores internos.", "Apenas alimentação saudável.", "Apenas exercício físico.", "Apenas sono adequado."], "B"]),
        ("Leia o texto sobre ecossistemas.", "Um ecossistema é composto por seres vivos (biocenose) e seu ambiente físico (biotopo). Os seres vivos interagem entre si e com o ambiente, formando uma teia complexa de relações ecológicas.", "Um ecossistema é composto por:", [["Apenas seres vivos.", "Apenas o ambiente físico.", "Seres vivos e seu ambiente físico, com interações entre si.", "Apenas plantas e animais.", "Apenas seres humanos."], "C"]),
        ("Leia o texto sobre mitose.", "A mitose é o processo de divisão celular no qual uma célula se divide em duas células-filhas geneticamente idênticas. Esse processo é essencial para o crescimento, reparação e manutenção dos tecidos do corpo.", "A mitose produz:", [["Células geneticamente diferentes.", "Células geneticamente idênticas à célula-mãe.", "Apenas células reprodutivas.", "Apenas células nervosas.", "Apenas células sanguíneas."], "B"]),
        ("Leia o texto sobre carboidratos.", "Os carboidratos são moléculas orgânicas que fornecem energia para os seres vivos. Eles são classificados em monossacarídeos, dissacarídeos e polissacarídeos, cada um com funções e estruturas diferentes.", "Os carboidratos são classificados em:", [["Proteínas, lipídeos e vitaminas.", "Monossacarídeos, dissacarídeos e polissacarídeos.", "Ácidos nucleicos e aminoácidos.", "Minerais e vitaminas.", "Gases e líquidos."], "B"]),
        ("Leia o texto sobre respiração celular.", "A respiração celular é o processo pelo qual as células obtêm energia a partir da glicose, utilizando oxigênio e produzindo dióxido de carbono e água. Esse processo ocorre nas mitocôndrias das células eucarióticas.", "A respiração celular ocorre em:", [["Os ribossomos.", "As mitocôndrias.", "O núcleo celular.", "A membrana plasmática.", "O citoplasma livre."], "B"]),
        ("Leia o texto sobre seleção natural.", "A seleção natural é o processo pelo qual organismos com características favoráveis ao ambiente têm maior chance de sobreviver e se reproduzir. Esse mecanismo é um dos principais motores da evolução das espécies.", "A seleção natural favorece:", [["Organismos com características desfavoráveis.", "Organismos com características favoráveis ao ambiente.", "Todos os organismos igualmente.", "Apenas organismos grandes.", "Apenas organismos jovens."], "B"]),
        ("Leia o texto sobre imunidade.", "O sistema imunológico do corpo humano é capaz de reconhecer e combater agentes patogênicos, como bactérias, vírus e fungos. A imunidade pode ser adquirida naturalmente ou por meio de vacinas.", "A imunidade pode ser adquirida:", [["Apenas por vacinas.", "Naturalmente ou por meio de vacinas.", "Apenas por medicamentos.", "Apenas por cirurgias.", "Apenas por dietas especiais."], "B"]),
        ("Leia o texto sobre clorofila.", "A clorofila é o pigmento responsável pela absorção da luz solar nas plantas, possibilitando a realização da fotossíntese. Ela confere a cor verde às folhas e é encontrada nos cloroplastos das células vegetais.", "A clorofila é encontrada em:", [["As mitocôndrias.", "Os cloroplastos.", "O núcleo celular.", "A membrana plasmática.", "Os ribossomos."], "B"]),
        ("Leia o texto sobre gases atmosféricos.", "A atmosfera terrestre é composta por diversos gases, incluindo nitrogênio (78%), oxigênio (21%) e outros gases em menor proporção, como argônio e dióxido de carbono. A composição atmosférica é essencial para a vida no planeta.", "A principal composição da atmosfera terrestre é:", [["Oxigênio e dióxido de carbono.", "Nitrogênio e oxigênio.", "Hidrogênio e hélio.", "Argônio e néon.", "Vapor d'água e ozônio."], "B"]),
    ]
    
    for ctx, txt, perg, (opts, gab) in biologia_items:
        diff = random.choices([1,2,3], weights=[40,40,20])[0]
        taxa = random.randint(65,85) if diff==1 else (random.randint(40,65) if diff==2 else random.randint(15,40))
        questions.append({"id": f"N{year}_{q_num:02d}", "ano": year, "area": "natureza", "disciplina": "biologia", "contexto": ctx, "texto": txt, "pergunta": perg, "opcoes": opts, "gabarito": gab, "dificuldade": diff, "taxaAcerto": taxa})
        q_num += 1
    
    # ===== MATEMÁTICA (45 questions) =====
    # Álgebra (15)
    algebra_items = [
        ("Leia o texto sobre desemprego.", f"Em {year}, o Brasil apresentou uma taxa de desemprego em torno de 5,4%, segundo dados do IBGE. Para calcular o número de desempregados em uma população economicamente ativa de 100 milhões de pessoas, é necessário aplicar a porcentagem sobre o total.", "Se a taxa de desemprego era de 5,4% e a população economicamente ativa era de 100 milhões, quantas pessoas estavam desempregadas?", [["5.400.000 pessoas.", "540.000 pessoas.", "54.000.000 pessoas.", "540.000.000 pessoas.", "5.400.000.000 pessoas."], "A"]),
        ("Leia o texto sobre PIB.", f"O Produto Interno Bruto (PIB) do Brasil em {year} foi de aproximadamente R$ 5,2 trilhões. Para comparar o PIB de dois estados, onde o Estado A tem PIB de R$ 200 bilhões e o Estado B tem PIB de R$ 350 bilhões, podemos calcular a razão entre eles.", "A razão entre o PIB do Estado B e o PIB do Estado A é:", [["1,75", "0,57", "2,50", "0,75", "1,25"], "A"]),
        ("Leia o texto sobre reajuste salarial.", "Uma empresa deseja aumentar o salário de seus funcionários em 10%. Se o salário atual é de R$ 2.500,00, qual será o novo salário após o reajuste?", "O novo salário após o aumento de 10% será de:", [["R$ 2.750,00", "R$ 2.500,00", "R$ 2.250,00", "R$ 3.000,00", "R$ 2.600,00"], "A"]),
        ("Leia o texto sobre inflação.", f"A inflação acumulada no Brasil em {year} foi de 5,91%. Se um produto custava R$ 100,00 em janeiro de {year}, qual era seu preço aproximado em dezembro do mesmo ano?", "O preço do produto em dezembro seria aproximadamente:", [["R$ 105,91", "R$ 94,09", "R$ 159,10", "R$ 100,00", "R$ 109,10"], "A"]),
        ("Leia o texto sobre financiamento.", "Um financiamento habitacional tem taxa de juros de 1% ao mês. Se o valor financiado é de R$ 200.000,00 e o prazo é de 360 meses (30 anos), qual o valor total pago ao final do financiamento?", "O valor total pago ao final do financiamento será superior a:", [["R$ 200.000,00", "R$ 400.000,00", "R$ 600.000,00", "R$ 800.000,00", "R$ 1.000.000,00"], "E"]),
        ("Leia o texto sobre pesquisa de opinião.", "Em uma pesquisa de opinião, 60% dos entrevistados disseram que o país estava indo na direção certa, enquanto 40% disseram que ia na direção errada. Se foram entrevistadas 1.500 pessoas, quantas disseram que o país ia na direção errada?", "O número de pessoas que disseram que o país ia na direção errada foi:", [["600", "900", "300", "1.200", "750"], "A"]),
        ("Leia o texto sobre juros compostos.", "Um investimento rende 2% ao mês. Se o capital inicial é de R$ 10.000,00, qual será o valor acumulado após 6 meses, considerando juros compostos?", "O valor acumulado após 6 meses será aproximadamente:", [["R$ 11.261,62", "R$ 11.200,00", "R$ 12.000,00", "R$ 10.600,00", "R$ 12.500,00"], "A"]),
        ("Leia o texto sobre desconto.", "Uma loja oferece um desconto de 20% em um produto que custa R$ 350,00. Qual será o preço final do produto após o desconto?", "O preço final do produto após o desconto será:", [["R$ 280,00", "R$ 250,00", "R$ 300,00", "R$ 320,00", "R$ 315,00"], "A"]),
        ("Leia o texto sobre crescimento populacional.", f"Uma cidade tinha 500.000 habitantes em {year} e sua população cresce 2% ao ano. Qual será a população aproximada da cidade após 5 anos?", "A população aproximada após 5 anos será:", [["552.040", "550.000", "540.000", "560.000", "530.000"], "A"]),
        ("Leia o texto sobre misturas.", "Uma fábrica mistura dois tipos de liga metálica. A liga A tem 30% de cobre e a liga B tem 50% de cobre. Se a fábrica deseja obter 100 kg de liga com 40% de cobre, quantos quilogramas de cada liga devem ser misturados?", "A quantidade de liga A necessária é:", [["50 kg", "60 kg", "40 kg", "70 kg", "30 kg"], "A"]),
        ("Leia o texto sobre progressão aritmética.", "Uma sequência aritmética tem primeiro termo igual a 3 e razão igual a 5. Qual é o 10º termo dessa sequência?", "O 10º termo da sequência é:", [["48", "50", "53", "55", "58"], "A"]),
        ("Leia o texto sobre progressão geométrica.", "Uma sequência geométrica tem primeiro termo igual a 2 e razão igual a 3. Qual é o 5º termo dessa sequência?", "O 5º termo da sequência é:", [["162", "148", "180", "120", "100"], "A"]),
        ("Leia o texto sobre equações.", "Resolva a equação 2x + 5 = 15. Qual é o valor de x?", "O valor de x que satisfaz a equação é:", [["5", "10", "7,5", "2,5", "15"], "A"]),
        ("Leia o texto sobre inequações.", "Resolva a inequação 3x - 7 > 8. Qual é o conjunto solução?", "O conjunto solução da inequação é:", [["x > 5", "x < 5", "x > 15", "x < 15", "x = 5"], "A"]),
        ("Leia o texto sobre funções.", "A função f(x) = 2x² - 3x + 1 é uma função quadrática. Qual é o valor de f(2)?", "O valor de f(2) é:", [["3", "5", "7", "11", "9"], "A"]),
    ]
    
    for ctx, txt, perg, (opts, gab) in algebra_items:
        diff = random.choices([1,2,3], weights=[40,40,20])[0]
        taxa = random.randint(65,85) if diff==1 else (random.randint(40,65) if diff==2 else random.randint(15,40))
        questions.append({"id": f"M{year}_{q_num:02d}", "ano": year, "area": "matematica", "disciplina": "algebra", "contexto": ctx, "texto": txt, "pergunta": perg, "opcoes": opts, "gabarito": gab, "dificuldade": diff, "taxaAcerto": taxa})
        q_num += 1
    
    # Geometria (15)
    geometria_items = [
        ("Leia o texto sobre a Praça dos Três Poderes.", "A Praça dos Três Poderes em Brasília, projetada por Oscar Niemeyer, é um espaço aberto que expressa a monumentalidade da arquitetura moderna brasileira. A geometria das formas arquitetônicas dialoga com o vazio e com a simetria do espaço urbano.", "A Praça dos Três Poderes se destaca por qual característica geométrica?", [["O uso de curvas assintóticas complexas.", "A simetria e o diálogo entre formas geométricas simples e o vazio do espaço.", "A ausência de qualquer padrão geométrico.", "O uso exclusivo de triângulos equiláteros.", "A irregularidade total das formas."], "B"]),
        ("Leia o texto sobre o Cristo Redentor.", "O Cristo Redentor, uma das Sete Maravilhas do Mundo Moderno, possui uma estrutura geométrica que combina formas cilíndricas e esféricas. A estátua tem 30 metros de altura (sem pedestal) e 28 metros de envergadura dos braços.", "A altura total do Cristo Redentor (incluindo pedestal) é de aproximadamente:", [["30 metros.", "38 metros.", "45 metros.", "50 metros.", "55 metros."], "B"]),
        ("Leia o texto sobre terreno.", "Um terreno retangular tem 50 metros de comprimento e 30 metros de largura. O proprietário deseja cercar todo o terreno com uma cerca de 1,5 metro de altura. Qual é a área total da cerca necessária?", "A área da cerca necessária para cercar o terreno é:", [["2.400 m²", "1.500 m²", "2.250 m²", "1.800 m²", "3.000 m²"], "A"]),
        ("Leia o texto sobre a Praça Central.", "A Praça Central de Brasília tem formato de semi-círculo com raio de 250 metros. Qual é a área aproximada dessa praça?", "A área da Praça Central (semi-círculo) é aproximadamente:", [["98.175 m²", "196.350 m²", "49.087 m²", "125.000 m²", "250.000 m²"], "A"]),
        ("Leia o texto sobre triângulo retângulo.", "Um triângulo retângulo possui catetos de 6 cm e 8 cm. Qual é o comprimento da hipotenusa?", "O comprimento da hipotenusa é:", [["10 cm", "12 cm", "14 cm", "16 cm", "18 cm"], "A"]),
        ("Leia o texto sobre cilindro.", "Um cilindro tem raio de base 5 cm e altura 12 cm. Qual é o volume desse cilindro?", "O volume do cilindro é aproximadamente:", [["942,48 cm³", "471,24 cm³", "1.884,96 cm³", "235,62 cm³", "1.178,10 cm³"], "A"]),
        ("Leia o texto sobre pirâmide.", "Uma pirâmide de base quadrada tem aresta de base igual a 6 cm e altura igual a 8 cm. Qual é o volume dessa pirâmide?", "O volume da pirâmide é:", [["96 cm³", "48 cm³", "144 cm³", "192 cm³", "288 cm³"], "A"]),
        ("Leia o texto sobre esfera.", "Uma esfera tem raio igual a 7 cm. Qual é o volume aproximado dessa esfera?", "O volume da esfera é aproximadamente:", [["1.436,76 cm³", "1.047,20 cm³", "439,82 cm³", "1.795,94 cm³", "2.144,66 cm³"], "A"]),
        ("Leia o texto sobre área do círculo.", "Um jardim circular tem diâmetro de 10 metros. Qual é a área desse jardim?", "A área do jardim circular é aproximadamente:", [["78,54 m²", "31,42 m²", "157,08 m²", "62,83 m²", "15,71 m²"], "A"]),
        ("Leia o texto sobre perímetro.", "Um terreno triangular tem lados de 5 m, 12 m e 13 m. Qual é o perímetro desse terreno?", "O perímetro do terreno é:", [["30 m", "25 m", "35 m", "40 m", "45 m"], "A"]),
        ("Leia o texto sobre cones.", "Um cone tem raio de base 3 cm e altura 4 cm. Qual é o volume desse cone?", "O volume do cone é aproximadamente:", [["37,70 cm³", "75,40 cm³", "113,10 cm³", "28,27 cm³", "50,27 cm³"], "A"]),
        ("Leia o texto sobre ângulos.", "Em um triângulo, a soma dos três ângulos internos é sempre igual a um valor fixo. Esse fato é fundamental para a geometria euclidiana.", "Qual é a soma dos ângulos internos de um triângulo?", [["180°", "360°", "90°", "270°", "450°"], "A"]),
        ("Leia o texto sobre semicírculo.", "Uma pista de dança tem formato de semicírculo com raio de 8 metros. Qual é a área dessa pista?", "A área da pista de dança é aproximadamente:", [["100,53 m²", "201,06 m²", "50,27 m²", "150,80 m²", "251,33 m²"], "A"]),
        ("Leia o texto sobre trapézio.", "Um terreno em formato de trapézio retângulo tem bases de 10 m e 20 m e altura de 8 m. Qual é a área desse terreno?", "A área do terreno é:", [["120 m²", "160 m²", "80 m²", "200 m²", "240 m²"], "A"]),
        ("Leia o texto sobre cubo.", "Um cubo tem aresta igual a 5 cm. Qual é a área total desse cubo?", "A área total do cubo é:", [["150 cm²", "125 cm²", "200 cm²", "250 cm²", "300 cm²"], "A"]),
    ]
    
    for ctx, txt, perg, (opts, gab) in geometria_items:
        diff = random.choices([1,2,3], weights=[40,40,20])[0]
        taxa = random.randint(65,85) if diff==1 else (random.randint(40,65) if diff==2 else random.randint(15,40))
        questions.append({"id": f"M{year}_{q_num:02d}", "ano": year, "area": "matematica", "disciplina": "geometria", "contexto": ctx, "texto": txt, "pergunta": perg, "opcoes": opts, "gabarito": gab, "dificuldade": diff, "taxaAcerto": taxa})
        q_num += 1
    
    # Estatística (10)
    estatistica_items = [
        ("Leia o texto sobre pesquisa de satisfação.", "Em uma pesquisa realizada em 2013, 1.000 pessoas foram entrevistadas sobre sua satisfação com os serviços públicos. Dos entrevistados, 45% disseram estar satisfeitos, 35% insatisfeitos e 20% neutros.", "Quantas pessoas disseram estar satisfeitas com os serviços públicos?", [["450", "350", "200", "500", "250"], "A"]),
        ("Leia o texto sobre média aritmética.", "A média aritmética das notas de uma turma de 30 alunos foi 7,2. Se a nota de um aluno que faltou ao exame não for considerada, a média da turma sobe para 7,5. Qual era a nota do aluno que faltou?", "A nota do aluno que faltou era:", [["2,7", "4,2", "5,7", "8,5", "10,0"], "A"]),
        ("Leia o texto sobre desvio-padrão.", "Em uma amostra de 200 famílias, verificou-se que o rendimento mensal médio era de R$ 3.500,00. O desvio-padrão do rendimento era de R$ 1.200,00.", "O desvio-padrão mede:", [["O valor máximo das observações.", "A dispersão dos dados em relação à média.", "O número de observações na amostra.", "A soma dos valores observados.", "A proporção de valores positivos."], "B"]),
        ("Leia o texto sobre variação percentual.", "Em um gráfico de barras que mostra a evolução do PIB brasileiro entre 2010 e 2013, observa-se que o PIB cresceu de R$ 3,8 trilhões para R$ 5,2 trilhões.", "A variação percentual do PIB foi aproximadamente:", [["36,8%", "26,9%", "42,1%", "20,0%", "15,0%"], "A"]),
        ("Leia o texto sobre margem de erro.", "Uma pesquisa de opinião indica que 48% dos brasileiros aprovavam o governo, com margem de erro de 3 pontos percentuais.", "A margem de erro indica:", [["O número exato de entrevistados.", "O intervalo de confiança em torno do resultado obtido.", "A porcentagem de pessoas que não responderam.", "O custo total da pesquisa.", "O tempo necessário para realizar a pesquisa."], "B"]),
        ("Leia o texto sobre mediana.", "Em uma pesquisa com 10 pessoas, as idades foram: 15, 20, 22, 25, 28, 30, 35, 40, 45, 50. Qual é a mediana das idades?", "A mediana das idades é:", [["28", "29", "30", "25", "32"], "A"]),
        ("Leia o texto sobre moda.", "Em uma pesquisa com 200 pessoas, as respostas sobre o meio de transporte mais utilizado foram: 80 usam ônibus, 60 usam carro, 30 usam metrô, 20 usam bicicleta e 10 caminham. Qual é a moda?", "A moda da pesquisa é:", [["Ônibus", "Carro", "Metrô", "Bicicleta", "Caminhar"], "A"]),
        ("Leia o texto sobre frequência relativa.", "Em uma amostra de 500 pessoas, 150 são jovens (até 25 anos), 200 são adultos (26 a 59 anos) e 150 são idosos (60 anos ou mais). Qual é a frequência relativa de adultos?", "A frequência relativa de adultos é:", [["40%", "30%", "50%", "25%", "35%"], "A"]),
        ("Leia o texto sobre probabilidades.", "Em um dado de 6 faces, qual é a probabilidade de sair um número par ao lançá-lo?", "A probabilidade de sair um número par é:", [["1/2", "1/3", "1/6", "2/3", "1/4"], "A"]),
        ("Leia o texto sobre correlação.", "Uma pesquisa mostrou que cidades com mais escolas têm menor taxa de desemprego. Isso indica uma relação estatística entre as duas variáveis.", "O que essa relação indica sobre escolas e desemprego?", [["Uma correlação positiva entre escolas e desemprego.", "Uma correlação negativa entre escolas e desemprego.", "Nenhuma correlação entre as variáveis.", "Uma correlação perfeita.", "Uma relação causal direta."], "B"]),
    ]
    
    for ctx, txt, perg, (opts, gab) in estatistica_items:
        diff = random.choices([1,2,3], weights=[40,40,20])[0]
        taxa = random.randint(65,85) if diff==1 else (random.randint(40,65) if diff==2 else random.randint(15,40))
        questions.append({"id": f"M{year}_{q_num:02d}", "ano": year, "area": "matematica", "disciplina": "estatistica", "contexto": ctx, "texto": txt, "pergunta": perg, "opcoes": opts, "gabarito": gab, "dificuldade": diff, "taxaAcerto": taxa})
        q_num += 1
    
    # Probabilidade (5)
    probabilidade_items = [
        ("Leia o texto sobre pesquisa educacional.", "Em uma pesquisa com 500 pessoas, verificou-se que 250 tinham ensino médio completo, 150 tinham ensino superior completo e 100 não tinham ensino médio completo.", "A probabilidade de escolher uma pessoa com ensino superior completo é:", [["0,30", "0,25", "0,50", "0,15", "0,60"], "A"]),
        ("Leia o texto sobre moedas.", "Ao lançar duas moedas ao mesmo tempo, qual é a probabilidade de obter caras em ambas?", "A probabilidade de obter caras em ambas as moedas é:", [["1/4", "1/2", "1/3", "3/4", "1/6"], "A"]),
        ("Leia o texto sobre baralho.", "Em um baralho comum de 52 cartas, qual é a probabilidade de sortear uma carta de copas?", "A probabilidade de sortear uma carta de copas é:", [["1/4", "1/13", "1/2", "1/52", "4/13"], "A"]),
        ("Leia o texto sobre urna.", "Em uma urna com 5 bolas vermelhas, 3 azuis e 2 brancas, qual é a probabilidade de sortear uma bola azul?", "A probabilidade de sortear uma bola azul é:", [["3/10", "1/5", "1/3", "3/5", "1/10"], "A"]),
        ("Leia o texto sobre seguro.", "Em uma seguradora, a probabilidade de um cliente sofrer um acidente é de 0,02. Se a seguradora tem 10.000 clientes, quantos clientes em média poderão sofrer um acidente?", "O número esperado de clientes que sofrerão um acidente é:", [["200", "100", "50", "300", "400"], "A"]),
    ]
    
    for ctx, txt, perg, (opts, gab) in probabilidade_items:
        diff = random.choices([1,2,3], weights=[40,40,20])[0]
        taxa = random.randint(65,85) if diff==1 else (random.randint(40,65) if diff==2 else random.randint(15,40))
        questions.append({"id": f"M{year}_{q_num:02d}", "ano": year, "area": "matematica", "disciplina": "probabilidade", "contexto": ctx, "texto": txt, "pergunta": perg, "opcoes": opts, "gabarito": gab, "dificuldade": diff, "taxaAcerto": taxa})
        q_num += 1
    
    return questions


def main():
    os.makedirs("data", exist_ok=True)
    
    for year in [2013, 2014, 2015, 2016]:
        questions = generate_questions(year)
        
        # Count by area
        area_counts = {}
        disc_counts = {}
        for q in questions:
            area = q["area"]
            disc = q["disciplina"]
            area_counts[area] = area_counts.get(area, 0) + 1
            disc_counts[f"{area}/{disc}"] = disc_counts.get(f"{area}/{disc}", 0) + 1
        
        # Verify counts
        print(f"Year {year} counts:")
        for k, v in sorted(disc_counts.items()):
            print(f"  {k}: {v}")
        
        assert len(questions) == 180, f"Year {year}: Expected 180 questions, got {len(questions)}"
        assert area_counts.get("linguagens", 0) == 45, f"Year {year}: linguagens count wrong: {area_counts.get('linguagens', 0)}"
        assert area_counts.get("humanas", 0) == 45, f"Year {year}: humanas count wrong: {area_counts.get('humanas', 0)}"
        assert area_counts.get("natureza", 0) == 45, f"Year {year}: natureza count wrong: {area_counts.get('natureza', 0)}"
        assert area_counts.get("matematica", 0) == 45, f"Year {year}: matematica count wrong: {area_counts.get('matematica', 0)}"
        
        with open(f"data/{year}.json", "w", encoding="utf-8") as f:
            json.dump(questions, f, ensure_ascii=False, indent=2)
        
        print(f"  Total: {len(questions)} questions")
        print(f"  Arquivo data/{year}.json criado com sucesso!")
        print()


if __name__ == "__main__":
    main()
