#!/usr/bin/env python3
import json, os
os.makedirs('data', exist_ok=True)
def q(id,ano,area,disc,texto,pergunta,opcoes,gab,diff,taxa):
    return {"id":id,"ano":ano,"area":area,"disciplina":disc,"contexto":"Leia o texto abaixo para responder à questão.","texto":texto,"pergunta":pergunta,"opcoes":opcoes,"gabarito":gab,"dificuldade":diff,"taxaAcerto":taxa}
Q=[];n=1;p="L";a="linguagens"
# Portugues 20
d="portugues"
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"A pandemia de COVID-19 transformou a forma como nos comunicamos. Distanciamento social e isolamento doméstico tornaram-se normas, enquanto plataformas digitais ganharam espaço nas relações interpessoais.","A pandemia transformou a comunicação porque:",["Mantiveram-se todas as formas anteriores de interação","Distanciamento social e plataformas digitais ganharam espaço","Apenas afetou empresas de tecnologia","Não houve mudanças na comunicação","Apenas modificou a comunicação empresarial"],"B",1,78));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"O uso de máscaras passou a ser obrigatório em ambientes públicos durante a pandemia. A escolha do tipo de máscara e sua cor tornaram-se formas de expressão pessoal.","As máscaras tornaram-se forma de expressão porque:",["Eram apenas obrigação legal","Permitiam expressar identidade pessoal através da escolha","Não tinham relação com comunicação","Apenas protegiam contra vírus","Não eram usadas pela população"],"B",2,52));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"A comunicação sobre a pandemia foi intensa nos meios de comunicação. Jornais, revistas e sites dedicaram grande espaço à cobertura da crise sanitária.","A cobertura da pandemia foi importante porque:",["Não teve impacto na sociedade","Informou a população sobre a crise sanitária e suas consequências","Apenas vendeu mais jornais","Apenas causou pânico","Não teve relevância jornalística"],"B",1,80));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"Fake news sobre a pandemia se espalharam rapidamente nas redes sociais. Informações falsas sobre tratamentos e vacinas geraram confusão e riscos à saúde pública.","As fake news sobre a pandemia são perigosas porque:",["Apenas entretem o público","Geram confusão e riscos à saúde pública com informações falsas","Apenas criticam governos","Não têm impacto na sociedade","Apenas vendem produtos milagrosos"],"B",2,55));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"A pandemia alterou o vocabulário brasileiro. Termos como lockdown, lockdown parcial, corona vírus e pandemic passaram a fazer parte do cotidiano.","A pandemia alterou o vocabulário porque:",["Não houve mudanças linguísticas","Novos termos passaram a fazer parte do cotidiano","Apenas modificou a escrita","Não afetou a língua portuguesa","Apenas influenciou músicas"],"B",2,50));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"A literatura sobre pandemias ganhou novo interesse durante a COVID-19. Obras como A Peste de Camus e Contágio de Robin Cook tornaram-se best-sellers.","A literatura sobre pandemias ganhou interesse porque:",["Não teve relação com a realidade","Leitores buscaram entender a situação através da ficção","Apenas por marketing editorial","Não teve impacto nas vendas","Apenas entreter público"],"B",2,48));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"O jornalismo investigativo desempenhou papel crucial durante a pandemia. Repórteres investigaram atrasos no sistema de saúde e corrupção em compras de equipamentos.","O jornalismo investigativo foi crucial porque:",["Não teve importância","Investigou atrasos no sistema de saúde e corrupção","Apenas entreter público","Apenas criticar governos","Não teve impacto na sociedade"],"B",2,52));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"A comunicação corporativa durante a pandemia precisou ser rápida e transparente. Empresas que comunicaram mal sofreram críticas e perda de credibilidade.","A comunicação corporativa precisou ser:",["Lenta e opaca","Rápida e transparente para manter credibilidade","Apenas seguir tendências","Não teve impacto nas empresas","Apenas publicar anúncios"],"B",2,50));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"O ativismo digital se intensificou durante a pandemia. Manifestações online cobraram ações do governo e solidariedade entre cidadãos.","O ativismo digital se intensificou porque:",["Não teve impacto","Permitiu mobilizar pessoas mesmo com distanciamento social","Apenas entreter usuários","Apenas vender produtos","Não teve relevância política"],"B",2,50));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"A linguagem científica precisou ser traduzida para o público geral durante a pandemia. Epidemiologistas e infectologistas buscaram formas mais acessíveis de comunicar.","A linguagem científica precisou ser traduzida porque:",["O público já entendia tudo","Complexidade das informações exigia explicação acessível","Apenas por obrigação legal","Não teve impacto na comunicação","Apenas entreter público"],"B",2,52));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"O podcast tornou-se formato popular durante a pandemia. Milhões de pessoas passaram a ouvir programas sobre saúde, política e cultura durante isolamento.","O podcast ficou popular porque:",["Não teve aumento de ouvintes","Formato permitiu informações durante isolamento doméstico","Apenas entreter público","Apenas vender produtos","Não teve impacto nas mídias"],"B",2,48));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"A comunicação visual sobre higiene passou a ser essencial. Sinais, cartazes e ícones sobre lavagem de mãos e uso de máscara foram amplamente divulgados.","A comunicação visual foi essencial porque:",["Não teve importância","Auxiliou na prevenção através de instruções claras","Apenas decorou ambientes","Apenas entreter público","Não teve impacto na saúde pública"],"B",1,82));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"O rádio voltou a ser importante durante a pandemia. Em regiões sem acesso à internet, estações de rádio transmitiram informações sobre a doença e orientações de saúde.","O rádio foi importante porque:",["Não teve relevância","Chegou a populações sem acesso à internet com informações essenciais","Apenas entreter ouvintes","Apenas vender produtos","Não teve impacto na comunicação"],"B",1,78));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"A comunicação sobre vacinas foi desafiadora durante a pandemia. Dúvidas sobre eficácia e segurança geraram hesitação vacinal em parte da população.","A comunicação sobre vacinas foi desafiadora porque:",["Não houve dúvidas na população","Hesitação vacinal exigiu explicações científicas claras","Apenas por questões políticas","Não teve impacto na vacinação","Apenas entreter público"],"B",2,50));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"O telejornalismo adaptou-se durante a apresentadores e repórteres passaram a trabalhar remotamente. Estúdios caseiros e entrevistas por videoconferência tornaram-se comuns.","O telejornalismo adaptou-se porque:",["Não houve mudanças","Distanciamento social exigiu trabalho remoto e adaptação","Apenas entreter público","Apenas manter audiência","Não teve impacto na TV"],"B",2,50));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"A arte digital ganhou espaço durante a pandemia. Artistas criaram obras sobre isolamento, solidão e esperança, divulgadas nas redes sociais.","A arte digital ganhou espaço porque:",["Não teve relação com a pandemia","Artistas expressaram emoções sobre isolamento e esperança","Apenas decorar redes sociais","Apenas entreter público","Não teve impacto na arte"],"B",2,48));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"O humor tornou-se forma de enfrentamento durante a pandemia. Memes e piadas sobre lockdown e isolamento ajudaram a lidar com a situação difícil.","O humor foi importante porque:",["Não teve impacto","Ajudou a lidar com dificuldades do isolamento através do riso","Apenas entreter público","Apenas criticar governos","Não teve relevância social"],"B",2,52));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"A comunicação institucional de hospitais e unidades de saúde foi intensificada. Informações sobre capacidade de leitos e protocolos foram divulgadas regularmente.","A comunicação institucional foi importante porque:",["Não teve importância","Informou sobre capacidade de leitos e protocolos de saúde","Apenas entreter público","Apenas publicar anúncios","Não teve impacto na saúde pública"],"B",1,80));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"O ensino remoto exigiu comunicação clara entre professores e alunos. Plataformas educacionais adaptaram-se para facilitar interação virtual.","O ensino remoto exigiu comunicação clara porque:",["Não houve necessidade de adaptação","Distanciamento social exigiu interação virtual eficaz","Apenas entreter alunos","Apenas manter escolas abertas","Não teve impacto na educação"],"B",2,50));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"A comunicação sobre estresse e ansiedade durante a pandemia foi essencial. Profissionais de saúde mental alertaram sobre impactos psicológicos do isolamento.","A comunicação sobre saúde mental foi essencial porque:",["Não teve importância","Alertou sobre impactos psicológicos do isolamento","Apenas entreter público","Apenas vender produtos","Não teve impacto na saúde"],"B",1,78));n+=1
# Ingles 10
d="ingles"
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"The COVID-19 pandemic changed how we work. Remote work became widespread, transforming traditional office routines and work-life balance.","Remote work changed because:",["Companies refused to adapt","Technology enabled working from home during the pandemic","Only small businesses adopted it","It was already the norm","Workers preferred offices"],"B",1,75));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"Digital literacy became essential during the pandemic. People needed to navigate online platforms for work, education and social interaction.","Digital literacy became essential because:",["It was already important","Pandemic required online interaction for work and education","Only young people needed it","It was optional","It had no impact"],"B",1,80));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"Mental health awareness increased during the pandemic. Isolation and uncertainty caused widespread anxiety and depression.","Mental health awareness increased because:",["People became happier","Isolation and uncertainty caused widespread anxiety","Therapy became cheaper","Medications became available","It was always a priority"],"B",2,52));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"The concept of social distancing became part of daily vocabulary. People learned to maintain physical distance while staying emotionally connected.","Social distancing became common because:",["It was already practiced","It helped prevent virus spread while maintaining connections","People enjoyed isolation","It was a government trend","It had no health benefits"],"B",2,50));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"Essential workers became heroes during the pandemic. Healthcare professionals, grocery store employees and delivery drivers kept society functioning.","Essential workers were recognized because:",["They were always appreciated","They kept society functioning during the crisis","They received high salaries","They worked from home","They had easy jobs"],"B",2,55));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"The pandemic accelerated digital transformation. Companies that previously resisted technology were forced to adopt digital tools.","Digital transformation accelerated because:",["Companies wanted to save money","Pandemic forced adoption of digital tools","Technology became cheaper","Government mandated it","Workers demanded it"],"B",2,48));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"Vaccine development was faster than ever before. Scientific collaboration and mRNA technology enabled rapid development of effective vaccines.","Vaccine development was faster because:",["Traditional methods were used","Scientific collaboration and new technology enabled rapid development","Funding was unlimited","No safety protocols were followed","It was purely luck"],"B",2,52));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"The pandemic highlighted global inequality. Developing countries faced greater challenges with healthcare systems and vaccine access.","Global inequality was highlighted because:",["All countries had equal resources","Developing countries had weaker healthcare systems","Rich countries also struggled equally","Vaccines were distributed fairly","Technology was available everywhere"],"B",2,50));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"Remote learning challenged students and teachers. Adapting to online education required new skills and patience from everyone involved.","Remote learning was challenging because:",["Everyone was prepared","It required new skills and adaptation from students and teachers","Technology was perfect","Students preferred it","Teachers were trained beforehand"],"B",2,48));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"The pandemic changed how we view public spaces. Parks and outdoor areas became valuable for mental health and social interaction.","Public spaces changed because:",["They were always valued","Outdoor areas became important for mental health","People stopped using them","They became dangerous","Technology replaced them"],"B",1,78));n+=1
# Espanhol 5
d="espanhol"
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"La pandemia de COVID-19 transformó la forma en que nos comunicamos. El distanciamiento social y el aislamiento doméstico se convirtieron en normas, mientras las plataformas digitales ganaron espacio.","La pandemia transformó la comunicación porque:",["Se mantuvieron todas las formas anteriores","El distanciamiento y plataformas digitales ganaron espacio","Solo afectó empresas de tecnología","No hubo cambios","Solo modificó la comunicación empresarial"],"B",1,72));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"El uso de mascarillas se convirtió en obligatorio en espacios públicos durante la pandemia. La elección del tipo y color de mascarilla se convirtió en forma de expresión personal.","Las mascarillas se convirtieron en expresión porque:",["Eran solo obligación legal","Permitían expresar identidad personal","No tenían relación con comunicación","Solo protegían contra virus","No eran usadas por la población"],"B",2,52));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"La comunicación sobre la pandemia fue intensa en los medios de comunicación. Diarios, revistas y sitios web dedicaron gran espacio a la cobertura de la crisis sanitaria.","La cobertura de la pandemia fue importante porque:",["No tuvo impacto en la sociedad","Informó a la población sobre la crisis sanitaria","Solo vendió más diarios","Solo causó pánico","No tuvo relevancia periodística"],"B",1,70));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"Las noticias falsas sobre la pandemia se propagaron rápidamente en las redes sociales. Informaciones falsas sobre tratamientos y vacunas generaron confusión y riesgos para la salud pública.","Las noticias falsas son peligrosas porque:",["Solo entretienen al público","Generan confusión y riesgos para la salud pública","Solo critican gobiernos","No tienen impacto","Solo venden productos milagrosos"],"B",2,48));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"La literatura sobre pandemias ganhou nuevo interés durante la COVID-19. Obras como La Peste de Camus y Contagio de Robin Cook se convirtieron en best-sellers.","La literatura sobre pandemias ganhou interés porque:",["No tuvo relación con la realidad","Lectores buscaron entender la situación a través de la ficción","Solo por marketing editorial","No tuvo impacto en ventas","Solo entretener al público"],"B",2,50));n+=1
# Literatura 5
d="literatura"
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"A A Peste de Albert Camus ganhou novo relevance durante a pandemia. Obra retrata epidemia em cidade argeliana e reflete sobre isolamento, solidão e resistência humana.","A A Peste ganhou relevance porque:",["Não tem relação com pandemias","Retratou situações semelhantes ao isolamento e resistência humana","Apenas ficção antiga","Não teve impacto nas vendas","Apenas entreter leitores"],"B",2,52));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"A literatura pandêmica explora temas como medo, isolamento e superação. Autores contemporâneos utilizam ficção para retratar impactos sociais e emocionais de crises sanitárias.","A literatura pandêmica explora:",["Apenas beleza da natureza","Medo, isolamento e superação em tempos de crise","Apenas política internacional","Não explora nenhum tema","Apenas entreter leitores"],"B",2,50));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"O diário íntimo ganhou novo formato durante a pandemia. Pessoas registraram experiências de isolamento, criatividade e adaptação em blogs e redes sociais.","O diário íntimo digital contribuiu ao:",["Apenas decorar redes sociais","Registrar experiências de isolamento e adaptação","Apenas entreter público","Não teve impacto na literatura","Apenas vender produtos"],"B",2,48));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"A poesia sobre pandemia expressou emoções coletivas. Versos sobre solidão, esperança e solidariedade circularam amplamente nas redes sociais.","A poesia pandêmica expressou:",["Apenas sentimentos individuais","Emoções coletivas sobre solidão, esperança e solidariedade","Apenas críticas ao governo","Não teve impacto na sociedade","Apenas decorar ambientes"],"B",2,50));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"A literatura infantil abordou pandemia de forma lúdica. Livros para crianças explicaram vírus, higiene e distanciamento social de forma acessível.","A literatura infantil contribuiu ao:",["Apenas entreter crianças","Explicar pandemia de forma lúdica e educativa","Apenas decorar estantes","Celebrar doenças","Não teve impacto na educação"],"B",1,80));n+=1
# Artes 2
d="artes"
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"Arte de rua sobre pandemia surgiu em cidades brasileiras. Pichações e murais retrataram profissionais de saúde, máscaras e esperança.","Arte de rua pandêmica retratou:",["Apenas temas aleatórios","Profissionais de saúde, máscaras e esperança","Apenas propagandas","Não teve impacto na arte","Apenas decorar muros"],"B",2,50));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"Exposições virtuais de arte se popularizaram durante a pandemia. Museus abriram acervos online, permitindo acesso cultural mesmo com isolamento.","Exposições virtuais popularizaram porque:",["Não houve interesse","Permitiram acesso cultural durante isolamento","Apenas entreter público","Apenas vender obras","Não teve impacto na arte"],"B",2,52));n+=1
# Educacao Fisica 2
d="educacao_fisica"
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"Exercícios em casa se tornaram necessários durante a pandemia. Profissionais de educação física adaptaram aulas para formatos online e-caseiros.","Exercícios em casa foram necessários porque:",["Sempre foram comuns","Academias fecharam durante lockdown","Apenas para perda de peso","Não teve impacto na saúde","Apenas entreter pessoas"],"B",1,78));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"Atividades ao ar livre ganharam importância durante a pandemia. Caminhadas e corridas em espaços abertos ajudaram a manter saúde física e mental.","Atividades ao ar livre foram importantes porque:",["Não tiveram impacto","Manteram saúde física e mental durante isolamento","Apenas competição esportiva","Apenas lazer","Não foram permitidas"],"B",1,76));n+=1
# TIC 1
d="tic"
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"A tecnologia foi essencial durante a pandemia. Plataformas de videoconferência permitiram trabalho remoto, educação à distância e encontros virtuais.","A tecnologia foi essencial porque:",["Não teve importância","Permitiu trabalho remoto e educação à distância","Apenas entreter usuários","Apenas vender produtos","Não teve impacto na sociedade"],"B",1,82));n+=1
# HUMANAS
p="H";a="humanas"
# Historia 15
d="historia"
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"A pandemia de COVID-19 foi comparada a crises sanitárias históricas como a gripe espanhola de 1918. Semelhanças incluem isolamento social e busca por vacinas.","A pandemia foi comparada a crises históricas porque:",["Não havia comparações possíveis","Semelhanças com gripe espanhola de 1918 em isolamento e busca por vacinas","Apenas para criticar governos","Não teve impacto histórico","Apenas para vender jornais"],"B",2,55));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"A história das pandemias mostra recorrência de crises sanitárias. Da peste negra ao COVID-19, humanidade enfrentou doenças que transformaram sociedades.","A história das pandemias mostra:",["Crises isoladas","Recorrência de doenças que transformaram sociedades","Apenas progresso médico","Não teve impacto na humanidade","Apenas catástrofes naturais"],"B",2,52));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"A gripe espanhola de 1918 matou milhões de pessoas ao redor do mundo. Semelhanças com COVID-19 incluem isolamento social e restrições de circulação.","A gripe espanhola matou milhões porque:",["Não causou mortes","Ausência de vacinas e tratamentos eficazes na época","Apenas afetou idosos","Não teve impacto global","Apenas causou pânico"],"B",2,50));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"A resposta brasileira à pandemia foi marcada por negacionismo governamental. Presidente minimizou gravidade da doença, causando milhares de mortes evitáveis.","O negacionismo causou:",["Salvou vidas","Milhares de mortes evitáveis por falta de ação governamental","Apenas polêmica política","Não teve impacto na saúde","Apenas entreter população"],"B",2,50));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"A corrida vacinal trouxe à tona questões de desigualdade global. Países ricos garantiram estoques enquanto nações pobres enfrentaram escassez.","A corrida vacinal revelou:",["Igualdade entre nações","Desigualdade global no acesso a vacinas","Apenas eficiência científica","Não teve impacto internacional","Apenas sucesso farmacêutico"],"B",2,55));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"A pandemia acelerou transformações históricas. Trabalho remoto, ensino à distância e consumo digital tornaram-se realidade em meses, processo que duraria décadas.","A pandemia acelerou transformações porque:",["Não houve mudanças","Transformou décadas de adaptação em meses","Apenas causou caos","Não teve impacto histórico","Apenas beneficiou empresas tecnológicas"],"B",2,50));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"A mobilização social durante a pandemia foi histórica. Cozinhas comunitárias, mutirões de costura de máscaras e campanhas de solidariedade emergiram em todo país.","A mobilização social foi histórica porque:",["Não houve ações comunitárias","Cozinhas comunitárias e mutirões demonstraram solidariedade","Apenas causaram transtornos","Não teve impacto na sociedade","Apenas visibilidade política"],"B",2,52));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"A pandemia mostrou fragilidade dos sistemas de saúde. Hospitais lotados e falta de respiradores revelaram décadas de subinvestimento em saúde pública.","A pandemia mostrou fragilidade porque:",["Sistemas eram perfeitos","Decadas de subinvestimento revelaram falhas em hospitais","Apenas causou pânico","Não teve impacto na saúde","Apenas beneficiou empresas privadas"],"B",2,50));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"A desinformação durante a pandemia foi tema histórico. Fake news sobre vírus, tratamentos e vacinas causaram mortes e prejudicaram enfrentamento da doença.","A desinformação causou:",["Benefícios à saúde pública","Mortes e prejuízos ao enfrentamento da doença","Apenas polêmica política","Não teve impacto","Apenas entreter população"],"B",2,52));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"A pandemia redefiniu o conceito de essencial. Profissionais de saúde, motoristas de aplicativo e entregadores passaram a ser reconhecidos como fundamentais.","A pandemia redefiniu essencial porque:",["Todos os trabalhos sempre foram essenciais","Novas profissões passaram a ser reconhecidas como fundamentais","Apenas causou confusão","Não teve impacto no trabalho","Apenas beneficiou sindicatos"],"B",2,48));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"A resposta科学 à pandemia mostrou importância da ciência. Desenvolvimento rápido de vacinas e tratamentos destacou papel da pesquisa científica.","A resposta科学 foi importante porque:",["Ciência sempre foi dispensável","Desenvolvimento rápido de vacinas destacou importância da pesquisa","Apenas causou controvérsia","Não teve impacto na saúde","Apenas beneficiou farmacêuticas"],"B",2,52));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"A pandemia gerou debate sobre liberdade versus segurança. Restrições de circulação e uso de máscara geraram discussões sobre limites do poder estatal.","O debate sobre liberdade versus segurança surgiu porque:",["Não houve restrições","Restrições geraram discussões sobre limites do poder estatal","Apenas causou polêmica","Não teve impacto político","Apenas entreter população"],"B",2,50));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"A pandemia afetou a memória coletiva. Experiências de isolamento, perdas e superações tornaram-se parte da história de gerações.","A pandemia afetou a memória coletiva porque:",["Não gerou experiências significativas","Isolamento e perdas tornaram-se parte da história de gerações","Apenas causou esquecimento","Não teve impacto histórico","Apenas beneficiou historiadores"],"B",2,48));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"A pandemia mostrou interconexão global. Surgimento do vírus na China afetou economias, políticas e vidas ao redor do mundo em questão de semanas.","A pandemia mostrou interconexão porque:",["Países são independentes","Surgimento na China afetou o mundo inteiro rapidamente","Apenas afetou regiões específicas","Não teve impacto global","Apenas beneficiou alguns países"],"B",2,52));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"A pandemia gerou novas narrativas históricas. Documentários, livros e filmes sobre COVID-19 preservam memória e ensinamentos para futuras gerações.","As novas narrativas históricas são importantes porque:",["Não preservam memória","Documentam lições para futuras gerações","Apenas entreter público","Não teve impacto na cultura","Apenas vender produtos"],"B",2,50));n+=1
# Geografia 15
d="geografia"
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"A pandemia afetou a mobilidade urbana global. Redução de deslocamentos melhorou qualidade do ar em grandes centros, mostrando impacto da atividade humana no meio ambiente.","A mobilidade urbana mudou porque:",["Não houve redução de deslocamentos","Quedas na atividade melhoraram qualidade do ar em centros urbanos","Apenas afetou transportes públicos","Não teve impacto ambiental","Apenas beneficiou ciclistas"],"B",2,52));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"A distribuição geográfica da pandemia mostrou desigualdades regionais. Favelas e periferias sofreram mais com falta de saneamento e acesso à saúde.","A distribuição mostrou desigualdades porque:",["Todos foram afetados igualmente","Comunidades vulneráveis sofreram mais com falta de infraestrutura","Apenas afetou centros urbanos","Não teve distribuição geográfica","Apenas beneficiou áreas ricas"],"B",2,55));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"A pandemia alterou fluxos migratórios. Restrições de viagem e fechamento de fronteiras bloquearam deslocamentos internacionais por meses.","Os fluxos migratórios foram alterados porque:",["Não houve restrições","Fechamento de fronteiras bloqueou deslocamentos internacionais","Apenas afetou turistas","Não teve impacto nas fronteiras","Apenas beneficiou imigrantes"],"B",2,50));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"A pandemia destacou importância do saneamento básico. Comunidades sem acesso à água limpa enfrentaram maiores dificuldades no enfrentamento da doença.","O saneamento básico foi importante porque:",["Não teve relevância","Comunidades sem água limpa enfrentaram mais dificuldades","Apenas afetou áreas urbanas","Não teve impacto na saúde","Apenas beneficiou empresas de água"],"B",2,52));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"A pandemia afetou o comércio internacional. Quebras na cadeia de suprimentos causaram escassez de produtos e encarecimento de mercadorias em diferentes países.","O comércio internacional foi afetado porque:",["Não houve quebras","Quebras na cadeia de suprimentos causaram escassez e encarecimento","Apenas afetou importações","Não teve impacto no comércio","Apenas beneficiou exportadores"],"B",2,50));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"A pandemia mostrou vulnerabilidade de cidades densamente populosas. Aglomerações urbanas facilitaram transmissão do vírus, exigindo novos planejamentos.","As cidades densas foram vulneráveis porque:",["Não tinham populações grandes","Aglomerações facilitaram transmissão do vírus","Apenas afetou cidades litorâneas","Não teve impacto urbano","Apenas beneficiou cidades pequenas"],"B",2,48));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"A pandemia destacou importância da logística de distribuição de vacinas. Transporte, armazenamento e distribuição exigiram infraestrutura geográfica específica.","A logística de vacinas foi importante porque:",["Não exigiu planejamento","Distribuição exigiu infraestrutura geográfica específica","Apenas afetou países ricos","Não teve impacto na vacinação","Apenas beneficiou transportadoras"],"B",2,55));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"A pandemia afetou o turismo global. Restrições de viagem causaram bilhões em prejuízos para destinos turísticos ao redor do mundo.","O turismo foi afetado porque:",["Não houve restrições","Restrições causaram bilhões em prejuízos para destinos","Apenas afetou hotéis","Não teve impacto no turismo","Apenas beneficiou agências de viagem"],"B",2,50));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"A pandemia mostrou interdependência entre áreas urbanas e rurais. Produção de alimentos e abastecimento de cidades dependeram de trabalhadores rurais essenciais.","A interdependência mostrou que:",["Áreas são independentes","Produção e abastecimento dependeram de trabalhadores rurais essenciais","Apenas afetou áreas urbanas","Não teve impacto no campo","Apenas beneficiou agricultores"],"B",2,52));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"A pandemia alterou a geopolítica global. Disputas por vacinas e insumos médicos redefiniram relações internacionais entre nações.","A geopolítica foi alterada porque:",["Não houve disputas","Disputas por vacinas redefiniram relações internacionais","Apenas causou tensões","Não teve impacto diplomático","Apenas beneficiou organizações internacionais"],"B",2,50));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"A pandemia mostrou importância da conectividade digital. Regiões sem acesso à internet ficaram isoladas de informações essenciais sobre prevenção e tratamento.","A conectividade digital foi importante porque:",["Não teve relevância","Regiões sem internet ficaram isoladas de informações essenciais","Apenas afetou áreas urbanas","Não teve impacto na comunicação","Apenas beneficiou provedores de internet"],"B",2,48));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"A pandemia afetou a dinâmica de trabalho. Home office transformou centros empresariais em áreas fantasma, mudando geografia do trabalho urbano.","A dinâmica de trabalho mudou porque:",["Não houve transformação","Home office transformou centros empresariais em áreas fantasma","Apenas afetou empresas de tecnologia","Não teve impacto no trabalho","Apenas beneficiou trabalhadores"],"B",2,52));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"A pandemia mostrou vulnerabilidade de sistemas alimentares globais. Quebras na cadeia de abastecimento causaram desperdício e escassez em diferentes regiões.","Os sistemas alimentares foram vulneráveis porque:",["Não houve quebras","Quebras causaram desperdício e escassez em regiões","Apenas afetou supermercados","Não teve impacto na alimentação","Apenas beneficiou produtores locais"],"B",2,50));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"A pandemia destacou importância do planejamento urbano para saúde pública. Cidades com mais espaços verdes e menor densidade enfrentaram menos impactos.","O planejamento urbano foi importante porque:",["Não teve relevância","Cidades com mais espaços verdes enfrentaram menos impactos","Apenas afetou construtoras","Não teve impacto na saúde","Apenas beneficiou arquitetos"],"B",2,52));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"A pandemia mostrou impacto das mudanças climáticas na saúde. Aumento de temperaturas e eventos climáticos extremos podem facilitar surgimento de doenças infecciosas.","As mudanças climáticas影响am saúde porque:",["Não afetam a saúde","Aumento de temperaturas pode facilitar surgimento de doenças","Apenas causam desastres naturais","Não teve relação com pandemia","Apenas beneficiou ambientalistas"],"B",2,48));n+=1
# Sociologia 8
d="sociologia"
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"A pandemia revelou desigualdades sociais profundas. Trabalhadores informais, minorias e populações vulneráveis sofreram desproporcionalmente com a crise.","A pandemia revelou desigualdades porque:",["Todos foram afetados igualmente","Trabalhadores informais e minorias sofreram desproporcionalmente","Apenas afetou ricos","Não teve impacto social","Apenas beneficiou classes médias"],"B",2,55));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"A solidariedade social emergiu durante a pandemia. Cozinhas comunitárias, mutirões de máscaras e campanhas de arrecadação mostraram capacidade de organização popular.","A solidariedade emergiu porque:",["Não houve ações comunitárias","Capacidade de organização popular demonstrou união","Apenas causou transtornos","Não teve impacto na sociedade","Apenas visibilidade política"],"B",2,50));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"A pandemia afetou relações familiares. Isolamento doméstico gerou conflitos, mas também fortaleceu laços entre familiares que conviviam em casa.","As relações familiares foram afetadas porque:",["Não houve mudanças","Isolamento gerou conflitos e fortaleceu laços familiares","Apenas causou separações","Não teve impacto nas famílias","Apenas beneficiou terapeutas"],"B",2,48));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"O trabalho essencial ganhou reconhecimento social durante a pandemia. Profissionais de saúde, limpeza e entregas foram celebrados como heróis.","O trabalho essencial ganhou reconhecimento porque:",["Sempre foi valorizado","Pandemia demonstrou importância desses profissionais","Apenas causou polêmica","Não teve impacto no trabalho","Apenas beneficiou sindicatos"],"B",2,52));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"A educação à distância revelou desigualdades de acesso. Alunos sem computador ou internet ficaram para trás, ampliando brechas educacionais.","A educação à distância revelou desigualdades porque:",["Todos tinham acesso","Alunos sem recursos ficaram para trás","Apenas afetou escolas privadas","Não teve impacto na educação","Apenas beneficiou professores"],"B",2,50));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"A ansiedade e a depressão aumentaram durante a pandemia. Isolamento, medo e perdas causaram impactos psicológicos profundos em diferentes gerações.","Os impactos psicológicos aumentaram porque:",["Não houve aumento de casos","Isolamento e perdas causaram impactos profundos em diferentes gerações","Apenas afetou idosos","Não teve impacto na saúde mental","Apenas beneficiou psicólogos"],"B",2,55));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"A mobilização política durante a pandemia foi intensa. Protestos, campanhas de vacinação e debates sobre liberdades civis marcaram o período.","A mobilização política foi intensa porque:",["Não houve protestos","Debates sobre liberdades civis e vacinação marcaram o período","Apenas causou caos","Não teve impacto político","Apenas beneficiou partidos"],"B",2,50));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"A pandemia gerou novas formas de sociabilidade. Encontros virtuais, festas online e celebrações digitais criaram novos rituais sociais.","As novas formas de sociabilidade surgiram porque:",["Não houve mudanças","Encontros virtuais criaram novos rituais sociais","Apenas causaram estranheza","Não teve impacto na sociedade","Apenas beneficiou plataformas digitais"],"B",2,48));n+=1
# Filosofia 7
d="filosofia"
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"A pandemia levantou questões éticas sobre distribuição de recursos. Quem deveria receber ventiladores e vacinas primeiro? Discussões sobre justiça social emergiram.","As questões éticas surgiram porque:",["Não houve dilemas","Distribuição de recursos gerou dilemas sobre justiça social","Apenas causou polêmica","Não teve impacto ético","Apenas beneficiou filósofos"],"B",2,52));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"A liberdade individual versus segurança coletiva foi tema central durante a pandemia. Restrições sanitárias geraram debates sobre limites do poder estatal.","O debate sobre liberdade versus segurança surgiu porque:",["Não houve restrições","Restrições geraram debates sobre limites do poder estatal","Apenas causou polêmica","Não teve impacto filosófico","Apenas beneficiou governos"],"B",2,50));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"A vulnerabilidade humana ficou evidente durante a pandemia. Acepts de que somos seres finitos e dependentes uns dos outros tornaram-se mais presentes.","A vulnerabilidade humana ficou evidente porque:",["Sempre fomos invulneráveis","Pandemia mostrou que somos seres finitos e dependentes","Apenas causou medo","Não teve impacto filosófico","Apenas beneficiou religiões"],"B",2,55));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"A solidariedade entre nações foi debatida durante a pandemia.cooperação científica e distribuição de vacinas levantaram questões sobre responsabilidade global.","A solidariedade entre nações foi debatida porque:",["Países sempre cooperaram","Cooperação científica levantou questões sobre responsabilidade global","Apenas causou disputas","Não teve impacto internacional","Apenas beneficiou organizações internacionais"],"B",2,50));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"A relação entre ciência e política ficou em evidência durante a pandemia. Negacionismo científico e interferência política no enfrentamento da crise geraram debates éticos.","A relação ciência-política ficou em evidência porque:",["Sempre foi harmônica","Negacionismo científico e interferência política geraram debates","Apenas causou controvérsia","Não teve impacto ético","Apenas beneficiou cientistas"],"B",2,52));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"A pandemia questionou modelos econômicos vigentes. Crise expôs fragilidades do capitalismo e gerou debates sobre alternativas econômicas mais justas.","A pandemia questionou modelos econômicos porque:",["Economias eram perfeitas","Crise expôs fragilidades do capitalismo e gerou debates","Apenas causou prejuízos","Não teve impacto econômico","Apenas beneficiou economistas"],"B",2,48));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"O conceito de bem-estar comum ganhou relevância durante a pandemia. Acepts de que saúde e segurança são direitos coletivos fortaleceram debate sobre cidadania.","O bem-estar comum ganhou relevância porque:",["Sempre foi prioridade","Pandemia mostrou que saúde e segurança são direitos coletivos","Apenas causou confusão","Não teve impacto social","Apenas beneficiou governos"],"B",2,52));n+=1
# NATUREZA
p="N";a="natureza"
# Fisica 15
d="fisica"
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"A ventilção é essencial em hospitais. Movimento do ar ajuda a remover partículas virais, exigindo sistemas de climatização eficientes.","A ventilção hospitalar é essencial porque:",["Não tem importância","Movimento do ar remove partículas virais","Apenas refresca ambientes","Não teve impacto na saúde","Apenas consome energia"],"B",1,80));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"O funcionamento de respiradores artificiais envolve princípios de física. Pressão e volume são controlados para auxiliar pacientes com dificuldade respiratória.","Respiradores artificiais usam princípios porque:",["Não envolvem física","Pressão e volume são controlados para auxiliar pacientes","Apenas movem ar","Não teve impacto na saúde","Apenas consomem energia"],"B",2,52));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"A difusão de vírus em ambientes fechados envolve física de aerossóis. Partículas suspensas no ar podem transportar vírus por distâncias maiores que 2 metros.","A difusão de vírus envolve física porque:",["Não há transporte de partículas","Partículas suspensas transportam vírus por distâncias maiores","Apenas causa sujeira","Não teve impacto na saúde","Apenas afeta alérgicos"],"B",2,55));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"O uso de máscaras N95 envolve filtragem de partículas por princípios físicos. Material retém partículas virais enquanto permite passagem de ar.","As máscaras N95 filtram porque:",["Não retêm partículas","Material retém partículas virais enquanto permite passagem de ar","Apenas cobrem rosto","Não teve impacto na saúde","Apenas são confortáveis"],"B",1,78));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"A disseminação de COVID-19 envolve fenômenos físicos como convecção e difusão. Ar condicionado pode redistribuir partículas virais em ambientes fechados.","A disseminação envolve fenômenos físicos porque:",["Não há movimentação de ar","Convecção e difusão redistribuem partículas virais","Apenas aquece ambientes","Não teve impacto na saúde","Apenas refresca pessoas"],"B",2,50));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"A energia é necessária para operação de equipamentos médicos. Geradores e baterias garantem funcionamento de respiradores durante quedas de energia.","A energia é necessária porque:",["Equipamentos funcionam sem energia","Geradores e baterias garantem funcionamento de respiradores","Apenas aquece hospitais","Não teve impacto na saúde","Apenas ilumina ambientes"],"B",1,76));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"ATransferência de calor em equipamentos médicos é importante. Ventiladores e respiradores precisam dissipar calor para manter funcionamento adequado.","A transferência de calor é importante porque:",["Não há geração de calor","Equipamentos precisam dissipar calor para funcionar adequadamente","Apenas aquece ambientes","Não teve impacto na saúde","Apenas consome energia"],"B",2,48));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"A óptica é usada em dispositivos de monitoramento. Câmeras térmicas detectam febre, auxiliando na identificação de pessoas com sintomas de COVID-19.","A óptica é usada porque:",["Não detecta febre","Câmeras térmicas identificam pessoas com sintomas","Apenas filmam","Não teve impacto na saúde","Apenas iluminam ambientes"],"B",2,52));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"A acústica é relevante em ambientes hospitalares. Ruídos excessivos podem causar estresse em pacientes e profissionais de saúde.","A acústica é relevante porque:",["Não afeta pacientes","Ruídos excessivos causam estresse em pacientes e profissionais","Apenas entorpece","Não teve impacto na saúde","Apenas alegra ambientes"],"B",2,50));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"A eletricidade é fundamental para equipamentos de terapia intensiva. Monitores, ventiladores e bombas de infusão dependem de sistemas elétricos confiáveis.","A eletricidade é fundamental porque:",["Equipamentos funcionam sem eletricidade","Monitores e ventiladores dependem de sistemas elétricos","Apenas ilumina hospitais","Não teve impacto na saúde","Apenas aquece ambientes"],"B",1,82));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"A mecânica dos fluidos explica circulação de ar em hospitais. Sistemas de ventilação são projetados para minimizar contaminação cruzada.","A mecânica dos fluidos é importante porque:",["Não há circulação de ar","Sistemas de ventilação minimizam contaminação cruzada","Apenas refresca ambientes","Não teve impacto na saúde","Apenas consome energia"],"B",2,55));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"A termodinâmica é aplicada em esterilização de equipamentos. Autoclaves usam calor e pressão para eliminar vírus e bactérias de instrumentos médicos.","A termodinâmica é aplicada porque:",["Não elimina vírus","Autoclaves usam calor e pressão para esterilizar","Apenas aquece instrumentos","Não teve impacto na saúde","Apenas limpa equipamentos"],"B",2,52));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"A física nuclear é usada em esterilização por radiação. Alimentos e equipamentos médicos podem ser esterilizados usando radiação gama.","A física nuclear é usada porque:",["Não esteriliza","Radiação gama elimina microrganismos de alimentos e equipamentos","Apenas contamina","Não teve impacto na saúde","Apenas ilumina ambientes"],"B",3,30));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"A óptica é essencial em equipamentos de diagnóstico. Microscópios e lentes são usados para identificar vírus em laboratórios.","A óptica é essencial porque:",["Não amplia objetos","Microscópios e lentes identificam vírus em laboratórios","Apenas ilumina","Não teve impacto na saúde","Apenas decora ambientes"],"B",1,80));n+=1
# Quimica 15
d="quimica"
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"O etanol 70% é usado para desinfecção de mãos e superfícies. Concentração adequada garante eficácia na eliminação do vírus COVID-19.","O etanol 70% é eficaz porque:",["Qualquer concentração serve","Concentração adequada elimina vírus eficazmente","Apenas fede","Não teve impacto na saúde","Apenas limpa superfícies"],"B",1,82));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"Desinfetantes químicos contêm compostos que inativam vírus. Hipoclorito de sódio e peróxido de hidrogênio são amplamente utilizados durante a pandemia.","Desinfetantes químicos inativam vírus porque:",["Não contêm compostos ativos","Compostos químicos inativam vírus eficazmente","Apenas cheiram bem","Não teve impacto na saúde","Apenas limpam superfícies"],"B",1,78));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"A síntese de vacinas envolve química farmacêutica. Processos de produção precisam seguir rigorosos padrões de qualidade e segurança.","A síntese de vacinas envolve química porque:",["Não há processos químicos","Produção segue padrões de qualidade e segurança","Apenas mistura substâncias","Não teve impacto na saúde","Apenas causa efeitos colaterais"],"B",2,52));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"A formulação de medicamentos antivirais é desafio químico. Moléculas precisam ser projetadas para interferir na replicação do vírus.","A formulação antiviral é desafio porque:",["Não há necessidade de projeção","Moléculas precisam interferir na replicação do vírus","Apenas causam efeitos colaterais","Não teve impacto na saúde","Apenas curam doenças"],"B",2,55));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"A água sanitária é usada para desinfecção de ambientes. Concentração adequada garante eliminação de vírus sem causar danos à saúde.","A água sanitária é usada porque:",["Não elimina vírus","Concentração adequada elimina vírus sem causar danos","Apenas cheira mal","Não teve impacto na saúde","Apenas mancha superfícies"],"B",1,80));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"A matéria orgânica é base de muitos desinfetantes. Compostos orgânicos como álcoois e aldeídos são eficazes contra vírus envelopados.","A matéria orgânica é base porque:",["Não há compostos orgânicos eficazes","Compostos orgânicos como álcoois são eficazes contra vírus","Apenas causam danos","Não teve impacto na saúde","Apenas cheiram bem"],"B",2,50));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"A oxidação é processo químico usado em esterilização. Peróxidos e ozônio oxidam componentes de vírus, inativando-os.","A oxidação é usada porque:",["Não inativa vírus","Peróxidos e ozônio oxidam componentes de vírus","Apenas contamina","Não teve impacto na saúde","Apenas limpa superfícies"],"B",2,52));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"A pH é controlado em desinfetantes. Acidificação ou alcalinização podem aumentar eficácia de produtos de limpeza contra vírus.","O pH é controlado porque:",["Não afeta eficácia","Controle de pH aumenta eficácia contra vírus","Apenas causa danos","Não teve impacto na saúde","Apenas mancha superfícies"],"B",2,48));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"A química analítica é usada em testes de COVID-19. Reações químicas identificam presença do vírus em amostras biológicas.","A química analítica é usada porque:",["Não detecta vírus","Reações químicas identificam presença do vírus","Apenas contamina","Não teve impacto na saúde","Apenas limpa equipamentos"],"B",2,55));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"A corrosão é desafio em equipamentos médicos. Materiais precisam resistir a processos de desinfecção química repetidos.","A corrosão é desafio porque:",["Não afeta equipamentos","Materiais precisam resistir a desinfecção química repetida","Apenas enferruja","Não teve impacto na saúde","Apenas mancha superfícies"],"B",2,50));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"A poluição química do ar é reduzida durante lockdowns. Menos emissões veiculares e industriais melhoram qualidade do ar em cidades.","A poluição é reduzida porque:",["Não há redução de emissões","Menos atividade humana reduz emissões químicas","Apenas causa cheiro","Não teve impacto ambiental","Apenas beneficia indústrias"],"B",2,52));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"A formulação de vacinas de mRNA envolve química molecular. Sequências de nucleotídeos são projetadas para instruir células a produzirem proteínas virais.","A química molecular é usada porque:",["Não há manipulação molecular","Sequências de nucleotídeos instruem células a produzirem proteínas","Apenas causa mutações","Não teve impacto na saúde","Apenas contamina células"],"B",3,30));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"A espectroscopia é usada em análise de medicamentos. Técnicas como infravermelho e UV identificam pureza e composição de fármacos.","A espectroscopia é usada porque:",["Não identifica成分","Técnicas espectroscópicas identificam pureza de fármacos","Apenas contamina","Não teve impacto na saúde","Apenas ilumina amostras"],"B",2,48));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"A eletroquímica é aplicada em biosensores. Dispositivos eletrônicos detectam antígenos virais através de reações eletroquímicas.","A eletroquímica é aplicada porque:",["Não detecta antígenos","Reações eletroquímicas detectam antígenos virais","Apenas gera eletricidade","Não teve impacto na saúde","Apenas ilumina dispositivos"],"B",2,52));n+=1
# Biologia 15
d="biologia"
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"O SARS-CoV-2 é um vírus de RNA que causa COVID-19. Estrutura viral inclui proteína Spike que permite entrada em células humanas.","O SARS-CoV-2 é perigoso porque:",["Não infecta humanos","Proteína Spike permite entrada em células humanas","Apenas causa gripe leve","Não teve impacto na saúde","Apenas afeta animais"],"B",1,80));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"O sistema imunológico combate vírus através de resposta inata e adaptativa. Anticorpos e células T reconhecem e neutralizam patógenos.","O sistema imunológico combate vírus porque:",["Não reconhece patógenos","Anticorpos e células T reconhecem e neutralizam vírus","Apenas causa inflamação","Não teve impacto na saúde","Apenas enfraquece corpo"],"B",1,78));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"A transmissão respiratória é principal via de contágio de COVID-19. Gotículas e aerossóis liberados ao tossir ou falar espalham vírus.","A transmissão respiratória é perigosa porque:",["Não espalha vírus","Gotículas e aerossóis espalham vírus ao tossir ou falar","Apenas causa sujeira","Não teve impacto na saúde","Apenas cheira mal"],"B",1,82));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"As mutações virais são comuns em vírus de RNA. Variantes como Alpha, Delta e Ômicron demonstraram capacidade de evolução do SARS-CoV-2.","As mutações virais são perigosas porque:",["Não alteram vírus","Variantes demonstraram capacidade de evolução e escape imunológico","Apenas causam curiosidade","Não teve impacto na pandemia","Apenas beneficiam cientistas"],"B",2,55));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"A vacinação estimula sistema imunológico a produzir anticorpos. Princípio biológico permite prevenção de doenças infecciosas.","A vacinação é eficaz porque:",["Não estimula imunidade","Vacinas estimulam produção de anticorpos contra vírus","Apenas causa efeitos colaterais","Não teve impacto na saúde","Apenas causa dor"],"B",1,80));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"As células-tronco têm potencial de regeneração tecidual. Pesquisa busca aplicação em tratamento de sequelas pulmonares causadas por COVID-19.","As células-tronco são importantes porque:",["Não regeneram tecidos","Potencial de regeneração pode tratar sequelas pulmonares","Apenas causam câncer","Não teve impacto na saúde","Apenas decoram laboratórios"],"B",2,52));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"A microbiota intestinal influencia resposta imunológica. Estudos mostram que saúde do sistema digestivo afeta capacidade de combater infecções.","A microbiota influencia imunidade porque:",["Não afeta sistema imunológico","Saúde digestiva afeta capacidade de combater infecções","Apenas causa gases","Não teve impacto na saúde","Apenas digere alimentos"],"B",2,50));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"A genética viral é estudada para entender evolução do SARS-CoV-2. Sequenciamento genômico permite rastrear mutações e variantes.","A genética viral é estudada porque:",["Não há evolução viral","Sequenciamento permite rastrear mutações e variantes","Apenas causa mutações","Não teve impacto na pandemia","Apenas beneficiam laboratórios"],"B",2,52));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"A imunidade de rebanho é conceito biológico importante. Quando proporção suficiente da população se imuniza, transmissão do vírus é reduzida.","A imunidade de rebanho é importante porque:",["Não reduz transmissão","Proporção imunizada reduz transmissão do vírus","Apenas causa pandemia","Não teve impacto na saúde","Apenas beneficia indivíduos"],"B",2,50));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"A interleucina-6 é proteína inflamatória associada a quadros graves de COVID-19. Bloqueio dessa citocina é usado em tratamentos contra tempestade de citocinas.","A interleucina-6 é importante porque:",["Não causa inflamação","Bloqueio trata quadros graves de COVID-19","Apenas causa febre","Não teve impacto na saúde","Apenas beneficia laboratórios"],"B",3,30));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"A angiotensina 2 (ACE2) é receptor celular utilizado pelo SARS-CoV-2 para entrada. Expressão desse receptor em diferentes tecidos explica sintomas variados.","A ACE2 é importante porque:",["Não permite entrada viral","Expressão em tecidos explica sintomas variados de COVID-19","Apenas causa hipertensão","Não teve impacto na saúde","Apenas beneficia medicamentos"],"B",2,55));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"A coagulação sanguínea é afetada em casos graves de COVID-19. Formação de trombos é complicação que pode levar a óbito.","A coagulação é afetada porque:",["Não há formação de trombos","COVID-19 causa formação de trombos em casos graves","Apenas causa dor","Não teve impacto na saúde","Apenas beneficia anticoagulantes"],"B",2,48));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"A apoptose é mecanismo de morte celular programada. COVID-19 pode desencadear apoptose em células pulmonares, causando danos teciduais.","A apoptose é afetada porque:",["Não há morte celular","COVID-19 desencadeia apoptose em células pulmonares","Apenas causa inflamação","Não teve impacto na saúde","Apenas beneficia células"],"B",2,52));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"A proteína C reativa é marcador inflamatório. Níveis elevados indicam inflamação sistêmica e são usados para monitorar gravidade de COVID-19.","A proteína C reativa é importante porque:",["Não indica inflamação","Níveis elevados indicam inflamação e monitoram gravidade","Apenas causa dor","Não teve impacto na saúde","Apenas beneficia laboratórios"],"B",2,50));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"A terapia com anticorpos monoclonais é tratamento para COVID-19 grave. Anticorpos artificiais neutralizam vírus e reduzem carga viral.","A terapia com anticorpos é importante porque:",["Não neutraliza vírus","Anticorpos artificiais neutralizam vírus e reduzem carga viral","Apenas causa efeitos colaterais","Não teve impacto na saúde","Apenas beneficia laboratórios"],"B",2,52));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"O oxigênio hiperbárico é usado em tratamento de sequelas de COVID-19. Pressão aumentada de oxigênio auxilia regeneração tecidual pulmonar.","O oxigênio hiperbárico é usado porque:",["Não regenera tecidos","Pressão aumentada auxilia regeneração pulmonar","Apenas causa efeitos colaterais","Não teve impacto na saúde","Apenas beneficia hospitais"],"B",3,28));n+=1
# MATEMATICA
p="M";a="matematica"
# Algebra 15
d="algebra"
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"Se município tem 500 mil habitantes e taxa de contágio de 2,5, número de casos pode ser estimado.","Se 500 mil habitantes e taxa 2,5, número estimado de casos é:",["1 milhão","1,25 milhão","2 milhões","2,5 milhões","5 milhões"],"B",1,85));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"Se 15% da população é idosa e 30% tem doenças crônicas, pode-se calcular grupo de risco.","Se 15% idosos e 30% com doenças crônicas, quanto do grupo de risco?",["15%","30%","45%","50%","60%"],"B",2,58));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"Se R$ 50 milhões são distribuídos entre 20 hospitais igualmente, quanto cada um recebe?","Se R$ 50 milhões entre 20 hospitais, quanto cada um recebe?",["R$ 1 milhão","R$ 2,5 milhões","R$ 5 milhões","R$ 10 milhões","R$ 25 milhões"],"B",1,88));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"Se população cresce 1,5% ao ano e é 10 milhões, após 5 anos será aproximadamente.","Se 10 milhões crescem 1,5% ao ano, após 5 anos será:",["10,5 milhões","10,75 milhões","11 milhões","11,5 milhões","12 milhões"],"B",2,52));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"Se 60% dos casos são assintomáticos e total é 100 mil, quantos casos assintomáticos?","Se 60% de 100 mil são assintomáticos, quantos são?",["40 mil","50 mil","60 mil","70 mil","80 mil"],"C",1,86));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"Se custo por leito é R$ 500 mil e necessários 100 leitos, investimento total?","Se R$ 500 mil por leito e 100 leitos, investimento total é:",["R$ 5 milhões","R$ 10 milhões","R$ 50 milhões","R$ 100 milhões","R$ 500 milhões"],"C",1,82));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"Se R$ 200 milhões são investidos em 4 etapas de vacinação, média por etapa?","Se R$ 200 milhões em 4 etapas, média por etapa é:",["R$ 25 milhões","R$ 50 milhões","R$ 75 milhões","R$ 100 milhões","R$ 200 milhões"],"B",1,90));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"Se 1.000 profissionais de saúde são vacinados por dia, tempo para vacinar 100 mil?","Se 1.000 profissionais por dia, tempo para 100 mil é:",["50 dias","100 dias","150 dias","200 dias","500 dias"],"B",2,50));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"Se 80% dos pacientes precisam de oxigênio e há 500 pacientes, quantos precisam?","Se 80% de 500 precisam de oxigênio, quantos são?",["200","300","400","450","500"],"C",1,84));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"Se gasto mensal com EPI é R$ 2 milhões, gasto anual?","Se R$ 2 milhões mensais, gasto anual é:",["R$ 12 milhões","R$ 18 milhões","R$ 24 milhões","R$ 36 milhões","R$ 48 milhões"],"C",1,80));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"Se incidência de 500 casos por 100 mil habitantes em cidade de 2 milhões, total de casos?","Se 500 por 100 mil em 2 milhões, total é:",["5 mil","10 mil","15 mil","20 mil","50 mil"],"B",2,52));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"Se R$ 100 milhões distribuídos proporcionalmente entre 3 estados com populações de 5, 10 e 15 milhões, quanto cada um recebe?","Se populações 5, 10 e 15 milhões, quanto cada estado recebe de R$ 100 milhões?",["R$ 16,7 milhões, R$ 33,3 milhões, R$ 50 milhões","R$ 20 milhões, R$ 40 milhões, R$ 60 milhões","R$ 25 milhões, R$ 50 milhões, R$ 75 milhões","R$ 30 milhões, R$ 60 milhões, R$ 90 milhões","R$ 33,3 milhões, R$ 33,3 milhões, R$ 33,3 milhões"],"A",3,35));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"Se 40% das mortes são de idosos e 25% de diabéticos e intersecção é 10%, quanto é união?","Se 40% idosos e 25% diabéticos, intersecção 10%, união é:",["55%","60%","65%","70%","75%"],"A",2,48));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"Se fórmula de contágio é C(x) = 2x² + 100x, custo para contact tracing de 100 casos?","Se C(x) = 2x² + 100x, custo para 100 casos é:",["R$ 12.000","R$ 12.200","R$ 12.400","R$ 12.600","R$ 12.800"],"B",3,32));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"Se testes custam R$ 50 cada e R$ 10 milhões disponíveis, quantos testes podem ser realizados?","Se R$ 50 por teste e R$ 10 milhões disponíveis, quantos testes?",["100 mil","200 mil","500 mil","1 milhão","2 milhões"],"B",1,86));n+=1
# Geometria 15
d="geometria"
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"Se hospital tem 200 leitos e taxa de ocupação de 80%, quantos leitos estão ocupados?","Se 200 leitos e 80% de ocupação, quantos ocupados?",["100","120","160","180","200"],"C",1,88));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"Se leito de UTI mede 2m x 1,5m, área necessária para 50 leitos?","Se leito 2m x 1,5m, área para 50 leitos é:",["75 m²","150 m²","150 m²","200 m²","300 m²"],"B",1,82));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"Se cela de isolamento mede 3m x 4m x 2,5m, volume é?","Se cela 3m x 4m x 2,5m, volume é:",["20 m³","30 m³","30 m³","40 m³","60 m³"],"B",2,55));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"Se prédio hospitalar tem 5 andares e cada um 1.000 m², área total?","Se 5 andares de 1.000 m², área total é:",["1.000 m²","2.500 m²","5.000 m²","10.000 m²","50.000 m²"],"C",1,90));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"Se garçom serve 12 mesas por hora e restaurante tem 60 mesas, tempo para servir todas?","Se 12 mesas por hora e 60 mesas, tempo é:",["2 horas","3 horas","4 horas","5 horas","6 horas"],"C",2,52));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"Se triângulo de isolamento tem lados de 2m, área de cada triângulo?","Se triângulo equilátero 2m, área é:",["√3 m²","2√3 m²","3√3 m²","4√3 m²","6√3 m²"],"A",3,38));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"Se círculo de isolamento tem raio de 5m, área aproximada?","Se raio 5m, área é:",["25π m²","50π m²","75π m²","100π m²","200π m²"],"B",2,50));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"Se caminhão de oxigênio tem cilindro de raio 0,3m e altura 1,5m, volume aproximado?","Se cilindro raio 0,3m e altura 1,5m, volume é:",["0,135π m³","0,27π m³","0,405π m³","0,54π m³","1,35π m³"],"C",2,48));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"Se esfera de desinfecção tem raio de 1m, volume aproximado?","Se raio 1m, volume é:",["4π/3 m³","8π/3 m³","4π m³","8π m³","32π/3 m³"],"A",3,35));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"Se pirâmide quadrada tem base 4m e altura 6m, volume?","Se pirâmide base 4m e altura 6m, volume é:",["16 m³","32 m³","48 m³","64 m³","96 m³"],"B",2,45));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"Se cone de coleta tem raio 0,2m e altura 0,3m, volume aproximado?","Se cone raio 0,2m e altura 0,3m, volume é:",["0,004π m³","0,008π m³","0,012π m³","0,016π m³","0,04π m³"],"C",2,48));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"Se esfera de vacina tem raio 0,1m, área superficial?","Se raio 0,1m, área superficial é:",["0,01π m²","0,04π m²","0,1π m²","0,4π m²","4π m²"],"B",3,35));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"Se cilindro de vacina tem raio 0,15m e altura 0,2m, área lateral?","Se cilindro raio 0,15m e altura 0,2m, área lateral é:",["0,03π m²","0,06π m²","0,09π m²","0,12π m²","0,18π m²"],"B",2,52));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"Se prisma triangular tem base equilátera de 3m e altura 5m, volume?","Se prisma base 3m e altura 5m, volume é:",["15√3/4 m³","45√3/4 m³","15√3/2 m³","45√3/2 m³","45√3 m³"],"B",3,35));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"Se paralelepípedo de caixa de remédio mede 10cm x 5cm x 3cm, volume?","Se caixa 10cm x 5cm x 3cm, volume é:",["50 cm³","75 cm³","100 cm³","150 cm³","300 cm³"],"D",1,85));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"Se terreno triangular para posto de saúde tem base 20m e altura 15m, área?","Se base 20m e altura 15m, área é:",["75 m²","150 m²","200 m²","300 m²","600 m²"],"B",2,50));n+=1
# Estatistica 10
d="estatistica"
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"Se pesquisa indica 55% de aprovação com margem de erro 3%, intervalo de confiança é?","Se 55% com margem 3%, intervalo é:",["50% a 60%","52% a 58%","53% a 57%","54% a 56%","55% a 57%"],"B",1,88));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"Se 8 municípios reportam casos de 10, 15, 20, 25, 30, 35, 40 e 45, mediana é?","Se casos 10, 15, 20, 25, 30, 35, 40, 45, mediana é:",["20","22,5","25","27,5","30"],"B",2,50));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"Se variância de mortes é alta, isso indica?","Se variância é alta, indica:",["Dados concentrados","Dados dispersos entre regiões","Igualdade","Ausência de mortes","Uniformidade"],"B",2,52));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"Se 40% dos casos são de homens e 60% de mulheres, proporção é?","Se 40% homens e 60% mulheres, proporção é:",["2:3","3:2","4:6","6:4","5:5"],"A",1,80));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"Se desvio padrão de casos entre estados é alto, isso significa?","Se desvio padrão é alto, significa:",["Casos similares entre estados","Grande variação no número de casos entre estados","Ausência de casos","Igualdade na distribuição","Todos estados com mesmos casos"],"B",2,48));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"Se total de casos é 10 mil e 1 mil morreram, taxa de letalidade é?","Se 10 mil casos e 1 mil mortes, letalidade é:",["1%","5%","10%","15%","20%"],"C",1,86));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"Se vaccine distribution segue distribuição normal com média 100 e desvio 15, 95% dos valores estão entre?","Se média 100 e desvio 15, 95% dos valores entre:",["70 e 130","85 e 115","70 e 130","60 e 140","50 e 150"],"A",2,52));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"Se 200 testes positivos de 1.000 realizados, taxa de positividade é?","Se 200 positivos de 1.000, positividade é:",["5%","10%","15%","20%","25%"],"D",1,82));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"Se R₀ de 2,5 significa que cada infectado contamina em média 2,5 pessoas,quantas pessoas 10 infectados contaminarão?","Se R₀ 2,5, 10 infectados contaminam:",["15 pessoas","20 pessoas","25 pessoas","30 pessoas","35 pessoas"],"C",2,50));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"Se intervalo de confiança 95% para R₀ é [1,8; 2,8], o que isso significa?","Se IC 95% é [1,8; 2,8], significa:",["R₀ é necessariamente 2,3","Com 95% de confiança, R₀ está entre 1,8 e 2,8","R₀ sempre será 2,8","Não há confiança nos dados","R₀ é sempre 1,8"],"B",3,35));n+=1
# Probabilidade 5
d="probabilidade"
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"Se 1 em cada 100 pessoas desenvolve COVID-19 grave, probabilidade é?","Se 1 em 100 desenvolve grave, probabilidade é:",["0,1%","1%","5%","10%","100%"],"B",1,82));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"Se vacina tem eficácia de 95%, probabilidade de não se infectar após vacinação?","Se eficácia 95%, probabilidade de não infectar é:",["5%","50%","90%","95%","100%"],"D",1,80));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"Se 70% da população se vacina e vacina é 90% eficaz, probabilidade de imunidade de rebanho?","Se 70% vacina e 90% eficácia, probabilidade é:",["63%","70%","77%","80%","90%"],"A",2,52));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"Se transmissão em casa é 10 vezes maior que em ambiente aberto, razão de chance?","Se transmissão em casa é 10x maior, razão é:",["1:10","1:5","1:2","2:1","10:1"],"E",2,48));n+=1
Q.append(q(f"{p}2020_{n:02d}",2020,a,d,"Se variante A é 50% mais transmissível que variante B, e B tem R₀ de 2, R₀ de A é?","Se A 50% mais transmissível que B (R₀=2), R₀ de A é:",["2,5","3","3,5","4","5"],"B",3,30));n+=1
print(f"Total 2020: {len(Q)}")
assert len(Q)==180,f"Esperado 180, obtido {len(Q)}"
with open('data/2020.json','w',encoding='utf-8') as f:
    json.dump(Q,f,ensure_ascii=False,indent=2)
print("Arquivo data/2020.json criado com sucesso!")
