#!/usr/bin/env python3
import json
import os

os.makedirs('data', exist_ok=True)

def q(id, ano, area, disc, texto, pergunta, opcoes, gab, diff, taxa):
    return {"id": id, "ano": ano, "area": area, "disciplina": disc, 
            "contexto": "Leia o texto abaixo para responder à questão.",
            "texto": texto, "pergunta": pergunta, "opcoes": opcoes,
            "gabarito": gab, "dificuldade": diff, "taxaAcerto": taxa}

questions = []
n = 1
p = "L"
a = "linguagens"

# Portugues 20
d = "portugues"
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "A campanha eleitoral de 2018 foi marcada por forte polarização política no Brasil. Candidatos de diferentes espectros ideológicos disputaram espaço nas mídias sociais e na TV, utilizando linguagem persuasiva para conquistar eleitores. A análise da retórica política revela estratégias de convencimento.", "A retórica política na campanha de 2018 utilizou:", ["Apenas argumentos lógicos", "Linguagem persuasiva para conquistar eleitores", "Apenas dados estatísticos", "Somente depoimentos pessoais", "Apenas promessas de campanha"], "B", 1, 75)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "O discurso de ódio nas eleições de 2018 gerou debates sobre limites da liberdade de expressão. Muitos candidatos utilizaram palavras de ordem que chocaram a sociedade brasileira. A justiça eleitoral precisou agir para conter a propagação de discursos de ódio nas redes sociais.", "O principal desafio da justiça eleitoral em 2018 foi:", ["Regular o financiamento de campanhas", "Conter a propagação de discursos de ódio nas redes sociais", "Aumentar o número de eleitores", "Proibir a propaganda eleitoral na TV", "Controlar os resultados das eleições"], "B", 2, 48)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "A fake news se tornou um fenômeno preocupante durante as eleições brasileiras de 2018. Informações falsas se espalhavam rapidamente pelas redes sociais, influenciando a opinião pública. A falta de verificação de fontes contribuiu para a disseminação de notícias falsas.", "Um problema causado pelas fake news nas eleições foi:", ["Aumentar a participação popular", "Influenciar a opinião pública com informações falsas", "Melhorar a qualidade do debate político", "Fortalecer os partidos políticos", "Aumentar a confiança nos meios de comunicação"], "B", 1, 82)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "O papel das redes sociais na campanha eleitoral de 2018 foi decisivo. Candidatos utilizaram plataformas como Facebook, Twitter e WhatsApp para alcançar diretamente os eleitores, contornando os filtros dos meios de comunicação tradicionais.", "As redes sociais foram importantes na campanha de 2018 porque:", ["Substituíram completamente a TV", "Permitiram alcançar diretamente os eleitores", "Eliminaram a necessidade de debates", "Reduziram o custo das campanhas", "Garantiram equilíbrio entre os candidatos"], "B", 2, 50)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "A polarização política brasileira de 2018 refletiu divisões profundas na sociedade. De um lado, defensores de mudanças radicais; de outro, apoiadores da manutenção do status quo. Essa divisão se manifestou em todas as esferas da sociedade.", "A polarização política de 2018 refletiu:", ["Unanimidade na sociedade brasileira", "Divisões profundas na sociedade sobre o rumo do país", "Fim dos conflitos políticos", "Apoio unânime a um único candidato", "Ausência de debate político"], "B", 2, 52)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "A abstenção nas eleições de 2018 gerou preocupação com a representatividade democratica. Muitos eleitores decidiram não comparecer às urnas por desilusão com a política, apontando falta de opções viáveis.", "A abstenção nas eleições de 2018 foi causada por:", ["Aumento da confiança nos políticos", "Desilusão com a política e falta de opções viáveis", "Proibição do voto obrigatório", "Redução do número de candidatos", "Aumento da qualidade das opções"], "B", 2, 48)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "O debate sobre moralidade na política ganhou força durante as eleições de 2018. Muitos candidatos se apresentaram como alternativas à corrupção, utilizandos slogans que enfatizavam valores éticos e morais.", "O debate sobre moralidade na política em 2018 focou em:", ["Promessas econômicas para a população", "Valores éticos e morais dos candidatos", "Aumento do poder do executivo", "Redução do número de partidos", "Aumento da participação popular"], "B", 2, 55)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "A mobilização de jovens eleitores nas eleições de 2018 foi um fenômeno importante. Redes sociais como Twitter e Instagram se tornaram espaços de debate político entre os jovens, que expressavam suas opiniões de forma ágil e direta.", "A mobilização de jovens nas eleições de 2018 se deu principalmente:", ["Através de comícios tradicionais", "Nas redes sociais como Twitter e Instagram", "Através de propagandas na TV", "Por meio de panfletos impressos", "Através de reuniões em partidos políticos"], "B", 1, 78)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "A comunicação política nas eleições de 2018 utilizou novas estratégias de marketing digital. Candidatos contrataram equipes especializadas em redes sociais para criar conteúdo viral e engajar seguidores.", "Uma estratégia de marketing digital utilizada em 2018 foi:", ["Aumentar o tempo de propaganda na TV", "Criar conteúdo viral para engajar seguidores nas redes sociais", "Proibir a publicidade eleitoral online", "Reduzir o número de candidatos", "Aumentar o custo das campanhas"], "B", 2, 52)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "O uso de inteligência artificial nas campanhas eleitorais de 2018 permitiu segmentação precisa de eleitores. Algoritmos analisavam dados de usuários para direcionar mensagens personalizadas, maximizando o impacto da propaganda política.", "O uso de inteligência artificial nas campanhas de 2018 permitiu:", ["Aumentar o custo das campanhas", "Segmentação precisa de eleitores para mensagens personalizadas", "Eliminar a necessidade de debates", "Reduzir a participação popular", "Aumentar o poder dos partidos tradicionais"], "B", 3, 32)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "A escolha de candidatos nas eleições de 2018 foi influenciada por fatores como carisma, imagem pública e capacidade de comunicação nas redes sociais. Muitos eleitores decidiram seu voto com base na imagem do candidato.", "A imagem pública do candidato em 2018 influenciou a escolha dos eleitores ao:", ["Não ter nenhuma importância", "Determinar parcialmente o voto dos eleitores", "Substituir completamente as propostas de governo", "Aumentar o custo das campanhas", "Eliminar a necessidade de debates"], "B", 2, 50)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "A violência política nas eleições de 2018 foi um problema preocupante. Candidatos e apoiadores sofreram ameaças e agressões, demonstrando a tensão existente no ambiente político brasileiro.", "A violência política nas eleições de 2018 demonstrou:", ["Harmonia na sociedade brasileira", "A tensão existente no ambiente político brasileiro", "Fim dos conflitos políticos", "Apoio unânime a um único candidato", "Ausência de debate político"], "B", 2, 52)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "O debate sobre direitos humanos nas eleições de 2018 foi marcado por divergências entre candidatos. Alguns defendiam a ampliação dos direitos, enquanto outros propunham restrições em nome da segurança pública.", "O debate sobre direitos humanos em 2018 foi marcado por:", ["Consenso entre todos os candidatos", "Divergências sobre a ampliação ou restrição dos direitos", "Ausência do tema na campanha", "Apoio unânime a ampliação dos direitos", "Rejeição total do tema pelos candidatos"], "B", 2, 48)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "A economia foi um tema central nas eleições de 2018. Candidatos apresentaram propostas para retomar o crescimento econômico, reduzir o desemprego e controlar a inflação. As propostas econômicas foram debatidas intensamente.", "A economia foi um tema central em 2018 porque:", ["Não tinha importância para os eleitores", "Afetava diretamente a vida da população", "Era irrelevante para as eleições", "Não havia problemas econômicos no país", "Todos os candidatos concordavam com as propostas"], "B", 1, 80)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "A segurança pública foi outro tema debatido nas eleições de 2018. Candidatos propunham diferentes abordagens para combater a violência, desde o endurecimento das penas até investimentos em políticas sociais.", "A segurança pública em 2018 gerou debates sobre:", ["Aumento do poder policial", "Diferentes abordagens para combater a violência", "Fim da polícia militar", "Eliminação de todos os direitos", "Aumento da violência urbana"], "B", 2, 55)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "A educação foi tema de debate nas eleições de 2018. Candidatos apresentaram propostas para melhorar a qualidade do ensino público, aumentar o investimento em educação e reformar o currículo escolar.", "As propostas de educação em 2018 focaram em:", ["Reduzir o investimento em educação", "Melhorar a qualidade do ensino público e aumentar investimentos", "Eliminar a escola pública", "Aumentar apenas o salário dos professores", "Fechar escolas em regiões pobres"], "B", 1, 78)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "A saúde pública foi debatida nas eleições de 2018, com candidatos apresentando propostas para melhorar o acesso da população aos serviços de saúde, reduzir filas de espera e investir em hospitais públicos.", "As propostas de saúde em 2018 focaram em:", ["Eliminar o SUS", "Melhorar o acesso da população aos serviços de saúde", "Fechar hospitais públicos", "Aumentar apenas o salário dos médicos", "Reduzir o investimento em saúde"], "B", 1, 82)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "A mobilidade urbana foi tema de discussão nas eleições de 2018. Candidatos apresentaram propostas para melhorar o transporte público, reduzir o trânsito e investir em infraestrutura viária nas cidades brasileiras.", "A mobilidade urbana em 2018 gerou propostas para:", ["Aumentar o número de carros", "Melhorar o transporte público e reduzir o trânsito", "Eliminar o transporte público", "Aumentar a poluição nas cidades", "Fechar estradas e avenidas"], "B", 2, 52)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "O meio ambiente foi tema de debate nas eleições de 2018. Candidatos apresentaram propostas para preservar o meio ambiente, combater o desmatamento e promover o desenvolvimento sustentável no Brasil.", "As propostas ambientais em 2018 focaram em:", ["Aumentar o desmatamento", "Preservar o meio ambiente e promover desenvolvimento sustentável", "Eliminar todas as reservas ambientais", "Aumentar a poluição nas cidades", "Fechar parques nacionais"], "B", 1, 76)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "A ciência e tecnologia foram temas debatidos nas eleições de 2018. Candidatos apresentaram propostas para aumentar investimentos em pesquisa e desenvolvimento, incentivar a inovação e formar profissionais qualificados.", "As propostas de ciência e tecnologia em 2018 focaram em:", ["Reduzir investimentos em pesquisa", "Aumentar investimentos em pesquisa e desenvolvimento", "Eliminar universidades públicas", "Apenas formar profissionais para o exterior", "Fechar centros de pesquisa"], "B", 2, 50)); n+=1

# Ingles 10
d = "ingles"
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "The 2018 Brazilian presidential election was marked by intense polarization and controversial campaigns. Social media played a crucial role in spreading political messages, both positive and negative. The election results reflected deep divisions in Brazilian society.", "The 2018 Brazilian election was characterized by:", ["Political unity and consensus", "Intense polarization and controversial campaigns", "Complete absence of debates", "Universal support for all candidates", "No use of social media"], "B", 1, 75)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "Fake news became a major concern during the 2018 Brazilian elections. False information spread rapidly through social media platforms, influencing public opinion and potentially affecting election outcomes. The lack of fact-checking contributed to the dissemination of false news.", "Fake news was a concern in 2018 because:", ["It improved the quality of political debate", "It spread false information that influenced public opinion", "It increased voter participation", "It strengthened political parties", "It reduced campaign costs"], "B", 1, 82)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "The use of social media in the 2018 Brazilian campaign was decisive. Candidates used platforms like Facebook, Twitter and WhatsApp to reach voters directly, bypassing traditional media filters. This direct communication changed the dynamics of political campaigns.", "Social media was important in 2018 because:", ["It replaced television completely", "It allowed candidates to reach voters directly", "It eliminated the need for debates", "It reduced campaign costs significantly", "It guaranteed balance between candidates"], "B", 2, 50)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "Youth participation in the 2018 Brazilian elections was notable. Young people used social media platforms to express their political opinions and mobilize peers. However, many young voters felt disillusioned with traditional political options.", "Youth participation in 2018 elections was notable because:", ["Young people were prohibited from voting", "They used social media to express opinions and mobilize peers", "They were not interested in politics", "They had no access to technology", "They supported only one candidate"], "B", 2, 48)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "The political polarization in the 2018 Brazilian elections reflected deep divisions in society. Supporters of different candidates held fundamentally different views about the country's future direction, leading to heated debates both online and offline.", "Political polarization in 2018 reflected:", ["Complete agreement among all citizens", "Deep divisions about the country's future direction", "Apathy towards politics", "Support for all candidates equally", "No political debates"], "B", 2, 52)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "Voter abstention in the 2018 Brazilian elections raised concerns about democratic representation. Many voters decided not to vote due to disillusionment with politics, pointing to lack of viable options and corruption scandals.", "Voter abstention in 2018 was caused by:", ["Increased trust in politicians", "Disillusionment with politics and lack of viable options", "Prohibition of compulsory voting", "Reduction in number of candidates", "Improved quality of options"], "B", 2, 48)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "The debate about morality in politics gained strength during the 2018 Brazilian elections. Many candidates presented themselves as alternatives to corruption, using slogans that emphasized ethical and moral values.", "The morality debate in 2018 focused on:", ["Economic promises for the population", "Ethical and moral values of candidates", "Increasing executive power", "Reducing number of parties", "Increasing popular participation"], "B", 2, 55)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "Artificial intelligence was used in 2018 Brazilian campaigns for precise voter segmentation. Algorithms analyzed user data to deliver personalized messages, maximizing the impact of political advertising on social media.", "AI was used in 2018 campaigns to:", ["Increase campaign costs", "Precisely segment voters for personalized messages", "Eliminate need for debates", "Reduce popular participation", "Increase power of traditional parties"], "B", 3, 32)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "The choice of candidates in the 2018 Brazilian elections was influenced by factors like charisma, public image and ability to communicate on social media. Many voters decided their vote based on the candidate's image rather than proposals.", "Candidate image in 2018 influenced voters by:", ["Having no importance", "Partially determining voters' choices", "Completely replacing government proposals", "Increasing campaign costs", "Eliminating need for debates"], "B", 2, 50)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "Political violence during the 2018 Brazilian elections was a concerning problem. Candidates and supporters faced threats and aggression, demonstrating the tension in Brazil's political environment.", "Political violence in 2018 demonstrated:", ["Harmony in Brazilian society", "Tension in the political environment", "End of political conflicts", "Universal support for one candidate", "Absence of political debate"], "B", 2, 52)); n+=1

# Espanhol 5
d = "espanhol"
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "Las elecciones presidenciales brasileñas de 2018 estuvieron marcadas por una intensa polarización y campañas controvertidas. Las redes sociales jugaron un papel crucial en la difusión de mensajes políticos.", "Las elecciones de 2018 se caracterizaron por:", ["Unidad política y consenso", "Intensa polarización y campañas controvertidas", "Ausencia total de debates", "Apoyo universal para todos los candidatos", "No uso de redes sociales"], "B", 1, 72)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "Las noticias falsas se convirtieron en una preocupación importante durante las elecciones brasileñas de 2018. La información falsa se propagaba rápidamente por las redes sociales, influenciando la opinión pública.", "Las noticias falsas fueron una preocupación en 2018 porque:", ["Mejoraron la calidad del debate político", "Propagaron información falsa que influenció la opinión pública", "Aumentaron la participación electoral", "Fortalecieron los partidos políticos", "Reducieron los costos de las campañas"], "B", 1, 70)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "El uso de redes sociales en la campaña de 2018 fue decisivo. Los candidatos utilizaron plataformas como Facebook, Twitter y WhatsApp para llegar directamente a los votantes, evitando los filtros de los medios tradicionales.", "Las redes sociales fueron importantes en 2018 porque:", ["Reemplazaron completamente la televisión", "Permitieron llegar directamente a los votantes", "Eliminaron la necesidad de debates", "Reducieron significativamente los costos de campaña", "Garantizaron equilibrio entre candidatos"], "B", 2, 48)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "La participación juvenil en las elecciones brasileñas de 2018 fue notable. Los jóvenes utilizaron las redes sociales para expresar sus opiniones políticas y movilizar a sus pares. Sin embargo, muchos jóvenes votantes se sintieron desilusionados.", "La participación juvenil en 2018 fue notable porque:", ["Los jóvenes estaban prohibidos de votar", "Usaron redes sociales para expresar opiniones y movilizar pares", "No estaban interesados en la política", "No tenían acceso a la tecnología", "Apoyaron solo a un candidato"], "B", 2, 45)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "La polarización política en las elecciones brasileñas de 2018 reflejó divisiones profundas en la sociedad. Los partidarios de diferentes candidatos tenían visiones fundamentalmente diferentes sobre el futuro del país.", "La polarización política en 2018 reflejó:", ["Unanimidad entre todos los ciudadanos", "Divisiones profundas sobre el futuro del país", "Indiferencia hacia la política", "Apoyo universal a un candidato", "Ausencia de debates políticos"], "B", 2, 50)); n+=1

# Literatura 5
d = "literatura"
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "A literatura brasileira tem retratado ao longo dos séculos as transformações políticas e sociais do país. De Machado de Assis a contemporâneos, os autores exploraram temas como poder, corrupção e identidade nacional.", "A literatura brasileira retrata as transformações políticas ao:", ["Ignorar completamente a política", "Explorar temas como poder, corrupção e identidade nacional", "Apenas celebrar governos", "Evitar temas sociais", "Focar apenas na natureza"], "B", 2, 52)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "O romance 'O Cortiço' de Aluísio Azevedo retrata a vida em uma comunidade de baixa renda no Rio de Janeiro do século XIX. A obra explora temas como desigualdade social, marginalização e a condição humana em ambientes urbanos.", "O Cortiço de Aluísio Azevedo retrata:", ["A vida da aristocracia carioca", "A vida em comunidades de baixa renda e desigualdade social", "O cotidiano do campo", "A política internacional", "A vida religiosa"], "B", 2, 50)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "A obra 'Capitães da Areia' de Jorge Amado retrata a vida de meninos de rua em Salvador. A obra é um exemplo do regionalismo brasileiro e explora temas como pobreza, marginalidade e solidariedade entre os personagens.", "Capitães da Areia exemplifica o:", ["Romantismo brasileiro", "Regionalismo brasileiro", "Modernismo", "Parnasianismo", "Simbolismo"], "B", 2, 48)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "A poesia de Fernando Pessoa explora a questão da identidade e dafragmentação do eu. O autor utilizou heterônimos para expressar diferentes visões de mundo, criando uma obra complexa e multifacetada.", "Fernando Pessoa utilizou heterônimos para:", ["Simplificar sua escrita", "Expressar diferentes visões de mundo e fragmentação do eu", "Aumentar suas vendas de livros", "Evitar problemas com a censura", "Celebrar o governo português"], "B", 2, 55)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "A obra 'Grande Sertão: Veredas' de Guimarães Rosa é considerada uma das mais importantes da literatura brasileira. O romance explora a journey de um jagunço pelo sertão mineiro, misturando linguagem regional com reflexões filosóficas.", "Grande Sertão: Veredas mistura:", ["Apenas linguagem culta europeia", "Linguagem regional com reflexões filosóficas", "Apenas humor e comédia", "Somente críticas políticas diretas", "Apenas descrições da natureza"], "B", 2, 52)); n+=1

# Artes 2
d = "artes"
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "A arte contemporânea brasileira tem se manifestado de diversas formas, desde intervenções urbanas até instalações em museus. Artistas utilizam diferentes linguagens para expressar críticas sociais e políticas.", "A arte contemporânea brasileira contribui ao:", ["Ignorar questões sociais", "Expressar críticas sociais e políticas através de diferentes linguagens", "Apenas decorar espaços públicos", "Celebrar apenas governos", "Evitar temas controversos"], "B", 2, 50)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "O movimento hip-hop brasileiro tem desempenhado um papel importante na expressão cultural de jovens de comunidades periféricas. Através do rap, artistas denunciam desigualdades sociais e problems urbanos.", "O hip-hop brasileiro contribui ao:", ["Apenas entreter o público", "Denunciar desigualdades sociais através da música", "Celebrar a vida nas grandes mansões", "Evitar temas sociais", "Aumentar o consumo de produtos"], "B", 1, 78)); n+=1

# Educacao Fisica 2
d = "educacao_fisica"
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "Os Jogos Olímpicos do Rio 2016 deixaram um legado importante para o esporte brasileiro. A ampliação de espaços para prática esportiva e a melhoria da infraestrutura esportiva beneficiaram diversas comunidades.", "O legado dos Jogos Olímpicos do Rio 2016 foi:", ["Apenas temporário", "Ampliação de espaços para prática esportiva e melhoria da infraestrutura", "Irrisório para a população", "Limitado apenas aos atletas profissionais", "Negativo para o país"], "B", 1, 80)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "A inclusão social através do esporte tem se mostrado uma estratégia eficaz para comunidades em situação de vulnerabilidade. Projetos sociais utilizam atividades esportivas para promover valores e oportunidades.", "O esporte contribui para a inclusão social ao:", ["Excluir pessoas com deficiência", "Promover valores e oportunidades para comunidades vulneráveis", "Apenas formar atletas profissionais", "Aumentar a competição entre comunidades", "Restringir o acesso a determinados grupos"], "B", 2, 52)); n+=1

# TIC 1
d = "tic"
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "A transformação digital tem impactado a política brasileira. Ferramentas de comunicação digital permitem maior interação entre governantes e cidadãos, facilitando a prestação de contas e a participação popular.", "A transformação digital na política contribui ao:", ["Aumentar a distância entre governantes e cidadãos", "Facilitar a prestação de contas e a participação popular", "Eliminar a necessidade de eleições", "Aumentar a corrupção", "Restringir o acesso à informação"], "B", 1, 82)); n+=1

# HUMANAS
p = "H"
a = "humanas"

# Historia 15
d = "historia"
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "As eleições de 2018 marcaram um momento de grande turbulência na história política brasileira. O impeachment de 2016 e a operação Lava Jato criaram um cenário de instabilidade que influenciou diretamente o processo eleitoral.", "As eleições de 2018 foram influenciadas por:", ["Estabilidade política total", "Turbulência política, impeachment e operação Lava Jato", "Fim de todos os escândalos de corrupção", "Apoio unânime da sociedade", "Ausência de debates políticos"], "B", 2, 55)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "A operação Lava Jato, iniciada em 2014, desmantelou uma das maiores redes de corrupção da história brasileira. A operação envolveu políticos de diferentes partidos e gerou reflexos profundos no sistema político do país.", "A operação Lava Jato gerou reflexos ao:", ["Não ter impacto na política", "Desmantelar rede de corrupção e gerar reflexos no sistema político", "Apenas prender alguns políticos", "Não envolver grandes empresas", "Beneficiar apenas um partido"], "B", 2, 52)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "O impeachment de Dilma Rousseff em 2016 foi um dos eventos mais marcantes da história política recente do Brasil. O processo gerou debates sobre legalidade, legitimidade e consequências para a democracia brasileira.", "O impeachment de 2016 gerou debates sobre:", ["Economia do país", "Legalidade, legitimidade e consequências para a democracia", "Educação pública", "Política externa", "Saúde da população"], "B", 2, 50)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "A história política brasileira é marcada por momentos de ruptura e continuidade. Desde a proclamação da República até as eleições de 2018, o país passou por transformações significativas em sua estrutura política.", "A história política brasileira é marcada por:", ["Estabilidade total desde 1889", "Momentos de ruptura e continuidade em sua estrutura política", "Ausência de transformações", "Governos sempre democráticos", "Fim de todos os conflitos políticos"], "B", 2, 48)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "O papel da imprensa na história política brasileira tem sido fundamental. Desde a abolição da escravatura até as eleições de 2018, os meios de comunicação influenciaram a opinião pública e o processo democrático.", "A imprensa brasileira influenciou a história política ao:", ["Não ter nenhuma importância", "Influenciar a opinião pública e o processo democrático", "Apenas entreter a população", "Controlar o governo diretamente", "Eliminar todos os conflitos"], "B", 2, 55)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "Os movimentos sociais brasileiros têm desempenhado papel importante na história política do país. De trabalhadores a estudantes, diferentes grupos sociais mobilizaram-se para conquistar direitos e influenciar políticas públicas.", "Os movimentos sociais brasileiros contribuíram ao:", ["Não ter nenhuma importância histórica", "Conquistar direitos e influenciar políticas públicas ao longo da história", "Apenas causar distúrbios", "Eliminar todos os conflitos", "Controlar o governo diretamente"], "B", 2, 52)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "A Constituição de 1988 é considerada a mais avançada da história brasileira em termos de direitos sociais. No entanto, sua implementação completa ainda enfrenta desafios políticos e econômicos.", "A Constituição de 1988 é considerada avançada porque:", ["Não garantiu nenhum direito social", "Estabeleceu direitos sociais avançados para a população", "Apenas copiou constituições estrangeiras", "Não teve impacto na sociedade", "Foi rejeitada pela população"], "B", 2, 50)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "O papel dos partidos políticos na história brasileira tem sido controverso. De oligarquias regionais a partidos modernos, a evolução dos partidos reflete as transformações políticas do país ao longo do tempo.", "A evolução dos partidos políticos brasileiros reflete:", ["Estabilidade total no sistema partidário", "As transformações políticas do país ao longo do tempo", "Ausência de mudanças políticas", "Fim de todos os partidos", "Controle total de um único partido"], "B", 2, 48)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "A redemocratização brasileira, iniciada na década de 1980, trouxe expectativas de profundas mudanças na estrutura política. No entanto, muitas das reformas prometidas ainda não foram completamente implementadas até as eleições de 2018.", "A redemocratização brasileira trouxe expectativas que:", ["Foram completamente implementadas", "Muitas ainda não foram completamente implementadas até 2018", "Não geraram nenhuma mudança", "Foram rejeitadas pela população", "Eliminaram todos os problemas políticos"], "B", 2, 52)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "O processo de industrialização brasileiro, iniciado na década de 1930, transformou profundamente a estrutura social e política do país. A urbanização acelerada trouxe novos desafios para a representação política.", "O processo de industrialização brasileiro transformou:", ["Apenas a economia do país", "A estrutura social e política do país", "Nada da sociedade brasileira", "Apenas a agricultura", "Apenas a política externa"], "B", 2, 50)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "A escravidão no Brasil, que durou mais de 300 anos, deixou marcas profundas na sociedade brasileira. A abolição, em 1888, não foi acompanhada de políticas de inclusão social, gerando desigualdades que persistem até hoje.", "A escravidão no Brasil deixou marcas ao:", ["Não ter impacto na sociedade atual", "Gerar desigualdades sociais que persistem até hoje", "Apenas influenciar a economia do passado", "Ser completamente superada", "Não ter nenhuma relevância histórica"], "B", 2, 55)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "O papel das Forças Armadas na história brasileira tem sido controverso. De intervenções militares a transições democráticas, as Forças Armadas influenciaram profundamente a política do país em diferentes momentos históricos.", "As Forças Armadas influenciaram a política brasileira ao:", ["Não ter nenhuma importância histórica", "Influenciar profundamente a política em diferentes momentos históricos", "Apenas defender o país de invasões externas", "Não participar de nenhuma transição política", "Controlar o governo continuamente"], "B", 2, 48)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "A política de desenvolvimento nacional, implementada em diferentes governos, buscou industrializar o país e reduzir desigualdades regionais. No entanto, os resultados dessas políticas foram desiguais ao longo do tempo.", "A política de desenvolvimento nacional buscou:", ["Manter o país apenas agrário", "Industrializar o país e reduzir desigualdades regionais", "Apenas exportar commodities", "Eliminar toda a indústria", "Não ter nenhuma política econômica"], "B", 2, 50)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "O sistema educacional brasileiro tem passado por transformações ao longo da história. De uma educação elitista a programas de democratização do acesso, o país buscou ampliar as oportunidades educacionais para toda a população.", "O sistema educacional brasileiro buscou ao longo da história:", ["Manter a educação apenas para elites", "Democratizar o acesso e ampliar oportunidades educacionais", "Eliminar todas as escolas", "Não investir em educação", "Controlar o pensamento dos alunos"], "B", 2, 52)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "A política externa brasileira tem oscilado entre alianças estratégicas e momentos de isolamento. Desde a Era Vargas até as eleições de 2018, o Brasil buscou posicionamento no cenário internacional de diferentes maneiras.", "A política externa brasileira tem sido caracterizada por:", ["Isolamento total desde sempre", "Oscilação entre alianças estratégicas e momentos de isolamento", "Apenas alianças com países vizinhos", "Não ter política externa", "Conflitos constantes com todos os países"], "B", 2, 48)); n+=1

# Geografia 15
d = "geografia"
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "A distribuição geográfica dos votos nas eleições de 2018 revelou padrões regionais interessantes. Candidatos de diferentes posições políticas obtiveram melhores resultados em diferentes regiões do país.", "A distribuição geográfica dos votos em 2018 revelou:", ["Padrões uniformes em todo o país", "Padrões regionais diferentes para cada candidato", "Apenas votos no Sudeste", "Ausência de votos no Norte", "Igualdade perfeita entre regiões"], "B", 2, 50)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "A urbanização brasileira tem impactado diretamente o processo eleitoral. Grandes centros urbanos concentram milhões de eleitores com diferentes necessidades e demandas políticas.", "A urbanização brasileira afeta o processo eleitoral ao:", ["Não ter nenhuma influência", "Concentrar milhões de eleitores com diferentes demandas políticas", "Apenas facilitar a contagem de votos", "Eliminar a participação rural", "Uniformizar todas as demandas"], "B", 2, 52)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "As desigualdades regionais no Brasil influenciam diretamente o comportamento eleitoral. Regiões com diferentes níveis de desenvolvimento econômico e social tendem a apoiar candidatos com propostas distintas.", "As desigualdades regionais influenciam o processo eleitoral ao:", ["Não ter nenhuma influência", "Levar regiões diferentes a apoiar candidatos com propostas distintas", "Uniformizar o comportamento eleitoral", "Eliminar diferenças regionais", "Apenas influenciar a economia"], "B", 2, 48)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "A infraestrutura de transporte e comunicação nas diferentes regiões do Brasil afeta diretamente a mobilização eleitoral. Regiões com melhor infraestrutura tendem a ter maior participação popular.", "A infraestrutura afeta o processo eleitoral ao:", ["Não ter nenhuma influência", "Facilitar a mobilização eleitoral em regiões com melhor infraestrutura", "Apenas causar transtornos", "Eliminar a participação popular", "Uniformizar todas as regiões"], "B", 1, 78)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "A distribuição populacional do Brasil é desigual, com a maioria da população concentrada na região Sudeste. Essa concentração influencia a distribuição de cadeiras no Congresso Nacional e o processo eleitoral.", "A distribuição populacional desigual influencia:", ["Não ter nenhuma influência na política", "A distribuição de cadeiras no Congresso e o processo eleitoral", "Apenas a economia do país", "A educação da população", "A infraestrutura das cidades"], "B", 2, 50)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "O processo de metropolização no Brasil gerou novos desafios para a representação política. Grandes regiões metropolitanas concentram milhões de pessoas e demandas específicas que nem sempre são atendidas pelo sistema político.", "O processo de metropolização gera desafios políticos porque:", ["Não gera nenhum desafio", "Concentra população e demandas que nem sempre são representadas", "Apenas melhora a infraestrutura", "Elimina todos os problemas", "Apenas aumenta a poluição"], "B", 2, 48)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "A questão ambiental brasileira tem se tornado cada vez mais presente no debate político. Conflitos como exploração de recursos naturais e desmatamento geram tensões entre diferentes setores da sociedade.", "A questão ambiental no Brasil é importante porque:", ["Não tem relação com a política", "Envolve tensões entre diferentes setores sobre o desenvolvimento sustentável", "Deve ser tratada apenas por cientistas", "É irrelevante para a política", "Deve ser resolvida apenas pelo mercado"], "B", 2, 52)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "A globalização tem impactado profundamente a política brasileira. A inserção do país no mercado global trouxe oportunidades, mas também desafios como dependência de investimentos estrangeiros e influência de organismos internacionais.", "A globalização afeta a política brasileira ao:", ["Isolar completamente o país", "Trazer desafios como dependência de investimentos estrangeiros", "Eliminar a necessidade de reformas", "Aumentar a soberania nacional", "Reduzir a influência de organismos internacionais"], "B", 2, 48)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "A mobilidade urbana afeta diretamente a participação eleitoral. Cidades com transporte público eficiente tendem a ter maior comparecimento às urnas. Muitas cidades brasileiras ainda enfrentam deficiências no transporte.", "A mobilidade urbana afeta o processo eleitoral ao:", ["Não ter nenhuma influência", "Influenciar o comparecimento dos eleitores às urnas", "Apenas causar transtornos", "Eliminar a necessidade de locais de votação", "Uniformizar todas as cidades"], "B", 1, 75)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "A distribuição de recursos públicos no Brasil é influenciada pela representação política de cada região. Estados com maior poder político tendem a receber mais investimentos do governo federal.", "A representação política influencia a distribuição de recursos ao:", ["Equalizar investimentos em todas as regiões", "Favorecer estados com maior poder político na distribuição de investimentos", "Eliminar tensões regionais", "Aumentar a participação popular", "Reduzir a importância da política"], "B", 2, 50)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "A diversidade geográfica do Brasil influencia diretamente a política brasileira. Diferentes regiões possuem necessidades e interesses distintos que devem ser representados no processo político.", "A diversidade geográfica influencia a política ao:", ["Criar necessidades comuns a todas as regiões", "Gerar necessidades e interesses distintos que devem ser representados", "Eliminar a necessidade de reformas", "Centralizar o poder em uma única região", "Uniformizar todas as necessidades"], "B", 2, 52)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "Os conflitos territoriais no Brasil muitas vezes estão associados a questões de representação política. Comunidades tradicionais enfrentam dificuldades para garantir seus direitos territoriais devido à falta de representação política adequada.", "A falta de representação política contribui para:", ["A proteção dos direitos territoriais", "Dificuldades na garantia dos direitos territoriais de comunidades tradicionais", "A diminuição dos conflitos territoriais", "O fortalecimento das comunidades", "A resolução imediata de todos os conflitos"], "B", 2, 48)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "A infraestrutura de transportes no Brasil é um fator que influencia a mobilização política. Regiões com melhor infraestrutura permitem maior mobilidade dos candidatos e eleitores.", "A infraestrutura de transportes influencia a política ao:", ["Não ter nenhuma influência", "Permitir maior mobilidade dos candidatos e eleitores em regiões com melhor infraestrutura", "Apenas causar transtornos", "Eliminar a necessidade de deslocamento", "Uniformizar todas as regiões"], "B", 2, 50)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "A questão hídrica brasileira tem se tornado cada vez mais presente no debate político. A distribuição desigual da água no território gera tensões entre diferentes regiões e setores da sociedade.", "A questão hídrica é importante porque:", ["Não tem relação com a política", "Envolve tensões entre regiões sobre a distribuição de água", "Deve ser tratada apenas por engenheiros", "É irrelevante para a política", "Deve ser resolvida apenas pelo mercado"], "B", 2, 55)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "O processo de urbanização acelerado no Brasil gerou novos desafios para a representação política. Grandes centros urbanos concentram milhões de pessoas com diferentes necessidades e demandas políticas.", "O processo de urbanização gera desafios políticos porque:", ["Não gera nenhum desafio", "Concentra população com diferentes necessidades e demandas políticas", "Apenas melhora a infraestrutura", "Elimina todos os problemas", "Apenas aumenta a poluição"], "B", 2, 50)); n+=1

# Sociologia 8
d = "sociologia"
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "A polarização política de 2018 refletiu divisões profundas na sociedade brasileira. A sociologia ajuda a compreender como diferentes grupos sociais se posicionaram diante das opções políticas disponíveis.", "A sociologia ajuda a compreender a polarização ao:", ["Ignorar as divisões sociais", "Analisar como diferentes grupos sociais se posicionaram politicamente", "Apenas descrever a situação", "Eliminar todas as divergências", "Controlar o pensamento da população"], "B", 2, 50)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "O fenômeno das fake news nas eleições de 2018 pode ser analisado sob a perspectiva sociológica. A disseminação de informações falsas está relacionada a fatores como desconfiança nas instituições e busca por identidade grupal.", "A disseminação de fake news em 2018 está relacionada a:", ["Apenas a falta de educação", "Desconfiança nas instituições e busca por identidade grupal", "Apenas a tecnologia", "Apenas a política", "Não ter nenhuma relação com a sociedade"], "B", 2, 52)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "O comportamento eleitoral dos brasileiros em 2018 pode ser analisado através de teorias sociológicas sobre identidade, pertencimento e conflito social. As escolhas eleitorais refletiram divisões de classe, raça e região.", "As escolhas eleitorais em 2018 refletiram:", ["Unanimidade na sociedade", "Divisões de classe, raça e região na sociedade brasileira", "Apenas fatores econômicos", "Apenas fatores regionais", "Não ter nenhuma relação com a sociedade"], "B", 2, 48)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "A mobilização política nas redes sociais em 2018 pode ser analisada sob a perspectiva da sociologia digital. As plataformas virtuais criaram novos espaços de sociabilidade política e organização coletiva.", "As redes sociais criaram na política em 2018:", ["Espaços de sociabilidade política e organização coletiva", "Apenas entretenimento", "Não geraram nenhuma mudança", "Apenas conflitos", "Não tiveram importância"], "B", 2, 52)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "A desigualdade social brasileira influenciou diretamente o comportamento eleitoral em 2018. Populações com diferentes níveis de renda e escolaridade tendem a apoiar candidatos com propostas distintas.", "A desigualdade social influenciou o comportamento eleitoral ao:", ["Não ter nenhuma influência", "Levar populações diferentes a apoiar candidatos com propostas distintas", "Uniformizar o comportamento", "Eliminar todas as diferenças", "Apenas influenciar a economia"], "B", 2, 50)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "O papel dos movimentos sociais nas eleições de 2018 pode ser analisado sob a perspectiva sociológica. Diferentes organizações buscaram influenciar o processo político através da mobilização de seus membros.", "Os movimentos sociais em 2018 buscaram:", ["Não ter nenhuma influência", "Influenciar o processo político através da mobilização de seus membros", "Apenas causar distúrbios", "Eliminar todos os conflitos", "Controlar o governo diretamente"], "B", 2, 52)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "A comunicação política nas eleições de 2018 pode ser analisada sob a perspectiva sociológica. O uso de linguagem persuasiva e apelos emocionais buscam influenciar o comportamento eleitoral da população.", "A comunicação política em 2018 utilizou:", ["Apenas argumentos lógicos", "Linguagem persuasiva e apelos emocionais para influenciar o comportamento eleitoral", "Apenas dados estatísticos", "Somente depoimentos pessoais", "Não houve comunicação política"], "B", 2, 48)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "A influência dos meios de comunicação na formação da opinião pública em 2018 pode ser analisada sob a perspectiva sociológica. A mídia moldou percepções sobre candidatos e propostas políticas.", "A influência da mídia em 2018 moldou:", ["Não teve nenhuma influência", "Percepções sobre candidatos e propostas políticas", "Apenas a economia", "Apenas a cultura", "Não teve importância"], "B", 2, 50)); n+=1

# Filosofia 7
d = "filosofia"
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "A polarização política de 2018 pode ser analisada sob a perspectiva filosófica do conflito entre diferentes visões de mundo. A filosofia política ajuda a compreender as tensões entre liberdade e igualdade.", "A filosofia política ajuda a compreender a polarização ao:", ["Ignorar os conflitos", "Analisar as tensões entre liberdade e igualdade", "Apenas descrever a situação", "Eliminar todas as divergências", "Controlar o pensamento da população"], "B", 2, 50)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "O conceito de democracia participativa é relevante para analisar as eleições de 2018. A filosofia política questiona se a participação popular é efetiva em contextos de polarização e fake news.", "A democracia participativa em 2018 gerou questionamentos sobre:", ["Não gerou nenhum questionamento", "Se a participação popular é efetiva em contextos de polarização", "Apenas sobre a economia", "Apenas sobre a cultura", "Não teve importância"], "B", 2, 48)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "O conceito de poder de Foucault é relevante para analisar as relações políticas em 2018. O poder não está apenas no Estado, mas se manifesta em diversas relações sociais, incluindo as redes sociais.", "Segundo Foucault, o poder em 2018 se manifestou:", ["Apenas no Estado", "Em diversas relações sociais, incluindo as redes sociais", "Apenas nos partidos políticos", "Não existia poder", "Apenas na economia"], "B", 2, 42)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "A teoria da justiça de John Rawls é relevante para analisar as propostas eleitorais de 2018. A justiça social deve ser o critério fundamental para avaliar políticas públicas e decisões coletivas.", "Segundo Rawls, as propostas eleitorais devem ser avaliadas por:", ["Benefício para os mais ricos", "Justiça social como critério fundamental", "Apenas crescimento econômico", "Apenas tradição cultural", "Não há critérios"], "B", 2, 45)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "O conceito de soberania popular de Rousseau é relevante para analisar as eleições de 2018. O poder político emana do povo, mas a questão é como garantir que esse poder seja exercido de forma consciente e informada.", "A soberania popular em 2018 gerou questionamentos sobre:", ["Não gerou nenhum questionamento", "Como garantir que o poder popular seja exercido de forma consciente", "Apenas sobre a economia", "Apenas sobre a cultura", "Não teve importância"], "B", 2, 48)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "A ética na política é um tema filosófico fundamental. As eleições de 2018 levantaram questões sobre os limites da liberdade de expressão, o uso de fake news e a responsabilidade dos candidatos.", "A ética na política em 2018 levantou questões sobre:", ["Não levantou nenhuma questão", "Limites da liberdade de expressão e responsabilidade dos candidatos", "Apenas sobre a economia", "Apenas sobre a cultura", "Não teve importância"], "B", 2, 52)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "O conceito de liberdade de Mill é relevante para analisar os debates sobre fake news e discurso de ódio em 2018. A liberdade de expressão deve ter limites quando afeta direitos de terceiros?", "A liberdade de expressão em 2018 gerou debates sobre:", ["Não gerou nenhum debate", "Se deve ter limites quando afeta direitos de terceiros", "Apenas sobre a economia", "Apenas sobre a cultura", "Não teve importância"], "B", 3, 35)); n+=1

# NATUREZA
p = "N"
a = "natureza"

# Fisica 15
d = "fisica"
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "A eficiência energética tem se tornado cada vez mais importante na política brasileira. O desenvolvimento de fontes renováveis de energia é essencial para garantir a sustentabilidade do desenvolvimento nacional.", "A eficiência energética busca:", ["Aumentar o consumo de energia", "Otimizar o uso de recursos energéticos", "Eliminar todas as fontes de energia", "Substituir completamente as fontes renováveis", "Aumentar os custos de produção"], "B", 1, 80)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "As energias renováveis, como solar e eólica, têm ganhado cada vez mais espaço na matriz energética brasileira. Essas fontes são consideradas mais limpas porque não emitem poluentes durante sua operação.", "Uma vantagem das energias renováveis é:", ["São mais baratas que todas as outras fontes", "Não emitem poluentes durante sua operação", "Podem ser utilizadas em qualquer lugar", "Não dependem de condições climáticas", "Substituem completamente as fontes fósseis"], "B", 1, 78)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "O aquecimento global é um dos maiores desafios ambientais da atualidade. O aumento da temperatura média do planeta está associado à emissão de gases de efeito estufa provenientes de atividades humanas.", "O aquecimento global é causado principalmente por:", ["A diminuição da radiação solar", "A emissão de gases de efeito estufa por atividades humanas", "O movimento da Terra em torno do Sol", "As erupções vulcânicas naturais", "A atividade de planetas vizinhos"], "B", 1, 75)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "A energia nuclear é uma fonte controversa. Pode gerar grandes quantidades de eletricidade sem emitir gases de efeito estufa, mas os riscos de acidentes e o problema do lixo radioativo geram preocupações.", "Uma desvantagem da energia nuclear é:", ["Emite gases de efeito estufa em grandes quantidades", "Risco de acidentes e problema do lixo radioativo", "Não pode gerar eletricidade", "É muito barata e acessível", "Não utiliza urânio como combustível"], "B", 2, 52)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "O princípio da conservação da energia estabelece que a energia não pode ser criada nem destruída, apenas transformada. Esse princípio é fundamental para a compreensão dos processos energéticos.", "O princípio da conservação da energia estabelece que:", ["A energia pode ser criada e destruída", "A energia não pode ser criada nem destruída, apenas transformada", "A energia sempre se dissipa no meio ambiente", "A energia só pode ser transformada em calor", "A energia é ilimitada na natureza"], "B", 2, 50)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "A Segunda Lei da Termodinâmica afirma que a entropia total de um sistema isolado só pode aumentar ao longo do tempo. Essa lei tem implicações para a eficiência energética.", "A Segunda Lei da Termodinâmica implica que:", ["A energia pode ser usada infinitamente sem perdas", "Sistemas energéticos sempre se tornam menos eficientes", "Máquinas de movimento perpétuo são possíveis", "A entropia pode diminuir em sistemas isolados", "A eficiência energética não é importante"], "B", 3, 30)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "O efeito fotoelétrico, explicado por Einstein, é a base do funcionamento de painéis solares fotovoltaicos, que convertem a luz solar diretamente em eletricidade.", "O efeito fotoelétrico é utilizado em:", ["Motores a combustão", "Painéis solares fotovoltaicos", "Turbinas eólicas", "Usinas nucleares", "Baterias de carros elétricos"], "B", 2, 52)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "A energia eólica, gerada pelo vento, é uma das fontes renováveis com maior potencial de crescimento no Brasil. A instalação de parques eólicos pode contribuir significativamente para a matriz energética.", "A energia eólica é considerada renovável porque:", ["Utiliza combustíveis fósseis", "Depende de uma fonte inesgotável como o vento", "É muito barata de produzir", "Não causa nenhum impacto ambiental", "Pode ser utilizada em qualquer lugar"], "B", 1, 76)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "A eficiência de uma máquina térmica é limitada pela Segunda Lei da Termodinâmica. Essa lei estabelece que nenhum ciclo pode ser 100% eficiente na conversão de calor em trabalho.", "A Segunda Lei da Termodinâmica limita a eficiência ao:", ["Permitir 100% de eficiência", "Estabelecer que nenhuma máquina pode ser 100% eficiente", "Aumentar a eficiência conforme a temperatura aumenta", "Permitir motores de movimento perpétuo", "Eliminar todas as perdas de energia"], "B", 3, 28)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "A lei de Ohm descreve a relação entre tensão, corrente e resistência em circuitos elétricos. Essa lei é fundamental para o projeto de sistemas de distribuição de energia elétrica.", "A lei de Ohm descreve a relação entre:", ["Temperatura e pressão", "Tensão, corrente e resistência em circuitos elétricos", "Massa e aceleração", "Volume e pressão de um gás", "Comprimento de onda e frequência"], "B", 2, 55)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "A potência elétrica é medida em watts e representa a taxa de consumo de energia. Se um eletrodoméstico consome 100 watts, significa que consome 100 joules de energia por segundo.", "Se um eletrodoméstico consome 100 watts, significa que consome:", ["100 joules de energia por segundo", "100 joules de energia por hora", "100 watts de energia por minuto", "100 newtons de força", "100 volts de tensão"], "A", 2, 48)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "A transferência de calor pode ocorrer por condução, convecção e radiação. A radiação é a transferência de calor por ondas eletromagnéticas, sem necessidade de meio material.", "A transferência de calor por radiação ocorre através de:", ["Contato direto entre materiais", "Movimento de fluidos", "Ondas eletromagnéticas", "Condução elétrica", "Pressão atmosférica"], "C", 2, 48)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "A energia solar é uma das fontes renováveis mais promissoras. O Brasil possui alta incidência de radiação solar em grande parte de seu território, tornando a energia solar uma opção viável.", "O Brasil tem potencial para energia solar porque:", ["Não possui incidência de radiação solar", "Possui alta incidência de radiação solar em grande parte do território", "É um país frio e nublado", "Não tem espaço para instalação de painéis", "A energia solar é proibida no país"], "B", 1, 78)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "O efeito estufa é um fenômeno natural que ajuda a manter a temperatura da Terra adequada. No entanto, a emissão excessiva de gases de efeito estufa tem intensificado esse processo, contribuindo para o aquecimento global.", "O efeito estufa em excesso causa:", ["Resfriamento do planeta", "Aquecimento global", "Aumento da camada de ozônio", "Diminuição da temperatura dos oceanos", "Redução da radiação solar"], "B", 1, 82)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "A camada de ozônio é importante para a proteção da vida na Terra. A destruição dessa camada por substâncias químicas como os CFCs é um problema ambiental que afeta a proteção contra a radiação ultravioleta.", "A camada de ozônio é importante porque:", ["Bloqueia toda a radiação solar", "Protege contra a radiação ultravioleta prejudicial", "Mantém a temperatura constante", "Impede a formação de nuvens", "Produz oxigênio para respiração"], "B", 2, 52)); n+=1

# Quimica 15
d = "quimica"
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "A água é um recurso natural essencial para a vida. No entanto, apenas 2,5% da água do planeta é doce e acessível para consumo humano. A poluição das águas tem se tornado um problema crescente.", "A principal preocupação com a poluição das águas é:", ["O aumento do nível dos oceanos", "A diminuição da disponibilidade de água potável", "O aquecimento da água dos rios", "A diminuição da evaporação", "O aumento da salinidade dos rios"], "B", 1, 80)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "Os agrotóxicos são amplamente utilizados na agricultura brasileira. No entanto, o uso excessivo pode causar contaminação do solo, da água e dos alimentos. A química ambiental estuda os impactos desses produtos.", "O uso excessivo de agrotóxicos pode causar:", ["Aumento da produtividade agrícola", "Contaminação do solo, da água e dos alimentos", "Melhoria da qualidade do solo", "Aumento da biodiversidade", "Redução dos custos de produção"], "B", 2, 52)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "O plástico é um dos materiais mais utilizados, mas sua produção e descarte inadequado causam sérios problemas ambientais. Muitos plásticos são produzidos a partir de petróleo, um recurso não renovável.", "Um problema ambiental associado ao uso de plásticos é:", ["A redução da poluição dos oceanos", "A contaminação dos oceanos e a decomposição lenta", "O aumento da biodiversidade marinha", "A diminuição do uso de petróleo", "O fortalecimento do solo"], "B", 1, 78)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "As baterias de íon-lítio são as mais utilizadas em dispositivos eletrônicos e veículos elétricos. Oferecem alta densidade de energia, mas a produção e descarte inadequados causam problemas ambientais.", "Uma vantagem das baterias de íon-lítio é:", ["São baratas e fáceis de produzir", "Oferecem alta densidade de energia e são leves", "São 100% recicláveis sem resíduos", "Não causam nenhum impacto ambiental", "Podem ser utilizadas infinitamente"], "B", 2, 48)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "O efeito estufa é um fenômeno natural que ajuda a manter a temperatura da Terra adequada. No entanto, a emissão excessiva de gases de efeito estufa tem intensificado esse processo.", "O efeito estufa em excesso causa:", ["Resfriamento do planeta", "Aquecimento global", "Aumento da camada de ozônio", "Diminuição da temperatura dos oceanos", "Redução da radiação solar"], "B", 1, 82)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "A tabela periódica organiza os elementos de acordo com seu número atômico e propriedades químicas. O conhecimento da tabela periódica é essencial para entender a composição da matéria e suas transformações.", "A tabela periódica organiza os elementos de acordo com:", ["Sua cor e textura", "Seu número atômico e propriedades químicas", "Sua massa molecular", "Sua temperatura de fusão", "Sua origem geográfica"], "B", 2, 52)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "A reciclagem de materiais como alumínio, papel e vidro é importante para a sustentabilidade. O alumínio pode ser reciclado infinitamente sem perder suas propriedades.", "O alumínio pode ser reciclado:", ["Apenas uma vez", "Até perder suas propriedades", "Infinitamente sem perder suas propriedades", "Nunca pode ser reciclado", "Apenas em fábricas especiais"], "C", 2, 50)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "A combustão é uma reação química que libera energia. A queima de combustíveis fósseis libera gases de efeito estufa na atmosfera, contribuindo para o aquecimento global.", "A combustão de combustíveis fósseis libera:", ["Oxigênio puro", "Gases de efeito estufa que contribuem para o aquecimento global", "Apenas vapor de água", "Substâncias que protegem a camada de ozônio", "Elementos químicos radioativos"], "B", 1, 76)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "A purificação de água é essencial para garantir acesso à água potável. Os métodos incluem filtração, desinfecção química e tratamento por ultravioleta, que removem impurezas e microorganismos nocivos.", "O principal objetivo da purificação de água é:", ["Tornar a água mais bonita", "Remover impurezas e microorganismos nocivos para consumo humano", "Aumentar o sabor da água", "Eliminar todos os minerais da água", "Tornar a água mais quente"], "B", 1, 84)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "Os polímeros são materiais formados por moléculas grandes repetidas, como o plástico. Muitos polímeros são derivados do petróleo e sua decomposição pode levar centenas de anos.", "Uma desvantagem dos polímeros convencionais é:", ["São biodegradáveis rapidamente", "Sua decomposição pode levar centenas de anos", "São muito caros de produzir", "Não têm aplicações práticas", "São sempre recicláveis"], "B", 2, 52)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "O ozônio é uma molécula formada por três átomos de oxigênio. Na estratosfera, o ozônio protege a vida na Terra absorvendo a radiação ultravioleta prejudicial.", "Na estratosfera, o ozônio é importante porque:", ["Causa problemas respiratórios", "Protege a vida na Terra absorvendo radiação ultravioleta", "Aumenta a temperatura do planeta", "Polui o ar que respiramos", "Diminui a pressão atmosférica"], "B", 2, 48)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "A corrosão é um processo químico que degrada metais quando expostos a ambientes corrosivos. A proteção contra corrosão é essencial para manutenção de estruturas metálicas.", "A corrosão é um processo que:", ["Fortalece os metais", "Degrada metais quando expostos a ambientes corrosivos", "Aumenta a vida útil das estruturas", "É benéfica para a indústria", "Não causa danos aos materiais"], "B", 1, 76)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "O pH é uma escala que mede a acidez ou alcalinidade de uma solução. Valores abaixo de 7 indicam acidez, enquanto valores acima de 7 indicam alcalinidade.", "Valores de pH abaixo de 7 indicam:", ["Alcalinidade", "Acidez", "Neutralidade", "Temperatura elevada", "Pressão atmosférica alta"], "B", 1, 80)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "A dessalinização é o processo de remoção de sal da água do mar, tornando-a própria para consumo humano. Essencial em regiões com escassez, mas consome grandes quantidades de energia.", "A dessalinização da água do mar é importante porque:", ["Torna a água do mar mais salgada", "Fornece água doce em regiões com escassez", "É um processo barato e eficiente", "Não consome energia", "Não causa impactos ambientais"], "B", 2, 50)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "As baterias de lítio-ion são amplamente utilizadas em dispositivos eletrônicos e veículos elétricos. No entanto, a mineração de lítio e descarte inadequado causam danos ambientais significativos.", "Um problema ambiental associado às baterias de lítio-ion é:", ["A poluição causada pela mineração e descarte inadequado", "A emissão de gases de efeito estufa durante seu uso", "A contaminação do solo por componentes radioativos", "O aquecimento global causado por seu funcionamento", "A diminuição da camada de ozônio"], "A", 2, 45)); n+=1

# Biologia 15
d = "biologia"
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "A biodiversidade brasileira é uma das maiores do mundo, com milhões de espécies. No entanto, o desmatamento e a degradação de habitats ameaçam a sobrevivência de muitas espécies.", "A principal ameaça à biodiversidade brasileira é:", ["O aumento da temperatura global", "O desmatamento e a degradação de habitats", "A diminuição da população humana", "O aumento da precipitação pluviométrica", "A redução do número de espécies invasoras"], "B", 1, 80)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "As mudanças climáticas afetam diretamente os ecossistemas naturais e a biodiversidade. O aumento da temperatura global pode alterar padrões de precipitação e causar a extinção de espécies.", "Uma consequência das mudanças climáticas para a biodiversidade é:", ["O aumento do número de espécies", "A extinção de espécies que não conseguem se adaptar", "A diminuição da temperatura dos oceanos", "O fortalecimento dos ecossistemas", "O aumento da produtividade agrícola"], "B", 2, 52)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "O desmatamento na Amazônia tem sido tema de preocupação internacional. A floresta abriga biodiversidade enorme e desempenha papel fundamental no equilíbrio climático global.", "A importância da Amazônia para o clima global reside em sua capacidade de:", ["Produzir dióxido de carbono", "Absorver dióxido de carbono e produzir oxigênio", "Aumentar a temperatura local", "Gerar energia hidrelétrica", "Produzir minerais preciosos"], "B", 1, 82)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "A fotossíntese é o processo pelo qual as plantas produzem seu próprio alimento usando luz solar, água e CO2. Esse processo é essencial para a vida na Terra, produzindo oxigênio eRemovendo carbono da atmosfera.", "A fotossíntese é essencial porque:", ["Remove oxigênio da atmosfera", "Produz oxigênio e remove carbono da atmosfera", "Aumenta a temperatura local", "Diminui a biodiversidade", "Produz dióxido de carbono"], "B", 1, 78)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "As células-tronco têm o potencial de se diferenciar em diferentes tipos de células do corpo humano. A pesquisa com células-tronco tem promessa para tratamentos de diversas doenças.", "As células-tronco são importantes porque:", ["Não têm capacidade de se diferenciar", "Têm potencial de se diferenciar em diferentes tipos de células", "Causam doenças no corpo humano", "São encontradas apenas em animais", "Não têm aplicações médicas"], "B", 2, 50)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "A cadeia alimentar mostra como a energia e nutrientes são transferidos entre organismos de um ecossistema. Os produtores formam a base, seguidos pelos consumidores primários, secundários e terciários.", "Na cadeia alimentar, os produtores são:", ["Os animais carnívoros", "Os vegetais que produzem seu próprio alimento", "Os decompositores", "Os animais herbívoros", "Os fungos"], "B", 1, 76)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "A seleção natural é o mecanismo proposto por Darwin para explicar a evolução das espécies. Através desse processo, organismos com características mais adequadas ao ambiente tendem a sobreviver e se reproduzir mais.", "A seleção natural explica:", ["A criação de novas espécies por intervenção humana", "A evolução das espécies através da sobrevivência dos mais aptos", "A extinção de todas as espécies", "A domesticação de animais", "A modificação genética artificial"], "B", 2, 52)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "O DNA é a molécula que armazena a informação genética de todos os seres vivos. A descoberta da estrutura de dupla hélice revolucionou a biologia e abriu caminho para avanços na medicina.", "O DNA é importante porque:", ["Armazena informação genética de todos os seres vivos", "É apenas uma molécula sem função específica", "Causa doenças em todos os organismos", "Não tem relação com a hereditariedade", "É encontrado apenas em plantas"], "A", 1, 80)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "As doenças infecciosas são causadas por patógenos como vírus, bactérias e fungos. O desenvolvimento de vacinas e antibióticos tem sido fundamental para o controle dessas doenças.", "O uso inadequado de antibióticos pode causar:", ["A cura imediata de todas as doenças", "O desenvolvimento de superbactérias resistentes", "O fortalecimento do sistema imunológico", "A eliminação de todos os patógenos", "Aumento da resistência natural do corpo"], "B", 2, 48)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "A engenharia genética permite modificar o DNA de organismos para obter características desejadas. Tem aplicações na agricultura, medicina e indústria, mas levanta questões éticas e ambientais.", "Uma aplicação da engenharia genética na medicina é:", ["A produção de combustíveis fósseis", "A produção de insulina para tratamento de diabetes", "O desenvolvimento de armas biológicas", "A contaminação de rios", "A eliminação de todas as espécies"], "B", 2, 50)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "Os ecossistemas aquáticos são particularmente vulneráveis à poluição e às mudanças climáticas. A acidificação dos oceanos ameaça organismos como corais e moluscos.", "A acidificação dos oceanos ameaça organismos porque:", ["Aumenta a temperatura da água", "Dissolve conchas e esqueletos de carbonato de cálcio", "Aumenta a quantidade de oxigênio", "Melhora as condições de vida dos corais", "Não causa danos aos organismos marinhos"], "B", 3, 30)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "A simbiose é uma relação ecológica em que duas espécies diferentes vivem juntas e se beneficiam mutuamente. Um exemplo é a relação entre abelhas e flores.", "Na relação de simbiose entre abelhas e flores:", ["Apenas as abelhas se beneficiam", "Apenas as flores se beneficiam", "Ambas as espécies se beneficiam", "Nenhuma das espécies se beneficia", "As espécies competem entre si"], "C", 2, 50)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "O ciclo do carbono é um dos ciclos biogeoquímicos mais importantes. A queima de combustíveis fósseis tem desequilibrado esse ciclo, aumentando a concentração de CO2 na atmosfera.", "O ciclo do carbono é desequilibrado pela:", ["Fotossíntese das plantas", "Queima de combustíveis fósseis que aumenta o CO2 na atmosfera", "Respiração dos animais", "Decomposição de organismos", "Absorção de carbono pelos oceanos"], "B", 2, 48)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "A biotecnologia tem potencial para contribuir com o desenvolvimento sustentável. O uso de organismos geneticamente modificados pode aumentar a produtividade agrícola e reduzir a necessidade de agrotóxicos.", "Uma aplicação da biotecnologia que pode contribuir com o desenvolvimento sustentável é:", ["A produção de combustíveis fósseis", "O uso de organismos geneticamente modificados para aumentar a produtividade", "O desenvolvimento de armas biológicas", "A eliminação de todas as espécies nativas", "A contaminação intencional de rios"], "B", 2, 46)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "A reciclagem de resíduos sólidos é essencial para a sustentabilidade ambiental. A separação correta do lixo permite que materiais como papel, vidro, plástico e metal sejam reprocessados.", "A reciclagem de resíduos sólidos é importante porque:", ["Aumenta a quantidade de lixo nos aterros", "Permite a reutilização de materiais e reduz o desperdício", "Elimina completamente a necessidade de produção de novos materiais", "Aumenta o consumo de recursos naturais", "Polui ainda mais o meio ambiente"], "B", 1, 86)); n+=1

# MATEMATICA
p = "M"
a = "matematica"

# Algebra 15
d = "algebra"
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "Se um partido recebe R$ 8 milhões para suas campanhas e precisa distribuir entre 40 candidatos, a média de recursos por candidato seria de R$ 200 mil.", "Se um partido tem R$ 8 milhões para distribuir entre 40 candidatos igualmente, quanto cada candidato receberia?", ["R$ 100 mil", "R$ 200 mil", "R$ 300 mil", "R$ 400 mil", "R$ 500 mil"], "B", 1, 85)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "Se em um município com 80 mil eleitores compareceram 60 mil às urnas, a taxa de comparecimento seria de 75%.", "Se 60 mil eleitores de 80 mil compareceram às urnas, a taxa de comparecimento foi de:", ["50%", "60%", "75%", "85%", "95%"], "C", 1, 88)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "O custo médio por voto pode ser calculado dividindo o total gasto pelo número de votos. Se um candidato gastou R$ 400 mil e recebeu 8 mil votos, o custo médio por voto seria R$ 50.", "Se um candidato gastou R$ 400 mil e recebeu 8 mil votos, quanto custou cada voto em média?", ["R$ 25", "R$ 50", "R$ 75", "R$ 100", "R$ 150"], "B", 2, 58)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "Se um candidato recebeu 6 mil votos no primeiro turno e 9 mil no segundo turno, a variação entre os turnos foi de 3 mil votos.", "Se um candidato recebeu 6 mil votos no primeiro turno e 9 mil no segundo, a variação foi de:", ["3 mil votos", "9 mil votos", "15 mil votos", "6 mil votos", "12 mil votos"], "A", 1, 82)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "Se a população de um município é de 60 mil e cresce 3% ao ano, pode-se projetar a população futura usando crescimento exponencial.", "Se a população é de 60 mil e cresce 3% ao ano, qual será a população aproximada após 5 anos?", ["65 mil", "69 mil", "70 mil", "72 mil", "75 mil"], "B", 3, 28)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "Se um partido precisa dividir R$ 800 mil entre dois estados de forma que o primeiro receba o triplo do segundo, pode-se usar um sistema de equações para determinar a distribuição.", "Se o primeiro estado deve receber o triplo do segundo, quanto cada um receberá de R$ 800 mil?", ["R$ 200 mil para cada", "R$ 400 mil para o primeiro e R$ 400 mil para o segundo", "R$ 600 mil para o primeiro e R$ 200 mil para o segundo", "R$ 200 mil para o primeiro e R$ 600 mil para o segundo", "R$ 300 mil para o primeiro e R$ 500 mil para o segundo"], "C", 2, 55)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "Se um candidato recebeu 40% dos votos válidos em um município de 120 mil eleitores, pode-se calcular o número exato de votos multiplicando o total pela porcentagem.", "Se um candidato recebeu 40% dos votos de 120 mil eleitores, quantos votos recebeu?", ["36 mil votos", "48 mil votos", "60 mil votos", "72 mil votos", "84 mil votos"], "B", 1, 86)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "Se o número de eleitores cresceu de 70 mil para 100 mil em 5 anos, a taxa de crescimento anual pode ser calculada.", "Se o número de eleitores cresceu de 70 mil para 100 mil em 5 anos, qual a taxa média anual?", ["6%", "8,5%", "10%", "12%", "15%"], "B", 2, 50)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "Se 25% dos eleitores de um município votam no partido A e o total de eleitores é 160 mil, pode-se calcular quantos eleitores isso representa.", "Se 25% dos 160 mil eleitores votam no partido A, quantos eleitores isso representa?", ["30 mil eleitores", "40 mil eleitores", "50 mil eleitores", "60 mil eleitores", "70 mil eleitores"], "B", 1, 82)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "Se o candidato A recebeu o triplo de votos do candidato B e juntos receberam 120 mil votos, pode-se usar proporção para descobrir quantos votos cada um recebeu.", "Se o candidato A recebeu o triplo de votos do candidato B e juntos receberam 120 mil votos:", ["A: 30 mil, B: 90 mil", "A: 40 mil, B: 80 mil", "A: 60 mil, B: 60 mil", "A: 90 mil, B: 30 mil", "A: 80 mil, B: 40 mil"], "D", 2, 52)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "Se seis candidatos receberam respectivamente 5, 10, 15, 20, 25 e 30 mil votos, a média pode ser calculada somando todos os valores e dividindo pelo número de candidatos.", "Se seis candidatos receberam 5, 10, 15, 20, 25 e 30 mil votos, qual é a média?", ["15 mil votos", "17,5 mil votos", "20 mil votos", "22,5 mil votos", "25 mil votos"], "B", 2, 55)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "Se o custo de uma campanha é modelado por C(x) = 3x² + 150x, onde x é o número de municípios, pode-se calcular o custo para visitar 8 municípios.", "Se C(x) = 3x² + 150x, qual é o custo para visitar 8 municípios?", ["R$ 1.392", "R$ 1.500", "R$ 1.608", "R$ 1.800", "R$ 2.000"], "A", 3, 32)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "A notação científica é útil para representar números muito grandes. O número 8.500.000.000 pode ser representado em notação científica.", "O número 8.500.000.000 em notação científica é:", ["8,5 x 10⁸", "8,5 x 10⁹", "85 x 10⁸", "0,85 x 10¹⁰", "850 x 10⁷"], "B", 2, 50)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "Se o gasto máximo por candidato é R$ 800 mil e o mínimo é R$ 80 mil, pode-se representar essa situação como uma inequação.", "Se o gasto máximo é R$ 800 mil e o mínimo R$ 80 mil, qual é a representação correta?", ["80.000 < gasto < 800.000", "80.000 ≤ gasto ≤ 800.000", "80.000 ≥ gasto ≥ 800.000", "gasto > 800.000", "gasto < 80.000"], "B", 2, 48)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "Se dois municípios realizam eleições a cada 3 e 5 anos respectivamente, o MMC indica quando as eleições coincidirão.", "Se dois municípios realizam eleições a cada 3 e 5 anos, quando coincidirão?", ["A cada 8 anos", "A cada 12 anos", "A cada 15 anos", "A cada 20 anos", "A cada 25 anos"], "C", 3, 35)); n+=1

# Geometria 15
d = "geometria"
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "Se um terreno quadrado tem 12 m de lado, sua área pode ser calculada elevando o comprimento da aresta ao quadrado.", "Qual é a área de um terreno quadrado com 12 m de lado?", ["24 m²", "48 m²", "120 m²", "144 m²", "1.440 m²"], "D", 1, 88)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "Se uma sala retangular mede 10 m de comprimento por 8 m de largura, sua área pode ser calculada multiplicando comprimento pela largura.", "Qual é a área de uma sala retangular com 10 m de comprimento e 8 m de largura?", ["18 m²", "36 m²", "60 m²", "80 m²", "180 m²"], "D", 1, 86)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "Se um triângulo retângulo tem catetos de 5 cm e 12 cm, a hipotenusa pode ser calculada pelo Teorema de Pitágoras.", "Se os catetos medem 5 cm e 12 cm, quanto mede a hipotenusa?", ["7 cm", "13 cm", "17 cm", "60 cm", "169 cm"], "B", 1, 82)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "Se um círculo tem raio de 10 m, sua área pode ser calculada usando A = πr². Considerando π ≈ 3,14, a área será aproximadamente 314 m².", "Se o raio de um círculo é 10 m, qual é sua área aproximada?", ["31,4 m²", "62,8 m²", "314 m²", "628 m²", "3.140 m²"], "C", 2, 55)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "Se um cubo tem aresta de 4 m, seu volume pode ser calculado elevando a aresta ao cubo.", "Qual é o volume de um cubo com aresta de 4 metros?", ["16 m³", "48 m³", "64 m³", "128 m³", "256 m³"], "C", 1, 90)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "Se um terreno retangular mede 25 m por 20 m, sua área pode ser facilmente calculada multiplicando comprimento pela largura.", "Qual é a área de um terreno retangular com 25 m de comprimento e 20 m de largura?", ["250 m²", "500 m²", "750 m²", "1.000 m²", "5.000 m²"], "B", 1, 85)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "Se um losango tem diagonais medindo 10 cm e 8 cm, sua área pode ser calculada usando A = (d1 × d2)/2.", "Qual é a área de um losango com diagonais de 10 cm e 8 cm?", ["18 cm²", "40 cm²", "80 cm²", "100 cm²", "160 cm²"], "B", 2, 52)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "Se um cilindro tem raio da base de 5 m e altura de 12 m, seu volume pode ser calculado usando V = πr²h.", "Se o raio de um cilindro é 5 m e a altura 12 m, qual é seu volume aproximado?", ["300 m³", "600 m³", "942 m³", "1.200 m³", "3.000 m³"], "C", 2, 50)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "Se um triângulo equilátero tem lados de 8 m, sua área pode ser calculada usando A = (l² × √3)/4.", "Qual é a área aproximada de um triângulo equilátero com lados de 8 m?", ["16 m²", "27,7 m²", "32 m²", "64 m²", "128 m²"], "B", 3, 38)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "Se um cone tem raio da base de 6 m e altura de 10 m, seu volume pode ser calculado usando V = (πr²h)/3.", "Se o raio de um cone é 6 m e a altura 10 m, qual é seu volume aproximado?", ["120 m³", "360 m³", "376,8 m³", "600 m³", "1.130 m³"], "C", 2, 48)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "Se uma esfera tem raio de 6 m, seu volume pode ser calculado usando V = (4πr³)/3.", "Se o raio de uma esfera é 6 m, qual é seu volume aproximado?", ["216 m³", "452 m³", "723 m³", "904 m³", "1.000 m³"], "C", 2, 45)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "Se um prisma retangular tem dimensões 6 m x 4 m x 5 m, seu volume pode ser calculado multiplicando-se as três dimensões.", "Qual é o volume de um prisma retangular com 6 m x 4 m x 5 m?", ["60 m³", "90 m³", "120 m³", "150 m³", "1.200 m³"], "C", 1, 80)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "Se um paralelepípedo retangular mede 8 cm x 5 cm x 3 cm, seu volume pode ser calculado multiplicando-se as três dimensões.", "Qual é o volume de um paralelepípedo com 8 cm x 5 cm x 3 cm?", ["40 cm³", "80 cm³", "120 cm³", "150 cm³", "240 cm³"], "C", 1, 82)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "Se um trapézio tem bases de 8 cm e 12 cm e altura de 6 cm, sua área pode ser calculada usando A = (B + b) × h / 2.", "Qual é a área de um trapézio com bases de 8 cm e 12 cm e altura de 6 cm?", ["40 cm²", "60 cm²", "80 cm²", "120 cm²", "140 cm²"], "B", 2, 52)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "Se um setor circular tem raio de 10 cm e ângulo central de 90°, sua área pode ser calculada usando A = (πr² × θ) / 360.", "Qual é a área de um setor circular com raio 10 cm e ângulo 90°?", ["25π cm²", "50π cm²", "78,5 cm²", "100π cm²", "314 cm²"], "C", 3, 35)); n+=1

# Estatistica 10
d = "estatistica"
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "Se 120 mil votos foram distribuídos entre 12 candidatos, a média de votos por candidato pode ser calculada dividindo o total pelo número de candidatos.", "Se 120 mil votos foram distribuídos entre 12 candidatos, qual é a média?", ["8 mil votos", "10 mil votos", "12 mil votos", "15 mil votos", "20 mil votos"], "B", 1, 88)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "O desvio padrão indica o quanto os dados se afastam da média. Um desvio padrão baixo indica que os votos estão concentrados em torno da média.", "Um desvio padrão baixo nos dados eleitorais indica:", ["Concentração de votos em torno da média", "Dispersão dos votos entre os candidatos", "Igualdade na distribuição dos votos", "Ausência de votos nulos", "Igualdade no número de eleitores"], "A", 2, 50)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "Se uma pesquisa indica 50% das intenções de voto com margem de erro de 4%, o percentual real pode variar entre 46% e 54%.", "Se uma pesquisa indica 50% com margem de erro de 4%, o percentual real pode variar entre:", ["44% e 56%", "46% e 54%", "48% e 52%", "49% e 51%", "45% e 55%"], "B", 2, 46)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "Se historicamente 65% dos eleitores de um município votam no partido Y, pode-se estimar a probabilidade de esse padrão se repetir.", "Se historicamente 65% votam no partido Y, qual a probabilidade estimada?", ["35%", "50%", "65%", "85%", "100%"], "C", 1, 78)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "Um coeficiente de correlação negativo alto entre desemprego e comparecimento eleitoral indica que municípios com mais desemprego tendem a ter menor comparecimento.", "Um coeficiente de correlação negativo alto indica que:", ["Municípios com mais desemprego têm maior comparecimento", "Municípios com mais desemprego tendem a ter menor comparecimento", "Não existe relação entre desemprego e comparecimento", "A renda não influencia o comparecimento", "Todos os municípios têm o mesmo comparecimento"], "B", 2, 48)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "A mediana é o valor que separa os dados em duas partes iguais. Na análise eleitoral, a mediana pode indicar o valor central das candidaturas.", "Se os candidatos receberam 8, 12, 18, 22 e 90 mil votos, qual é a mediana?", ["8 mil votos", "12 mil votos", "18 mil votos", "22 mil votos", "90 mil votos"], "C", 2, 52)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "A moda é o valor que mais se repete em um conjunto de dados. Na análise eleitoral, a moda pode indicar o número de votos mais comum entre os candidatos.", "Se os candidatos receberam 8, 15, 20, 15 e 15 mil votos, qual é a moda?", ["8 mil votos", "15 mil votos", "20 mil votos", "17 mil votos", "25 mil votos"], "B", 1, 80)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "A variância é uma medida de dispersão que indica o quanto os dados se afastam da média. Quanto maior a variância, mais dispersos estão os dados.", "Se a variância dos votos é baixa, isso indica:", ["Dados dispersos da média", "Dados concentrados na média", "Dados iguais em todos os candidatos", "Dados uniformemente distribuídos", "Dados com valor zero"], "B", 2, 50)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "Se uma pesquisa indica 55% ± 2%, o intervalo de confiança indica a precisão da estimativa.", "Se uma pesquisa indica 55% ± 2%, qual é o intervalo de confiança?", ["51% a 59%", "53% a 57%", "50% a 60%", "54% a 56%", "55% a 57%"], "B", 2, 52)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "O percentil indica a posição de um valor em relação ao restante dos dados. Se um candidato está no percentil 80, significa que 80% dos candidatos receberam menos votos.", "Se um candidato está no percentil 80:", ["80% dos candidatos receberam mais votos", "80% dos candidatos receberam menos votos", "Ele recebeu 80% dos votos totais", "Ele recebeu apenas 20% dos votos", "Ele está na posição 80 de 100 candidatos"], "B", 3, 35)); n+=1

# Probabilidade 5
d = "probabilidade"
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "Se um eleitor escolhe aleatoriamente entre 4 candidatos, a probabilidade de votar em cada candidato seria de 1/4.", "Se um eleitor escolhe aleatoriamente entre 4 candidatos, qual a probabilidade?", ["1/2", "1/3", "1/4", "1/5", "1/6"], "C", 1, 82)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "Se a probabilidade de um candidato ser eleito é de 40%, a probabilidade de não ser eleito é de 60%. A soma deve ser igual a 1.", "Se a probabilidade de ser eleito é 40%, qual a probabilidade de não ser eleito?", ["30%", "40%", "50%", "60%", "100%"], "D", 1, 80)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "Se 55% dos eleitores de um partido são do sexo masculino, a probabilidade de escolher aleatoriamente um eleitor desse partido é de 55%.", "Se 55% dos eleitores são homens, qual a probabilidade de escolher um homem?", ["25%", "45%", "55%", "65%", "75%"], "C", 2, 52)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "A distribuição binomial é utilizada para modelar o número de sucessos em tentativas independentes. Pode ser utilizada para calcular a probabilidade de k votos em n eleitores.", "A distribuição binomial é utilizada para calcular:", ["A média de votos", "A probabilidade de k sucessos em n tentativas", "O desvio padrão", "A correlação entre variáveis", "A área de um terreno"], "B", 3, 28)); n+=1
questions.append(q(f"{p}2018_{n:02d}", 2018, a, d, "O Teorema de Bayes é utilizado para atualizar probabilidades com base em novas evidências. Na análise eleitoral, pode ser utilizado para ajustar previsões quando novos dados são disponibilizados.", "O Teorema de Bayes é utilizado para:", ["Calcular a média", "Atualizar probabilidades com base em novas evidências", "Determinar a área de um círculo", "Calcular a soma de uma progressão", "Prever o tempo"], "B", 3, 25)); n+=1

print(f"Total de questões 2018: {len(questions)}")
assert len(questions) == 180, f"Esperado 180, obtido {len(questions)}"

with open('data/2018.json', 'w', encoding='utf-8') as f:
    json.dump(questions, f, ensure_ascii=False, indent=2)

print("Arquivo data/2018.json criado com sucesso!")
