// Submatérias oficiais do ENEM baseadas na Matriz de Referência do INEP
var SUBTOPICOS_OFICIAIS = {
  // ===== LINGUAGENS, CÓDIGOS E SUAS TECNOLOGIAS =====
  portugues: [
    'Interpretação de Texto',
    'Gramática Normativa',
    'Ortografia',
    'Pontuação',
    'Classes Gramaticais',
    'Sintaxe',
    'Semântica',
    'Concordância Verbal',
    'Regência Verbal',
    'Crase',
    'Vozes Verbais',
    'Coesão Textual',
    'Figuras de Linguagem'
  ],
  ingles: [
    'Interpretação de Texto em Inglês',
    'Vocabulário em Contexto',
    'Estruturas Gramaticais'
  ],
  espanhol: [
    'Interpretação de Texto em Espanhol',
    'Vocabulário em Contexto',
    'Estruturas Gramaticais'
  ],
  artes: [
    'Linguagens Artísticas',
    'Artes Visuais',
    'Música',
    'Teatro',
    'Dança',
    'História da Arte'
  ],
  literatura: [
    'Literatura Medieval',
    'Literatura Clássica',
    'Literatura Barroca',
    'Literatura Arcádica',
    'Literatura Romântica',
    'Literatura Realista',
    'Literatura Parnasiana',
    'Literatura Simbolista',
    'Literatura Moderna',
    'Literatura Contemporânea',
    'Movimentos Literários'
  ],

  // ===== CIÊNCIAS HUMANAS E SUAS TECNOLOGIAS =====
  historia: [
    'Pré-História',
    'Civilizações Antigas',
    'Idade Média',
    'Idade Moderna',
    'Descobrimentos e Colonização',
    'Brasil Colônia',
    'Iluminismo',
    'Revolução Industrial',
    'Independência do Brasil',
    'Brasil Imperial',
    'Abolição da Escravatura',
    'República Velha',
    'Revolução de 1930',
    'Era Vargas',
    'Estado Novo',
    'Redemocratização',
    'Regime Militar',
    'Contemporaneidade',
    'Movimentos Sociais',
    'Direitos Humanos'
  ],
  geografia: [
    'Espaço Geográfico',
    'Globalização',
    'Migrações e Urbanização',
    'Geografia do Brasil',
    'Regiões Brasileiras',
    'Relevo e Clima',
    'Hidrografia',
    'Vegetação',
    'População Brasileira',
    'Atividades Econômicas',
    'Agricultura e Pecuária',
    'Industrialização',
    'Geopolítica',
    'Meio Ambiente',
    'Desenvolvimento Sustentável',
    'Questões Sociais'
  ],
  sociologia: [
    'Cultura e Identidade',
    'Socialização e Grupos Sociais',
    'Estratificação Social',
    'Movimentos Sociais',
    'Cidadania e Democracia',
    'Educação',
    'Religião',
    'Comunicação e Opinião Pública',
    'Violência e Cidadania'
  ],
  filosofia: [
    'Origens do Pensamento Filosófico',
    'Filosofia Antiga',
    'Filosofia Medieval',
    'Filosofia Moderna',
    'Filosofia Contemporânea',
    'Ética',
    'Política',
    'Direitos Humanos',
    'Cidadania',
    'Liberdade e Igualdade'
  ],

  // ===== CIÊNCIAS DA NATUREZA E SUAS TECNOLOGIAS =====
  fisica: [
    'Cinemática',
    'Dinâmica',
    'Estática',
    'Gravitação Universal',
    'Trabalho e Energia',
    'Máquinas Simples',
    'Termodinâmica',
    'Calorimetria',
    'Ondulatória',
    'Óptica',
    'Eletricidade',
    'Eletrostática',
    'Eletrodinâmica',
    'Magnetismo',
    'Eletromagnetismo',
    'Física Moderna',
    'Rele Relatividade',
    'Física Nuclear'
  ],
  quimica: [
    'Matéria e Mudanças',
    'Modelo Atômico',
    'Tabela Periódica',
    'Ligações Químicas',
    'Nomenclatura',
    'Reações Químicas',
    'Estequiometria',
    'Soluções',
    'Cinética Química',
    'Equilíbrio Químico',
    'Acidez e Alcalinidade',
    'Eletroquímica',
    'Química Orgânica',
    'Química Ambiental',
    'Química dos Alimentos',
    'Bioquímica'
  ],
  biologia: [
    'Bioquímica',
    'Citologia',
    'Genética',
    'Evolução',
    'Ecologia',
    'Biodiversidade',
    'Fisiologia Humana',
    'Sistema Nervoso',
    'Sistema Endócrino',
    'Sistema Reprodutor',
    'Sistema Circulatório',
    'Sistema Respiratório',
    'Sistema Digestório',
    'Sistema Excretor',
    'Sistema Imunológico',
    'Biotecnologia',
    'Saúde e Doenças',
    'Meio Ambiente'
  ],

  // ===== MATEMÁTICA E SUAS TECNOLOGIAS =====
  algebra: [
    'Números Naturais',
    'Números Inteiros',
    'Números Racionais',
    'Números Reais',
    'Conjuntos Numéricos',
    'Porcentagem',
    'Juros Simples e Compostos',
    'Proporção e Razão',
    'Equações do 1º Grau',
    'Equações do 2º Grau',
    'Sistemas Lineares',
    'Inequações',
    'Funções do 1º Grau',
    'Funções do 2º Grau',
    'Funções Polinomiais',
    'Funções Racionais',
    'Funções Exponenciais',
    'Funções Logarítmicas',
    'Progressão Aritmética',
    'Progressão Geométrica',
    'Princípios de Contagem',
    'Logaritmos'
  ],
  geometria: [
    'Geometria Plana',
    'Triângulos',
    'Quadriláteros',
    'Polígonos',
    'Circunferência e Círculo',
    'Área e Perímetro',
    'Geometria Espacial',
    'Prismas',
    'Pirâmides',
    'Corpos de Revolução',
    'Trigonometria',
    'Relações Trigonométricas',
    'Lei dos Senos',
    'Lei dos Cossenos',
    'Vetores',
    'Matrizes',
    'Plano Cartesiano',
    'Retas e Planos'
  ],
  estatistica: [
    'Estatística Descritiva',
    'Média Aritmética',
    'Mediana',
    'Moda',
    'Amplitude',
    'Desvio Padrão',
    'Gráficos',
    'Tabelas de Frequência',
    'Análise de Dados',
    'Fontes de Dados'
  ],
  probabilidade: [
    'Probabilidade',
    'Probabilidade Simples',
    'Probabilidade Composta',
    'Evento Independente',
    'Evento Dependente',
    'Espaço Amostral',
    'Árvore de Probabilidade'
  ]
};
